p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ROP_Business_Phone__c</fullName>
        <label>Business Phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Home_Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <externalId>true</externalId>
        <label>ROP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Seat_Preference__c</fullName>
        <label>Seat Preference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the membership whether it is Active, Inactive, Dead, Closed or Merged</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/TempPassenger__c.object
<CustomObject>
    <fields>
        <fullName>ROP_Business_Phone__c</fullName>
        <description>ROP business phone number</description>
        <label>ROP Business Phone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Date_of_Birth__c</fullName>
        <description>ROP date of birth</description>
        <label>ROP Date of Birth</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Email__c</fullName>
        <description>ROP Email</description>
        <label>ROP Email</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Fax_Phone__c</fullName>
        <description>ROP fax number</description>
        <label>ROP Fax Phone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_First_Name__c</fullName>
        <description>ROP firstname</description>
        <label>ROP First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Food_Preference__c</fullName>
        <description>ROP food preference (ex. SPML)</description>
        <label>ROP Food Preference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Gender__c</fullName>
        <description>ROP Gender</description>
        <label>ROP Gender</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Home_Phone__c</fullName>
        <description>ROP home phone number</description>
        <label>ROP Home Phone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Language__c</fullName>
        <description>ROP language preference</description>
        <label>ROP Language</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Last_Name__c</fullName>
        <description>ROP lastname</description>
        <label>ROP Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Mailing_Address__c</fullName>
        <description>ROP mailing address</description>
        <label>ROP Mailing Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ROP_Mobile_Phone__c</fullName>
        <description>ROP mobile phone number</description>
        <label>ROP Mobile Phone</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <description>ROP membership number</description>
        <label>ROP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Seat_Preference__c</fullName>
        <description>ROP seat prefer type (ex.NSSW = near window)</description>
        <label>ROP Seat Preference</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Status__c</fullName>
        <description>ROP status (ex. AC = active)</description>
        <label>ROP Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <description>ROP Tier</description>
        <label>ROP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Title__c</fullName>
        <description>ROP title / salutation</description>
        <label>ROP Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>TempPassenger</label>
    <nameField>
        <label>TempPassenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TempPassengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/TempPassengerTriggerTest.cls
@isTest
private class TempPassengerTriggerTest {
	
	/* This function is used to reconcile the input date */
	@isTest static void testCorrectnessOfInputData() {
		String name = 'Earth Pho-ngoen';
		String ropNo = 'TS00001';
		String tier = 'Member';
		String gender = 'M';
		String status = 'AC';
		String email = 'Earth@earth.com';

		TempPassenger__c temp1 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, status, email);
		insert temp1;
		List<TempPassenger__c> templist = [SELECT Id, Name, ROP_Title__c, ROP_Number__c, ROP_First_Name__c, 
											ROP_Last_Name__c, ROP_Date_of_Birth__c, ROP_Mailing_Address__c, 
												ROP_Home_Phone__c, ROP_Business_Phone__c, ROP_Mobile_Phone__c, 
													ROP_Fax_Phone__c, ROP_Gender__c, ROP_Email__c, ROP_Tier__c, 
														ROP_Seat_Preference__c, ROP_Food_Preference__c, ROP_Language__c, ROP_Status__c 
															FROM TempPassenger__c 
																WHERE ROP_Number__c = :ropNo];
		//List<TempPassenger__c> templist = [SELECT Id FROM TempPassenger__c WHERE ROP_Number__c = :ropNo];
		System.assertNotEquals(null, templist);
	}

	@isTest static void testCreateNewAccount(){
		String name = 'Earth Pho-ngoen';
		String ropNo = 'TS00001';
		String tier = 'Member';
		String gender = 'M';
		String status = 'AC';
		String email = 'Earth@earth.com';

		TempPassenger__c temp1 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, status, email);
		insert temp1;
		List<Account> accountlist = [SELECT Id FROM Account WHERE ROP_Number__c = :ropNo];
		System.assertNotEquals(null, accountlist);
	}

	@isTest static void testUpdateAccount(){
		String name = 'Earth Pho-ngoen';
		String ropNo = 'TS00001';
		String tier = 'Member';
		String gender = 'M';
		String status = 'AC';
		String email = 'Earth@earth.com';
		TempPassenger__c temp1 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, status, email);
		insert temp1;
		TempPassenger__c temp2 = MockupData_Test.createTempPassenger('E A', ropNo, tier, gender, status, email);
		insert temp2;

		List<Account> accountlist = [SELECT Id, Name FROM Account WHERE ROP_Number__c = :ropNo];
		System.assertEquals(1, accountlist.size());
		System.assertEquals('E A', accountlist.get(0).Name);
	}

	@isTest static void testCreateNewMembership(){
		String name = 'Earth Pho-ngoen';
		String ropNo = 'TS00001';
		String tier = 'Member';
		String gender = 'M';
		String status = 'AC';
		String email = 'Earth@earth.com';

		TempPassenger__c temp1 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, status, email);
		insert temp1;
		List<Membership__c> memlist = [SELECT Id FROM Membership__c WHERE Name = :ropNo];
		System.assertNotEquals(null, memlist);
	}

	@isTest static void testUpdateMembership(){
		String name = 'Earth Pho-ngoen';
		String ropNo = 'TS00001';
		String tier = 'Member';
		String gender = 'M';
		String status = 'AC';
		String email = 'Earth@earth.com';
		TempPassenger__c temp1 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, status, email);
		insert temp1;
		TempPassenger__c temp2 = MockupData_Test.createTempPassenger(name, ropNo, tier, gender, 'IN', email);
		insert temp2;

		List<Membership__c> memlist = [SELECT Id, Status__c FROM Membership__c WHERE Name = :ropNo];
		System.assertEquals(1, memlist.size());
		System.assertEquals('Inactive', memlist.get(0).Status__c);
	}
}