p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <description>INVALID</description>
        <label>Channel (Delete)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Walk-in</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>In-flight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latest_Document__c</fullName>
        <label>Latest Document</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_Body__c</fullName>
        <label>Letter Body</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Used for display</description>
        <label>Travel Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSR_Service__c</fullName>
        <label>Service</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/UpgradeConfirmationController_Test.cls
@isTest
private class UpgradeConfirmationController_Test {

    @isTest static void testGetViewUpgradeConfirmation() {
        MockupData_Test.initializeWebServiceCustomSetting();
        MockupData_Test.initializeSystemConfigurationCustomSetting();

        Flight__c flight = MockupData_Test.createFlight('TG 1234', '', 1);
        insert flight;

        Flight__c dummyFlight = MockupData_Test.createFlight('TGXXX', '', null);
        insert dummyFlight;

        Case thisCase = MockupData_Test.createCase('', 'New', 'CTI');
        thisCase.FlightId__c = flight.Id;
        thisCase.Latest_Document__c = 'LetterEN';
        thisCase.Status = 'New';
        thisCase.Channel__c = 'Phone';
        thisCase.Letter_Body__c = '| Line1 <br>   Line2 <br> @:LINE3:@ <br>';
        insert thisCase;

        Test.startTest();
        Test.setCurrentPage(Page.UpgradeConfirmation);
        ApexPages.currentPage().getParameters().put('id', String.valueOf(thisCase.Id));
        ApexPages.StandardController sc = new ApexPages.StandardController(thisCase);
        UpgradeConfirmationController ctrl = new UpgradeConfirmationController(sc);
        Test.stopTest();

        Assert.assertNotEquals(null, ctrl.view);
        Assert.assertEquals(thisCase.Id, ctrl.view.caseObj.Id);
        Assert.assertEquals('&nbsp;Line1 \n&nbsp;&nbsp;&nbsp;Line2 \n&nbsp;...@:LINE3... \n', ctrl.view.letterBody);
    }
	
	// positive UpgradeConfirmation page
	//@isTest static void testGetViewUpgradeConfirmation() {
 //   	MockupData_Test.initializeWebServiceCustomSetting();
 //       MockupData_Test.initializeSystemConfigurationCustomSetting();

 //   	String firstName = 'First Name';
 //   	String lastName = 'Last Name';
 //   	String comment = 'comment test 1234';

 //   	Account a = new Account();
 //   	a.Name = firstName + ' ' + lastName;
 //   	a.First_Name__c = firstName;
 //   	a.Last_Name__c = lastName;
 //   	a.ROP_Tier__c = 'Gold';
 //   	insert a;

 //   	Flight__c f = new Flight__c();
 //   	f.Name = 'TG 1234';
 //   	insert f;

 //       Flight__c fdummy = new Flight__c();
 //       fdummy.Name = 'TGXXX';
 //       insert fdummy;

 //   	Passenger__c p = new Passenger__c();
 //       p.SSR_Service__c = '';
 //       p.First_Name__c = firstName;
 //       p.Last_Name__c = lastName;
 //       p.FlightId__c = f.Id;
 //       p.AccountId__c = a.Id;
 //       p.Class__c = 'C';
 //       insert p;

 //       Passenger__c p2 = new Passenger__c();
 //       p2.SSR_Service__c = '';
 //       p2.First_Name__c = firstName;
 //       p2.Last_Name__c = lastName;
 //       p2.FlightId__c = f.Id;
 //       p2.AccountId__c = a.Id;
 //       p2.Class__c = 'C';
 //       insert p2;

 //       Case thisCase = new Case();
 //       thisCase.PassengerId__c = p.Id;
 //       thisCase.FlightId__c = f.Id;
 //       thisCase.Status = 'New';
 //       thisCase.Channel__c = 'Phone';
 //       insert thisCase;

 //   	Test.startTest();

 //   	Test.setCurrentPage(Page.UpgradeConfirmation);
	//	ApexPages.currentPage().getParameters().put('id', String.valueOf(thisCase.Id));
	//	ApexPages.StandardController sc = new ApexPages.StandardController(thisCase);
 //       UpgradeConfirmationController controller = new UpgradeConfirmationController(sc);

 //   	Test.stopTest();

 //   	System.assertNotEquals(null, controller.view);
 //       System.assertEquals(thisCase.Id, controller.view.caseObj.Id);
	//}

	//// positive UpgradeStandby page
	//@isTest static void testGetViewUpgradeStandby() {

 //   	MockupData_Test.initializeWebServiceCustomSetting();
 //       MockupData_Test.initializeSystemConfigurationCustomSetting();

 //   	String firstName = 'First Name';
 //   	String lastName = 'Last Name';
 //   	String comment = 'comment test 1234';

 //   	Account a = new Account();
 //   	a.Name = firstName + ' ' + lastName;
 //   	a.First_Name__c = firstName;
 //   	a.Last_Name__c = lastName;
 //   	a.ROP_Tier__c = 'Gold';
 //   	insert a;

 //   	Flight__c f = new Flight__c();
 //   	f.Name = 'TG 1234';
 //   	insert f;

 //       Flight__c fdummy = new Flight__c();
 //       fdummy.Name = 'TGXXX';
 //       insert fdummy;

 //   	Passenger__c p = new Passenger__c();
 //       p.SSR_Service__c = '';
 //       p.First_Name__c = firstName;
 //       p.Last_Name__c = lastName;
 //       p.FlightId__c = f.Id;
 //       p.AccountId__c = a.Id;
 //       p.Class__c = 'C';
 //       insert p;

 //       Passenger__c p2 = new Passenger__c();
 //       p2.SSR_Service__c = '';
 //       p2.First_Name__c = firstName;
 //       p2.Last_Name__c = lastName;
 //       p2.FlightId__c = f.Id;
 //       p2.AccountId__c = a.Id;
 //       p2.Class__c = 'C';
 //       insert p2;

 //       Case thisCase = new Case();
 //       thisCase.PassengerId__c = p.Id;
 //       thisCase.FlightId__c = f.Id;
 //       thisCase.Status = 'New';
 //       thisCase.Channel__c = 'Phone';
 //       insert thisCase;

 //   	Test.startTest();

 //   	Test.setCurrentPage(Page.UpgradeStandby);
	//	ApexPages.currentPage().getParameters().put('id', String.valueOf(thisCase.Id));
	//	ApexPages.StandardController sc = new ApexPages.StandardController(thisCase);
 //       UpgradeConfirmationController controller = new UpgradeConfirmationController(sc);

 //   	Test.stopTest();

 //   	System.assertNotEquals(null, controller.view);
 //       System.assertEquals(thisCase.Id, controller.view.caseObj.Id);
	//}

}