p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Email_1__c</fullName>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that uses this membership</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXTMember__c</fullName>
        <description>The External Id of this membership which is Airline__c + &apos;_&apos; + Name</description>
        <externalId>true</externalId>
        <label>EXT Member</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>The date when the Tier of Royal Orchid Plus expired</description>
        <label>Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the membership whether it is Active, Inactive, Dead, Closed or Merged</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <description>Used for display</description>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CSE_ROPCalloutBatch_Test.cls
@isTest
private class CSE_ROPCalloutBatch_Test {
	@isTest
	static void test() {
		MockupData_Test.initializeWebServiceCustomSetting();
		Flight__c flight = MockupData_Test.getMockUpFlight();
		insert flight;

		Account account = MockupData_Test.createAccount('AccountName');
		account.First_Name__c = 'A';
		account.Last_Name__c = 'B';
		account.Date_of_Birth__c = Date.today();
		insert account;

		Passenger__c passenger = new Passenger__c(FlightId__c = flight.Id , Name = 'ALAN NEAL', First_Name__c = 'ALAN', Last_Name__c = 'NEAL', Date_of_Birth_Input__c = Date.valueOf('1942-02-06'), FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Number__c = 'NY67945', AccountId__c = account.Id);
		insert passenger;
		System.debug('passenger: ' + passenger);

		Membership__c memberShip = MockupData_Test.createMembership();
		memberShip.AccountId__c = account.Id;
		memberShip.Name = 'NY67945';
		memberShip.EXTMember__c = 'TG_NY67945';
		memberShip.Status__c = 'Active';
		membership.Expiry_Date__c = Date.today().addDays(365);
		insert memberShip;

		SingleRequestMock fakeROPMileageResp = Mock_CSE_ROP_Response.getCurrentMileage();
		SingleRequestMock fakeROPResp = Mock_CSE_ROP_Response.getROPProfile();
		SingleRequestMock fakeAdditionalProfile = Mock_CSE_ROP_Response.getAdditionalProfile();

		Map<String, HttpCalloutMock> endpoint2TestResp = new Map<String, HttpCalloutMock>();
		endpoint2TestResp.put(Mock_CSE_ROP_Response.getCurrentMileageEndPoint(), fakeROPMileageResp);
		endpoint2TestResp.put(Mock_CSE_ROP_Response.getROPProfileEndPoint(), fakeROPResp);
		endpoint2TestResp.put(Mock_CSE_ROP_Response.getAdditionalProfileEndPoint(), fakeAdditionalProfile);

		HttpCalloutMock multiCalloutMock = new MultiRequestMock(endpoint2TestResp);
		Test.setMock(HttpCalloutMock.class, multiCalloutMock);

		Test.startTest();
		Database.executeBatch(new CSE_ROPCalloutBatch(new Set<Id> {flight.Id}));
		Test.stopTest();

		List<Account> actualAccounts = [SELECT Id, Email_1__c, ROP_Email_1__c, First_Name__c, Last_Name__c FROM Account];
		System.debug('---------SELECT ACCOUNT-------');
		System.debug(actualAccounts);
		Assert.assertEquals(1, actualAccounts.size());
		Account actualAccount = actualAccounts.get(0);
		Assert.assertEquals('test@beryl8.com', actualAccount.Email_1__c);
		Assert.assertEquals('test@beryl8.com', actualAccount.ROP_Email_1__c);
		Assert.assertEquals('ALAN', actualAccount.First_Name__c);
		Assert.assertEquals('NEAL', actualAccount.Last_Name__c);

	}

	@isTest static void testFindExistingROPAndAccount(){
		CSE_ROPCalloutBatch ropBatch = new CSE_ROPCalloutBatch(new List<String>{'TG12345'});
		ropBatch.findExistingROPAndAccount(new List<String>{'TG12345'});
	}

	//@isTest static void testGetStringDate(){
	//	CSE_ROPCalloutBatch ropBatch = new CSE_ROPCalloutBatch(new List<String>{'TG12345'});
	//	String dateNull = ropBatch.getStringDate(null);
	//	String dateNotNull = ropBatch.getStringDate(Date.valueOf('2050-06-01'));
	//}


}