p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <externalId>true</externalId>
        <label>ROP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that uses this membership</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Airline__c</fullName>
        <description>The airline that issued this membership</description>
        <label>Airline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXTMember__c</fullName>
        <description>The External Id of this membership which is Airline__c + &apos;_&apos; + Name</description>
        <externalId>true</externalId>
        <label>EXT Member</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MembershipId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>In case of duplication, this field will related to the actual membership</description>
        <label>Merge with memership no.</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the membership whether it is Active, Inactive, Dead, Closed or Merged</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Merge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_First_Name_Auto__c</fullName>
        <label>Passenger First Name Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Salutation_Auto__c</fullName>
        <description>This field stores the value of salutation of this passenger which is the result of automatic detection of salutation from passenger&apos;s first name.</description>
        <label>Passenger Salutation Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaxKey__c</fullName>
        <formula>First_Name__c &amp; &apos;_&apos; &amp;  Last_Name__c &amp; &apos;_&apos; &amp;  PNR__c &amp; &apos;_&apos; &amp; Flight_Master__c</formula>
        <label>PaxKey</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/ROP_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to the customer that this enrollment belong to</description>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>ROP Enrollment</relationshipLabel>
        <relationshipName>ROP_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Area code of phone number</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Country code of phone number</description>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the customer</description>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <description>The date that this ROP Enrollment occured</description>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>External Id of this ROP Enrollment which is ROP Number + PaxKey</description>
        <externalId>true</externalId>
        <label>ExternalId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the customer</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Flight that originated this ROP Enrollment</description>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>ROP Enrollments</relationshipLabel>
        <relationshipName>ROP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the customer</description>
        <label>Gender</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Reason__c</fullName>
        <description>The error from Web Service Callout</description>
        <label>Integration Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether this ROP Enrollment encountered error during Web Service Callout</description>
        <label>Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the customer</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Enrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate wheter this ROP Enrollment must be done manually because the salutation cannot be extracted from the customer&apos;s name</description>
        <label>Manual Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MembershipId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to the membership object</description>
        <label>Membership</label>
        <referenceTo>Membership__c</referenceTo>
        <relationshipLabel>ROP Enrollment</relationshipLabel>
        <relationshipName>ROP_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PassengerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Passenger that enrolled</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ROP Enrollment</relationshipLabel>
        <relationshipName>ROP_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaxKey__c</fullName>
        <description>PaxKey of the passenger</description>
        <externalId>true</externalId>
        <label>PaxKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number_F__c</fullName>
        <description>The text version of the ROP Number</description>
        <formula>ROP_Number__r.ROP_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ROP Number Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related to the assigned ROP Number record</description>
        <label>ROP Number</label>
        <referenceTo>ROP_Number_Inventory__c</referenceTo>
        <relationshipLabel>ROP Enrollments</relationshipLabel>
        <relationshipName>ROP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Response_from_THAI__c</fullName>
        <description>Response from Web Service Callout to TG</description>
        <label>Response from THAI</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the ROP Enrollment whether</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enroll</fullName>
                    <default>true</default>
                    <label>Enroll</label>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ROP Enrollment</label>
    <nameField>
        <label>ROP Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/objects/ROP_Number_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <description>This field keeps the ROP Numbers. It also acts as the external key to prevent duplicate ROP Numbers in the system.</description>
        <externalId>true</externalId>
        <label>ROP Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Register_DateTime__c</fullName>
        <description>This is the timestamp when this ROP Number has been registered.</description>
        <label>Register Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>ROP Number Inventory</label>
    <nameField>
        <label>ROP Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Number Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTROPEnrollment.cls
@RestResource(urlMapping = '/ropenrollment/*')
global class MB_RESTROPEnrollment {

	@HttpGet
	global static List<MB_RESTResponseInfoModel.ropEnrollment> getROPEnrollment() {
		Set<Id> flightIdSet = BE8_GlobalUtility.getFlightIdSetFromUserId(UserInfo.getUserId());
		return ROPEnrollmentService.getROPEnrollmentMobileList(flightIdSet);
	}

	@HttpPost
	global static List<MB_RestResponseInfoModel.ropEnrollment> enrollROPNumber(List<MB_RestRequestInfoModel.ropEnrollment> ropEnrollmentList) {
		AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTROPEnrollment', 'enrollROPNumber', '', 'ROP_Number_Inventory__c', 'The ROP Enrollments that are sent from mobile.', System.JSON.serialize(ropEnrollmentList), null, System.currentTimeMillis());

		List<ROP_Number_Inventory__c> ropNumberInventoryList = ROPEnrollmentService.getUnregisteredROPNumberList(ropEnrollmentList.size());

		Integer numberOfROPNumberRequired = ropEnrollmentList.size();
		Integer numberOfROPNumberAvailable = ropNumberInventoryList.size();
		Boolean hasSufficientNumberOfROPNumber = numberOfROPNumberRequired <= numberOfROPNumberAvailable;
		Boolean isLowNumberOfROPNumber = numberOfROPNumberAvailable > 0 && (numberOfROPNumberRequired * 1.0 / numberOfROPNumberAvailable * 1.0) < 0.2;
		if (!hasSufficientNumberOfROPNumber) {
			String message = 'The number of ROP Enrollment Inventory is inadequate. (Required: ' + numberOfROPNumberRequired + ' Available: ' + numberOfROPNumberAvailable + ')';
			BE8_GlobalUtility.logMessage(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTROPEnrollment', 'enrollROPNumber', '', 'ROP_Number_Inventory__c', message, System.JSON.serialize(ropEnrollmentList), null, System.currentTimeMillis());
			ROPEnrollmentService.sendEmailNotifyInsufficientNumberOfROPNumber(numberOfROPNumberAvailable);
			return null;
		}
		if (isLowNumberOfROPNumber) {
			ROPEnrollmentService.sendEmailNotifyInsufficientNumberOfROPNumber(numberOfROPNumberAvailable);
		}

		Map<String, Account> accountMapByROPNumber = new Map<String, Account>();
		Map<String, Membership__c> membershipMapByROPNumber = new Map<String, Membership__c>();
		Map<String, ROP_Number_Inventory__c> ropNumberSObjectMapByROPNumber = new Map<String, ROP_Number_Inventory__c>();
		Map<String, ROP_Enrollment__c> ropEnrollmentSObjectMapByROPNumber = new Map<String, ROP_Enrollment__c>();

		Set<Id> passengerIdSet = new Set<Id>();
		for (MB_RestRequestInfoModel.ropEnrollment eachEnrollment : ropEnrollmentList) {
			passengerIdSet.add(eachEnrollment.paxId);
		}
		Map<Id, Passenger__c> passengerMap = new Map<Id, Passenger__c>([SELECT Id, Name, First_Name__c, Last_Name__c, Passenger_Salutation_Auto__c, Passenger_First_Name_Auto__c FROM Passenger__c WHERE Id IN :passengerIdSet AND Passenger_Salutation_Auto__c != null AND Passenger_First_Name_Auto__c != null]);

		for (Integer i = 0; i < numberOfROPNumberRequired; i++) {
			ROP_Number_Inventory__c ropNumberSObject = ropNumberInventoryList.get(i);
			MB_RestRequestInfoModel.ropEnrollment ropEnrollment = ropEnrollmentList.get(i);
			Boolean isNotVoid = ROPEnrollmentService.ROP_ENROLLMENT_STATUS_FROM_MOBILE_MAP_BY_NUMBER.get(ropEnrollment.status) != ROPEnrollmentService.STATUS_VOID;
			if (isNotVoid) {
				String ropNumber = ropNumberSObject.ROP_Number__c;
				ropEnrollment.ropNumber = ropNumber;
				ropEnrollment.sfdcId = ropNumberSObject.Id;
				ropenrollment.isSynced = '1';
				try {
					Boolean isEnrollmentByWebService = passengerMap.containsKey(ropEnrollment.paxId);
					Boolean isManualEnrollment = !isEnrollmentByWebService;

					ROP_Enrollment__c ropEnrollmentSObject = null;

					if (isEnrollmentByWebService) {
						Passenger__c passengerWithCorrectSalutation = passengerMap.get(ropEnrollment.paxId);
						ropEnrollment.salut = passengerWithCorrectSalutation.Passenger_Salutation_Auto__c;
						ropEnrollment.firstN = passengerWithCorrectSalutation.Passenger_First_Name_Auto__c;
						ropEnrollment.lastN = passengerWithCorrectSalutation.Last_Name__c;

						WS_ROPEnrollmentResponseModel response = ROPEnrollmentService.enrollROPMemberFromMobileModel(ropEnrollment);
						System.debug('response: ' + response);
						ropEnrollmentSObject = ROPEnrollmentService.createROPEnrollmentRecord(ropNumberSObject, ropEnrollment, response);
						ropEnrollmentSObjectMapByROPNumber.put(ropNumber, ropEnrollmentSObject);
						System.debug(ropEnrollmentSObject);

						if (!ropEnrollmentSObject.Integration_Error__c && ropEnrollmentSObject.Status__c == ROPEnrollmentService.STATUS_ENROLL) {
							Account newAccount = new Account();
							newAccount.Name = ropEnrollment.lastN + ' ' + ropEnrollment.firstN + ' ' + ropEnrollment.salut;
							newAccount.Id = ropEnrollment.accId;
							newAccount.ROP_Number__c = ropNumber;
							accountMapByROPNumber.put(ropNumber, newAccount);

							Membership__c newMembership = new Membership__c();
							newMembership.Name = ropNumber;
							newMembership.Airline__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY;
							newMembership.EXTMember__c = newMembership.Airline__c + '_' + newMembership.Name;
							newMembership.Status__c = BE8_GlobalConstants.MEMBERSHIP_STATUS_INACTIVE;
							membershipMapByROPNumber.put(ropNumber, newMembership);

							ropNumberSObject.Register_DateTime__c = System.now();
						}
					} else if(isManualEnrollment){
						ropEnrollment.ropNumber = null;
						ropEnrollment.sfdcId = null;
						ropEnrollmentSObject = ROPEnrollmentService.createROPEnrollmentRecord(null, ropEnrollment, null, true);
						ropEnrollmentSObjectMapByROPNumber.put(ropNumber, ropEnrollmentSObject);
					}


					if (ropEnrollmentSObject.Status__c == ROPEnrollmentService.STATUS_ENROLL) {
						ropNumberSObjectMapByROPNumber.put(ropNumber, ropNumberSObject);
					}
				} catch (Exception e) {
					String message = 'Problem occured during integration with THAI.\n' + e.getMessage() + '\n' + e.getStackTraceString();
					AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTROPEnrollment', 'enrollROPNumber', '', 'ROP_Number_Inventory__c', message, System.JSON.serialize(ropEnrollment), null, System.currentTimeMillis());
				}
			} else {
				ROP_Enrollment__c ropEnrollmentSObject = ROPEnrollmentService.createROPEnrollmentRecord(null, ropEnrollment, null);
				ropEnrollmentSObjectMapByROPNumber.put(ropEnrollmentSObject.PaxKey__c, ropEnrollmentSObject);
			}
		}

		List<Passenger__c> passengerList = new List<Passenger__c>();
		try {
			if (!accountMapByROPNumber.isEmpty()) {
				upsert accountMapByROPNumber.values();
			}

			for (String ropNumber : accountMapByROPNumber.keySet()) {
				Account account = accountMapByROPNumber.get(ropNumber);
				if (account != null) {
					Membership__c newMembership = membershipMapByROPNumber.get(ropNumber);
					if (newMembership != null) {
						newMembership.AccountId__c = account.Id;
					}

					ROP_Enrollment__c ropEnrollmentSObject = ropEnrollmentSObjectMapByROPNumber.get(ropNumber);
					ropEnrollmentSObject.AccountId__c = account.Id;
					if (ropEnrollmentSObject != null && ropEnrollmentSObject.PassengerId__c != null) {
						passengerList.add(new Passenger__c(Id = ropEnrollmentSObject.PassengerId__c, AccountId__c = account.Id));
					}
				}
			}

			if (!membershipMapByROPNumber.isEmpty()) {
				insert membershipMapByROPNumber.values();
			}

			if (!passengerList.isEmpty()) {
				update passengerList;
			}

			for (String ropNumber : membershipMapByROPNumber.keySet()) {
				Membership__c membership = membershipMapByROPNumber.get(ropNumber);
				ROP_Enrollment__c ropEnrollmentSObject = ropEnrollmentSObjectMapByROPNumber.get(ropNumber);
				if (membership != null && ropEnrollmentSObject != null) {
					ropEnrollmentSObject.MembershipId__c = membership.Id;
				}
			}

			if (!ropNumberSObjectMapByROPNumber.isEmpty()) {
				update ropNumberSObjectMapByROPNumber.values();
			}

			if (!ropEnrollmentSObjectMapByROPNumber.isEmpty()) {
				upsert ropEnrollmentSObjectMapByROPNumber.values() ExternalId__c;
				for (ROP_Enrollment__c each : ropEnrollmentSObjectMapByROPNumber.values()) {
					if (each.Integration_Error__c) {
						AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTROPEnrollment', 'enrollROPNumber', each.Id, 'ROP_Enrollment__c', 'ROP Enrollment with Integration Error to THAI\n' + each.Response_from_THAI__c, System.JSON.serialize(each), null, System.currentTimeMillis());
						String toEmails = MailList_Repository.getEmailAddress('ROP Enrollment', 'ROPEnrollment_Monitoring');
						Email_Service.sendEmail('SFDC | ROP Enrollment Error', toEmails, each.Id + ' ' + each.Integration_Error_Reason__c);
					} else if(each.Manual_Enrollment__c){
						ROPEnrollment_Manual_Queueable.process(each.Id);
					}
				}
			}
		} catch (Exception e) {
			String message = e.getMessage() + '\n' + e.getStackTraceString();
			AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTROPEnrollment', 'enrollROPNumber', '', 'ROP_Number_Inventory__c', message, System.JSON.serialize(ropEnrollmentList), null, System.currentTimeMillis());
			AppLogger.insertLogs();
			//return new Map<String, String> {
			//	'status' => '500',
			//	'message' => message
			//};
			Set<Id> ropEnrollmentSObjectIdSet = BE8_GlobalUtility.getIdSet('Id', ropEnrollmentSObjectMapByROPNumber.values());
			return ROPEnrollmentService.convertROPEnrollmentSObjectToResponseModel([SELECT FlightId__c, FlightId__r.Name, FlightId__r.Flight_External_ID__c, PassengerId__r.First_Name__c, PassengerId__r.Last_Name__c, PassengerId__r.PNR__c, ROP_Number_F__c, AccountId__c, Area_Code__c, Birthdate__c, Country_Code__c, CreatedById, CreatedDate, Email__c, Enrollment_Date__c, First_Name__c, Gender__c, Id, Integration_Error_Reason__c, Integration_Error__c, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, Last_Name__c, MembershipId__c, Name, Nationality__c, OwnerId, PassengerId__c, PaxKey__c, Phone_Number__c, Phone_Type__c, Response_from_THAI__c, ROP_Number__c, Salutation__c, Status__c FROM ROP_Enrollment__c WHERE Id IN : ropEnrollmentSObjectIdSet]);
		}

		AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTROPEnrollment', 'enrollROPNumber', '', 'ROP_Number_Inventory__c', 'The ROP Enrollments after ROP Number assignment', System.JSON.serialize(ropEnrollmentList), null, System.currentTimeMillis());
		AppLogger.insertLogs();
		Monitoring.sendEmail();
		//return new Map<String, String> {
		//	'status' => '200',
		//	'message' => 'ROP Enrollments are successful.',
		//	'result' => System.JSON.serialize(ropEnrollmentList)
		//};
		Set<Id> ropEnrollmentSObjectIdSet = BE8_GlobalUtility.getIdSet('Id', ropEnrollmentSObjectMapByROPNumber.values());
		return ROPEnrollmentService.convertROPEnrollmentSObjectToResponseModel([SELECT Created_By_Crew__c, Reported_By_Crew__c, FlightId__c, FlightId__r.Name, FlightId__r.Flight_External_ID__c, PassengerId__r.First_Name__c, PassengerId__r.PaxKey__c, PassengerId__r.Last_Name__c, PassengerId__r.PNR__c, ROP_Number_F__c, AccountId__c, Area_Code__c, Birthdate__c, Country_Code__c, CreatedById, CreatedDate, Email__c, Enrollment_Date__c, First_Name__c, Gender__c, Id, Integration_Error_Reason__c, Integration_Error__c, IsDeleted, LastActivityDate, LastModifiedById, LastModifiedDate, LastReferencedDate, LastViewedDate, Last_Name__c, MembershipId__c, Name, Nationality__c, OwnerId, PassengerId__c, PaxKey__c, Phone_Number__c, Phone_Type__c, Response_from_THAI__c, ROP_Number__c, Salutation__c, Status__c FROM ROP_Enrollment__c WHERE Id IN : ropEnrollmentSObjectIdSet]);
	}
}