p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_External_Id__c</fullName>
        <description>External ID :Firstname, Lastname, Birthdate, Passport/Travel Number</description>
        <externalId>true</externalId>
        <label>Customer External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailling_Address__c</fullName>
        <label>Mailling Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <label>Travel Document Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Document__c</fullName>
        <label>Travel Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Date__c</fullName>
        <description>Used for input when creating new Flights</description>
        <label>Flight Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <description>Used for display</description>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Date__c</fullName>
        <description>Flight Date local time</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IgnoreProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag used for controlling process builder.
To prevent process builder execute while inserting new PAX.</description>
        <label>IgnoreProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <description>Used for display</description>
        <label>Travel Document Expiry Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Number__c</fullName>
        <description>Used for display</description>
        <label>Travel Document Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WS_KEY__c</fullName>
        <description>Flight number + Flight date + RLOC + First name + Last name</description>
        <externalId>true</externalId>
        <label>WS KEY</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Travel_Document__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account that is the parent of this travel document.</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Documents</relationshipLabel>
        <relationshipName>Travel_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExtDocument__c</fullName>
        <description>External Id :Travel document / Passport number</description>
        <externalId>true</externalId>
        <label>Ext Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <label>Travel Document Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Number__c</fullName>
        <label>Travel Document Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Travel Document</label>
    <nameField>
        <displayFormat>TD-{0000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CreatePassengerFromPaxProcessBuilder.cls
public with sharing class CreatePassengerFromPaxProcessBuilder {
	@InvocableMethod
	public static void createAccountFromPax(List<Passenger__c> paxlist){
		System.debug('DEBUG FROM CLASS');
		Set<Id> paxIsSet = BE8_GlobalUtility.getIdSet('Id', paxlist);
		Map<String, List<SObject>> caseListMap = BE8_GlobalUtility.getSObjectListMap('Passengerid__c', [SELECT Id, Passengerid__c FROM Case WHERE Passengerid__c IN :paxIsSet]);
		Map<String, List<SObject>> caseGroupListMap = BE8_GlobalUtility.getSObjectListMap('Passengerid__c', [SELECT Id, Passengerid__c FROM Case_Group_Member__c WHERE Passengerid__c IN :paxIsSet]);
		Map<String, Account> acclist = new Map<String, Account>();
		Map<String, Travel_Document__c> travellist = new Map<String, Travel_Document__c>();
		List<Passenger__c> newPaxList = new List<Passenger__c>();
		for(Passenger__c pax : paxlist){
			if(pax.IgnoreProcessBuilder__c){
				continue;
			}
			String paxExternalId = pax.FlightId__r.Flight_Number__c + '_' + pax.Flight_Date__c + '_' + pax.First_Name__c + '_' + pax.Last_Name__c + '_' + pax.PNR__c + '_' + pax.FlightId__r.Leg_Number__c;
			String paxDOB = BE8_DateUtility.convertDateFormatToTraditionalFormat(String.valueOf(pax.Date_of_Birth_Input__c).split(' ')[0]);
			Account acc = new Account(
				Name = pax.Last_Name__c + ' ' + pax.First_Name__c,
				First_Name__c = pax.First_Name__c,
				Last_Name__c = pax.Last_Name__c,
				Mailling_Address__c = pax.Email_1__c,
				Date_of_Birth__c = Date.valueOf(pax.Date_of_Birth_Input__c),
				Travel_Document__c = pax.Travel_Document_Number__c,
				Travel_Document_Expiry_Date__c = null,
				Customer_External_Id__c = pax.First_Name__c + '_' + pax.Last_Name__c + '_' + paxDOB + '_' + pax.Travel_Document_Number__c
				);
			Travel_Document__c travel = new Travel_Document__c(
				ExtDocument__c = pax.Travel_Document_Number__c,
				Travel_Document_Number__c = pax.Travel_Document_Number__c
				);
			System.debug('Account: ' + acc);
			acclist.put(paxExternalId, acc);
			travellist.put(paxExternalId, travel);
			newPaxList.add(new Passenger__c(Id = pax.Id, WS_KEY__c = paxExternalId));
			//newPaxList.add(new Passenger__c(Id = pax.Id));
		}
		upsert acclist.values() Customer_External_Id__c;
		List<Case> caseUpdateList = new List<Case>();
		List<Case_Group_Member__c> caseGroupUpdateList = new List<Case_Group_Member__c>();
		for(Passenger__c pax : newPaxList){
			//String ws_key = pax.FlightId__r.Flight_Number__c + '_' + pax.Flight_Date__c + '_' + pax.First_Name__c + '_' + pax.Last_Name__c + '_' + pax.PNR__c + '_' + pax.FlightId__r.Leg_Number__c;
			pax.AccountId__c = acclist.get(pax.WS_KEY__c).Id;
			travellist.get(pax.WS_KEY__c).AccountId__c = acclist.get(pax.WS_KEY__c).Id;
			pax.WS_KEY__c = null;
			System.debug('Account ID: ' + pax.AccountId__c);
			System.debug('PAX: ' + pax);
			List<Case> caseList = (List<Case>)caseListMap.get(pax.Id);
			if(caseList != null){
				for(Case cases : caseList){
					caseUpdateList.add(new Case(Id = cases.Id, AccountId = pax.AccountId__c));
				}	
			}
			List<Case_Group_Member__c> caseGroupList = (List<Case_Group_Member__c>)caseGroupListMap.get(pax.Id);
			if(caseGroupList != null){
				for(Case_Group_Member__c caseGroup : caseGroupList){
					caseGroupUpdateList.add(new Case_Group_Member__c(Id = caseGroup.Id, AccountId__c = pax.AccountId__c));
				}
			}
		}
		upsert travellist.values() ExtDocument__c;
		update newPaxList;
		update caseUpdateList;
		update caseGroupUpdateList;
	}
}