p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the aircraft the position is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booking_Seat__c</fullName>
        <description>The seat that has been booked by the passenger since the reservation was placed</description>
        <label>Booking Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_with_ROP__c</fullName>
        <description>Check if the passenger is ROP member with matching last name and date of birth</description>
        <formula>AND(FFP_Carrier__c == &apos;TG&apos;, AccountId__r.ROP_Number__c != null, AccountId__c != null, AccountId__r.Last_Name__c == Last_Name__c, AccountId__r.Date_of_Birth__c == Date_of_Birth_Input__c)</formula>
        <label>Match with ROP</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTLOPAService.cls
@RestResource(urlMapping = '/lopa/*')
global class MB_RESTLOPAService {
	@HttpGet
	global static List<MB_RestResponseInfoModel.lopaInfo_model> retrieveLOPAInfo() {
		Id currentUserId = UserInfo.getUserId();
		User currentUser = [SELECT Id, Name FROM User WHERE Id = :currentUserId LIMIT 1];
		Crew__c currentCrew = [SELECT Id, Name FROM Crew__c WHERE Id = :BE8_GlobalUtility.getCrewIdByUserId(currentUserId) LIMIT 1];
		List<MB_RestResponseInfoModel.lopaInfo_model> result = new List<MB_RestResponseInfoModel.lopaInfo_model>();
		Set<Id> flightIdSet = BE8_GlobalUtility.getFlightIdSetFromUserId(currentUserId);
		List<Flight__c> flightList = [SELECT Id, AircraftId__c, Flight_External_ID__c, Leg_Number__c FROM Flight__c WHERE Id IN :flightIdSet];

		//Set<Id> flightIdSet = BE8_GlobalUtility.getIdSet('Id', flightList);
		Set<Id> aircrafIdSet = BE8_GlobalUtility.getIdSet('AircraftId__c', flightList);

		Map<String, SObject> attachmentMap = BE8_GlobalUtility.getSObjectMap('ParentId', [SELECT Id, Name, Body, ParentId FROM Attachment WHERE ParentId IN :flightIdSet AND Name LIKE 'Master%']);
		Map<String, SObject> passengerMapByFlightIdAndSeatNumber = BE8_GlobalUtility.getSObjectMap(new Set<String> {'FlightId__c', 'Checkin_Seat__c'}, [SELECT Id, Checkin_Seat__c , Booking_Seat__c, FFP_Tier__c, FFP_Carrier__c, FlightId__c, Cabin_Code__c, AccountId__r.Last_Name__c, AccountId__r.Date_Of_Birth__c, Last_Name__c, Date_of_Birth_Input__c, Match_with_ROP__c FROM Passenger__c WHERE FlightId__c IN :flightIdSet AND Checkin_Seat__c != null]);
		List<String> caseImpactList = new List<String> {BE8_GlobalConstants.IMPACT_BLOCK, BE8_GlobalConstants.IMPACT_MALFUNCTION};
		Set<String> caseStatusNotIncludedSet = new Set<String> {BE8_GlobalConstants.CASE_STATUS_CLOSED, BE8_GlobalConstants.CASE_STATUS_VOID};
		Map<String, List<SObject>> caseMapByAircraftIdAndPosition = BE8_GlobalUtility.getSObjectListMap(new Set<String> {'Aircraft__c', 'Position__c'}, [SELECT Id, Impact__c, Position__c, Aircraft__c FROM Case_Group_Member__c WHERE Aircraft__c IN :aircrafIdSet AND Impact__c IN :caseImpactList AND Position__c != null AND CaseId__r.Status NOT IN :caseStatusNotIncludedSet ORDER BY CreatedDate ASC]);

		Integer lopaSize = 0;
		String lopaFltId = '';
		for (Flight__c flight : flightList) {
			if (attachmentMap.containsKey(flight.Id)) {
				Attachment lopaFile = (Attachment) attachmentMap.get(flight.Id);
				MB_RestResponseInfoModel.lopaInfo_model lopaModel = (MB_RestResponseInfoModel.lopaInfo_model)System.JSON.deserialize(lopaFile.Body.toString(), MB_RestResponseInfoModel.lopaInfo_model.class);
				MB_RestResponseInfoModel.lopaInfo_model lopaModelWithStatus = LOPAService.assignStatusToLOPA(lopaModel, flight, passengerMapByFlightIdAndSeatNumber, caseMapByAircraftIdAndPosition, new InFlightLOPAStatusHandler());
				if (lopaModel != null && lopaModel.lopaPos != null) {
					lopaFltId += lopaModel.fltId + ',';
					lopaSize += lopaModel.lopaPos.size();
				}
				result.add(lopaModelWithStatus);
			}
		}
		Applogger.debug('MB_RESTLOPAService', 'retrieveLOPAInfo', '' + flightIdSet, 'User: ' + currentUser.Id + '-' + currentUser.Name + ' Crew: ' + currentCrew.Name + ' retrieved LOPA size: ' + lopaSize + ' from: ' + lopaFltId, null);
		AppLogger.insertLogs();
		return result;
	}


}