p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Update_Passenger_By_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Passenger By Code</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the aircraft the position is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <label>FFP Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <formula>Passengerid__r.AccountId__r.ROP_Tier__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ROP Tier</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Class__c</fullName>
        <label>Travel Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Seat__c</fullName>
        <formula>IF( Checkin_Seat__c != &quot;&quot;,  Checkin_Seat__c ,  Booking_Seat__c )</formula>
        <label>Seat</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIP_VVIP_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP/VVIP Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/AddCasePassengerListController.cls
/*
  https://be8-sccc.atlassian.net/browse/TGSIC-133 - Custom Page on Case Creation Dialog to add Passenger before Save

  Controller Class of Visualforce page for adding passenger list to case and set case passenger when one of the passenger is the list is marked as
  primary passenger.

    As a ground customer service agent, I shall be able to select multiple passengers that have been affect by an issue and create a case for all of 
    them so that I can efficiently record cases.
    - Must also be able to select multiple Passenger (Visualforce Page)
    - Add search field on the top of the page
    -----------------------------------
    Estimation = 2 MD
*/

public with sharing class AddCasePassengerListController {

    public Case thisCase {get; set;}
    public String thisPassengerIds {get; set;}
    public List<Id> existingPassengerList = new List<Id>();
    public Id primaryPassenger {get; set;}
    public String retURL {get; set;}
    public String topURL {get; set;}

    public AddCasePassengerListController() {
        List<Case> caseList = [Select Passengerid__c, 
                                        Flightid__c, 
                                        Flightid__r.AircraftId__c, 
                                        ParentId, 
                                        AccountId, 
                                        Account.ROP_Tier__c, 
                                        Priority, 
                                        Subject, 
                                        Status, 
                                        Origin 
                                    from Case Where id = :Apexpages.Currentpage().getParameters().get('id')];
        if(caseList!=null && caseList.size()>0) {
            thisCase = caseList.get(0);
            primaryPassenger = thisCase.Passengerid__c;

            List<Case_Group_Member__c> existingCaseMemeberList = [Select Passengerid__c from Case_Group_Member__c where Caseid__c = :thisCase.Id];
            for(Case_Group_Member__c m : existingCaseMemeberList) {
                existingPassengerList.add(m.Passengerid__c);
            }

        }

        retURL = Apexpages.Currentpage().getParameters().get('ret');
        topURL = Apexpages.Currentpage().getParameters().get('top');
    }

    public List<Passenger__c> getPassengerList(){

        if(thisCase==null){return null;}

        List<Passenger__c> passengerList = [Select  id,
                                Name, 
                                PNR__c, 
                                FFP_Number__c, 
                                FFP_Tier__c, 
                                Seat__c, 
                                VIP_VVIP_Flag__c, 
                                Cabin_Code__c 
                       from  Passenger__c 
                       Where FlightId__c = :thisCase.FlightId__c 
                       AND id not in :existingPassengerList
                       Order by Name asc];
          
      return passengerList;
    }

    public List<List<Passenger__c>> getPassengerListList() {
        if(thisCase==null){return null;}
        List<List<Passenger__c>> paxListList = null;

        List<Passenger__c> passengerList = [Select  id,
                                Name, 
                                PNR__c, 
                                FFP_Number__c, 
                                FFP_Tier__c, 
                                Seat__c, 
                                VIP_VVIP_Flag__c, 
                                Cabin_Code__c 
                       from  Passenger__c 
                       Where FlightId__c = :thisCase.FlightId__c 
                       AND id not in :existingPassengerList
                       Order by Name asc];
        if(passengerList != null && !passengerList.isEmpty()) {
            paxListList = new List<List<Passenger__c>>();
            Integer loopcount = 1;
            List<Passenger__c> tempPaxList = new List<Passenger__c>();
            for(Passenger__c pax : passengerList){
                tempPaxList.add(pax);
                if(math.mod(loopcount, 1000) == 0 || loopcount == passengerList.size()) {
                    paxListList.add(tempPaxList);
                    tempPaxList = new List<Passenger__c>();
                }
                loopcount++;
            }
        }

        return paxListList;
    }

    public void addToPassengerList() {

        if(thisCase==null){return;}

        String query = 'Select  id,' +
                            'Name, ' +
                            'AccountId__c, ' +
                            'PNR__c, ' + 
                            'FFP_Number__c, ' + 
                            'FFP_Tier__c, ' +
                            'Seat__c, ' +
                            'VIP_VVIP_Flag__c, ' +
                            'Cabin_Code__c ' +
                   'from  Passenger__c ' + 
                   'Where Id in (\'' + thisPassengerIds.replaceAll(',', '\',\'') + '\') Order by Name asc';
            
        List<Passenger__c> passengerList = Database.query(query);

        List<Case_Group_Member__c> caseMemeberList = new List<Case_Group_Member__c>();

        for(Passenger__c p : passengerList){

            Case_Group_Member__c caseMember = new Case_Group_Member__c();
            
            caseMember.AccountId__c = p.AccountId__c;
            caseMember.Aircraft__c = thisCase.Flightid__r.AircraftId__c;
            caseMember.Caseid__c = thisCase.Id;
            caseMember.FFP_Number__c = p.FFP_Number__c;
            caseMember.FFP_Tier__c = p.FFP_Tier__c;
            caseMember.FlightId__c = thisCase.FlightId__c;
            caseMember.Passengerid__c = p.Id;
            caseMember.PNR__c = p.PNR__c;
            caseMember.Position__c = p.Seat__c;
            caseMember.Travel_Class__c = p.Cabin_Code__c;
            caseMember.VIP__c = p.VIP_VVIP_Flag__c;

            caseMemeberList.add(caseMember);
        }

        insert caseMemeberList;

        if(primaryPassenger==null && (thisCase.Passengerid__c==null || String.valueOf(thisCase.Passengerid__c).length()==0)){
            primaryPassenger = passengerList.size()>0?passengerList.get(0).Id:null;
        }
        
        if(primaryPassenger!=null && String.valueOf(primaryPassenger).length()>0){
            Case updateCase = new Case();
            updateCase.Id = thisCase.Id;
            updateCase.PassengerId__c = primaryPassenger;
            updateCase.Update_Passenger_By_Code__c = true;
            update updateCase;
        }
        
    }

}