p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABW</fullName>
                </value>
                <value>
                    <fullName>AFG</fullName>
                </value>
                <value>
                    <fullName>AGO</fullName>
                </value>
                <value>
                    <fullName>AIA</fullName>
                </value>
                <value>
                    <fullName>ALB</fullName>
                </value>
                <value>
                    <fullName>AND</fullName>
                </value>
                <value>
                    <fullName>ARE</fullName>
                </value>
                <value>
                    <fullName>ARG</fullName>
                </value>
                <value>
                    <fullName>ARM</fullName>
                </value>
                <value>
                    <fullName>ASM</fullName>
                </value>
                <value>
                    <fullName>ATG</fullName>
                </value>
                <value>
                    <fullName>AUS</fullName>
                </value>
                <value>
                    <fullName>AUT</fullName>
                </value>
                <value>
                    <fullName>AZE</fullName>
                </value>
                <value>
                    <fullName>BDI</fullName>
                </value>
                <value>
                    <fullName>BEL</fullName>
                </value>
                <value>
                    <fullName>BEN</fullName>
                </value>
                <value>
                    <fullName>BFA</fullName>
                </value>
                <value>
                    <fullName>BGD</fullName>
                </value>
                <value>
                    <fullName>BGR</fullName>
                </value>
                <value>
                    <fullName>BHR</fullName>
                </value>
                <value>
                    <fullName>BHS</fullName>
                </value>
                <value>
                    <fullName>BIH</fullName>
                </value>
                <value>
                    <fullName>BLR</fullName>
                </value>
                <value>
                    <fullName>BLZ</fullName>
                </value>
                <value>
                    <fullName>BMU</fullName>
                </value>
                <value>
                    <fullName>BOL</fullName>
                </value>
                <value>
                    <fullName>BRA</fullName>
                </value>
                <value>
                    <fullName>BRB</fullName>
                </value>
                <value>
                    <fullName>BRN</fullName>
                </value>
                <value>
                    <fullName>THA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document__c</fullName>
        <label>Travel Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <description>Used for display</description>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <label>Mobile (Clarify)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality for Integration and Ground</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Travel_Document__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account that is the parent of this travel document.</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Documents</relationshipLabel>
        <relationshipName>Travel_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality of the passenger</description>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABW (Aruban)</fullName>
                </value>
                <value>
                    <fullName>AFG (Afghan)</fullName>
                </value>
                <value>
                    <fullName>AGO (Angolan)</fullName>
                </value>
                <value>
                    <fullName>AIA (Anguillan)</fullName>
                </value>
                <value>
                    <fullName>ALB (Albanian)</fullName>
                </value>
                <value>
                    <fullName>AND (Andorran)</fullName>
                </value>
                <value>
                    <fullName>ARE (Emirati)</fullName>
                </value>
                <value>
                    <fullName>ARG (Argentine)</fullName>
                </value>
                <value>
                    <fullName>ARM (Armenian)</fullName>
                </value>
                <value>
                    <fullName>ASM (American Samoan)</fullName>
                </value>
                <value>
                    <fullName>ATG (Antiguans)</fullName>
                </value>
                <value>
                    <fullName>AUS (Australian)</fullName>
                </value>
                <value>
                    <fullName>AUT (Austrian)</fullName>
                </value>
                <value>
                    <fullName>AZE (Azerbaijani)</fullName>
                </value>
                <value>
                    <fullName>BDI (Burundian)</fullName>
                </value>
                <value>
                    <fullName>BEL (Belgian)</fullName>
                </value>
                <value>
                    <fullName>BEN (Beninese)</fullName>
                </value>
                <value>
                    <fullName>BFA (Burkinabe)</fullName>
                </value>
                <value>
                    <fullName>BGD (Bangladeshi)</fullName>
                </value>
                <value>
                    <fullName>BGR (Bulgarian)</fullName>
                </value>
                <value>
                    <fullName>BHR (Bahraini)</fullName>
                </value>
                <value>
                    <fullName>BHS (Bahamian)</fullName>
                </value>
                <value>
                    <fullName>BIH (Bosnian)</fullName>
                </value>
                <value>
                    <fullName>BLR (Belarusian)</fullName>
                </value>
                <value>
                    <fullName>BLZ (Belizean)</fullName>
                </value>
                <value>
                    <fullName>BMU (Bermudian)</fullName>
                </value>
                <value>
                    <fullName>BOL (Bolivian)</fullName>
                </value>
                <value>
                    <fullName>BRA (Brazilian)</fullName>
                </value>
                <value>
                    <fullName>BRB (Barbadian)</fullName>
                </value>
                <value>
                    <fullName>BRN (Bruneian)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Travel Document</label>
    <nameField>
        <displayFormat>TD-{0000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/DCS_Pax_Record_Service_Test.cls
@isTest
private class DCS_Pax_Record_Service_Test {

	@testSetup static void DataPreparation(){
		List<Account> accs = new List<Account>();
    	Account acc1 = Mockup_DCS_Pax.getAccount('1');
    	Account acc2 = Mockup_DCS_Pax.getAccount('2');
    	Account acc3 = Mockup_DCS_Pax.getAccount('3');
    	accs.add(acc1);
    	accs.add(acc2);
    	accs.add(acc3);
    	insert accs;
	}

	/**
										Manage Account
	*/
	
	@isTest static void test_getSFDCAccountMap() {
		Set<String> keySet = new Set<String>{'accountmr_name1_01jan90_12341', 'accountmr_name2_01jan90_12342', 'accountmr_name3_01jan90_12343'};
		Map<String, Account> accMap = DCS_Pax_Record_Service.getSFDCAccountMap(keySet);
		System.assertNotEquals(null, accMap);
		System.assertEquals(3, accMap.size());

		accMap = DCS_Pax_Record_Service.getSFDCAccountMap();
		System.assertNotEquals(null, accMap);
		System.assertEquals(3, accMap.size());
	}
	
	@isTest static void test_querySFDCAccountMap() {
		Set<String> keySet = new Set<String>{'accountmr_name1_01jan90_12341', 'accountmr_name2_01jan90_12342', 'accountmr_name3_01jan90_12343'};
		DCS_Pax_Record_Service.querySFDCAccountMap(keySet);
		Map<String, Account> accMap = DCS_Pax_Record_Service.sfdcAccountMap;
		System.assertNotEquals(null, accMap);
		System.assertEquals(3, accMap.size());
	}
	
	@isTest static void test_isContainsAllKey() {
		Set<String> keySet = new Set<String>{'accountmr_name1_01jan90_12341', 'accountmr_name2_01jan90_12342', 'accountmr_name3_01jan90_12343'};
		Map<String, Account> accMap = DCS_Pax_Record_Service.getSFDCAccountMap(keySet);
		Boolean isContainsAllKey = DCS_Pax_Record_Service.isContainsAllKey(accMap, keySet);
		System.assertEquals(true, isContainsAllKey);
	}
	
	@isTest static void test_concreteAccount() {
		
	}

	@isTest static void test_isReadyForCreateAccount() {
		Boolean isReadyForCreateAccount = DCS_Pax_Record_Service.isReadyForCreateAccount(Mockup_DCS_Pax.getPassenger('1'));
		System.assertEquals(true, isReadyForCreateAccount);
	}
	
	@isTest static void test_createAccountFromPax() {
		Passenger__c pax = Mockup_DCS_Pax.getPassenger('1');
		Account acc1 = DCS_Pax_Record_Service.createAccountFromPax(pax, true);
		System.assertEquals('Passenger', acc1.First_Name__c);
		System.assertEquals('name1', acc1.Last_Name__c);
		System.assertEquals('Male', acc1.Gender__c);
		System.assertEquals('Mr', acc1.Salutation__c);
		System.assertEquals('email@gmail.com', acc1.Email_1__c);
		System.assertEquals('+66900909999', acc1.Mobile__c);
		System.assertEquals('12341', acc1.Travel_Document__c);
		System.assertEquals('THA', acc1.Nationality__c);
		System.assertEquals(Date.valueOf('1990-01-01'), acc1.Date_of_Birth__c);

		insert acc1;
		insert pax;
		
		BE8_SoqlBuilder soqlBuilder = new BE8_SoqlBuilder('Passenger__c');
		soqlBuilder.addField('AccountId__c');
		soqlBuilder.addCondition('Id', pax.Id);
		soqlBuilder.setLimit(1);
		pax = Database.query(soqlBuilder.getQueryStr());

		System.assertEquals(pax.AccountId__c, acc1.Id);
	}

	@isTest static void test_getCustomerExternalIdTrimFromAccount() {
		Passenger__c pax = Mockup_DCS_Pax.getPassenger('1');
		Set<String> customerExternalIds = DCS_Pax_Record_Service.getCustomerExternalIdTrimFromAccount(new List<Passenger__c>{pax});

		System.assertNotEquals(null, customerExternalIds);
		System.assertEquals(1, customerExternalIds.size());
		System.assertEquals('passengermr_name1_01jan90_12341', new List<String>(customerExternalIds).get(0));
	}

	/**
										Manage Membership
	*/
	
	@isTest static void test_concreteMembership() {
		Account acc1 = Mockup_DCS_Pax.getAccount('1');
		insert acc1;
		Passenger__c pax1 = Mockup_DCS_Pax.getPassenger('1');
		pax1.AccountId__c = acc1.Id;

		
	}

	@isTest static void test_getPaxMapToCreateMembership() {
		
	}
	
	@isTest static void test_createMembershipFromPax() {
		
	}

    /**
										Manage Travel Document
    */

	@isTest static void test_concreteTravelDoc() {
		
	}

	@isTest static void test_getPaxListToCreateTravelDoc() {
		
	}
	
	@isTest static void test_createTravelDocumentFromPax() {
		
	}

	/**
										Manage Passenger
	*/

	@isTest static void test_getFlight() {
		
	}

	@isTest static void test_updatePaxInfoCheckbox() {
		
	}
	
	@isTest static void test_updatePaxPersonalInfo() {
		
	}

	@isTest static void test_updatePaxSeatInfo() {
		
	}

	@isTest static void test_updatePaxFlightInfo() {
		
	}

	@isTest static void test_updatePaxWSKey() {
		
	}
	
	@isTest static void test_getPaxConnectingFlight() {
		
	}

	@isTest static void test_getPaxTicketInfo() {
		
	}

	@isTest static void test_SSRPaxTravelDoc() {
		
	}

	@isTest static void test_SSRPaxFQTV() {
		
	}

	@isTest static void test_SSRPaxEmail() {
		
	}

	@isTest static void test_SSRPaxPhone() {
		
	}

	@isTest static void test_SSRPaxSpecialMeal() {
		
	}

	@isTest static void test_SSRPaxVipVVip() {
		
	}

	@isTest static void test_SSRPaxInfant() {
		
	}

	@isTest static void test_SSROthers() {
		
	}
}