p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <externalId>true</externalId>
        <label>ROP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <label>ROP Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booking_Seat__c</fullName>
        <description>The seat that has been booked by the passenger since the reservation was placed</description>
        <label>Booking Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_with_ROP__c</fullName>
        <description>Check if the passenger is ROP member with matching last name and date of birth</description>
        <formula>AND(FFP_Carrier__c == &apos;TG&apos;, AccountId__r.ROP_Number__c != null, AccountId__c != null, AccountId__r.Last_Name__c == Last_Name__c, AccountId__r.Date_of_Birth__c == Date_of_Birth_Input__c)</formula>
        <label>Match with ROP</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/InFlightLOPAStatusHandlerTest.cls
@isTest
private class InFlightLOPAStatusHandlerTest {
	private static String LAST_NAME = 'TEST';

	@testSetup static void setUp() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
	}

	private static void testAndAssert(String ffpTier, String expectedStatus) {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Account account = new Account(Name = LAST_NAME, Last_Name__c = LAST_NAME, Date_Of_Birth__c = Date.today(), ROP_Number__c = '234234234');
		insert account;
		Passenger__c passenger = new Passenger__c(Last_Name__c = LAST_NAME, Date_Of_Birth_Input__c = Date.today(), AccountId__c = account.Id, Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = ffpTier);
		insert passenger;
		passenger = [SELECT Id, Checkin_Seat__c , Booking_Seat__c, FFP_Tier__c, FFP_Carrier__c, FlightId__c, Cabin_Code__c, AccountId__r.Last_Name__c, AccountId__r.Date_Of_Birth__c, Last_Name__c, Date_of_Birth_Input__c, Match_with_ROP__c FROM Passenger__c WHERE Id = :passenger.Id];
		//Assert.assert(passenger.Match_with_ROP__c);
		String status = new InFlightLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, null, lopaPos);
		Assert.assertEquals(expectedStatus, status);
	}

	private static void testAndAssert(String ffpTier, String expectedStatus, String impact, Boolean hasPassenger) {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Account account = new Account(Name = LAST_NAME, Last_Name__c = LAST_NAME, Date_Of_Birth__c = Date.today(), ROP_Number__c = 'asdasddsa');
		insert account;
		Passenger__c passenger;
		if(hasPassenger){
			passenger = new Passenger__c(Last_Name__c = LAST_NAME, Date_Of_Birth_Input__c = Date.today(), AccountId__c = account.Id, Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = ffpTier);
			insert passenger;
			passenger = [SELECT Id, Checkin_Seat__c , Booking_Seat__c, FFP_Tier__c, FFP_Carrier__c, FlightId__c, Cabin_Code__c, AccountId__r.Last_Name__c, AccountId__r.Date_Of_Birth__c, Last_Name__c, Date_of_Birth_Input__c, Match_with_ROP__c FROM Passenger__c WHERE Id = :passenger.Id];
		}
		//Assert.assert(passenger.Match_with_ROP__c);
		Case maintenanceCase = new Case();
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = impact);

		String status = new InFlightLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(expectedStatus, status);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedFromLOPA() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', 'Z');
		String status = new InFlightLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.LOPA_STATUS_BLOCKED_FROM_LOPA, status);
	}

	@isTest static void testGetLOPAPositionStatus_Available() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		String status = new InFlightLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.LOPA_STATUS_AVAILABLE, status);
	}

	@isTest static void testGetLOPAPositionStatus_Occupied() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A');
		String status = new InFlightLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.LOPA_STATUS_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_Blocked() {
		testAndAssert(null, BE8_GlobalConstants.LOPA_STATUS_BLOCK, BE8_GlobalConstants.IMPACT_BLOCK, false);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedOccupied() {
		testAndAssert(null, BE8_GlobalConstants.LOPA_STATUS_BLOCK_OCCUPIED, BE8_GlobalConstants.IMPACT_BLOCK, true);
	}

	@isTest static void testGetLOPAPositionStatus_Malfunction() {
		testAndAssert(null, BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION, BE8_GlobalConstants.IMPACT_MALFUNCTION, false);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionOccupied() {
		testAndAssert(null, BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_OCCUPIED, BE8_GlobalConstants.IMPACT_MALFUNCTION, true);
	}

	@isTest static void testGetLOPAPositionStatus_OccupiedPlatinum() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_PLATINUM, BE8_GlobalConstants.LOPA_STATUS_OCCUPIED_PLATINUM);
		//testAndAssert(BE8_GlobalConstants.FFP_TIER_PLATINUM, BE8_GlobalConstants.LOPA_STATUS_OCCUPIED_PLATINUM, BE8_GlobalConstants.IMPACT_MALFUNCTION, true);
	}

	@isTest static void testGetLOPAPositionStatus_OccupiedGold() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_GOLD, BE8_GlobalConstants.LOPA_STATUS_OCCUPIED_GOLD);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedPlatinum() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_PLATINUM, BE8_GlobalConstants.LOPA_STATUS_BLOCK_PLATINUM, BE8_GlobalConstants.IMPACT_BLOCK, true);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedGold() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_GOLD, BE8_GlobalConstants.LOPA_STATUS_BLOCK_GOLD, BE8_GlobalConstants.IMPACT_BLOCK, true);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionPlatinum() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_PLATINUM, BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_PLATINUM, BE8_GlobalConstants.IMPACT_MALFUNCTION, true);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionGold() {
		testAndAssert(BE8_GlobalConstants.FFP_TIER_GOLD, BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_GOLD, BE8_GlobalConstants.IMPACT_MALFUNCTION, true);
	}
}