p2ws_package/Devpp2ws-Package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROP_Tier__c</fullName>
        <label>ROP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Used for display</description>
        <label>Travel Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IgnoreProcessBuilder__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A flag used for controlling process builder.
To prevent process builder execute while inserting new PAX.</description>
        <label>IgnoreProcessBuilder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSR_Service__c</fullName>
        <label>Service</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Number__c</fullName>
        <description>Used for display</description>
        <label>Travel Document Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CreatePassengerFromPaxPB_Test.cls
@isTest
private class CreatePassengerFromPaxPB_Test {
	
	@isTest static void testCreateAccountFromPax() {

		MockupData_Test.initializeSystemConfigurationCustomSetting();

		String firstName = 'First Name';
    	String lastName = 'Last Name';

    	Account a = new Account();
    	a.Name = firstName + ' ' + lastName;
    	a.First_Name__c = firstName;
    	a.Last_Name__c = lastName;
    	a.ROP_Tier__c = 'Gold';
    	insert a;

    	Flight__c f = new Flight__c();
    	f.Name = 'TG 1234';
    	insert f;

        Flight__c fdummy = new Flight__c();
        fdummy.Name = 'TGXXX';
        insert fdummy;

    	Passenger__c p = new Passenger__c();
        p.SSR_Service__c = '';
        p.First_Name__c = firstName;
        p.Last_Name__c = lastName;
        p.FlightId__c = f.Id;
        p.AccountId__c = a.Id;
        p.Class__c = 'C';
        p.Travel_Document_Number__c = '1234asdf';
        p.Date_of_Birth_Input__c = Date.today();
        insert p;

        Passenger__c p2 = new Passenger__c();
        p2.SSR_Service__c = '';
        p2.First_Name__c = firstName;
        p2.Last_Name__c = lastName;
        p2.FlightId__c = f.Id;
        p2.AccountId__c = a.Id;
        p2.Class__c = 'C';
        p2.Travel_Document_Number__c = '5678asdf';
        p2.IgnoreProcessBuilder__c = true;
        p2.Date_of_Birth_Input__c = Date.today();
        insert p2;

        Case thisCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
	    thisCase.Flightid__c = f.Id;
	    thisCase.PassengerId__c = p.Id;
	    insert thisCase;

	    List<Passenger__c> pList = new List<Passenger__c>{p,p2};

	    Test.startTest();
	    CreatePassengerFromPaxProcessBuilder.createAccountFromPax(pList);
	    Test.stopTest();

        List<Account> accList = [select id from Account];
        Assert.assertEquals(2, accList.size());
	}
	
}