p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Main_Type__c</fullName>
        <label>Aircraft Main Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Aircraft_Registration__c</fullName>
        <externalId>true</externalId>
        <label>Aircraft Registration</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Aircraft_Station__mdt.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Station</label>
    <pluralLabel>Aircraft Stations</pluralLabel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departed__c</fullName>
        <description>STD_UTC_DateTime__c &lt; NOW()</description>
        <formula>Departure_Time_UTC__c  &lt; NOW()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Departed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STA__c</fullName>
        <description>Used for display</description>
        <formula>IF(LEFT(SUBSTITUTE(LEFT(RIGHT( STA_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;),1) = &quot;0&quot;, MID
(
SUBSTITUTE(LEFT(RIGHT( STA_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;), 2, 
LEN(SUBSTITUTE(LEFT(RIGHT( STA_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;)
)
), SUBSTITUTE(LEFT(RIGHT( STA_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;))</formula>
        <label>STA</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD__c</fullName>
        <description>Used for display</description>
        <formula>IF(LEFT(SUBSTITUTE(LEFT(RIGHT( STD_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;),1) = &quot;0&quot;, MID
(
SUBSTITUTE(LEFT(RIGHT( STD_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;), 2, 
LEN(SUBSTITUTE(LEFT(RIGHT( STD_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;)
)
), SUBSTITUTE(LEFT(RIGHT( STD_LT__c , 8), 5), &quot;:&quot;, &quot;.&quot;))</formula>
        <label>STD</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/FlightScheduleController.cls
global with sharing class FlightScheduleController {
	public String acTypeListJSON {get; set;}
	public String acRegListJSON {get; set;}
	//global class FlightView{
	//	String name;
	//	String std;
	//	String sta;
	//	Decimal legNumber;
	//	String departureStation;
	//	String arrivalStation;
	//	Boolean departed;

	//	public FlightView(Flight__c flight){
	//		name = flight.Name;
	//		std = '' + flight.STD__c;
	//		sta = '' + flight.STA__c;
	//		legNumber = flight.Leg_Number__c;
	//		departureStation = flight.Departure_STN__c;
	//		arrivalStation = flight.Arrival_STN__c;
	//		departed = flight.Departed__c;
	//	}
	//}

	public String stationPickList {get{
			List<Aircraft_Station__mdt> stationList = [SELECT Id, Full_Name__c, Code__c FROM Aircraft_Station__mdt];
			return System.JSON.serialize(stationList);
		}
		set;
	}

	public FlightScheduleController(ApexPages.StandardController controller) {
		List<AggregateResult> acTypeAircraftList = [SELECT Aircraft_Main_Type__c FROM Aircraft__c GROUP BY Aircraft_Main_Type__c];
		List<Map<String, String>> acTypeList = new List<Map<String, String>>();
		for (AggregateResult each : acTypeAircraftList) {
			acTypeList.add(new Map<String, String> { 'id' => (String) each.get('Aircraft_Main_Type__c'), 'text' => (String) each.get('Aircraft_Main_Type__c')});
		}
		acTypeListJSON = System.JSON.serialize(acTypeList);

		List<AggregateResult> acRegAircraftList = [SELECT Aircraft_Registration__c, Aircraft_Main_Type__c FROM Aircraft__c GROUP BY Aircraft_Registration__c, Aircraft_Main_Type__c];
		List<Map<String, String>> acRegList = new List<Map<String, String>>();
		for (AggregateResult each : acRegAircraftList) {
			acRegList.add(new Map<String, String> { 'id' => (String) each.get('Aircraft_Registration__c'), 'text' => (String) each.get('Aircraft_Registration__c'), 'acType' => (String) each.get('Aircraft_Main_Type__c')});
		}
		acRegListJSON = System.JSON.serialize(acRegList);
	}

	@RemoteAction
	global static List<FlightScheduleService.FlightScheduleRecord> getSchedule(Integer startTimeOffset, Integer endTimeOffset, DateTime currentTime, String currentStation) {
		List<FlightScheduleService.FlightScheduleRecord> aircraftList = FlightScheduleService.getSchedule(startTimeOffset, endTimeOffset, currentTime, currentStation);
		return aircraftList;
	}

}