p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the aircraft the position is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>A_C_Reg__c</fullName>
        <label>A/C Reg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Seat__c</fullName>
        <description>The seat that has been booked by the passenger since the reservation was placed</description>
        <label>Booking Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTLOPADetailService.cls
@RestResource(urlMapping = '/lopa/detail/*')
global class MB_RESTLOPADetailService {

	global class lopaPos {
		public String pos;
		public String fltId;
		public String acReg;
		public String tclass;
		public String sts;
	}

	@HttpPost
	global static List<lopaPos> getLOPADetail(List<String> flightIdList) {
		List<lopaPos> result = new List<lopaPos>();

		Map<Id, Flight__c> flightMap = new Map<Id, Flight__c>([SELECT Id, A_C_Reg__c, AircraftId__r.Name, Flight_External_ID__c, Leg_Number__c FROM Flight__c WHERE Id IN :flightIdList]);
		Set<Id> aircrafIdSet = BE8_GlobalUtility.getIdSet('AircraftId__c', flightMap.values());
		Map<String, SObject> passengerMapByFlightIdAndSeatNumber = BE8_GlobalUtility.getSObjectMap(new Set<String> {'FlightId__c', 'Checkin_Seat__c'}, [SELECT Id, Checkin_Seat__c , Booking_Seat__c, FFP_Tier__c, FFP_Carrier__c, FlightId__c, Cabin_Code__c FROM Passenger__c WHERE FlightId__c IN :flightIdList AND Checkin_Seat__c != null]);
		Set<String> caseStatusNotIncludedSet = new Set<String> {BE8_GlobalConstants.CASE_STATUS_CLOSED, BE8_GlobalConstants.CASE_STATUS_VOID};
		Map<String, List<SObject>> caseMapByAircraftIdAndPosition = BE8_GlobalUtility.getSObjectListMap(new Set<String> {'Aircraft__c', 'Position__c'}, [SELECT Id, Impact__c, Position__c, Aircraft__c FROM Case_Group_Member__c WHERE Aircraft__c IN :aircrafIdSet AND Position__c != null AND CaseId__r.Status NOT IN :caseStatusNotIncludedSet ORDER BY CreatedDate ASC]);

		for (Attachment lopaFile : [SELECT Id, Body, ParentId FROM Attachment WHERE Name = 'Master_LOPA.txt' AND ParentId IN :flightIdList]) {
			Flight__c flight = flightMap.get(lopaFile.ParentId);
			System.debug(lopaFile.ParentId);
			flightMap.remove(lopaFile.ParentId);
			processLOPAAttachment(result, lopaFile, flight, passengerMapByFlightIdAndSeatNumber, caseMapByAircraftIdAndPosition);
		}

		if (flightMap.size() > 0) {
			Set<Id> aircraftIdSet = BE8_GlobalUtility.getIdSet('AircraftId__c', flightMap.values());
			Map<String, List<SObject>> flightMapByAircraftId = BE8_GlobalUtility.getSObjectListMap('AircraftId__c', flightMap.values());
			for (Attachment lopaFile : [SELECT Id, Body, ParentId FROM Attachment WHERE Name = 'Master_LOPA.txt' AND ParentId IN :aircraftIdSet]) {
				System.debug('aircraftId: ' + lopaFile.ParentId);
				if (flightMapByAircraftId.containsKey(lopaFile.ParentId)) {
					List<Flight__c> flightList = (List<Flight__c>) flightMapByAircraftId.get(lopaFile.ParentId);
					System.debug('flightList: ' + flightList);
					for(Flight__c flight : flightList){
						System.debug('flight: ' + flight);
						processLOPAAttachment(result, lopaFile, flight, passengerMapByFlightIdAndSeatNumber, caseMapByAircraftIdAndPosition);
					}
				}
			}
		}

		return result;
	}

	private static void processLOPAAttachment(List<lopaPos> result, Attachment lopaFile, Flight__c flight, Map<String, SObject> passengerMapByFlightIdAndSeatNumber, Map<String, List<SObject>> caseMapByAircraftIdAndPosition) {
		MB_RestResponseInfoModel.lopaInfo_model lopaModel = (MB_RestResponseInfoModel.lopaInfo_model)System.JSON.deserialize(lopaFile.Body.toString(), MB_RestResponseInfoModel.lopaInfo_model.class);
		MB_RestResponseInfoModel.lopaInfo_model lopaModelWithStatus = LOPAService.assignStatusToLOPA(lopaModel, flight, passengerMapByFlightIdAndSeatNumber, caseMapByAircraftIdAndPosition, new MaintenanceLOPAStatusHandler());

		if (lopaModelWithStatus.lopaPos != null) {
			for (MB_RestResponseInfoModel.lopaInfo_lopaPos each : lopaModelWithStatus.lopaPos) {
				//System.debug(each.pos + ' ' + each.sts);
				if (each.sts != BE8_GlobalConstants.LOPA_STATUS_OCCUPIED) {
					lopaPos pos = new lopaPos();
					pos.pos = each.pos;
					pos.fltId = flight.Id;
					pos.acReg = flight.AircraftId__r.Name;
					pos.tclass = each.tclass;
					pos.sts = each.sts;
					result.add(pos);
				}
			}
		}
	}
}