p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Registration__c</fullName>
        <externalId>true</externalId>
        <label>Aircraft Registration</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Application_Log__c.object
<CustomObject>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Displays the booking class of the Passenger that is related to the Case</description>
        <formula>Passengerid__r.Booking_Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Booking Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_By_Crew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Created By Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Crew)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Json_Body__c</fullName>
        <description>Source</description>
        <label>Json Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reported_By_Crew__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Reported By Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Reported By Crew)</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Crew_First_Name__c</fullName>
        <description>First name of the crew.</description>
        <label>Crew First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Crew_Last_Name__c</fullName>
        <description>Last name of the crew.</description>
        <label>Crew Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crew_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Crew External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Crew_Temp__c</fullName>
        <label>Crew Temp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Source__c</fullName>
        <label>Integration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block_Time__c</fullName>
        <description>Displays actual flying time in units of minutes</description>
        <label>Block Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Source__c</fullName>
        <label>Integration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STA_LT__c</fullName>
        <label>STA LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Depend_On_Object__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to parent data level 1</description>
        <label>Depend On Object</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Depend_On_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>Define type of data</description>
        <externalId>true</externalId>
        <label>Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Flight Number</description>
        <label>Flight Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Map</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Booking class of the passenger which could be any value from A-Z depending on the ticket and the reservation of the passenger</description>
        <label>Booking Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Used for verifying result of PaxFlowDetail_Batch</description>
        <formula>FlightId__r.Flight_Date_UTC_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Date UTC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CSE_SOAPCabinReport_WS_Test.cls
@isTest
public with sharing class CSE_SOAPCabinReport_WS_Test {

	@testSetup static void MockData(){
		MockupData_Test.initializeWebServiceCustomSetting();
		MockupData_Test.initialApplicationLogCustomSetting();
		MockupData_Test.initializeSystemConfigurationCustomSetting();
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CREW_LIST_TRIGGER, false);
		List<Flight__c> flightList = new List<Flight__c>();
		List<Passenger__c> paxList = new List<Passenger__c>();
		List<Crew_List__c> crewlistList = new List<Crew_List__c>();
		List<Crew__c> cList = new List<Crew__c>();
		List<Case> caseList = new List<Case>();
		List<Master_Map__c> mastermapList = new List<Master_Map__c>();
		Aircraft__c air = new Aircraft__c(Aircraft_Registration__c = 'HS-TBA', Name = 'HS-TBA');
		insert air;

		Flight__c flight1 = new Flight__c(
			Name = '0628',
		    Flight_Number__c = 'TG0628',
		    Flight_Date_UTC__c = '20Dec25',
		    Flight_Date_LT__c = '20Dec25',
		    Departure_STN__c  = 'BKK',
		    Arrival_STN__c = '',
		    STD_UTC__c = '20Dec25 0330',
		    STD_LT__c  = '20Dec25 1030',
		    STA_UTC__c = '20Dec25 0620',
		    STA_LT__c = '20Dec25 1420',
		    Block_Time__c = '170',
		    Integration_Source__c = '1',
		    Leg_Number__c = 1,
		    Flight_External_ID__c = 'TG0628_20Dec25_1',
		    AircraftId__c = air.Id
		);
		flightList.add(flight1);
		insert flightList;

		Passenger__c pax1 = new Passenger__c(
			Name = 'Pax Mockja',
			Booking_Class__c = 'W',
			Cabin_Code__c = 'F',
			First_Name__c = 'Mockja',
			Last_Name__c = 'Pax',
			Checkin_Seat__c = '12A',
			FlightId__c = flight1.Id
		);
		paxList.add(pax1);

		Crew__c c1 = new Crew__c(Crew_First_Name__c = 'Kung', Crew_Last_Name__c = 'Earth', Personel_Id__c = '12345');
		Crew__c c2 = new Crew__c(Crew_First_Name__c = 'Khun', Crew_Last_Name__c = 'Sawan', Personel_Id__c = '54321');
		cList.add(c1);
		cList.add(c2);

		insert cList;

		Crew_List__c crew1 = new Crew_List__c(
			Name = 'Kung Earth',
			Crew_Temp__c = '12345',
			Crew_External_ID__c = '12345_TG0628_20Dec25_1',
			FlightId__c = flight1.Id,
			CrewId__c = c1.Id
		);
		crewlistList.add(crew1);

		Crew_List__c crew2 = new Crew_List__c(
			Name = 'Khun Sawan',
			Crew_Temp__c = '54321',
			Crew_External_ID__c = '54321_TG0628_20Dec25_1',
			FlightId__c = flight1.Id,
			CrewId__c = c2.Id
		);
		crewlistList.add(crew2);

		Master_Map__c eq1 = new Master_Map__c(
			Name = 'ELECTRICAL & PNEUMATIC HEADPHONE', 
			Field_Name__c = 'SERVICE EQUIPMENT');
		mastermapList.add(eq1);

		Master_Map__c eq2 = new Master_Map__c(
			Name = 'HEADPHONE BODY',
			Field_Name__c = 'PART',
			Depend_On_Object__c = eq1.Id);
		mastermapList.add(eq2);

		insert crewlistList;
		insert paxList;
		insert mastermapList;

		List<Crew__c> crewList = [SELECT Id FROM Crew__c];
		System.debug('JK: crew - ' + JSON.serialize(crewList));

		List<MB_RESTRequestInfoModel.incident_model> incidentModelList = MockupData_Test.getIncidentModelList(1, flight1.Id, crew1.Id, eq1.Id, eq2.Id, 2);

		Case case1 = new Case(
			Json_Body__c = JSON.serialize(incidentModelList.get(0)), 
			Status = 'OPEN'
		);
		case1.FlightId__c = flight1.Id;
		case1.PassengerId__c = pax1.Id;
		case1.Created_By_Crew__c = crewList.get(0).Id;
		case1.Reported_By_Crew__c = crewList.get(1).Id;
		caseList.add(case1);
		insert caseList;
		System.debug('JK: case - ' + JSON.serialize(caseList));
	}

	@isTest static void testSendCabinReportToThai(){
		Test.setMock(HttpCalloutMock.class, new MockCabinReportWSResponseGenerator());
		Set<Id> caseIdSet = BE8_GlobalUtility.getIdSet('Id', [SELECT Id FROM Case]);
		Test.startTest();
		Map<String, CSE_SOAPCabinReport_WS.tgIDMap> responseMap = CSE_SOAPCabinReport_WS.sendCabinReportToThai(caseIdSet, null);
		Test.stopTest();
		System.debug('JK: testSendCabinReportToThai - ' + JSON.serialize(responseMap));
        Map<String, CSE_SOAPCabinReport_WS.tgIDMap> returnMap = CSE_SOAPCabinReport_WS.sendCabinReportToThai(caseIdSet, null);
        List<CSE_SOAPCabinReport_WS.tgIDMap> tgidMapList = new List<CSE_SOAPCabinReport_WS.tgIDMap>();
        for (CSE_SOAPCabinReport_WS.tgIDMap tgid : returnMap.values()) {
           tgidMapList.add(tgid);
        }
        CSE_SOAPCabinReport_WS.logMessage(tgidMapList);
        List<Application_Log__c> applogList = [SELECT Id, Name FROM Application_Log__c];
        System.debug('JK: logMessage - ' + JSON.serialize(tgidMapList));
		System.assertNotEquals(null, applogList, 'app log should not be null');
	}

	@isTest static void testSendCabinReportToThai_NullCaseIsSet(){
		Test.setMock(HttpCalloutMock.class, new MockCabinReportWSResponseGenerator());
		Set<Id> caseIdSet = null;
		Test.startTest();
		Map<String, CSE_SOAPCabinReport_WS.tgIDMap> responseMap = CSE_SOAPCabinReport_WS.sendCabinReportToThai(caseIdSet, null);
		Test.stopTest();
		System.debug('JK: testSendCabinReportToThai_NullCaseIsSet - ' + JSON.serialize(responseMap));
        Map<String, CSE_SOAPCabinReport_WS.tgIDMap> returnMap = CSE_SOAPCabinReport_WS.sendCabinReportToThai(caseIdSet, null);
        List<CSE_SOAPCabinReport_WS.tgIDMap> tgidMapList = new List<CSE_SOAPCabinReport_WS.tgIDMap>();
        for (CSE_SOAPCabinReport_WS.tgIDMap tgid : returnMap.values()) {
           tgidMapList.add(tgid);
        }
        CSE_SOAPCabinReport_WS.logMessage(tgidMapList);
        List<Application_Log__c> applogList = [SELECT Id, Name FROM Application_Log__c];
        System.assertNotEquals(null, applogList, 'app log should not be null');
	}
	
	@isTest static void testUpsertCabinReport_ResponseContainsTGID_ReturnCorrectResponseModel() {
		MockupData_Test.initializeWebServiceCustomSetting();
		Test.setMock(HttpCalloutMock.class, new MockCabinReportWSResponseGenerator());
		Test.startTest();
		CSE_SOAPCabinReport_WS.CabinReportModel c = new CSE_SOAPCabinReport_WS.CabinReportModel();
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = new CSE_SOAPCabinReport_WS().upsertCabinReport(c);
		Test.stopTest();
		CSE_SOAPCabinReport_WS.logMessage(new List<CSE_SOAPCabinReport_WS.CabinReportResponseModel>{m});
		List<Application_Log__c> applogList = [SELECT Id, Name FROM Application_Log__c];
		System.assertNotEquals(null, applogList, 'app log should not be null');
		System.assertEquals('T00061/2016', m.tgID);
		System.assertEquals(true, m.status);
	}

	@isTest static void testUpsertCabinReport_ResponseContainsTGID_NullParameter() {
		MockupData_Test.initializeWebServiceCustomSetting();
		Test.setMock(HttpCalloutMock.class, new MockCabinReportWSResponseGenerator());
		Test.startTest();
		CSE_SOAPCabinReport_WS.CabinReportModel c = new CSE_SOAPCabinReport_WS.CabinReportModel();
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = new CSE_SOAPCabinReport_WS().upsertCabinReport(null);
		Test.stopTest();
		CSE_SOAPCabinReport_WS.logMessage(new List<CSE_SOAPCabinReport_WS.CabinReportResponseModel>{m});
		List<Application_Log__c> applogList = [SELECT Id, Name FROM Application_Log__c];
		System.assertNotEquals(null, applogList, 'app log should not be null');
		System.assertEquals(false, m.status);
	}

	@isTest static void testGetResponseModel_XMLContainsTGID_ReturnValidData(){
		String xml = '' +
			'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
				'<soapenv:Body>' +
					'<ns2:InsertCabinReportResponse xmlns:ns2="http://bean.crmsinterface.cw.tg/">' +
  						'<return>T00061/2016</return>' +
					'</ns2:InsertCabinReportResponse>' +
  				'</soapenv:Body>' +
  			'</soapenv:Envelope>';
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = CSE_SOAPCabinReport_WS.getResponseModel(xml, '');
		System.assertEquals('T00061/2016', m.tgID);
		System.assertEquals(true, m.status);
	}

	@isTest static void testGetResponseModel_XMLContainsException_ReturnErrorData(){
		String xml = '' +
			'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
				'<soapenv:Body>' +
					'<soapenv:Fault>' +
  						'<faultcode>soapenv:Server</faultcode>' +
  						'<faultstring>Flight No Error format</faultstring>' +
						'<detail>' +
							'<ns2:Exception xmlns:ns2="http://bean.crmsinterface.cw.tg/">' +
  								'<message>Flight No Error format</message>' +
  							'</ns2:Exception>' +
  						'</detail>' +
  					'</soapenv:Fault>' +
  				'</soapenv:Body>' +
  			'</soapenv:Envelope>';
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = CSE_SOAPCabinReport_WS.getResponseModel(xml, '');
		System.assertEquals('Flight No Error format', m.errorMessage);
		System.assertEquals(false, m.status);
	}

	@isTest static void testGetResponseModel_XMLContainsException_ReturnErrorData_InvalidDescription(){
		String xml = '' +
			'<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">' +
				'<soapenv:Body>' +
					'<soapenv:Fault>' +
  						'<faultcode>soapenv:Server</faultcode>' +
  						'<faultstring>Flight No Error format</faultstring>' +
						'<detail>' +
  						'</detail>' +
  					'</soapenv:Fault>' +
  				'</soapenv:Body>' +
  			'</soapenv:Envelope>';
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = CSE_SOAPCabinReport_WS.getResponseModel(xml, '');
		System.assertEquals('Error data has return invalid description.', m.errorMessage);
		System.assertEquals(false, m.status);
	}

	@isTest static void testGetResponseModel_XMLContainsException_ReturnErrorData_ResponseNull(){
		String xml = null;
		CSE_SOAPCabinReport_WS.CabinReportResponseModel m = CSE_SOAPCabinReport_WS.getResponseModel(xml, '');
		System.assertEquals('Error no data response', m.errorMessage);
		System.assertEquals(false, m.status);
	}
}