p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_REG_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Aircraft the Case is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Crew)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the aircraft the position is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Mappings</relationshipLabel>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Crew Mapping</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Crew Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTLOPAServiceTest.cls
@isTest
private class MB_RESTLOPAServiceTest {

	@testSetup static void setUp() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
	}

	@isTest static void testRetrieveLOPAInfo() {
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CREW_LIST_TRIGGER, false);
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_TRIGGER, false);
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_GROUP_MEMBER_TRIGGER, false);

		Aircraft__c aircraft = new Aircraft__c(Name = 'TEST');
		insert aircraft;
		Flight__c flight = MockupData_Test.getMockUpFlight();
		flight.STD_UTC__c = String.valueOf(DateTime.now());
		flight.STA_UTC__c = String.valueOf(DateTime.now().addHours(10));
		flight.AircraftId__c = aircraft.Id;
		insert flight;
		Crew__c airPurser = new Crew__c(Personel_Id__c = 'AP');
		Crew__c airHostage = new Crew__c(Personel_Id__c = 'AH');
		insert new List<Crew__c> {airPurser, airHostage};
		Crew_List__c crewList = new Crew_List__c(CrewId__c = airPurser.Id, FlightId__c = flight.Id);
		insert crewList;
		Crew_Mapping__c crewMapping = new Crew_Mapping__c(CrewId__c = airPurser.Id, UserId__c = UserInfo.getUserId(), isActive__c = true, Last_Sync_Time__c = Datetime.now());
		insert crewMapping;

		Account ropAccount = new Account(Name = 'TEST');
		insert ropAccount;
		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'F');
		passenger.AccountId__c = ropAccount.Id;
		passenger.Checkin_Seat__c = '1A';
		insert passenger;

		List<Case> allCaseList = new List<Case>();
		List<Case_Group_Member__c> allCaseGroupMemberList = new List<Case_Group_Member__c>();
		Case caseOnAccountFromPreviousFlight = new Case(AccountId = ropAccount.Id);
		allCaseList.add(caseOnAccountFromPreviousFlight);
		Case caseOnPassengerOfThisFlight = new Case(AccountId = ropAccount.Id, Passengerid__c = passenger.Id, Flightid__c = flight.Id, A_C_REG_ID__c = aircraft.Id);
		allCaseList.add(caseOnPassengerOfThisFlight);
		insert allCaseList;

		allCaseGroupMemberList.add(new Case_Group_Member__c(AccountId__c = ropAccount.Id, CaseId__c = caseOnAccountFromPreviousFlight.Id, Position__c = '1A'));
		allCaseGroupMemberList.add(new Case_Group_Member__c(AccountId__c = ropAccount.Id, CaseId__c = caseOnAccountFromPreviousFlight.Id));
		insert allCaseGroupMemberList;

		MB_RestResponseInfoModel.lopaInfo_model lopaModel = MockupData_Test.getMockUpLOPA_HSTUB();
		String lopaJSON = System.JSON.serialize(lopaModel);
		Attachment lopaAttachment = new Attachment(Name = 'Master_LOPA.txt', Body = Blob.valueOf(lopaJSON), ParentId = flight.Id);
		insert lopaAttachment;

		MB_RESTLOPAService.retrieveLOPAInfo();
	}

}