p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <fields>
        <fullName>DEP_STN__c</fullName>
        <label>DEP STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Blocks__c</fullName>
        <description>Displays the number of cases with action being blocked</description>
        <label>Number Of Blocks</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Completes__c</fullName>
        <description>Displays the number of cases with action being complete</description>
        <label>Number Of Completes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_NoActions__c</fullName>
        <description>Displays the number of cases with no action</description>
        <label>Number Of NoActions</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_REG_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Aircraft the Case is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DEP_STN__c</fullName>
        <description>Displays the station the aircraft is located in</description>
        <label>DEP STN</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_Of_Blocks__c</fullName>
        <description>Displays the number of cases where impact is blocked</description>
        <label>Number Of Blocks</label>
        <summaryFilterItems>
            <field>Case_Group_Member__c.Impact_F__c</field>
            <operation>equals</operation>
            <value>Block</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Group_Member__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_Of_Completes__c</fullName>
        <description>Displays the number of cases where impact is completed</description>
        <label>Number Of Completes</label>
        <summaryFilterItems>
            <field>Case_Group_Member__c.Impact_F__c</field>
            <operation>equals</operation>
            <value>Complete</value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Group_Member__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Number_Of_NoActions__c</fullName>
        <description>Displays the number of cases where impact has no value</description>
        <label>Number Of NoActions</label>
        <summaryFilterItems>
            <field>Case_Group_Member__c.Impact_F__c</field>
            <operation>equals</operation>
            <value></value>
        </summaryFilterItems>
        <summaryForeignKey>Case_Group_Member__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Ground_Service</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>Ground Service</label>
    </recordTypes>
    <recordTypes>
        <fullName>Ground_Service_Closed</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>Ground Service Closed</label>
    </recordTypes>
    <recordTypes>
        <fullName>Maintenance</fullName>
        <active>true</active>
        <businessProcess>Maintenance Case</businessProcess>
        <label>Maintenance</label>
    </recordTypes>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the aircraft the position is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Case_Trigger_Test.cls
@isTest
private class Case_Trigger_Test {
	@isTest static void testClosedCaseShouldChangeRecordType() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();

		User groundUser = MockupData_User_Test.createUserIfNotExist('Ground Customer Service', 'KO_B_Ground_Flight_Manager_Controller_Gate');

		System.runAs(groundUser) {
		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'Ground_Service');
		    newCase.DEP_STN__c = 'BKK';
		    insert newCase;

		    Test.startTest();
		    newCase.Status = 'Closed';
		    update newCase;
		    Test.stopTest();
		}

		Id expectRecordTypeId = BE8_RecordTypeRepository.getInstance().getRecordTypeMapByDevName('Case').get('Ground_Service_Closed').Id;

		Case actualCase = [SELECT Id, Status, RecordTypeId FROM Case];
		Assert.assertEquals('Closed', actualCase.Status);
		Assert.assertEquals(expectRecordTypeId, actualCase.RecordTypeId);
	}

	@isTest static void testSumOfImpactWhenInsert() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
        Aircraft__c aircraft = MockupData_Test.createAircraft('HS-TUA', 'HS-TUA', '787');
        insert aircraft;

        List<Case> casesForInsert = new List<Case>();
		Case case1 = MockupData_Test.createCase('0001', 'New', 'Maintenance');
		case1.A_C_REG_ID__c = aircraft.Id;
		case1.DEP_STN__c = 'BKK';
		casesForInsert.add(case1);
		insert casesForInsert;

		List<Case_Group_Member__c> cgmsForInsert = new List<Case_Group_Member__c>();
		Case_Group_Member__c cgm1 = MockupData_Test.createCaseGroupMember(case1.Id);
		cgm1.Impact__c = 'Block';
		cgmsForInsert.add(cgm1);

		Case_Group_Member__c cgm3 = MockupData_Test.createCaseGroupMember(case1.Id);
		cgmsForInsert.add(cgm3);

		Test.startTest();
		insert cgmsForInsert;
		Test.stopTest();

		Aircraft__c actualAircraft = [SELECT Id, Number_Of_Completes__c, Number_Of_Blocks__c, Number_Of_NoActions__c FROM Aircraft__c WHERE Id = :aircraft.Id];
		System.assertEquals(1, actualAircraft.Number_Of_Blocks__c);
		System.assertEquals(1, actualAircraft.Number_Of_NoActions__c);
	}

	@isTest static void testSumOfImpact() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
        Aircraft__c aircraft = MockupData_Test.createAircraft('HS-TUA', 'HS-TUA', '787');
        insert aircraft;

        List<Case> casesForInsert = new List<Case>();
		Case case1 = MockupData_Test.createCase('0001', 'New', 'Maintenance');
		case1.A_C_REG_ID__c = aircraft.Id;
		casesForInsert.add(case1);
		insert casesForInsert;

		List<Case_Group_Member__c> cgmsForInsert = new List<Case_Group_Member__c>();
		Case_Group_Member__c cgm1 = MockupData_Test.createCaseGroupMember(case1.Id);
		cgm1.Impact__c = 'Block';
		cgmsForInsert.add(cgm1);

		Case_Group_Member__c cgm3 = MockupData_Test.createCaseGroupMember(case1.Id);
		cgmsForInsert.add(cgm3);
		insert cgmsForInsert;

		//Test.startTest();

		//Test.stopTest();

		Aircraft__c actualAircraft = [SELECT Id, Number_Of_Completes__c, Number_Of_Blocks__c, Number_Of_NoActions__c FROM Aircraft__c WHERE Id = :aircraft.Id];
		System.assertEquals(1, actualAircraft.Number_Of_Blocks__c);
		System.assertEquals(1, actualAircraft.Number_Of_NoActions__c);

		Case_Group_Member__c cgm2 = MockupData_Test.createCaseGroupMember(case1.Id);
		cgm2.Impact__c = 'Block';
		insert cgm2;

		actualAircraft = [SELECT Id, Number_Of_Blocks__c, Number_Of_NoActions__c FROM Aircraft__c WHERE Id = :aircraft.Id];
		System.assertEquals(2, actualAircraft.Number_Of_Blocks__c);
		System.assertEquals(1, actualAircraft.Number_Of_NoActions__c);

		cgm1.Impact__c = 'Complete';
		update cgm1;

		cgm3.Impact__c = 'Block';
		update cgm3;

		actualAircraft = [SELECT Id, Number_Of_Completes__c, Number_Of_Blocks__c, Number_Of_NoActions__c FROM Aircraft__c WHERE Id = :aircraft.Id];
		System.assertEquals(2, actualAircraft.Number_Of_Blocks__c);
		System.assertEquals(1, actualAircraft.Number_Of_Completes__c);
	}
}