p2ws_package/Devpp2ws-Package/objects/Application_Log__c.object
<CustomObject>
    <fields>
        <fullName>Debug_Level__c</fullName>
        <description>Error, Info, Warn, Debug</description>
        <label>Debug Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Debug</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Info</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>Message to log</description>
        <label>Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>The related record id</description>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Information__c</fullName>
        <description>The related record info (e.g. Apex Batch Job Id, Contact etc)</description>
        <label>Reference Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <description>The originating class (e.g. CustomerManagement)</description>
        <label>Source</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Application Log</label>
    <nameField>
        <label>Application Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Logs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Crew)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Rank of the crew such as FC or AP.</description>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>Acting_Rank__c</fullName>
        <label>Acting Rank</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crew_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Crew External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Crew_Temp__c</fullName>
        <label>Crew Temp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Temp__c</fullName>
        <label>Flight Temp</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Source__c</fullName>
        <label>Integration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Rank of the crew such as FC or AP.</description>
        <label>Rank</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Mappings</relationshipLabel>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Crew Mapping</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Crew Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Description__c</fullName>
        <formula>AircraftId__r.Aircraft_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>A/C Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block_Time__c</fullName>
        <description>Displays actual flying time in units of minutes</description>
        <label>Block Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Source__c</fullName>
        <label>Integration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STA_LT__c</fullName>
        <label>STA LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Description__c</fullName>
        <description>Aircraft Model</description>
        <label>Aircraft Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depend_On_Object__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to parent data level 1</description>
        <label>Depend On Object</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Depend_On_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>Define type of data</description>
        <externalId>true</externalId>
        <label>Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Flight Number</description>
        <label>Flight Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Map</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CSE_SOAPUpdateComplaintStatus_WS_Test.cls
@isTest
private class CSE_SOAPUpdateComplaintStatus_WS_Test {
	@testSetup static void MockData(){
		MockupData_Test.initialApplicationLogCustomSetting();
		List<Flight__c> flightList = new List<Flight__c>();
		List<Crew_List__c> crewList = new List<Crew_List__c>();
		//Initiate Flight
		Flight__c flight1 = new Flight__c(
			Name = '0628',
		    Flight_Number__c = 'TG0628',
		    Flight_Date_UTC__c = '20Dec25',
		    Flight_Date_LT__c = '20Dec25',
		    Departure_STN__c  = 'BKK',
		    STD_UTC__c = '20Dec25 0330',
		    STD_LT__c  = '20Dec25 1030',
		    STA_UTC__c = '20Dec25 0620',
		    STA_LT__c = '20Dec25 1420',
		    Block_Time__c = '170',
		    Integration_Source__c = '1',
		    Leg_Number__c = 1,
		    Flight_External_ID__c = 'TG0628_20Dec25_1');
		flightList.add(flight1);

		Crew_List__c crew2 = new Crew_List__c(
			Name = 'Temp Crew2',
		    Flight_Temp__c = 'TG0628_20Dec25_1',
		    //FlightId__c = flight1.Id,
		    Crew_Temp__c = '01232',
		    Crew_External_ID__c = '01232_TG0628_20Dec25_1',
		    Acting_Rank__c = 'AP',
		    Rank__c = 'AP');
		crewList.add(crew2);

		insert flightList;
		insert crewList;

		//Initiate Crew Mapping
		List<Crew_List__c> crew = [SELECT Id, CrewId__c FROM Crew_List__c WHERE Name = 'Temp Crew2' LIMIT 1];
		Crew_Mapping__c crewMap = new Crew_Mapping__c(
			UserId__c = '00528000004uNdcAAE',
			CrewId__c = crew.get(0).CrewId__c);
		insert crewMap;		

		Master_Map__c eq1 = new Master_Map__c(
			Name = 'ELECTRICAL & PNEUMATIC HEADPHONE', 
			Field_Name__c = 'SERVICE EQUIPMENT');
		insert eq1;
		Master_Map__c eq2 = new Master_Map__c(
			Name = 'HEADPHONE BODY',
			Field_Name__c = 'PART',
			Depend_On_Object__c = eq1.Id);
		insert eq2;
	}
	
	@isTest static void testApplicationLogShouldbeCreatedForPostStatusEqualToCLOSE() {
		//Amount of Case
		Integer incidentNumber = 3;
		//Amount of position in wach case
		Integer positionNumber = 2;
		//Set up
		MockupData_Test.initializeWebServiceCustomSetting();
		String flightId = [SELECT Id FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1'].get(0).Id;
		String crewId = [SELECT Id FROM Crew__c WHERE Personel_Id__c = '01232'].get(0).Id;
		//Map<String, Master_Map__c> equipMap = new Map<String, Master_Map__c>([SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null]);
		List<Master_Map__c> equipList = [SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null];
		Master_Map__c equip = equipList.get(0);
		String equipId = equip.Id;
		String partId = equip.Depend_On_Object__r.get(0).Id;

		List<MB_RESTRequestInfoModel.incident_model> incidentModelList = MockupData_Test.getIncidentModelList(incidentNumber, flightId, crewId, equipId, partId, positionNumber);
		List<MB_RestResponseInfoModel.incident_model> responseList = MB_RESTIncidentService.createIncident(incidentModelList);
		for(MB_RESTRequestInfoModel.incident_model incident : incidentModelList){
			CSE_SOAPUpdateComplaintStatus_WS.updateStatus(incident.seqNo, 'CLOSE');
		}
		List<Case> caseList = [SELECT Id, Subject, Status FROM Case];
		List<Application_Log__c> applogList = [SELECT Id, Name, Source__c, Reference_Id__c, Reference_Information__c, Message__c, Debug_Level__c FROM Application_Log__c WHERE Source__c = 'CSE_SOAPUpdateComplaintStatus_WS'];
		for(Application_Log__c applog : applogList){
			System.debug(applog);
		}
		for(Case c : caseList){
			System.debug(c);
		}
		System.assertEquals(3, applogList.size());
	}

		@isTest static void testApplicationLogShouldbeCreatedForPostStatusNOTEqualToCLOSE() {
		//Amount of Case
		Integer incidentNumber = 3;
		//Amount of position in wach case
		Integer positionNumber = 2;
		//Set up
		MockupData_Test.initializeWebServiceCustomSetting();
		String flightId = [SELECT Id FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1'].get(0).Id;
		String crewId = [SELECT Id FROM Crew__c WHERE Personel_Id__c = '01232'].get(0).Id;
		//Map<String, Master_Map__c> equipMap = new Map<String, Master_Map__c>([SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null]);
		List<Master_Map__c> equipList = [SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null];
		Master_Map__c equip = equipList.get(0);
		String equipId = equip.Id;
		String partId = equip.Depend_On_Object__r.get(0).Id;

		List<MB_RESTRequestInfoModel.incident_model> incidentModelList = MockupData_Test.getIncidentModelList(incidentNumber, flightId, crewId, equipId, partId, positionNumber);
		List<MB_RestResponseInfoModel.incident_model> responseList = MB_RESTIncidentService.createIncident(incidentModelList);
		for(MB_RESTRequestInfoModel.incident_model incident : incidentModelList){
			CSE_SOAPUpdateComplaintStatus_WS.updateStatus(incident.seqNo, 'CLOS');
		}
		List<Case> caseList = [SELECT Id, Subject, Status FROM Case];
		List<Application_Log__c> applogList = [SELECT Id, Name, Source__c, Reference_Id__c, Reference_Information__c, Message__c, Debug_Level__c FROM Application_Log__c WHERE Source__c = 'CSE_SOAPUpdateComplaintStatus_WS'];
		for(Application_Log__c applog : applogList){
			System.debug(applog);
		}
		for(Case c : caseList){
			System.debug(c);
		}
		System.assertEquals(3, applogList.size());
	}

	@isTest static void testApplicationLogShouldbeCreatedForPostStatusIsNULL() {
		//Amount of Case
		Integer incidentNumber = 3;
		//Amount of position in wach case
		Integer positionNumber = 2;
		//Set up
		MockupData_Test.initializeWebServiceCustomSetting();
		String flightId = [SELECT Id FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1'].get(0).Id;
		String crewId = [SELECT Id FROM Crew__c WHERE Personel_Id__c = '01232'].get(0).Id;
		//Map<String, Master_Map__c> equipMap = new Map<String, Master_Map__c>([SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null]);
		List<Master_Map__c> equipList = [SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null];
		Master_Map__c equip = equipList.get(0);
		String equipId = equip.Id;
		String partId = equip.Depend_On_Object__r.get(0).Id;

		List<MB_RESTRequestInfoModel.incident_model> incidentModelList = MockupData_Test.getIncidentModelList(incidentNumber, flightId, crewId, equipId, partId, positionNumber);
		List<MB_RestResponseInfoModel.incident_model> responseList = MB_RESTIncidentService.createIncident(incidentModelList);
		for(MB_RESTRequestInfoModel.incident_model incident : incidentModelList){
			CSE_SOAPUpdateComplaintStatus_WS.updateStatus(incident.seqNo, null);
		}
		List<Case> caseList = [SELECT Id, Subject, Status FROM Case];
		List<Application_Log__c> applogList = [SELECT Id, Name, Source__c, Reference_Id__c, Reference_Information__c, Message__c, Debug_Level__c FROM Application_Log__c WHERE Source__c = 'CSE_SOAPUpdateComplaintStatus_WS'];
		for(Application_Log__c applog : applogList){
			System.debug(applog);
		}
		for(Case c : caseList){
			System.debug(c);
		}
		System.assertEquals(3, applogList.size());
	}

	@isTest static void testApplicationLogShouldbeCreatedForPostSeqNoIsNULL() {
		//Amount of Case
		Integer incidentNumber = 3;
		//Amount of position in wach case
		Integer positionNumber = 2;
		//Set up
		MockupData_Test.initializeWebServiceCustomSetting();
		String flightId = [SELECT Id FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1'].get(0).Id;
		String crewId = [SELECT Id FROM Crew__c WHERE Personel_Id__c = '01232'].get(0).Id;
		//Map<String, Master_Map__c> equipMap = new Map<String, Master_Map__c>([SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null]);
		List<Master_Map__c> equipList = [SELECT Id, Depend_On_Object__c, (SELECT Id, Name FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null];
		Master_Map__c equip = equipList.get(0);
		String equipId = equip.Id;
		String partId = equip.Depend_On_Object__r.get(0).Id;

		List<MB_RESTRequestInfoModel.incident_model> incidentModelList = MockupData_Test.getIncidentModelList(incidentNumber, flightId, crewId, equipId, partId, positionNumber);
		List<MB_RestResponseInfoModel.incident_model> responseList = MB_RESTIncidentService.createIncident(incidentModelList);
		for(MB_RESTRequestInfoModel.incident_model incident : incidentModelList){
			CSE_SOAPUpdateComplaintStatus_WS.updateStatus(null, 'CLOSE');
		}
		List<Case> caseList = [SELECT Id, Subject, Status FROM Case];
		List<Application_Log__c> applogList = [SELECT Id, Name, Source__c, Reference_Id__c, Reference_Information__c, Message__c, Debug_Level__c FROM Application_Log__c WHERE Source__c = 'CSE_SOAPUpdateComplaintStatus_WS'];
		for(Application_Log__c applog : applogList){
			System.debug(applog);
		}
		for(Case c : caseList){
			System.debug(c);
		}
		System.assertEquals(3, applogList.size());
	}
}