p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MaintenanceLOPAStatusHandler.cls
public with sharing class MaintenanceLOPAStatusHandler implements LOPAStatusHandler {
	
	public String getLOPAPositionStatus(String position, String positionType, Passenger__c matchedPassenger, List<Case_Group_Member__c> matchedCaseList, MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos) {
		Boolean isPassengerSeat = positionType == BE8_GlobalConstants.TYPE_SEAT;
		Boolean isPassengerSeatOccupied = isPassengerSeat && (matchedPassenger != null);
		Boolean isROP = isPassengerSeatOccupied && (matchedPassenger.FFP_Carrier__c == BE8_GlobalConstants.DEFAULT_TG_COMPANY);

		Boolean hasCase = matchedCaseList != null;
		Boolean needRepair = !(!hasCase || matchedCaseList.size() == 0);

		Boolean isOccupied = isPassengerSeatOccupied;
		Boolean isBlock = false;
		Boolean isMalfunction = false;
		Boolean isGold = false;
		Boolean isPlatinum = false;
		Boolean isNoAction = false;
		Boolean isServiceable = false;

		Boolean isBlockedFromLOPA = lopaPos.sOcp != null && BE8_GlobalConstants.SEAT_OCCUPATION_BLOCKED_SEAT.contains(lopaPos.sOcp);

		String status = '';
		if (isPassengerSeat) {
			if (needRepair) {
				for (Case_Group_Member__c eachMember : matchedCaseList) {
					if (eachMember.Impact__c == null) {
						isNoAction = true;
						break;
					}
					if (eachMember.Impact__c == BE8_GlobalConstants.IMPACT_BLOCK) {
						isBlock = true;
						break;
					}
					if (eachMember.Impact__c == BE8_GlobalConstants.IMPACT_MALFUNCTION) {
						isMalfunction = true;
						break;
					}
					if (eachMember.Impact__c == BE8_GlobalConstants.IMPACT_SERVICABLE) {
						isServiceable = true;
						break;
					}
				}
			}
		}

		if (isROP) {
			isGold = matchedPassenger.FFP_Tier__c != null && matchedPassenger.FFP_Tier__c == BE8_GlobalConstants.FFP_TIER_GOLD;
			isPlatinum = matchedPassenger.FFP_Tier__c != null && matchedPassenger.FFP_Tier__c == BE8_GlobalConstants.FFP_TIER_PLATINUM;
		}


		if (isNoAction) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_NO_ACTION;
		}
		if (isBlockedFromLOPA && !isOccupied) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCKED_FROM_LOPA;
		}
		if (isMalfunction && isOccupied) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION_OCCUPIED;
		}
		if (isBlock && isOccupied) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK_OCCUPIED;
		}
		if (isMalfunction) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION;
		}
		if (isBlock) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK;
		}
		if (isServiceable) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_SERVICEABLE;
		}
		if (isOccupied) {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_OCCUPIED;
		} else {
			return BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_AVAILABLE;
		}
	}
}