p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <formula>CreatedBy.UserRole.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Role Name</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>มูลค่าเป็นเงินของสิ่งที่ Compensate</description>
        <label>Amount (Cash/EMD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>ID of the case associated with this compensation.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Compensation_Tools__c</fullName>
        <label>Compensation Tools</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Number__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Complimentary Ticket</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
                <value>
                    <fullName>Excess Baggage</fullName>
                </value>
                <value>
                    <fullName>Gifts</fullName>
                </value>
                <value>
                    <fullName>Lounge Access Voucher</fullName>
                </value>
                <value>
                    <fullName>Mileage Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upgrading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Rate of exchange</description>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>จำนวนของสิ่งที่ Compensate</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <recordTypes>
        <fullName>GS_Compensation</fullName>
        <active>true</active>
        <label>GS Compensation</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Compensation_AO__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <label>Maximum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation AO</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation_Chief__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <label>Maximum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation Chief</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation_D7__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <label>Maximum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation D7</label>
</CustomObject>

prd_package/objects/Compensation_Ground_Service__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Port__c</fullName>
        <label>Port</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation Ground Service</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation_In_flight__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation In-flight</label>
</CustomObject>

prd_package/objects/Compensation_Manager__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <label>Maximum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation Manager</label>
</CustomObject>

prd_package/objects/Compensation_Tier_2__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Maximum_Value__c</fullName>
        <label>Maximum Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_Name__c</fullName>
        <label>Role Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation Tier 2</label>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/User.object
<CustomObject>
    <fields>
        <fullName>Port__c</fullName>
        <label>Port</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Compensation_Management_Test.cls
@isTest
private class Compensation_Management_Test {
	@testSetup static void DataPreparation(){
		System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
		insert sysconfig;
	}
	
	@isTest static void testAutoApproveGround() {

		String port = 'port';

	    UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles',
        Port__c=port);

	    System.runAs(u) {

	    	Compensation_Ground_Service__c gsSetting = new Compensation_Ground_Service__c(Name=port, Port__c=port);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New');
		    c.RecordTypeId = BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Compensation__c', 'GS_Compensation');
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveInFlight() {

	    UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_In_flight__c gsSetting = new Compensation_In_flight__c(Name='name1234', Role_Name__c=uRole.Name);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New');
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveTier2Zero() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Tier_2__c gsSetting = new Compensation_Tier_2__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=Compensation_Management.zero);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveTier2() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Tier_2__c gsSetting = new Compensation_Tier_2__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveChiefZero() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Chief__c gsSetting = new Compensation_Chief__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=Compensation_Management.zero);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveChief() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Chief__c gsSetting = new Compensation_Chief__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveManagerZero() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Manager__c gsSetting = new Compensation_Manager__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=Compensation_Management.zero);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveManager() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_Manager__c gsSetting = new Compensation_Manager__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveAOZero() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_AO__c gsSetting = new Compensation_AO__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=Compensation_Management.zero);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveAO() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_AO__c gsSetting = new Compensation_AO__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveD7Zero() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_D7__c gsSetting = new Compensation_D7__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=Compensation_Management.zero);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveD7() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_D7__c gsSetting = new Compensation_D7__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveD7Gift() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_D7__c gsSetting = new Compensation_D7__c(Name=Compensation_Management.GIFTS, Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c=Compensation_Management.GIFTS, Total__c=100);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}

	@isTest static void testAutoApproveD7ROE() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    Profile profile = [select name from profile where id = :UserInfo.getProfileId() limit 1];

	    User u = new User(Alias = 'newUser', Email='newuser@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='12234@testorg.com', userroleid=uRole.Id,
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');

	    System.runAs(u) {

	    	Compensation_D7__c gsSetting = new Compensation_D7__c(Name='Cash', Role_Name__c=profile.Name,
	    		Maximum_Value__c=100);
			insert gsSetting;

	    	Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		    insert flight;

		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

	    	Test.startTest();

		    Compensation__c c = new Compensation__c(CaseId__c = newCase.Id, Status__c = 'New', Compensation_Tools__c='Cash', Amount__c=100, ROE__c=1);
		    insert c;

		    Compensation__c cUpdate = [Select Status__c from Compensation__c where id = :c.Id limit 1];
		    Assert.assertEquals(Compensation_Management.Approved, cUpdate.Status__c);

		    Test.stopTest();
	    }

	}
	
}