p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerCaseControllerTest.cls
@isTest
private class PassengerCaseControllerTest {
	
	@isTest static void testConstructor() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_TRIGGER, false);
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_GROUP_MEMBER_TRIGGER, false);

		Flight__c flight = MockupData_Test.getMockUpFlight();
		insert flight;

		List<Passenger__c> passengerList = new List<Passenger__c>();
		passengerList.addAll(MockupData_Test.createAcceptedPassengers(10, flight.Id, 'Y', 'BKK-HKG'));
		insert passengerList;

		List<Case> caseList = new List<Case>();
		caseList.add(new Case(FlightId__c = flight.Id, PassengerId__c = passengerList.get(0).Id));
		insert caseList;

		ApexPages.currentPage().getParameters().put('id', flight.Id);
		ApexPages.StandardController stdCaseController = new ApexPages.StandardController(flight);
		PassengerCaseController ctrl = new PassengerCaseController(stdCaseController);

		Assert.assertEquals(caseList.size(), ctrl.caseList.size());
		Assert.assert(ctrl.hasNext != null);
		Assert.assert(ctrl.hasPrevious != null);
		ctrl.next();
		ctrl.previous();
		Assert.assert(ctrl.pageNumber != null);
	}
	
}