p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SEQ_No_Display__c</fullName>
        <externalId>true</externalId>
        <label>Seq No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MaintenanceAppIncidentFactory.cls
public without sharing class MaintenanceAppIncidentFactory extends IncidentMobileFactory {
	public MaintenanceAppIncidentFactory(List<MB_RestRequestInfoModel.incident_model> incidentList) {
		super(incidentList);
		instanceName = 'MaintenanceAppIncidentFactory';
		isCreateCabinReport = false;
	}

	public override List<MB_RestResponseInfoModel.incident_model> generateResponseList() {
		Set<Id> caseIdSetAfterInsert = BE8_GlobalUtility.getIdSet('Id', allCaseList);
		List<Case> caseListFromDatabase = Database.query(IncidentService.caseQueryWithoutCGM + ' WHERE Id IN :caseIdSetAfterInsert AND SEQ_No_Display__c != null');
		System.debug('caseListFromDatabase: ' + caseListFromDatabase);
		Map<Id, List<Case_Group_Member__c>> cgmListMapByCaseId = new Map<Id, List<Case_Group_Member__c>>();
		for (Case_Group_Member__c eachCGM : Database.query('SELECT ' + IncidentService.caseGroupMemberFields + ' FROM Case_Group_Member__c WHERE Caseid__c IN :caseIdSetAfterInsert')) {
			if (!cgmListMapByCaseId.containsKey(eachCGM.Caseid__c)) {
				cgmListMapByCaseId.put(eachCGM.Caseid__c, new List<Case_Group_Member__c>());
			}
			cgmListMapByCaseId.get(eachCGM.Caseid__c).add(eachCGM);
		}

		List<MB_RestResponseInfoModel.incident_model> responseList = IncidentService.createIncidentModelList(caseListFromDatabase, cgmListMapByCaseId);
		System.debug('caseSaveResultList: ' + caseSaveResultList);
		System.debug('caseWithSEQNoList: ' + caseWithSEQNoList);
		responseList.addAll(IncidentService.createIncidentModelListForErrorRecords(caseSaveResultList, caseWithSEQNoList, incidentRequestMapByMobileAppKey, flightMap));
		return responseList;
	}
}