p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Number_Custom_F__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers</description>
        <formula>CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number_Custom__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers as a hyperlink</description>
        <formula>IF( $User.UIThemeDisplayed == &apos;Theme4t&apos;, HYPERLINK(&quot;/&quot; &amp; Id, CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber, &quot;_self&quot; ), HYPERLINK(&quot;javascript:srcUp(&apos;/&quot; &amp; Id &amp; &quot;&apos;)&quot;, 

CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber &amp; &quot; &quot; &amp; 

if( Text(Priority) == &quot;Urgent&quot;, 

IMAGE(&quot;/resource/icon_case/Priority_Exclamation.png&quot;,&quot;&quot;,13,13), 

&quot; &quot;)&amp; 

if(Text(Approval_Status__c) == &quot;Pending&quot;, 

IMAGE(&quot;/resource/icon_case/Icon_Lock.png&quot;,&quot;&quot;,15,15), 

&quot; &quot;) 

, &quot;_self&quot; ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number_Link_For_Console__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers as a hyperlink</description>
        <formula>HYPERLINK(&quot;javascript:openNewTab(&apos;&quot; &amp; Id &amp; &quot;&apos;)&quot;,if( Text(Priority) == &quot;Urgent&quot;,

CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber &amp; &quot; &quot; &amp;   
IMAGE(&quot;/servlet/servlet.FileDownload?file=01528000003KdRV&quot;,&quot;&quot;,13,13), 

CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Displays the value of case type used in case management</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commendation</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Incident</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Star Alliance</fullName>
                </value>
                <value>
                    <fullName>Baggage Claim</fullName>
                </value>
                <value>
                    <fullName>Court Case</fullName>
                </value>
                <value>
                    <fullName>14 CFR</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Arrival/Transit/Connections</fullName>
                </value>
                <value>
                    <fullName>Authorities and Airport Facilities</fullName>
                </value>
                <value>
                    <fullName>Boarding and Departure Area</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SPECIAL MEAL</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DGC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DBC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SEAT</fullName>
                </value>
                <value>
                    <fullName>Check-in &amp; Service pre-immigration-SPML</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - OTHER</fullName>
                </value>
                <value>
                    <fullName>General Comments on TG Services</fullName>
                </value>
                <value>
                    <fullName>Handling of flight Irregularities</fullName>
                </value>
                <value>
                    <fullName>Lounges</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>Unruly</fullName>
                </value>
                <value>
                    <fullName>Junk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerCaseController.cls
public with sharing class PassengerCaseController {
    public String theme {get; set;}
    public ApexPages.StandardSetController con {get; set;}
    public PassengerCaseController (ApexPages.StandardController stdController) {
        Id flightId = Apexpages.currentpage().getparameters().get('id');
        //Flight__c flight = [SELECT Id, AircraftId__c FROM Flight__c WHERE Id = :flightId LIMIT 1];
        List<Case> caseList = [SELECT Id, PassengerId__r.Name, Case_Number_Custom__c, Case_Number_Custom_F__c,  Case_Number_Link_For_Console__c, Subject, Origin, Priority, Status, Case_Type__c, CreatedDate FROM Case WHERE FlightId__c =:flightId AND PassengerId__c != null ORDER BY CreatedDate DESC LIMIT 1000];
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(caseList);
        con = ssc;
        con.setPageSize(8);
        theme = UserInfo.getUiTheme().toLowerCase();
    }
    public List<Case> caseList {
        get
        {
            if (con != null)
                return (List<Case>)con.getRecords();
            else
                return null ;
        }
        set;
    }
    public Boolean hasNext {
        get
        {
            return con.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get
        {
            return con.getHasPrevious();
        }
        set;
    }
    public Integer pageNumber {
        get
        {
            return con.getPageNumber();
        }
        set;
    }
    public void previous() {
        con.previous();
    }
    public void next() {
        con.next();
    }

}