p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MaintenanceLOPAStatusHandlerTest.cls
@isTest

private class MaintenanceLOPAStatusHandlerTest {
	@testSetup static void DataPreparation(){

		System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
		insert sysconfig;
		
	}
	
	@isTest static void testGetLOPAPositionStatus_BlockedFromLOPA() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', 'Z');
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCKED_FROM_LOPA, status);
	}

	@isTest static void testGetLOPAPositionStatus_Available() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_AVAILABLE, status);
	}

	@isTest static void testGetLOPAPositionStatus_Occupied() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A');
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_Blocked() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_BLOCK);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK, status);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedOccupied() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A');
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_BLOCK);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_Malfunction() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_MALFUNCTION);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, null, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION, status);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionOccupied() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A');
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_MALFUNCTION);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_OccupiedPlatinum() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_PLATINUM);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_OccupiedGold() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_GOLD);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, null, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedPlatinum() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_PLATINUM);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_BLOCK);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_BlockedGold() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_GOLD);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_BLOCK);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_BLOCK_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionPlatinum() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_PLATINUM);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_MALFUNCTION);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_MalfunctionGold() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_GOLD);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_MALFUNCTION);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_MALFUNCTION_OCCUPIED, status);
	}

	@isTest static void testGetLOPAPositionStatus_NoAction() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_GOLD);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = null);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_NO_ACTION, status);
	}

	@isTest static void testGetLOPAPositionStatus_Serviceable() {
		MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos = MockupData_Test.createMockUpLopaPos('1A', null);
		Passenger__c passenger = new Passenger__c(Checkin_Seat__c = '1A', FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY, FFP_Tier__c = BE8_GlobalConstants.FFP_TIER_GOLD);
		Flight__c flight = MockupData_Test.createFlight('TG0628', '2025-04-30', 1);
		insert flight;
		Case maintenanceCase = new Case();
		maintenanceCase.Flightid__c = flight.Id;
		insert maintenanceCase;
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c(CaseId__c = maintenanceCase.Id, Position__c = '1A', Impact__c = BE8_GlobalConstants.IMPACT_SERVICABLE);
		String status = new MaintenanceLOPAStatusHandler().getLOPAPositionStatus('1A', BE8_GlobalConstants.TYPE_SEAT, passenger, new List<Case_Group_Member__c> {caseGroupMember}, lopaPos);
		Assert.assertEquals(BE8_GlobalConstants.MAINTENANCE_LOPA_STATUS_SERVICEABLE, status);
	}
	
}