p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTI__c</fullName>
        <description>Counts all the CTI records on the case</description>
        <label>CTI</label>
        <summaryForeignKey>CTI__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Crew)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Crew_First_Name__c</fullName>
        <description>First name of the crew.</description>
        <label>Crew First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Mappings</relationshipLabel>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Crew Mapping</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Crew Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/CTI__c.object
<CustomObject>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Case which CTI is related.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <description>Flight Carrier which flight reat to CTI&apos;s case</description>
        <formula>LEFT(Flight_Number_F__c , 2 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is look up to Object Flight to relate CTI with Flight.</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is for user input. Type value is concate between Type 1 and Type 2 which in format &apos;Type 1 &gt; Type 2&apos;.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Aircraft</fullName>
                </value>
                <value>
                    <fullName>Alternative Flight Arrangement</fullName>
                </value>
                <value>
                    <fullName>Announcement / Information</fullName>
                </value>
                <value>
                    <fullName>Announcement in Lounge</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Cabin crew announcement</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Others</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Pilot announcement</fullName>
                </value>
                <value>
                    <fullName>Arrangement during irregularities</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Cabin Crew</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Check-in Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Check-in staff at Transfer desk</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Lost and Found Staff on Arrival</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Lounge Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Other Airport Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Other Arrival Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and care of Reservation and Ticketing Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Special Unit Staff (LP-S)</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Special Unit staff (LP-S) on Arrival</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of staff at boarding and departure area</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Staff Concern</fullName>
                </value>
                <value>
                    <fullName>Attitude and care of Ticketing &amp; Reservation staff at Airport</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Ticketing Staff at Airport</fullName>
                </value>
                <value>
                    <fullName>Availability of check-in counter</fullName>
                </value>
                <value>
                    <fullName>Baggage Handling at check-in</fullName>
                </value>
                <value>
                    <fullName>Baggage Handling on Arrival</fullName>
                </value>
                <value>
                    <fullName>Benefit/Privilege/Global Recognition</fullName>
                </value>
                <value>
                    <fullName>Beverage in Lounge</fullName>
                </value>
                <value>
                    <fullName>Boarding Announcement</fullName>
                </value>
                <value>
                    <fullName>Boarding Gate Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Issue__c</fullName>
        <description>To identify type of CTI as &apos;Complaint&apos;, &apos;Commend&apos;, &apos;Suggstion&apos;.</description>
        <label>Type of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint</fullName>
                    <color>#FF9900</color>
                    <label>Complaint</label>
                </value>
                <value>
                    <fullName>Commendation</fullName>
                    <color>#33CC00</color>
                    <label>Commendation</label>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                    <color>#6600CC</color>
                    <label>Suggestion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTI</label>
    <nameField>
        <displayFormat>CTI00{0000000000}</displayFormat>
        <label>CTI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTTopCaseInFlightTest.cls
@isTest
private class MB_RESTTopCaseInFlightTest {
	@isTest static void testGetTopCase() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_TRIGGER, false);
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CREW_LIST_TRIGGER, false);

		Flight__c flight = MockupData_Test.getMockUpFlight();
		flight.STD_UTC__c = String.valueOf(DateTime.now());
		flight.STA_UTC__c = String.valueOf(DateTime.now().addHours(10));
		insert flight;
		Crew__c crew = new Crew__c (Crew_First_Name__c = 'TEST', Personel_Id__c = 'TEST');
		insert crew;
		Crew_List__c crewList = new Crew_List__c(CrewId__c = crew.Id, FlightId__c = flight.Id);
		insert crewList;
		Crew_Mapping__c crewMapping = new Crew_Mapping__c(CrewId__c = crew.Id, UserId__c = UserInfo.getUserId(), isActive__c = true, Last_Sync_Time__c = Datetime.now());
		insert crewMapping;
		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'F');
		passenger.FlightId__c = flight.Id;
		insert passenger;
		Case newCase = new Case();
		newCase.FlightId__c = flight.Id;
		newCase.PassengerId__c = passenger.Id;
		newCase.RecordTypeId = BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case', BE8_GlobalConstants.CASE_RECORD_TYPE_IN_FLIGHT);
		insert newCase;
		CTI__c cti = new CTI__c();
		cti.Flightid__c = flight.Id;
		cti.CaseId__c = newCase.Id;
		cti.Type_of_Issue__c = 'Complaint';
		cti.Type__c = 'Attitude and Care of Cabin Crew';
		insert cti;
		List<MB_RESTTopCaseInFlight.TopCase> result = MB_RESTTopCaseInFlight.getTopCase();
		Assert.assertEquals(1, result.size());
	}
}