p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_REG_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Aircraft the Case is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the account related to the case group member</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <externalId>true</externalId>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Booking_Seat__c</fullName>
        <description>The seat that has been booked by the passenger since the reservation was placed</description>
        <label>Booking Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PaxKey__c</fullName>
        <formula>First_Name__c &amp; &apos;_&apos; &amp;  Last_Name__c &amp; &apos;_&apos; &amp;  PNR__c &amp; &apos;_&apos; &amp; Flight_Master__c</formula>
        <label>PaxKey</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTIncidentService.cls
@RestResource(urlMapping = '/incident/*')
global without sharing class MB_RESTIncidentService {

    @HttpGet
    global static List<MB_RestResponseInfoModel.incident_model> retrieveIncidentInfo() {
        Set<Id> flightIdSet = BE8_GlobalUtility.getFlightIdSetFromUserId(UserInfo.getUserId());
        List<Flight__c> flightList = [SELECT Id, Flight_Master__c FROM Flight__c WHERE Id IN: flightIdSet];
        Set<String> flightMasterSet = BE8_GlobalUtility.getStringSet('Flight_Master__c', flightList);

        Set<Id> aircraftIdSet = BE8_GlobalUtility.getIdSet('AircraftId__c', [SELECT Id, AircraftId__c FROM Flight__c WHERE Id IN :flightIdSet]);

        List<Passenger__c> passengerList = [SELECT Id, PaxKey__c, Checkin_Seat__c, Booking_Seat__c, AccountId__c, First_Name__c, Last_Name__c, PNR__c, Flight_Master__c FROM Passenger__c WHERE FlightId__c IN :flightIdSet];
        Map<Id, Passenger__c> passengerMap = new Map<Id, Passenger__c>(passengerList);
        Set<Id> accountIdSet = BE8_GlobalUtility.getIdSet('AccountId__c', passengerList);

        Map<String, SObject> passengerMapByAccountId = BE8_GlobalUtility.getSObjectMap('AccountId__c', passengerList);
        //List<Case_Group_Member__c> caseGroupMemberOfAccountList = Database.query(caseGroupMemberQuery + ' WHERE AccountId__c IN :accountIdSet OR PassengerId__r.Flight_Master__c IN :flightMasterSet ORDER BY CreatedDate DESC');
        List<Case_Group_Member__c> caseGroupMemberOfAccountList = IncidentService.getCaseGroupMemberOfAccountList(accountIdSet,  flightMasterSet);
        System.debug('caseGroupMemberOfAccountList ' + caseGroupMemberOfAccountList);
        Set<Id> accountCaseIdSet = BE8_GlobalUtility.getIdSet('Caseid__c', caseGroupMemberOfAccountList);
        //List<Case> accountCaseList = Database.query(caseQuery + ' WHERE Id IN :accountCaseIdSet');
        List<Case> accountCaseList = IncidentService.getCaseList(accountCaseIdSet);
        System.debug('accountCaseList ' + accountCaseList);
        Map<Id, Case> accountCaseMap = new Map<Id, Case>(accountCaseList);

        Map<Id, Set<Case>> accountCaseMapByAccountId = new Map<Id, Set<Case>>();
        for (Case_Group_Member__c eachMember : caseGroupMemberOfAccountList) {
            Case accountCase = accountCaseMap.get(eachMember.Caseid__c);

            if (accountCase != null) {
                Set<Case> caseSet = accountCaseMapByAccountId.get(eachMember.AccountId__c);
                if (caseSet == null) {
                    caseSet = new Set<Case>();
                    accountCaseMapByAccountId.put(eachMember.AccountId__c, caseSet);
                }
                caseSet.add(accountCase);
            }
        }

        List<Case> allCaseList = new List<Case>();
        Integer accountCaseLimit = 10;
        System.debug('accountCaseMapByAccountId ' + accountCaseMapByAccountId);
        for (String key : accountCaseMapByAccountId.keySet()) {
            List<Case> caseListOfEachAccount = new List<Case>(accountCaseMapByAccountId.get(key));
            if (caseListOfEachAccount.size() > accountCaseLimit) {
                Integer exceedAmount = caseListOfEachAccount.size() - accountCaseLimit;
                for (Integer i = 0 ; i < exceedAmount; i++) {
                    caseListOfEachAccount.remove(accountCaseLimit);
                }
            }
            allCaseList.addAll(caseListOfEachAccount);
        }

        Set<Id> queriedCaseIdSet = new Set<Id>();
        queriedCaseIdSet.addAll(accountCaseIdSet);
        //List<Case> flightCaseList = Database.query(caseQuery + ' WHERE Id NOT IN :queriedCaseIdSet AND Flightid__c IN :flightIdSet ');

        Set<String> caseStatusNotIncludedSet = new Set<String> {BE8_GlobalConstants.CASE_STATUS_CLOSED, BE8_GlobalConstants.CASE_STATUS_VOID};
        //List<Case> flightCaseList = Database.query(caseQueryWithoutCGM + ' WHERE Id NOT IN :queriedCaseIdSet AND Flightid__c IN :flightIdSet AND Status NOT IN :caseStatusNotIncludedSet');
        List<Case> flightCaseList = IncidentService.getFlightCaseList(flightIdSet, caseStatusNotIncludedSet, queriedCaseIdSet);
        System.debug('flightCaseList: ' + flightCaseList);

        queriedCaseIdSet.addAll(BE8_GlobalUtility.getIdSet('Id', flightCaseList));
        Id maintenanceCaseRecordTypeId = BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case', BE8_GlobalConstants.CASE_RECORD_TYPE_MAINTENANCE);
        //List<Case> aircraftCaseList = Database.query(caseQuery + ' WHERE Id NOT IN :queriedCaseIdSet AND A_C_REG_ID__c IN :aircraftIdSet AND Status NOT IN :caseStatusNotIncludedSet AND RecordTypeId = :maintenanceCaseRecordTypeId');
        List<Case> aircraftCaseList = IncidentService.getAircraftCaseList(aircraftIdSet, caseStatusNotIncludedSet, queriedCaseIdSet);
        System.debug('aircraftCaseList: ' + aircraftCaseList);

        allCaseList.addAll(flightCaseList);
        allCaseList.addAll(aircraftCaseList);

        Set<Id> allCaseIdSet = BE8_GlobalUtility.getIdSet('Id', allCaseList);
        Map<Id, List<Case_Group_Member__c>> cgmListMapByCaseId = new Map<Id, List<Case_Group_Member__c>>();
        //for (Case_Group_Member__c eachCGM : Database.query('SELECT ' + caseGroupMemberFields + ' FROM Case_Group_Member__c WHERE Caseid__c IN :allCaseIdSet')) {
        for (Case_Group_Member__c eachCGM : IncidentService.getCaseGroupMemberFromCase(allCaseIdSet)) {
            if (!cgmListMapByCaseId.containsKey(eachCGM.Caseid__c)) {
                cgmListMapByCaseId.put(eachCGM.Caseid__c, new List<Case_Group_Member__c>());
            }
            cgmListMapByCaseId.get(eachCGM.Caseid__c).add(eachCGM);
        }

        List<MB_RestResponseInfoModel.incident_model> incidentList = IncidentService.createIncidentModelList(allCaseList, cgmListMapByCaseId, new InFlightIncidentStatusHandler());
        return incidentList;
    }

    @HttpPost
    global static List<MB_RestResponseInfoModel.incident_model> createIncident(List<MB_RestRequestInfoModel.incident_model> incidentList) { 
        InFlightAppIncidentFactory factory = new InFlightAppIncidentFactory(incidentList);
        factory.createIncident();
        factory.createCabinLogInSAP();
        factory.sendEmergencyEmail();
        List<MB_RestResponseInfoModel.incident_model> responseList = factory.generateResponseList();
        AppLogger.insertLogs();
        return responseList;
    }
}