p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Account_Debited__c</fullName>
        <description>Displays the value of the Account Number the Cash Compensation is transferred to</description>
        <label>Account Debited</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Baggage_Check_Number__c</fullName>
        <description>Displays the baggage check number</description>
        <label>Baggage Check Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number_Custom_F__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers</description>
        <formula>CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Excess_Bag_Ticket_Number__c</fullName>
        <label>Excess Bag Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_Manual__c</fullName>
        <label>Flight Date Manual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_From_Manual__c</fullName>
        <label>Flight From Manual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_Manual__c</fullName>
        <label>Flight Number Manual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_To_Manual__c</fullName>
        <label>Flight To Manual</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LCD_Detail__c</fullName>
        <label>LCD Detail</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Ticket_Number__c</fullName>
        <label>Passenger Ticket Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>มูลค่าเป็นเงินของสิ่งที่ Compensate</description>
        <label>Amount (Cash/EMD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the case group member associated with this compensation.</description>
        <label>Case Group Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CaseId__c</field>
                <operation>equals</operation>
                <valueField>Case_Group_Member__c.Caseid__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Group_Member__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compensation_Account_Number__c</fullName>
        <label>Compensation Account Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Center__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>631070</fullName>
                    <label>631070 - Baggage Claims Compensation</label>
                </value>
                <value>
                    <fullName>631071</fullName>
                    <label>631071 - Injury</label>
                </value>
                <value>
                    <fullName>631080</fullName>
                    <label>631080 - Compensation EX-Gratia Passenger Complaint&amp;Claim</label>
                </value>
                <value>
                    <fullName>631130</fullName>
                    <label>631130 - DBC / DGC</label>
                </value>
                <value>
                    <fullName>631140</fullName>
                    <label>631140 - Customer Relations EMD</label>
                </value>
                <value>
                    <fullName>631150</fullName>
                    <label>631150 - Inflight Service Compliment</label>
                </value>
                <value>
                    <fullName>811106</fullName>
                    <label>811106 -  Int.Charge for Other Flight Kitchen (for Lounge Access Voucher)</label>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Tools__c</fullName>
        <label>Compensation Tools</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Number__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Complimentary Ticket</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
                <value>
                    <fullName>Excess Baggage</fullName>
                </value>
                <value>
                    <fullName>Gifts</fullName>
                </value>
                <value>
                    <fullName>Lounge Access Voucher</fullName>
                </value>
                <value>
                    <fullName>Mileage Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upgrading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>SO code of the currency. Must be one of the valid alphabetic, three-letter currency ISO codes defined by the ISO 4217 standard, such as USD, GBP, or JPY.</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>KHR</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>DKK</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>IRR</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>LAK</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>NPR</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>OMR</fullName>
                </value>
                <value>
                    <fullName>PKR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>LKR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Individual__c</fullName>
        <description>Checks whether the compensation is meant for an individual</description>
        <formula>!ISBLANK(Case_Group_Member__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Individual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PassengerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the passenger associated with this compensation.</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Rate of exchange</description>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_THB__c</fullName>
        <formula>IF( ROE__c &gt; 0 &amp;&amp;  Amount__c &gt; 0 , Amount__c * ROE__c ,  Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total (THB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/LCDController.cls
public with sharing class LCDController {

    private final sObject mysObject;
    public LCDView view {get; set;}
    public String logoURL {get; set;}
    public String currencyWord;
    public String subCurrencyWord;
    public String selectedCaseGroupMemberId {get; set;}
    public String pdfName {get; set;}

    public class LCDView {
        public String passengerName {get; set;}
        public String flightDate {get; set;}
        public String flightNumber {get; set;}
        public String origin {get; set;}
        public String destination {get; set;}
        public String passengerTicketNumber {get; set;}
        public String baggageCheckNumber {get; set;}
        public String excessBagTicketNumber {get; set;}
        public String settlementAuthorizedBy {get; set;}
        public String amountInWords {get; set;}
        public Decimal amountInFigures {get; set;}
        public String detail {get; set;}
        public String accountDebited {get; set;}
        public Case caseObj {get; set;}
        public Boolean displayTHB {get; set;}
        public String displayCurrency {get; set;}
    }

    public LCDController(ApexPages.StandardController stdController) {
        this.mysObject = (sObject)stdController.getRecord();
        Case currentCase;
        String compensationIds = Apexpages.Currentpage().getParameters().get('compensationIds');
        if(String.isBlank(compensationIds)) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select compensation'));
            return;
        } else {
            List<Id> compensationIdList = compensationIds.split(',');
            currentCase = [SELECT Id, Flight_Number_Manual__c, Flight_Date_Manual__c, Flight_From_Manual__c, Flight_To_Manual__c, Passengerid__r.Name, Flightid__r.Flight_Date_LT__c, Flightid__r.Name, Flightid__r.Origin__c, Flightid__r.Destination__c, Case_Number_Custom_F__c, Passenger_Ticket_Number__c, Baggage_Check_Number__c, Excess_Bag_Ticket_Number__c, Account_Debited__c, LCD_Detail__c, (SELECT Id, Total_THB__c, Compensation_Tools__c, ROE__c, Amount__c, Currency__c, Is_Individual__c, Case_Group_Member__c, Compensation_Account_Number__c, Compensation_Account_Center__c FROM Compensations__r WHERE Id IN :compensationIdList AND Total_THB__c != null and Status__c = 'Approved') FROM Case WHERE Id = : stdController.getId() LIMIT 1];

            if(!Compensation_Service.validateAccountNumberAndAccountCenter(currentCase.Compensations__r)) {
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Invalid Account Number or Account Center'));
                return;
            }
        }
        
        selectedCaseGroupMemberId = Apexpages.CurrentPage().getParameters().get('selectedCaseGroupMemberId');
        List<Document> docList = [SELECT id FROM Document where name = 'THAI_Logo'];
        if (docList != null && docList.size() > 0) {
            logoURL = '/servlet/servlet.FileDownload?file=' + docList.get(0).Id;
        }

        view = createLCDView(currentCase);
        pdfName = Apexpages.Currentpage().getParameters().get('pdfName');
        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=' + pdfName);
    }

    private LCDView createLCDView(Case caseObj) {
        LCDView view = new LCDView();
        //view.passengerName = caseObj.Passengerid__r.Name;
        view.passengerName = Apexpages.Currentpage().getParameters().get('passengerName');
        String displayTHB = Apexpages.CurrentPage().getParameters().get('displayTHB');
        view.displayTHB = false;
        if (!String.isBlank(displayTHB)) {
            view.displayTHB = Boolean.valueOf(displayTHB);
        }
        currencyWord = Apexpages.Currentpage().getParameters().get('currencyWord');
        subCurrencyWord = Apexpages.Currentpage().getParameters().get('subCurrencyWord');
        //Date flightDate = Date.valueOf(caseObj.Flightid__r.Flight_Date_LT__c);
        //view.flightDate = BE8_DateUtility.convertDateFormatToTraditionalFormat(caseObj.Flightid__r.Flight_Date_LT__c);
        //view.flightNumber = caseObj.Flightid__r.Name.split(' ')[0];
        //view.origin = caseObj.Flightid__r.Origin__c;
        //view.destination = caseObj.Flightid__r.Destination__c;

        //if (view.flightNumber == BE8_GlobalConstants.DUMMY_FLIGHT_NAME) {
        view.flightNumber = caseObj.Flight_Number_Manual__c;
        view.flightDate = caseObj.Flight_Date_Manual__c;
        view.origin = caseObj.Flight_From_Manual__c;
        view.destination = caseObj.Flight_To_Manual__c;
        //}

        User currentUser = [SELECT Id, Alias, Department FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        view.settlementAuthorizedBy = currentUser.Department + '/' + caseObj.Case_Number_Custom_F__c + '-' + currentUser.Alias;

        Decimal totalAmount = 0;
        view.displayCurrency = 'THB';

        Boolean hasOtherCashEMD = false;
        for (Compensation__c each : caseObj.Compensations__r) {
            if (each.Compensation_Tools__c == 'Cash' || each.Compensation_Tools__c == 'EMD') {
                if (each.Amount__c != null) {
                    System.debug('Individual :' + each.Case_Group_Member__c + ' ' + selectedCaseGroupMemberId);
                    if (each.Is_Individual__c && each.Case_Group_Member__c != selectedCaseGroupMemberId) {
                        continue;
                    }

                    Decimal eachAmount = Compensation_Service.getAmountPerPassenger(each, view.displayTHB);
                    if (view.displayTHB) {
                        currencyWord = 'BAHT';
                        subCurrencyWord = 'SATANG';
                    } else {
                        view.displayCurrency = each.Currency__c;
                    }
                    totalAmount += eachAmount;
                }

            } else {
                hasOtherCashEMD = true;
            }
        }

        totalAmount = totalAmount.setScale(2);
        view.amountInFigures = totalAmount;
        if (totalAmount >= 0) {
            String amount = String.valueOf(totalAmount);
            String amountInFiguresDec = amount.substring(amount.indexOf('.') + 1);
            view.amountInWords = new NumbersToWordsClass().convert((Long)view.amountInFigures).toUpperCase();
            view.amountInWords += ' ' +  currencyWord + ' ' + (Long.valueOf(amountInFiguresDec) > 0 ? new NumbersToWordsClass().convert(Long.valueOf(amountInFiguresDec)).toUpperCase() + ' ' + subCurrencyWord : 'ONLY');
            //System.debug('SJ :amount :' + amount);
            //System.debug('SJ :amountInFiguresDec :' + amountInFiguresDec);
            //System.debug('SJ :Long.valueOf(amountInFiguresDec) :' + Long.valueOf(amountInFiguresDec));
            //if (view.displayTHB) {
            //    view.amountInWords += ' ' +  currencyWord + ' ' + (Long.valueOf(amountInFiguresDec) > 0 ? new NumbersToWordsClass().convert(Long.valueOf(amountInFiguresDec)).toUpperCase() + ' ' + subCurrencyWord : 'ONLY');
            //} else {
            //    view.amountInWords += ' ' + currencyWord;
            //}
        }
        view.passengerTicketNumber = caseObj.Passenger_Ticket_Number__c;
        view.baggageCheckNumber = caseObj.Baggage_Check_Number__c;
        view.excessBagTicketNumber = caseObj.Excess_Bag_Ticket_Number__c;
        view.accountDebited = caseObj.Account_Debited__c;
        view.detail = caseObj.LCD_Detail__c;

        if(hasOtherCashEMD) {
            view.displayCurrency = '';
            view.amountInWords = '';
            view.amountInFigures = null;
        }

        return view;
    }

}