p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Caseid__r.Status )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>มูลค่าเป็นเงินของสิ่งที่ Compensate</description>
        <label>Amount (Cash/EMD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>ID of the case associated with this compensation.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the case group member associated with this compensation.</description>
        <label>Case Group Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CaseId__c</field>
                <operation>equals</operation>
                <valueField>Case_Group_Member__c.Caseid__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Group_Member__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compensation_Tools__c</fullName>
        <label>Compensation Tools</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Number__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Complimentary Ticket</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
                <value>
                    <fullName>Excess Baggage</fullName>
                </value>
                <value>
                    <fullName>Gifts</fullName>
                </value>
                <value>
                    <fullName>Lounge Access Voucher</fullName>
                </value>
                <value>
                    <fullName>Mileage Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upgrading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Type__c</fullName>
        <description>Displays the compensation tools</description>
        <label>Compensation Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Baggage Damage</fullName>
                </value>
                <value>
                    <fullName>Baggage Delay</fullName>
                </value>
                <value>
                    <fullName>Baggage Loss</fullName>
                </value>
                <value>
                    <fullName>Baggage Pilferage</fullName>
                </value>
                <value>
                    <fullName>Boarding</fullName>
                </value>
                <value>
                    <fullName>Check in Service</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>Denied Boarding</fullName>
                </value>
                <value>
                    <fullName>Downgrade</fullName>
                </value>
                <value>
                    <fullName>EC261</fullName>
                </value>
                <value>
                    <fullName>Food poisoning</fullName>
                </value>
                <value>
                    <fullName>Foreign object</fullName>
                </value>
                <value>
                    <fullName>Handling of Flight Irregularity</fullName>
                </value>
                <value>
                    <fullName>IFE (in-flight entertainment) malfunction</fullName>
                </value>
                <value>
                    <fullName>Inadmissible passenger</fullName>
                </value>
                <value>
                    <fullName>In-Flight Service</fullName>
                </value>
                <value>
                    <fullName>Injury before boarding/after/on arrival/Medical assistance</fullName>
                </value>
                <value>
                    <fullName>Injury on Board</fullName>
                </value>
                <value>
                    <fullName>Lounge</fullName>
                </value>
                <value>
                    <fullName>Medical assistance</fullName>
                </value>
                <value>
                    <fullName>On board Catering</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Reservation Service</fullName>
                </value>
                <value>
                    <fullName>Schedule Deviation</fullName>
                </value>
                <value>
                    <fullName>Seat malfunction</fullName>
                </value>
                <value>
                    <fullName>Special meal request</fullName>
                </value>
                <value>
                    <fullName>Ticketing Service</fullName>
                </value>
                <value>
                    <fullName>Web Booking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>SO code of the currency. Must be one of the valid alphabetic, three-letter currency ISO codes defined by the ISO 4217 standard, such as USD, GBP, or JPY.</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>KHR</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>DKK</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>IRR</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>LAK</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>NPR</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>OMR</fullName>
                </value>
                <value>
                    <fullName>PKR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>LKR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Individual__c</fullName>
        <description>Checks whether the compensation is meant for an individual</description>
        <formula>!ISBLANK(Case_Group_Member__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Individual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Passenger_Name__c</fullName>
        <description>Name of the passenger.</description>
        <formula>Case_Group_Member__r.Passengerid__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Passenger Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_THB__c</fullName>
        <formula>IF( ROE__c &gt; 0 &amp;&amp;  Amount__c &gt; 0 , Amount__c * ROE__c ,  Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total (THB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <defaultValue>0</defaultValue>
        <description>จำนวนของสิ่งที่ Compensate</description>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>Displays the unit of the compensation</description>
        <label>Unit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Kilogramme</fullName>
                </value>
                <value>
                    <fullName>Miles</fullName>
                </value>
                <value>
                    <fullName>Sector</fullName>
                </value>
                <value>
                    <fullName>Ticket</fullName>
                </value>
                <value>
                    <fullName>Person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Approval_Email_Templete_Controller.cls
public class Approval_Email_Templete_Controller {
    private final List<Compensation__c> listcomp;

    public Decimal totalAmount {get; set;}
    //public Decimal totalAmountEachPassenger {get; set;}
    public String currencyWord {get; set;}
    public Decimal totalAmountTHB {get; set;}
    public String debugString {get; set;}
    public Integer caseGroupMemberSize {get; set;}

    public Approval_Email_Templete_Controller() {
        Id caseId = Apexpages.Currentpage().getParameters().get('id');
        //totalAmountEachPassenger = 0;
        listcomp = [SELECT Compensation_Type__c, Compensation_Tools__c, Status__c,
                    Total__c, Amount__c, Unit__c, Currency__c, Total_THB__c, Is_Individual__c, Passenger_Name__c, Name
                    FROM Compensation__c
                    WHERE Caseid__c = :caseId AND status__c = : BE8_GlobalConstants.CASE_STATUS_PENDING];
        System.debug('List Compensation :: ' + listcomp.size());
        debugString = caseId + ' ' + listcomp.size();

        List<Case_Group_Member__c> caseGroupMembers = [SELECT Id FROM Case_Group_Member__c WHERE Caseid__c = :caseId];
        caseGroupMemberSize = caseGroupMembers.size();
        totalAmount = 0;
        totalAmountTHB = 0;
        for (Compensation__c compensation : listcomp) {
            if (compensation.Compensation_Tools__c == 'Cash') {
                currencyWord = compensation.Currency__c;
            } else {
                currencyWord = compensation.Unit__c;
            }

            if (!compensation.Is_Individual__c) {
                totalAmount += (compensation.Amount__c * caseGroupMemberSize);
                totalAmountTHB += (compensation.Total_THB__c * caseGroupMemberSize);
            } else {
                totalAmount += compensation.Amount__c;
                totalAmountTHB += compensation.Total_THB__c;
            }
            //totalAmountEachPassenger += compensation.Amount__c;
        }
    }

    public List<Compensation__c> getCompensations() {
        return listcomp;
    }

}