p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

prd_package/objects/Case_Member__c.object
<CustomObject>
    <fields>
        <fullName>Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Teamid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>relate case team object</description>
        <label>Case Team</label>
        <referenceTo>Case_Team__c</referenceTo>
        <relationshipLabel>Case Members</relationshipLabel>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Display type of member</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>External User</fullName>
                </value>
                <value>
                    <fullName>Internal User</fullName>
                </value>
                <value>
                    <fullName>Investigation Staff</fullName>
                </value>
                <value>
                    <fullName>Round Robin User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relate with user object</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Case_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays the Status active or inactive for the Case Teams</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_ID__c</fullName>
        <description>This field use mapping with case owner for point to Case Team</description>
        <label>Queue ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Team</label>
    <nameField>
        <label>Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Round_Robin_Controller_Test.cls
@isTest
private class Round_Robin_Controller_Test {
	@testSetup static void DataPreparation(){

		System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
		insert sysconfig;
		
	}
	
	@isTest static void testRoundrobin_method() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    User u1Q1 = new User(Alias = 'User1Q1', Email='User1Q1@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User1Q1@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u1Q1;

        User u2Q1 = new User(Alias = 'User2Q1', Email='User2Q1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User2Q1@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u2Q1;

        User u1Q2 = new User(Alias = 'User1Q2', Email='User1Q2@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User1Q2@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u1Q2;

        User u2Q2 = new User(Alias = 'User2Q2', Email='User2Q2@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User2Q2@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u2Q2;

        Id caseMemberId;

        System.runAs(u2q1){

        	Case_Team__c q1 = new Case_Team__c(Queue_ID__c=String.valueof(u1Q1.Id), Active__c=true);
			insert q1;

			Case_Team__c q2 = new Case_Team__c(Queue_ID__c=String.valueof(u1Q2.Id), Active__c=true);
			insert q2;

	        Case_Member__c m1 = new Case_Member__c(Userid__c=u1q1.id, Type__c='Round Robin User', Case_Teamid__c=q1.id, Assigned__c=true);
	        insert m1;

	        Case_Member__c m2 = new Case_Member__c(Userid__c=u2q1.id, Type__c='Round Robin User', Case_Teamid__c=q1.id, Assigned__c=false);
	        insert m2;

	        Case_Member__c m3 = new Case_Member__c(Userid__c=u1q2.id, Type__c='Round Robin User', Case_Teamid__c=q2.id, Assigned__c=true);
	        insert m3;
	        
	        Case_Member__c m4 = new Case_Member__c(Userid__c=u2q2.id, Type__c='Round Robin User', Case_Teamid__c=q2.id, Assigned__c=false);
	        insert m4;

	        Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
			insert flight;

	        Test.startTest();
		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;

		    //newCase.OwnerId = u1q1.Id;
		    newCase.OwnerId = u1q1.Id;
		    update newCase;
	        Test.stopTest();
	        caseMemberId = m2.Id;
        }
        Case_Member__c updateMember = [Select Assigned__c from Case_Member__c where Id = :caseMemberId limit 1];
        Assert.assertEquals(true, updateMember.Assigned__c);

	}

	@isTest static void testRoundrobin_method_markFirstMember() {

		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    User u1Q1 = new User(Alias = 'User1Q1', Email='User1Q1@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User1Q1@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u1Q1;

        User u2Q1 = new User(Alias = 'User2Q1', Email='User2Q1@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User2Q1@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u2Q1;

        User u1Q2 = new User(Alias = 'User1Q2', Email='User1Q2@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User1Q2@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u1Q2;

        User u2Q2 = new User(Alias = 'User2Q2', Email='User2Q2@testorg.com', 
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User2Q2@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u2Q2;

        Id caseMemberId;

        System.runAs(u1q1){

        	Case_Team__c q1 = new Case_Team__c(Queue_ID__c=String.valueof(u1Q1.Id), Active__c=true);
			insert q1;

			Case_Team__c q2 = new Case_Team__c(Queue_ID__c=String.valueof(u1Q2.Id), Active__c=true);
			insert q2;

	        Case_Member__c m1 = new Case_Member__c(Userid__c=u1q1.id, Type__c='Round Robin User', Case_Teamid__c=q1.id, Assigned__c=true);
	        insert m1;

	        Case_Member__c m2 = new Case_Member__c(Userid__c=u2q1.id, Type__c='Round Robin User', Case_Teamid__c=q1.id, Assigned__c=false);
	        insert m2;

	        Case_Member__c m3 = new Case_Member__c(Userid__c=u1q2.id, Type__c='Round Robin User', Case_Teamid__c=q2.id, Assigned__c=true);
	        insert m3;
	        
	        Case_Member__c m4 = new Case_Member__c(Userid__c=u2q2.id, Type__c='Round Robin User', Case_Teamid__c=q2.id, Assigned__c=false);
	        insert m4;

	        Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
			insert flight;
	        
	        Test.startTest();
		    Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		    newCase.Flightid__c = flight.Id;
		    insert newCase;
		    newCase.OwnerId = u2q1.Id;
		    update newCase;
	        Test.stopTest();

	        caseMemberId = m1.Id;
        }
        Case_Member__c updateMember = [Select Assigned__c from Case_Member__c where Id=:caseMemberId limit 1];
        Assert.assertEquals(true, updateMember.Assigned__c);
	}
	
}