p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTI__c</fullName>
        <description>Counts all the CTI records on the case</description>
        <label>CTI</label>
        <summaryForeignKey>CTI__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <formula>if(Flightid__r.Sector__c == &quot;-&quot; || Flightid__r.Sector__c == null,&quot;XXX&quot;,Flightid__r.Sector__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/CTI__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Type__c</fullName>
        <description>Displays the Aircraft Type that the Case is related to (via Aircraft).</description>
        <formula>IF(NOT(ISBLANK(Flightid__r.Aircraft_Type__c)),Flightid__r.Aircraft_Type__c,&quot;Unidentified&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Aircraft Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <description>Flight area value which from Sector</description>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTI_Station__c</fullName>
        <description>Station that case occured. This field value is from user input.</description>
        <label>Station</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Case which CTI is related.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <description>Flight Carrier which flight reat to CTI&apos;s case</description>
        <formula>LEFT(Flight_Number_F__c , 2 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is look up to Object Flight to relate CTI with Flight.</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Return null value which used in DW report.</description>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STN__c</fullName>
        <description>To descibe Statin that case ocuured as &apos;Bangkok&apos;, &apos;Abroad&apos; &apos;Provincial&apos;, &apos;Unidentified&apos;.</description>
        <label>STN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Abroad</fullName>
                </value>
                <value>
                    <fullName>Provincial</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Flight&apos;s Sector from Sector_txt__c which have no &apos;-&apos; between 2 sector and default value as XXX. (e.g. BKKHKG)</description>
        <formula>IF( OR(Sector_txt__c = &quot;XXX&quot;,ISBLANK(Sector_txt__c)),&quot;XXX&quot;, 
LEFT(Sector_txt__c ,3) &amp; RIGHT(Sector_txt__c ,3))</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector_txt__c</fullName>
        <description>Flight&apos;s Sector from user input.</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CTI</label>
    <nameField>
        <displayFormat>CTI00{0000000000}</displayFormat>
        <label>CTI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/CTI_Area_with_Sector__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <label>Flight Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CTI Area with Sector</label>
</CustomObject>

prd_package/objects/CTI_Route_Area__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STN__c</fullName>
        <label>STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CTI Route Area (Mapping Station - STN)</label>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Type__c</fullName>
        <label>Aircraft Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block_Time__c</fullName>
        <description>Displays actual flying time in units of minutes</description>
        <label>Block Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Source__c</fullName>
        <label>Integration Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STA_LT__c</fullName>
        <label>STA LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/CTI_Management_Test.cls
@isTest
private class CTI_Management_Test {

    @testSetup
    static void MockData(){
        System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
        insert sysconfig;
        List<Flight__c> flightList = new List<Flight__c>();
        List<CTI_Route_Area__c> ctiRouteAreaList = new List<CTI_Route_Area__c>();
        List<CTI_Area_with_Sector__c> ctiAreaWithSectorList = new List<CTI_Area_with_Sector__c>();
        Flight__c flight1 = new Flight__c(
            Name = '0628',
            Flight_Number__c = 'TG0628',
            Flight_Date_UTC__c = '20Dec25',
            Flight_Date_LT__c = '20Dec25',
            STD_UTC__c = '20Dec25 0330',
            STD_LT__c  = '20Dec25 1030',
            STA_UTC__c = '20Dec25 0620',
            STA_LT__c = '20Dec25 1420',
            Block_Time__c = '170',
            Integration_Source__c = '1',
            Leg_Number__c = 1,
            Flight_External_ID__c = 'TG0628_20Dec25_1',
            Destination__c = 'ICN',
            Departure_STN__c = 'BKK',
            Arrival_STN__c = 'HKG',
            Aircraft_Type__c = '33H');
        flightList.add(flight1);
        System.debug('Test Method - Flight: ' + flight1);

        Flight__c flight2 = new Flight__c(
            Name = '0628',
            Flight_Number__c = 'TG0628',
            Flight_Date_UTC__c = '20Dec25',
            Flight_Date_LT__c = '20Dec25',
            STD_UTC__c = '20Dec25 0730',
            STD_LT__c  = '20Dec25 1450',
            STA_UTC__c = '20Dec25 1020',
            STA_LT__c = '20Dec25 1820',
            Block_Time__c = '170',
            Integration_Source__c = '1',
            Leg_Number__c = 1,
            Flight_External_ID__c = 'TG0628_20Dec25_2',
            Destination__c = 'ICN',
            Departure_STN__c = 'HKG',
            Arrival_STN__c = 'ICN',
            Aircraft_Type__c = '33H');
        flightList.add(flight2);

        Flight__c flight3 = new Flight__c(
            Name = 'TGXXX');
        flightList.add(flight3);

        CTI_Route_Area__c ctiRouteArea = new CTI_Route_Area__c(
            name='HKG', 
            STN__c='Abroad');
        ctiRouteAreaList.add(ctiRouteArea);

        CTI_Route_Area__c ctiRouteArea2 = new CTI_Route_Area__c(
            name='ICN', 
            STN__c='Abroad');
        ctiRouteAreaList.add(ctiRouteArea2);

        CTI_Area_with_Sector__c ctiAreaWithSector = new CTI_Area_with_Sector__c(
            Name = '628BKKHKG',
            Area__c = 'Northern', 
            Flight_Number__c = '628', 
            Region__c = 'Regional', 
            Sector__c = 'BKKHKG');
        ctiAreaWithSectorList.add(ctiAreaWithSector);

        CTI_Area_with_Sector__c ctiAreaWithSector2 = new CTI_Area_with_Sector__c(
            Name = '628HKGICN',
            Area__c = 'Northern', 
            Flight_Number__c = '628', 
            Region__c = 'Regional', 
            Sector__c = 'HKGICN');
        ctiAreaWithSectorList.add(ctiAreaWithSector2);

        CTI_Area_with_Sector__c ctiAreaWithSector3 = new CTI_Area_with_Sector__c(
            Name = 'XXXBKKHKG',
            Area__c = 'Northern', 
            Flight_Number__c = 'XXX', 
            Region__c = 'Regional', 
            Sector__c = 'BKKHKG');
        ctiAreaWithSectorList.add(ctiAreaWithSector3);

        insert flightList;
        insert ctiRouteAreaList;
        insert ctiAreaWithSectorList;

    }
    
    @isTest static void testInsertNewCTI() {
        Flight__c getFlight = [SELECT Id, Name FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1' LIMIT 1];
        Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
        newCase.Flightid__c = getFlight.Id;
        insert newCase;
        System.debug('Test Method - Case: ' + newCase);

        Test.startTest();

        CTI__c cti = new CTI__c(caseid__c=newCase.Id, CTI_Station__c='HKG', Sector_txt__c = 'BKK-HKG', FlightId__c = getFlight.Id);
        insert cti;
        System.debug('Test Method - Inserted CTI: ' + cti);
        Test.stopTest();

        CTI__c insertCti = [SELECT area__c, STN__c FROM CTI__c WHERE id =:cti.Id LIMIT 1];
        Assert.assertEquals('Northern', insertCti.area__c, 'Before Test Start - test area');
        Assert.assertEquals('Abroad', insertCti.STN__c, 'Before Test Start - test stn');
    }

    @isTest static void testUpdateCTI() {
        Flight__c getFlight1 = [SELECT Id, Name FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_1' LIMIT 1];
        Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
        newCase.Flightid__c = getFlight1.Id;
        insert newCase;

        CTI__c cti = new CTI__c(caseid__c=newCase.Id, CTI_Station__c = 'ICN', Sector_txt__c = 'HKG-ICN', FlightId__c = getFlight1.Id);
        insert cti;

        CTI__c insertCti = [SELECT area__c, STN__c FROM CTI__c WHERE id =:cti.Id limit 1];
        Assert.assertEquals('Northern', insertCti.area__c, 'Before Test Start 2 - test area');
        Assert.assertEquals('Abroad', insertCti.STN__c , 'Before Test Start 2 - test stn');

        Flight__c getFlight2 = [SELECT Id, Name FROM Flight__c WHERE Flight_External_ID__c = 'TG0628_20Dec25_2' LIMIT 1];

        Test.startTest();
        cti.flightid__c = getFlight2.Id;
        update cti;
        Test.stopTest();

        Assert.assertEquals('Northern', insertCti.area__c, 'After Test Start 2 - test area');
        Assert.assertEquals('Abroad', insertCti.STN__c , 'After Test Start 2 - test stn');
    }

    @isTest static void testTGXXXArea(){
        Flight__c getFlight1 = [SELECT Id, Name FROM Flight__c WHERE Name = 'TGXXX' LIMIT 1];
        Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
        newCase.Flightid__c = getFlight1.Id;
        insert newCase;

        Test.startTest();
        CTI__c cti = new CTI__c(caseid__c=newCase.Id, CTI_Station__c = 'BKK', Sector_txt__c = 'BKK-HKG', FlightId__c = getFlight1.Id);
        insert cti;
        Test.stopTest();

        CTI__c newcti = [SELECT Area__c FROM CTI__c WHERE Id = :cti.Id];
        System.debug('JK: testTGXXXArea - ' + JSON.serialize(newcti));

        System.assertEquals('Northern', newcti.Area__c, 'cti area should be Northern according to cti sector');
    }
    
}