p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SEQ_No_Display__c</fullName>
        <externalId>true</externalId>
        <label>Seq No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Void_AUTH_NO__c</fullName>
        <description>Displays the authorisation number of the personnel who voided the case</description>
        <label>Void AUTH NO.</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Void_Block_Name__c</fullName>
        <description>Displays the block name of the personnel who voided the case</description>
        <label>Void Block Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Void_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays the reason why the case is voided</description>
        <label>Void Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Void_Reason__c</fullName>
        <description>Used in VF page where it is then concatenated at the end of the Description field after voiding a maintenance Case.</description>
        <label>Void Reason</label>
        <length>111072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Void_Time__c</fullName>
        <label>Void Time</label>
        <type>DateTime</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/VoidCaseController.cls
global with sharing class VoidCaseController {

    public Case voidCase{get; set;}
    public String returl{get; set;}
    public String topurl{get; set;}
    public Id caseId{get; set;}
    public String seqNo{get; set;}
    public String fieldSetString{get; set;}

    public VoidCaseController() {
        caseId = Apexpages.currentpage().getparameters().get('id');
        voidCase = [SELECT Subject, Void_Time__c, Description, Void_Flag__c, Void_AUTH_NO__c, Void_Block_Name__c, Void_Reason__c, SEQ_No_Display__c FROM Case WHERE Id = :caseId];
        seqNo = voidCase.SEQ_No_Display__c;
        returl = Apexpages.Currentpage().getParameters().get('ret');
        topurl = Apexpages.Currentpage().getParameters().get('top');
        fieldSetString = JSON.serialize(Schema.SObjectType.Case.fieldSets.getMap().get('Void_Case').getFields());
    }

    @RemoteAction
    global static Case saveCase(Case inputCase, String voidCase){
        inputCase.Void_Time__c = System.now();
        inputCase.Description = voidCase != null ? voidCase + '\n\n' + inputCase.Void_AUTH_NO__c + ' ' + inputCase.Void_Block_Name__c + ' ' + inputCase.Void_Time__c  + ' \n' + inputCase.Void_Reason__c : inputCase.Void_AUTH_NO__c + ' ' + inputCase.Void_Block_Name__c + ' ' + inputCase.Void_Time__c  + ' \n' + inputCase.Void_Reason__c;
        inputCase.Void_Flag__c = true;
        update inputCase;
        return inputCase;
    }
}