p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Displays the value of case type used in case management</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commendation</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Incident</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Star Alliance</fullName>
                </value>
                <value>
                    <fullName>Baggage Claim</fullName>
                </value>
                <value>
                    <fullName>Court Case</fullName>
                </value>
                <value>
                    <fullName>14 CFR</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Arrival/Transit/Connections</fullName>
                </value>
                <value>
                    <fullName>Authorities and Airport Facilities</fullName>
                </value>
                <value>
                    <fullName>Boarding and Departure Area</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SPECIAL MEAL</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DGC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DBC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SEAT</fullName>
                </value>
                <value>
                    <fullName>Check-in &amp; Service pre-immigration-SPML</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - OTHER</fullName>
                </value>
                <value>
                    <fullName>General Comments on TG Services</fullName>
                </value>
                <value>
                    <fullName>Handling of flight Irregularities</fullName>
                </value>
                <value>
                    <fullName>Lounges</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>Unruly</fullName>
                </value>
                <value>
                    <fullName>Junk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Latest_Document__c</fullName>
        <label>Latest Document</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Letter_Body__c</fullName>
        <label>Letter Body</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <formula>TEXT(  Caseid__r.Case_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>ID of the case associated with this compensation.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the case group member associated with this compensation.</description>
        <label>Case Group Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CaseId__c</field>
                <operation>equals</operation>
                <valueField>Case_Group_Member__c.Caseid__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Group_Member__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compensation_Account_Center__c</fullName>
        <label>Compensation Account Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1030100</fullName>
                </value>
                <value>
                    <fullName>1015519</fullName>
                </value>
                <value>
                    <fullName>1301220</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Account_Number__c</fullName>
        <label>Compensation Account Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Center__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>631070</fullName>
                    <label>631070 - Baggage Claims Compensation</label>
                </value>
                <value>
                    <fullName>631071</fullName>
                    <label>631071 - Injury</label>
                </value>
                <value>
                    <fullName>631080</fullName>
                    <label>631080 - Compensation EX-Gratia Passenger Complaint&amp;Claim</label>
                </value>
                <value>
                    <fullName>631130</fullName>
                    <label>631130 - DBC / DGC</label>
                </value>
                <value>
                    <fullName>631140</fullName>
                    <label>631140 - Customer Relations EMD</label>
                </value>
                <value>
                    <fullName>631150</fullName>
                    <label>631150 - Inflight Service Compliment</label>
                </value>
                <value>
                    <fullName>811106</fullName>
                    <label>811106 -  Int.Charge for Other Flight Kitchen (for Lounge Access Voucher)</label>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PassengerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the passenger associated with this compensation.</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Print_Document_Controller_Test.cls
@isTest
private class Print_Document_Controller_Test {
	@testSetup static void DataPreparation(){
		MockupData_Test.initializeWebServiceCustomSetting();
		System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
		insert sysconfig;
	}

	static Print_Document_Controller getDefaultController() {
		return getDefaultController(false, false);
	}

	static Print_Document_Controller getDefaultController(Boolean setupAttachment, Boolean setupCaseGroupMember) {
		Flight__c flight = MockupData_Test.createFlight('0680', '30Sep16', 1);
		insert flight;

		Case newCase = MockupData_Test.createCase('UA007C011016', 'Open', 'CTI');
		newCase.Flightid__c = flight.Id;
		newCase.Case_Type__c = 'DBC';
		insert newCase;

		Compensation__c compensation = MockupData_Test.createCompensation(newCase.Id);
		compensation.Compensation_Account_Center__c = '1030100';
		compensation.Compensation_Account_Number__c = '631070';
		insert compensation;

		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'C');
		insert passenger;

		String attachmentName = 'version1';
		if (setupCaseGroupMember) {
			Case_Group_Member__c caseGroupMember = new Case_Group_Member__c();
			caseGroupMember.Caseid__c = newCase.Id;
			caseGroupMember.Passengerid__c = passenger.Id;
			insert caseGroupMember;
			attachmentName += caseGroupMember.Id;
		}
		attachmentName += 'PV';

		if (setupAttachment) {
			Attachment attachment = new Attachment(
			    ParentId = newCase.Id,
			    Description = attachmentName,
			    Name = attachmentName,
			    Body = Blob.valueOf('BodyVersion1'));
			insert attachment;
		}

		ApexPages.currentPage().getParameters().put('id', newCase.Id);

		ApexPages.StandardController stdCaseController = new ApexPages.StandardController(newCase);
		return new Print_Document_Controller(stdCaseController);
	}

	static List<Letter_Master__c> mockLetterMasterList() {
		List<Letter_Master__c> letterMasterList = new List<Letter_Master__c>();
		letterMasterList.add(MockupData_Test.createLetterMaster('EN', 'Letter EN 1'));
		letterMasterList.add(MockupData_Test.createLetterMaster('TH', 'Letter TH 1'));
		letterMasterList.add(MockupData_Test.createLetterMaster('TH', 'Letter TH 2'));
		return letterMasterList;
	}

	@isTest
	static void testGetTemplateList() {
		Print_Document_Controller ctrl = getDefaultController();
		ctrl.hasUpgradeDocumentPermission = false;
		List<SelectOption> options = ctrl.getTemplatelist();
		Assert.assertEquals(5, options.size());

		ctrl.hasUpgradeDocumentPermission = true;
		options = ctrl.getTemplatelist();
		Assert.assertEquals(7, options.size());
	}

	@isTest
	static void testGetTravelTypeList() {
		Print_Document_Controller ctrl = getDefaultController();
		List<SelectOption> options = ctrl.getTravelTypeList();
		Assert.assertEquals(2, options.size());
	}

	@isTest
	static void testSaveAndAttachWithNewVersion() {
		List<Attachment> initAttachments = [SELECT Id, Name, Description FROM Attachment];
		System.assertEquals(0, initAttachments.size());

		Print_Document_Controller ctrl = getDefaultController(true, true);
		ctrl.FilterTemplate = 'PV';
		ctrl.getOldVersionSelectOptions();
		ctrl.isNewVersion = true;
		ctrl.saveAndAttach();

		List<Attachment> attachments = [SELECT Id, Name, Description FROM Attachment];
		System.assertEquals(ctrl.attchmentMap.size(), attachments.size());
		System.assertEquals(ctrl.attchmentMap.values(), attachments);
	}

	@isTest
	static void testSaveAndAttachWithOldVersion() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		//ctrl.selec
		ctrl.FilterTemplate = 'PV';
		ctrl.getOldVersionSelectOptions();
		ctrl.isNewVersion = false;
		ctrl.selectedOldVersion = ctrl.attchmentMap.values().get(0).Id;
		ctrl.saveAndAttach();

		List<Attachment> attachments = [SELECT Id FROM Attachment];
		System.assertEquals(ctrl.attchmentMap.size(), attachments.size());
	}

	@isTest
	static void testGetOldVersionSelectOptions() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		List<SelectOption> options = ctrl.getOldVersionSelectOptions();
		Assert.assertEquals(0, options.size());
		ctrl.selectedCaseGroupMemberId = (new List<Id>(ctrl.caseGroupMemberMap.keySet())).get(0);
		ctrl.FilterTemplate = 'PV';
		options = ctrl.getOldVersionSelectOptions();
		Assert.assertEquals(1, options.size());
	}

	@isTest
	static void testGetPreviewURL() {
		Print_Document_Controller ctrl = getDefaultController();
		ctrl.comment = 'comment';
		String actualPreviewUrl = ctrl.getPreviewURL();
		Assert.assert(actualPreviewUrl.contains('/apex/LetterEN?id=' + ctrl.caseId));
		Assert.assert(actualPreviewUrl.contains('comment=comment'));
	}

	@isTest
	static void testAttachmentMapByCaseGroupMemberId() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
	}

	@isTest
	static void testGetSelectOptions() {
		Print_Document_Controller ctrl = getDefaultController();
		List<SelectOption> travelTypeOptions = ctrl.getTravelTypeList();
		Assert.assertEquals(2, travelTypeOptions.size());
	}

	@isTest
	static void testGetLetterBodyListOptions() {
		List<Letter_Master__c> letterMasterList = mockLetterMasterList();
		insert letterMasterList;

		Print_Document_Controller ctrl = getDefaultController();
		List<SelectOption> letterBodyOptions = ctrl.getLetterBodyList();
		Assert.assertEquals(1, letterBodyOptions.size());
	}

	@isTest
	static void testChangeDocument() {
		List<Letter_Master__c> letterMasterList = mockLetterMasterList();
		insert letterMasterList;

		Print_Document_Controller ctrl = getDefaultController();
		ctrl.changeDocument();
		Assert.assertEquals(true, ctrl.hasBody);
		Assert.assertEquals('Letter EN 1', ctrl.templateBody);

		ctrl.FilterTemplate = ctrl.LETTER_TH_2_PAGE_NAME;
		ctrl.changeDocument();
		Assert.assertEquals(true, ctrl.hasBody);
		Assert.assertEquals('Letter TH 1', ctrl.templateBody);
	}

	@isTest
	static void testChangeTemplate() {
		List<Letter_Master__c> letterMasterList = mockLetterMasterList();
		insert letterMasterList;

		Print_Document_Controller ctrl = getDefaultController();
		ctrl.letterBodyId = letterMasterList.get(0).Id;
		ctrl.changeTemplate();
		Assert.assertEquals(true, ctrl.hasBody);
		Assert.assertEquals('Letter EN 1', ctrl.templateBody);

		ctrl.letterBodyId = letterMasterList.get(2).Id;
		ctrl.changeTemplate();
		Assert.assertEquals(true, ctrl.hasBody);
		Assert.assertEquals('Letter TH 2', ctrl.templateBody);
	}

	@isTest
	static void testPreview() {
		List<Letter_Master__c> letterMasterList = mockLetterMasterList();
		insert letterMasterList;

		Print_Document_Controller ctrl = getDefaultController();
		ctrl.letterBodyId = letterMasterList.get(1).Id;
		ctrl.FilterTemplate = ctrl.LETTER_TH_1_PAGE_NAME;
		ctrl.changeTemplate();
		ctrl.templateBody = ctrl.templateBody += ' Edit';
		ctrl.updateBody();
		System.debug('SJ : ' + ctrl.caseId);
		Case actualCase = [SELECT Id, Letter_Body__c, Latest_Document__c, Latest_Template__c FROM Case WHERE Id = :ctrl.caseId];
		Assert.assertEquals('|Letter TH 1 Edit', actualCase.Letter_Body__c);
		Assert.assertEquals(ctrl.LETTER_TH_1_PAGE_NAME, actualCase.Latest_Document__c);
		Assert.assertEquals(ctrl.letterBodyId, actualCase.Latest_Template__c);
		ctrl.preview();
		actualCase = [SELECT Id, Letter_Body__c FROM Case WHERE Id = :ctrl.caseId];
		Assert.assertEquals(letterMasterList.get(1).Description__c , actualCase.Letter_Body__c);
	}

	@isTest 
	static void testSetSelectedAccountNumber() {
		Print_Document_Controller ctrl = getDefaultController();
		ctrl.selectedAccountNumber = '12345';
		System.assertEquals('12345', ctrl.selectedAccountNumberPartial);
		ctrl.selectedAccountNumber = '123456';
		System.assertEquals('123456', ctrl.selectedAccountNumberPartial);
		ctrl.selectedAccountNumber = '1234567';
		System.assertEquals('123456', ctrl.selectedAccountNumberPartial);
	}

	@isTest 
	static void testSetSelectedAccountCenter() {
		Print_Document_Controller ctrl = getDefaultController();
		ctrl.selectedAccountCenter = '123456';
		System.assertEquals('123456', ctrl.selectedAccountCenterPartial);
		ctrl.selectedAccountCenter = '1234567';
		System.assertEquals('1234567', ctrl.selectedAccountCenterPartial);
		ctrl.selectedAccountCenter = '12345678';
		System.assertEquals('1234567', ctrl.selectedAccountCenterPartial);
	}

	@isTest
	static void testGetAccountCenterSelectOptions() {
		Print_Document_Controller ctrl = getDefaultController();
		List<SelectOption> accountCenterSelectOptions = ctrl.getAccountCenterSelectOptions();
		Assert.assertEquals(1, accountCenterSelectOptions.size());
	}

	@isTest
	static void testGetAccountNumberSelectOptions() {
		Print_Document_Controller ctrl = getDefaultController();
		List<SelectOption> accountNumberSelectOptions = ctrl.getAccountNumberSelectOptions();
		Assert.assertEquals(1, accountNumberSelectOptions.size());
	}

	@isTest
	static void testGetCaseGroupMemberSelectOptions() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		List<SelectOption> cgmSelectOptions = ctrl.getCaseGroupMemberSelectOptions();
		Assert.assertEquals(1, cgmSelectOptions.size());
	}

	@isTest
	static void testChangePassenger() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		ctrl.selectedCaseGroupMemberId = ctrl.caseGroupMemberMap.values().get(0).Id;
		ctrl.changePassenger();
		Assert.assertNotEquals('', ctrl.passengerName);
	}

	@isTest
	static void testChangeToDisplayTHB() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		ctrl.displayTHB = true;
		ctrl.changeDisplayTHB();
		Assert.assertEquals('BAHT', ctrl.currencyWord);
		Assert.assertEquals('SATANG', ctrl.subCurrencyWord);
	}

	@isTest
	static void testChangeToDisplayNotTHB() {
		Print_Document_Controller ctrl = getDefaultController(true, true);
		ctrl.displayTHB = false;
		ctrl.targetCurrency = null;
		ctrl.changeDisplayTHB();
		System.debug('JK: targetCurrentcy - ' + ctrl.targetCurrency);
		Assert.assertEquals('[CURRENCY]', ctrl.currencyWord);
		Assert.assertEquals('[SUBCURRENCY]', ctrl.subCurrencyWord);
	}
}