p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>ID of the case associated with this compensation.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Compensation_Tools__c</fullName>
        <label>Compensation Tools</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Number__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Complimentary Ticket</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
                <value>
                    <fullName>Excess Baggage</fullName>
                </value>
                <value>
                    <fullName>Gifts</fullName>
                </value>
                <value>
                    <fullName>Lounge Access Voucher</fullName>
                </value>
                <value>
                    <fullName>Mileage Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upgrading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Approval_Email_Templete_Controller_Test.cls
@isTest
private class Approval_Email_Templete_Controller_Test {
	
	@isTest static void testConstructor() {
		MockupData_Test.initializeSystemConfigurationCustomSetting();
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CASE_TRIGGER, false);
		Case testCase = MockupData_Test.createCase(null, BE8_GlobalConstants.CASE_STATUS_PENDING, BE8_GlobalConstants.CASE_RECORD_TYPE_MAINTENANCE);
		insert testCase;
		Compensation__c compensation = new Compensation__c(CaseId__c = testCase.Id);
		compensation.Compensation_Tools__c = 'Cash';
		compensation.Status__c = BE8_GlobalConstants.CASE_STATUS_PENDING;
		insert compensation;
		Compensation__c compensation2 = new Compensation__c(CaseId__c = testCase.Id);
		compensation2.Compensation_Tools__c = 'Miles';
		compensation2.Status__c = BE8_GlobalConstants.CASE_STATUS_PENDING;
		insert compensation2;
		Apexpages.currentpage().getparameters().put('id', testCase.Id);
		Approval_Email_Templete_Controller ctrl = new Approval_Email_Templete_Controller();
		ctrl.getCompensations();
	}
}