p2ws_package/Devpp2ws-Package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>มูลค่าเป็นเงินของสิ่งที่ Compensate</description>
        <label>Amount (Cash/EMD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Compensation_Account_Center__c</fullName>
        <label>Compensation Account Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1030100</fullName>
                </value>
                <value>
                    <fullName>1015519</fullName>
                </value>
                <value>
                    <fullName>1301220</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Account_Number__c</fullName>
        <label>Compensation Account Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Center__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>631070</fullName>
                    <label>631070 - Baggage Claims Compensation</label>
                </value>
                <value>
                    <fullName>631071</fullName>
                    <label>631071 - Injury</label>
                </value>
                <value>
                    <fullName>631080</fullName>
                    <label>631080 - Compensation EX-Gratia Passenger Complaint&amp;Claim</label>
                </value>
                <value>
                    <fullName>631130</fullName>
                    <label>631130 - DBC / DGC</label>
                </value>
                <value>
                    <fullName>631140</fullName>
                    <label>631140 - Customer Relations EMD</label>
                </value>
                <value>
                    <fullName>631150</fullName>
                    <label>631150 - Inflight Service Compliment</label>
                </value>
                <value>
                    <fullName>811106</fullName>
                    <label>811106 -  Int.Charge for Other Flight Kitchen (for Lounge Access Voucher)</label>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>SO code of the currency. Must be one of the valid alphabetic, three-letter currency ISO codes defined by the ISO 4217 standard, such as USD, GBP, or JPY.</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>KHR</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>DKK</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>IRR</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>LAK</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>NPR</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>OMR</fullName>
                </value>
                <value>
                    <fullName>PKR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>LKR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Rate of exchange</description>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Compensation_Service.cls
public with sharing class Compensation_Service {
	public Compensation_Service() {
		
	}

	public static Decimal getAmountPerPassenger(Compensation__c compensation, Boolean displayTHB) {
		Decimal amount = 0;
		if(displayTHB) {
			if(compensation.Currency__c != 'THB' && compensation.ROE__c != null) {
				amount = compensation.Amount__c * compensation.ROE__c;
			} else {
				amount = compensation.Amount__c;
			}
		} else {
			amount = compensation.Amount__c;
		}
		return amount;
	}

	public static Boolean validateAccountNumberAndAccountCenter(List<Compensation__c> compensations) {
        String previousAccountNumber;
        String previousAccountCenter;
		for(Compensation__c eachCompensation : compensations) {
            Boolean isError = false;
            if(String.isNotBlank(previousAccountNumber)) {
                if(previousAccountNumber != eachCompensation.Compensation_Account_Number__c) {
                	return false;
                }
            }

            if(String.isNotBlank(previousAccountCenter)) {
                if(previousAccountCenter != eachCompensation.Compensation_Account_Center__c) {
                	return false;
                }
            }

            previousAccountNumber = eachCompensation.Compensation_Account_Number__c;
            previousAccountCenter = eachCompensation.Compensation_Account_Center__c;
        }
        return true;
	}
}