p2ws_package/Devpp2ws-Package/objects/Config_Parameter__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Config Parameter</label>
    <pluralLabel>Config Parameters</pluralLabel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Area__c</fullName>
        <label>Flight Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC_F__c</fullName>
        <formula>DATEVALUE( Flight_Date_UTC__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Date UTC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT_DateTime__c</fullName>
        <formula>DATETIMEVALUE( STD_LT__c )</formula>
        <label>STD LT DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduling_Type__c</fullName>
        <formula>CASE(MID(Flight_Number__c, 3, 1),
&quot;8&quot;, &quot;Non-Schedule&quot;,
&quot;Schedule&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Scheduling Type</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Cabin_Class_Description__c</fullName>
        <description>The full name of the Cabin Class which are</description>
        <formula>CASE( Cabin_Code__c ,
&quot;F&quot;, &quot;Royal First&quot;,
&quot;C&quot;, &quot;Royal Silk&quot;,
&quot;U&quot;, &quot;Premium Economy&quot;,
&quot;Y&quot;, &quot;Economy&quot;,
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cabin Class Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <description>Used for display</description>
        <label>Travel Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PaxKey__c</fullName>
        <formula>First_Name__c &amp; &apos;_&apos; &amp;  Last_Name__c &amp; &apos;_&apos; &amp;  PNR__c &amp; &apos;_&apos; &amp; Flight_Master__c</formula>
        <label>PaxKey</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/PAX_Flown_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Royal First</fullName>
                </value>
                <value>
                    <fullName>Royal Silk</fullName>
                </value>
                <value>
                    <fullName>Premium Economy</fullName>
                </value>
                <value>
                    <fullName>Economy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Data_Date_Key__c</fullName>
        <externalId>true</externalId>
        <label>Data Date Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Data_Date__c</fullName>
        <label>Data Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Area__c</fullName>
        <label>Flight Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Indo-China</fullName>
                </value>
                <value>
                    <fullName>Western</fullName>
                </value>
                <value>
                    <fullName>Southern</fullName>
                </value>
                <value>
                    <fullName>Northern</fullName>
                </value>
                <value>
                    <fullName>Middle-East</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Intercontinental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight_Scheduling_Type__c</fullName>
        <label>Flight Scheduling Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Schedule</fullName>
                </value>
                <value>
                    <fullName>Non-Schedule</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PAX_Flown_Summary__c</fullName>
        <label>PAX Flown Summary</label>
        <referenceTo>PAX_Flown_Summary__c</referenceTo>
        <relationshipLabel>PAX Flown Detail</relationshipLabel>
        <relationshipName>PAX_Flown_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Passengers__c</fullName>
        <label>Total Passengers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PAX Flown Detail</label>
    <nameField>
        <displayFormat>PXF-{00000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAX Flown Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/PAX_Flown_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Data_Date_Key__c</fullName>
        <description>yyyy-MM-dd example 2017-02-01. Always put day = 01</description>
        <externalId>true</externalId>
        <label>Data Date Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Date__c</fullName>
        <label>Data Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Passengers__c</fullName>
        <label>Total Passengers</label>
        <summarizedField>PAX_Flown_Detail__c.Total_Passengers__c</summarizedField>
        <summaryForeignKey>PAX_Flown_Detail__c.PAX_Flown_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>PAX Flown Summary</label>
    <nameField>
        <label>PAX Flown Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PAX Flown Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PaxFlownDetailBatch.cls
global class PaxFlownDetailBatch implements Database.Batchable<sObject>,Database.Stateful {
	
	String query;
	String flightDateText;
	Date flightDateUTC;
	Set<String> paxKeySet;
	Map<String,PAX_Flown_Detail__c> paxFlownDetailMap;
	PAX_Flown_Summary__c masterPaxFlownSummary;
	Boolean executeFlag = true;
	final String developerName ='Count_PAX_Flown_Backdate';
	
	global PaxFlownDetailBatch() {
		Integer pastDay;
		Config_Parameter__mdt[]  paxDetailConfigList = [SELECT DeveloperName,Id,Value__c FROM Config_Parameter__mdt where DeveloperName=:developerName LIMIT 1];
		if(!paxDetailConfigList.isEmpty() && paxDetailConfigList.get(0) !=NULL && paxDetailConfigList.get(0).Value__c !=NULL ){
			pastDay = Integer.valueOf(paxDetailConfigList.get(0).Value__c);
		}else{
			pastDay = 1;
		}

		Date today = System.today();
		flightDateUTC = today.addDays(-pastDay);
		flightDateText = DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),flightDateUTC.day()).format('YYYY-MM-dd');
		initData();
		setupQuery(pastDay);
	}

	global PaxFlownDetailBatch(String fixFlightDate) {//Input Format YYYY-MM-DD
		Date today = System.today();
		Date tempFlightDate = BE8_DateUtility.convertStringToDate(fixFlightDate);
		if(today.daysBetween(tempFlightDate) >= 0){
			executeFlag = false;
		}
		flightDateUTC = tempFlightDate;
		flightDateText = DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),flightDateUTC.day()).format('YYYY-MM-dd');
		initData();
		Integer pastDay = today.dayOfYear() - tempFlightDate.dayOfYear();
		setupQuery(pastDay);
	}

	private void setupQuery(Integer pastDay) {
		this.query = 'SELECT id, PaxKey__c ,Cabin_Class_Description__c, flightid__r.Flight_Date_UTC_F__c, flightid__r.Flight_Area__c, flightid__r.Flight_Region__c, flightid__r.Scheduling_Type__c FROM Passenger__c WHERE flightid__r.STD_LT_DateTime__c = N_DAYS_AGO:'+pastDay+' AND Checkin_Seat__c !=NULL  ORDER BY PaxKey__c';
	}

	private void initData(){
		paxKeySet = new Set<String>();
		paxFlownDetailMap = new Map<String,PAX_Flown_Detail__c>();
		if(executeFlag){
			String conditionDate = DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),01).format('YYYY-MM');
			List<PAX_Flown_Summary__c> paxSummaryList = [SELECT ID,Data_Date_Key__c from PAX_Flown_Summary__c where Data_Date_Key__c =:conditionDate ];
			if(paxSummaryList.isEmpty()){
				masterPaxFlownSummary = new PAX_Flown_Summary__c(Name=(DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),01).format('YYYY-MM')),Data_Date_Key__c=conditionDate,Data_Date__c=date.newInstance(flightDateUTC.year(),flightDateUTC.month(),01));
				insert masterPaxFlownSummary;
			}else{
				masterPaxFlownSummary = paxSummaryList.get(0);
			}
		}
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		if(executeFlag){
			return Database.getQueryLocator(query);
		}else{
			return null;
		}
		
	}

   	global void execute(Database.BatchableContext BC, List<Passenger__c> passengerList) {
   		String extKeyDetail;
		for(Passenger__c eachPassenger : passengerList){
			extKeyDetail = eachPassenger.Cabin_Class_Description__c+'_'+eachPassenger.flightid__r.Flight_Area__c+'_'+eachPassenger.flightid__r.Flight_Region__c+'_'+eachPassenger.flightid__r.Scheduling_Type__c+'_'+flightDateText;
			//System.debug('extKeyDetail : '+extKeyDetail);
			//System.debug('PaxKey__c : '+eachPassenger.PaxKey__c);
			if(!paxKeySet.contains(eachPassenger.PaxKey__c)){
				//System.debug('Count');
				if(paxFlownDetailMap.containsKey(extKeyDetail)){
					paxFlownDetailMap.get(extKeyDetail).Total_Passengers__c++;
				}else{
					paxFlownDetailMap.put(extKeyDetail,new PAX_Flown_Detail__c(Class__c=eachPassenger.Cabin_Class_Description__c,Flight_Area__c=eachPassenger.flightid__r.Flight_Area__c,Flight_Region__c=eachPassenger.flightid__r.Flight_Region__c,Flight_Scheduling_Type__c=eachPassenger.flightid__r.Scheduling_Type__c,PAX_Flown_Summary__c=masterPaxFlownSummary.id,Total_Passengers__c=1,Data_Date__c=flightDateUTC,Data_Date_Key__c=extKeyDetail));
					//System.debug('New Record');
				}
				//System.debug('Total_Passengers__c :'+paxFlownDetailMap.get(extKeyDetail).Total_Passengers__c);
				paxKeySet.add(eachPassenger.PaxKey__c);
			}

		}
	}
	
	global void finish(Database.BatchableContext BC) {
		if(paxFlownDetailMap.size() >0){
			//System.debug('paxFlownDetailMap :'+ paxFlownDetailMap);
			upsert paxFlownDetailMap.values() Data_Date_Key__c;
		}
	}
	
}