p2ws_package/Devpp2ws-Package/objects/Config_Parameter__mdt.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Config Parameter</label>
    <pluralLabel>Config Parameters</pluralLabel>
</CustomObject>

prd_package/classes/Assert.cls
public class Assert {
	public static Boolean needAssert;

	static {
		Config_Parameter__mdt needAssertParameter = [SELECT DeveloperName, Value__c FROM Config_Parameter__mdt WHERE DeveloperName = 'Assert'];
		needAssert = Boolean.valueOf(needAssertParameter.Value__c);
	}

	public static void assertEquals(Object expect, Object actual) {
		if(needAssert) {
			System.assertEquals(expect, actual);
		}
	}

	public static void assertEquals(Object expect, Object actual, String text) {
		if(needAssert) {
			System.assertEquals(expect, actual, text);
		}
	}

	public static void assertNotEquals(Object expect, Object actual) {
		if(needAssert) {
			System.assertNotEquals(expect, actual);
		}
	}

	public static void assertNotEquals(Object expect, Object actual, String text) {
		if(needAssert) {
			System.assertNotEquals(expect, actual, text);
		}
	}

	public static void assert(Boolean assertEquation) {
		if(needAssert) {
			System.assert(assertEquation);
		}
	}

	public static void assert(Boolean assertEquation, String text) {
		if(needAssert) {
			System.assert(assertEquation, text);
		}
	}
}