p2ws_package/Devpp2ws-Package/objects/CTI__c.object
<CustomObject>
    <fields>
        <fullName>Accepted_Class__c</fullName>
        <description>Passenger&apos;s Travel Class</description>
        <label>Accepted Class</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>U</fullName>
                </value>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                    <default>true</default>
                    <label>Unidentified</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <description>Flight Carrier which flight reat to CTI&apos;s case</description>
        <formula>LEFT(Flight_Number_F__c , 2 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is look up to Object Flight to relate CTI with Flight.</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>This field is for user input. Type value is concate between Type 1 and Type 2 which in format &apos;Type 1 &gt; Type 2&apos;.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Advertising</fullName>
                </value>
                <value>
                    <fullName>Aircraft</fullName>
                </value>
                <value>
                    <fullName>Alternative Flight Arrangement</fullName>
                </value>
                <value>
                    <fullName>Announcement / Information</fullName>
                </value>
                <value>
                    <fullName>Announcement in Lounge</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Cabin crew announcement</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Others</fullName>
                </value>
                <value>
                    <fullName>Announcement on Board &gt; Pilot announcement</fullName>
                </value>
                <value>
                    <fullName>Arrangement during irregularities</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Cabin Crew</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Check-in Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Check-in staff at Transfer desk</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Lost and Found Staff on Arrival</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Lounge Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Other Airport Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Other Arrival Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and care of Reservation and Ticketing Staff</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Special Unit Staff (LP-S)</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Special Unit staff (LP-S) on Arrival</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of staff at boarding and departure area</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Staff Concern</fullName>
                </value>
                <value>
                    <fullName>Attitude and care of Ticketing &amp; Reservation staff at Airport</fullName>
                </value>
                <value>
                    <fullName>Attitude and Care of Ticketing Staff at Airport</fullName>
                </value>
                <value>
                    <fullName>Availability of check-in counter</fullName>
                </value>
                <value>
                    <fullName>Baggage Handling at check-in</fullName>
                </value>
                <value>
                    <fullName>Baggage Handling on Arrival</fullName>
                </value>
                <value>
                    <fullName>Benefit/Privilege/Global Recognition</fullName>
                </value>
                <value>
                    <fullName>Beverage in Lounge</fullName>
                </value>
                <value>
                    <fullName>Boarding Announcement</fullName>
                </value>
                <value>
                    <fullName>Boarding Gate Location</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_Issue__c</fullName>
        <description>To identify type of CTI as &apos;Complaint&apos;, &apos;Commend&apos;, &apos;Suggstion&apos;.</description>
        <label>Type of Issue</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complaint</fullName>
                    <color>#FF9900</color>
                    <label>Complaint</label>
                </value>
                <value>
                    <fullName>Commendation</fullName>
                    <color>#33CC00</color>
                    <label>Commendation</label>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                    <color>#6600CC</color>
                    <label>Suggestion</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CTI</label>
    <nameField>
        <displayFormat>CTI00{0000000000}</displayFormat>
        <label>CTI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTTopCaseInFlight.cls
@RestResource(urlMapping = '/topcase/*')
global without sharing class MB_RESTTopCaseInFlight {

	global class TopCase {
		public String issueType;
		public String type;
		public Decimal total;
		public String flightNumber;
		public String tClass;
	}

	@HttpGet
	global static List<TopCase> getTopCase() {
		Set<Id> flightIdSet = BE8_GlobalUtility.getFlightIdSetFromUserId(UserInfo.getUserId());
		Map<Id, Flight__c> flightMap = new Map<Id, Flight__c>([SELECT Id, Flight_Number__c FROM Flight__c WHERE Id IN :flightIdSet]);
		Set<String> flightNumberSet = BE8_GlobalUtility.getStringSet('Flight_Number__c', flightMap.values());
		Set<String> caseTypeSet = new Set<String> {'Commendation', 'Complaint'};
		List<AggregateResult> ctiList = [SELECT COUNT(Id) Total, Type_of_Issue__c, Type__c, Accepted_Class__c, FlightId__r.Flight_Number__c  FROM CTI__c WHERE Type_of_Issue__c IN: caseTypeSet AND FlightId__r.Flight_Number__c IN: flightNumberSet AND CreatedDate = LAST_N_DAYS:30 GROUP BY Type_of_Issue__c, Type__c, Accepted_Class__c, FlightId__r.Flight_Number__c ORDER BY COUNT(Id) DESC];
		List<TopCase> topCaseList = new List<TopCase>();
		for (AggregateResult eachCTI : ctiList) {
			TopCase topCase = new TopCase();
			topCase.issueType = (String) eachCTI.get('Type_of_Issue__c');
			topCase.type = (String) eachCTI.get('Type__c');
			topCase.total = (Decimal) eachCTI.get('Total');
			topCase.flightNumber = (String) eachCTI.get('Flight_Number__c');
			topCase.tClass = (String) eachCTI.get('Accepted_Class__c');
			topCaseList.add(topCase);
		}
		return topCaseList;
	}
}