p2ws_package/Devpp2ws-Package/objects/Custom_Mail_List__mdt.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emergency Case</fullName>
                    <default>true</default>
                    <label>Emergency Case</label>
                </value>
                <value>
                    <fullName>Monitoring</fullName>
                </value>
                <value>
                    <fullName>ROP Enrollment</fullName>
                </value>
                <value>
                    <fullName>Upgrade Seat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Mail List</label>
    <pluralLabel>Custom Mail Lists</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/BE8_MasterData.cls
public with sharing class BE8_MasterData {
	private String masterDataName = '';
	private Boolean hasQueryAll = false;
	private String keyName = 'DeveloperName';

	private Map<String, SObject> objMapByName = new Map<String, SObject>();
	private Map<Id, SObject> objMapById = new Map<Id, SObject>();

    private static ProfileData instance = null;
    private Map<String, Profile> profileMapByName;
    private Map<Id, Profile> profileMapById;

	public BE8_MasterData(String masterDataName) {
		this.masterDataName = masterDataName;
		hasQueryAll = false;

		if(!Schema.getGlobalDescribe().get(this.masterDataName).getDescribe().fields.getMap().containsKey(keyName)) {
			keyName = 'Name';
		}
	}

	public SObject getObjectByName(String objectName) {
		if(!hasQueryAll) {
			queryAll();
		}

		if(objMapByName.containsKey(objectName)) {
			return objMapByName.get(objectName);
		}

		return null;
	}

	public void queryAll() {
		BE8_SoqlBuilder soql = new BE8_SoqlBuilder(this.masterDataName);
		soql.addField(new Set<String>{'Id', keyName});
		if(this.masterDataName == 'Custom_Mail_List__mdt') {
			soql.addField(new Set<String>{'Email_Address__c', 'Email_Type__c'});
		}

		String queryAllSoql = soql.getQueryStr();
		System.debug('queryAllSoql :'+ queryAllSoql);
        objMapById = BE8_CacheQuery.getInstance().query('all_' + this.masterDataName, queryAllSoql);
        for(sObject eachObject : objMapById.values()) {
        	objMapByName.put((String)eachObject.get(keyName), eachObject);
        }
	}
}