p2ws_package/Devpp2ws-Package/objects/Custom_Mail_List__mdt.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Type__c</fullName>
        <label>Email Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Emergency Case</fullName>
                    <default>true</default>
                    <label>Emergency Case</label>
                </value>
                <value>
                    <fullName>Monitoring</fullName>
                </value>
                <value>
                    <fullName>ROP Enrollment</fullName>
                </value>
                <value>
                    <fullName>Upgrade Seat</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Mail List</label>
    <pluralLabel>Custom Mail Lists</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MailList_Repository.cls
public with sharing class MailList_Repository{
    private static MailList_Repository instance = null;
    private Map<String, Map<String, String>> mailMap = new Map<String, Map<String,String>>();
    private static String defaultEmail = 'somwut.j@beryl8.com';
    public static Map<String, String> getEmailList(String type) {
        Map<String, Map<String, String>> mailMap = getInstance().mailMap;
        if(!mailMap.containsKey(type)) {
            Map<String, String> mailMapByDevName = new Map<String, String>();
            List<Custom_Mail_List__mdt> mails = [SELECT Id, DeveloperName, Email_Address__c, Email_Type__c FROM Custom_Mail_List__mdt WHERE Email_Type__c = :type];
            for(Custom_Mail_List__mdt eachMail : mails) {
                mailMapByDevName.put(eachMail.DeveloperName, eachMail.Email_Address__c);
            }
            mailMap.put(type, mailMapByDevName);
        } 
        return mailMap.get(type);
    }
    
    public static String getEmailAddress(String type, String key) {
        Map<String, String> mailMapByType = getEmailList(type);
        if(mailMapByType.containsKey(key)) {
            return mailMapByType.get(key);
        } else {
            return defaultEmail;
        }        
    }

    public static MailList_Repository getInstance() {
        if(instance == null) instance = new MailList_Repository();
        return instance;
    }
}