p2ws_package/Devpp2ws-Package/objects/Job_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Queued_Time__c</fullName>
        <description>The timestamp when this Job Queue entered Scheduled Job in Salesforce</description>
        <label>Queued Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the Job Queue has been scheduled</description>
        <label>Scheduled</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Queue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/ClearScheduledJobBatch.cls
global class ClearScheduledJobBatch implements Database.Batchable<sObject> {

	//String query = 'SELECT Id FROM AsyncApexJob WHERE status!=\'Completed\' AND status!=\'Aborted\' AND status != \'Failed\' ';
	String query = 'SELECT Id FROM Job_Queue__c WHERE Scheduled__c = true AND Queued_Time__c = null';

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		//for (AsyncApexJob each : (List<AsyncApexJob>)scope) {
		//	System.abortJob(each.Id);
		//}

		delete scope;
	}

	global void finish(Database.BatchableContext BC) {

	}

}