p2ws_package/Devpp2ws-Package/objects/LOPA_Label__mdt.object
<CustomObject>
    <fields>
        <fullName>Actual_Label__c</fullName>
        <label>Actual Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Version__c</fullName>
        <label>Cabin Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Temp_Label__c</fullName>
        <description>Temporary label that is generated by code</description>
        <label>Temp Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LOPA Label</label>
    <pluralLabel>LOPA Labels</pluralLabel>
</CustomObject>

prd_package/classes/LOPALabelRepository.cls
public with sharing class LOPALabelRepository {
	private Map<String, SObject> lopaLabelMap;

	public LOPALabelRepository(String cabinVersion) {
		List<LOPA_Label__mdt> lopaLabelList = [SELECT Id, DeveloperName, Temp_Label__c, Actual_Label__c FROM LOPA_Label__mdt WHERE Cabin_Version__c = :cabinVersion];
		lopaLabelMap = BE8_GlobalUtility.getSObjectMap('Temp_Label__c', lopaLabelList);
	}

	public String getActualLabelFromTempLabel(String tempLabel){
		if(lopaLabelMap.containsKey(tempLabel)){
			LOPA_Label__mdt label = (LOPA_Label__mdt) lopaLabelMap.get(tempLabel);
			return label.Actual_Label__c;
		} else {
			return null;
		}
	}
}