p2ws_package/Devpp2ws-Package/objects/ROP_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>PaxKey__c</fullName>
        <description>PaxKey of the passenger</description>
        <externalId>true</externalId>
        <label>PaxKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ROP Enrollment</label>
    <nameField>
        <label>ROP Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/classes/MB_RESTROPEnrollmentAttachment.cls
@RestResource(urlMapping = '/ropEnrollment/attachment/*')
global class MB_RESTROPEnrollmentAttachment {

	@HttpPost
	global static MB_RestRequestInfoModel.attachment_response doPost(MB_RestRequestInfoModel.attachment_list receiveAttachment) {
		ROP_Enrollment__c ropEnrollment = [SELECT Id FROM ROP_Enrollment__c WHERE PaxKey__c = : receiveAttachment.parentId LIMIT 1];
		return AttachmentService.createAttachmentFromMobile(ropEnrollment, receiveAttachment);
	}
}