p2ws_package/Devpp2ws-Package/objects/ROP_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <description>The date that this ROP Enrollment occured</description>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Type__c</fullName>
        <description>The type of enrollment whether it is via TG Web Service or manually enrolled</description>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web Service</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether this ROP Enrollment encountered error during Web Service Callout</description>
        <label>Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the ROP Enrollment whether</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Enroll</fullName>
                    <default>true</default>
                    <label>Enroll</label>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ROP Enrollment</label>
    <nameField>
        <label>ROP Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/ROPEnrollment_Success_Report_Test.cls
@isTest
private class ROPEnrollment_Success_Report_Test {

	@isTest
	static void testSendSummaryReport() {
		ROP_Enrollment__c ropEnrollment = new ROP_Enrollment__c();
		ropEnrollment.Enrollment_Date__c = System.today().addDays(-1);
		ropEnrollment.Enrollment_Type__c = 'Web Service';
		ropEnrollment.Integration_Error__c = false;
		ropEnrollment.Status__c = 'Enroll';
		insert ropEnrollment;

		ROPEnrollment_Success_Report report = new ROPEnrollment_Success_Report();
		report.sendSummaryReport();

		Assert.assertEquals(1, report.ropEnrollments.size());
	}

	@isTest
	static void testSchedule() {
		String CRON_EXP = '0 0 0 15 3 ? 2022';
		Test.startTest();
		String jobId = System.schedule('ScheduleApexClassTest',
                        CRON_EXP, 
                        new ROPEnrollment_Success_Report_Schedulable());
         
		CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
		System.assertEquals(CRON_EXP, ct.CronExpression);
		System.assertEquals(0, ct.TimesTriggered);
		System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));
		Test.stopTest();
	}
}