prd_package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Dislike__c</fullName>
        <label>Dislike (By In-Flight</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Information__c</fullName>
        <label>Information (By In-Flight)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Like__c</fullName>
        <label>Like (By In-Flight)</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>by_Ground_Customer_Service__c</fullName>
        <description>Displays the passenger psychological information written by ground service staff</description>
        <label>by Ground Customer Service</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>by_Sale_and_Marketing__c</fullName>
        <description>Customer Psychology by Sale and Marketing team</description>
        <label>by Sale and Marketing</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Aircraft__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Description__c</fullName>
        <label>A/C Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Aircraft</label>
    <nameField>
        <label>A/C REG</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aircrafts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Cases (Crew)</relationshipLabel>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Displays the frequent flyer program tier of the passenger that is related to the case</description>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Crew_First_Name__c</fullName>
        <description>First name of the crew.</description>
        <label>Crew First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Crew_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Mappings</relationshipLabel>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Crew Mapping</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Crew Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Aircraft_Description__c</fullName>
        <formula>AircraftId__r.Aircraft_Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>A/C Model</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STA_UTC__c</fullName>
        <label>STA UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_UTC__c</fullName>
        <label>STD UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that uses this membership</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Airline__c</fullName>
        <description>The airline that issued this membership</description>
        <label>Airline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Used for verifying result of PaxFlowDetail_Batch</description>
        <formula>FlightId__r.Flight_Date_UTC_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Date UTC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pax_Key_txt__c</fullName>
        <description>Text version of PaxKey__c</description>
        <externalId>true</externalId>
        <label>Pax Key txt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSR_Service__c</fullName>
        <label>Service</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SSR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SSR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Special_Meal__c</fullName>
        <label>Special Meal</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/MB_RESTPassengerServiceTest.cls
@isTest
private class MB_RESTPassengerServiceTest {

	@isTest static void testRetrievePassengerInfo() {
		TriggerActivator.overrideTriggerActivation(TriggerActivator.CREW_LIST_TRIGGER, false);

		Aircraft__c aircraft = MockupData_Test.getMockUpAircraft();
		insert aircraft;
		MockupData_Test.insertMockUpServiceEquipment();
		MockupData_Test.insertEquipmentOnAircraft(aircraft.Aircraft_Description__c);
		Flight__c flight = MockupData_Test.getMockUpFlight();
		flight.STD_UTC__c = String.valueOf(DateTime.now());
		flight.STA_UTC__c = String.valueOf(DateTime.now().addHours(10));
		flight.AircraftId__c = aircraft.Id;
		insert flight;
		Crew__c crew = new Crew__c (Crew_First_Name__c = 'TEST', Personel_Id__c = 'TEST');
		insert crew;
		Crew_List__c crewList = new Crew_List__c(CrewId__c = crew.Id, FlightId__c = flight.Id);
		insert crewList;
		Crew_Mapping__c crewMapping = new Crew_Mapping__c(CrewId__c = crew.Id, UserId__c = UserInfo.getUserId(), isActive__c = true, Last_Sync_Time__c = Datetime.now());
		insert crewMapping;

		Passenger__c passengerWithoutAccount = new Passenger__c(
		    Name = 'John Smith',
		    First_Name__c = 'John',
		    Last_Name__c = 'Smith',
		    FlightId__c = flight.Id
		);
		insert passengerWithoutAccount;

		Account account = new Account(Name = 'Alan Smith');
		insert account;
		Membership__c ropMembership = new Membership__c(Name = '12345', Airline__c = 'TG', AccountId__c = account.Id);
		insert ropMembership;
		Passenger__c passengerWithROP = new Passenger__c(
		    Name = 'Alan Smith',
		    First_Name__c = 'Alan',
		    Last_Name__c = 'Smith',
		    AccountId__c = account.Id,
		    FlightId__c = flight.Id,
		    FFP_Carrier__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY,
		    FFP_Number__c = '12345',
		    FFP_Tier__c = 'PLAT',
		    SSR__c = true,
		    SSR_Service__c = 'WCHS(Confirmed)',
		    Special_Meal__c = 'SFML[- NO Crab]'
		);
		insert passengerWithROP;

		List<MB_RestResponseInfoModel.passengerInfo_model> passengerModelList = MB_RESTPassengerService.retrievePassengerInfo();
		Assert.assertEquals(2, passengerModelList.size());
	}

	@isTest static void testGetPaxKey() {
		Flight__c flight = new Flight__c(Name = 'TG930 / 04MAR25', Flight_Number__c = 'TG0930', Leg_Number__c = 1, STD_UTC__c = '04Mar25 1730', STD_LT__c = '04Mar25 1830', STA_UTC__c = '04Mar25 2030', Flight_Date_UTC__c = '04Mar25', Flight_Date_LT__c = '04Mar25', Flight_External_Id__c = 'TG0930_04Mar25_1');
		insert flight;
		String firstName = 'JOHN MR';
		String lastName = 'SMITH';
		String pnr = '1234';
		Passenger__c pax = new Passenger__c(First_Name__c = firstName, Last_Name__c = lastName, PNR__c = pnr, FlightId__c = flight.Id);
		insert pax;
		Passenger__c queryPax = [SELECT Id, Pax_Key_txt__c FROM Passenger__c WHERE Id = :pax.Id];
		String paxKey = queryPax.Pax_Key_txt__c;
		Assert.assertEquals(firstName + '_' + lastName + '_' + pnr + '_TG0930_04Mar25', paxKey);
	}

	/*
		Scenario: Update Passenger Psychology of a Passenger with an Account
		Positive/Negative Case: Postive
		Expected Result:
		- Psychology fields in Account will be updated
	*/
	@isTest static void testUpdatePassengerPsychologyPositiveOneAccount(){
		String pLike = 'A';
		String dislike = 'B';
		String byOther = 'C';
		String byGnd = 'D';
		String bySale = 'E';

		Account testAccount = MockupData_Test.createAccount('Gas');
		insert testAccount;
		MB_RestRequestInfoModel.passengerPsychology_model paxPsy = new MB_RestRequestInfoModel.passengerPsychology_model();
		paxPsy.accId = testAccount.Id;
		paxPsy.pLike = pLike;
		paxPsy.dislike = dislike;
		paxPsy.byOther = byOther;
		paxPsy.byGnd = byGnd;
		paxPsy.bySale = bySale;

		List<MB_RestRequestInfoModel.passengerPsychology_model> paxPsyList = new List<MB_RestRequestInfoModel.passengerPsychology_model> {paxPsy};
		MB_RESTPassengerService.updatePassengerPsychology(paxPsyList);

		testAccount = [SELECT Id, Like__c, Dislike__c, Information__c, By_Ground_Customer_Service__c, By_Sale_and_Marketing__c FROM Account WHERE Id = :testAccount.Id LIMIT 1];
		Assert.assertEquals(pLike, testAccount.Like__c);
		Assert.assertEquals(dislike, testAccount.Dislike__c);
		Assert.assertEquals(byOther, testAccount.Information__c);
		Assert.assertEquals(byGnd, testAccount.By_Ground_Customer_Service__c);
		Assert.assertEquals(bySale, testAccount.By_Sale_and_Marketing__c);
	}

	/*
		Scenario: Update Passenger Psychology of two Passenger with two Account
		Positive/Negative Case: Postive
		Expected Result:
		- Psychology fields in Accounts will be updated
	*/
	@isTest static void testUpdatePassengerPsychologyPositiveTwoAccount(){
		String pLike = 'A';
		String dislike = 'B';
		String byOther = 'C';
		String byGnd = 'D';
		String bySale = 'E';

		Account testAccount = MockupData_Test.createAccount('Gas');
		insert testAccount;

		Account testAccount2 = MockupData_Test.createAccount('Vee');
		insert testAccount2;

		MB_RestRequestInfoModel.passengerPsychology_model paxPsy = new MB_RestRequestInfoModel.passengerPsychology_model();
		paxPsy.accId = testAccount.Id;
		paxPsy.pLike = pLike;
		paxPsy.dislike = dislike;
		paxPsy.byOther = byOther;
		paxPsy.byGnd = byGnd;
		paxPsy.bySale = bySale;

		MB_RestRequestInfoModel.passengerPsychology_model paxPsy2 = new MB_RestRequestInfoModel.passengerPsychology_model();
		paxPsy2.accId = testAccount2.Id;
		paxPsy2.pLike = pLike + '2';
		paxPsy2.dislike = dislike + '2';
		paxPsy2.byOther = byOther + '2';
		paxPsy2.byGnd = byGnd + '2';
		paxPsy2.bySale = bySale + '2';

		List<MB_RestRequestInfoModel.passengerPsychology_model> paxPsyList = new List<MB_RestRequestInfoModel.passengerPsychology_model> ();
		paxPsyList.add(paxPsy);
		paxPsyList.add(paxPsy2);
		MB_RESTPassengerService.updatePassengerPsychology(paxPsyList);

		testAccount = [SELECT Id, Like__c, Dislike__c, Information__c, By_Ground_Customer_Service__c, By_Sale_and_Marketing__c FROM Account WHERE Id = :testAccount.Id LIMIT 1];
		Assert.assertEquals(pLike, testAccount.Like__c);
		Assert.assertEquals(dislike, testAccount.Dislike__c);
		Assert.assertEquals(byOther, testAccount.Information__c);
		Assert.assertEquals(byGnd, testAccount.By_Ground_Customer_Service__c);
		Assert.assertEquals(bySale, testAccount.By_Sale_and_Marketing__c);

		testAccount2 = [SELECT Id, Like__c, Dislike__c, Information__c, By_Ground_Customer_Service__c, By_Sale_and_Marketing__c FROM Account WHERE Id = :testAccount2.Id LIMIT 1];
		Assert.assertEquals(pLike + '2', testAccount2.Like__c);
		Assert.assertEquals(dislike + '2', testAccount2.Dislike__c);
		Assert.assertEquals(byOther + '2', testAccount2.Information__c);
		Assert.assertEquals(byGnd + '2', testAccount2.By_Ground_Customer_Service__c);
		Assert.assertEquals(bySale + '2', testAccount2.By_Sale_and_Marketing__c);
	}

}