prd_package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_External_Id__c</fullName>
        <description>External ID :Firstname, Lastname, Birthdate, Passport/Travel Number</description>
        <externalId>true</externalId>
        <label>Customer External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailling_Address__c</fullName>
        <label>Mailling Address</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <label>Travel Document Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Document__c</fullName>
        <label>Travel Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Maintenance</fullName>
        <active>true</active>
        <businessProcess>Maintenance Case</businessProcess>
        <label>Maintenance</label>
    </recordTypes>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_1__c</fullName>
        <description>Used for display</description>
        <label>Email 1</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <description>Used for display</description>
        <label>Travel Document Expiry Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Number__c</fullName>
        <description>Used for display</description>
        <label>Travel Document Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/System_Configuration__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>AO_Baggage_Claim__c</fullName>
        <label>AO Baggage Claim</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Closed_Record_Type_ID__c</fullName>
        <label>Case Closed Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member_Record_Type_ID__c</fullName>
        <label>Case Group Member Record Type ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reminder_Time__c</fullName>
        <label>Reminder Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Chief_Queue_ID__c</fullName>
        <label>S3 Chief Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3_Tier_1_Queue_ID__c</fullName>
        <label>S3 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_First_Platinum_Queue_ID__c</fullName>
        <label>S4 First &amp; Platinum Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Ground_Queue_ID__c</fullName>
        <label>S4 Level 8 Ground Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_In_Flight_Queue_ID__c</fullName>
        <label>S4 Level 8 In-Flight Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Level_8_Queue_ID__c</fullName>
        <label>S4 Level 8 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_1_Queue_ID__c</fullName>
        <label>S4 Tier 1 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S4_Tier_2_Queue_ID__c</fullName>
        <label>S4 Tier 2 Queue ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>System Configuration</label>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Travel_Document__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the account that is the parent of this travel document.</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Travel Documents</relationshipLabel>
        <relationshipName>Travel_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExtDocument__c</fullName>
        <description>External Id :Travel document / Passport number</description>
        <externalId>true</externalId>
        <label>Ext Document</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Expiry_Date__c</fullName>
        <label>Travel Document Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Travel_Document_Number__c</fullName>
        <label>Travel Document Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Travel Document</label>
    <nameField>
        <displayFormat>TD-{0000000000}</displayFormat>
        <label>Reference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Travel Documents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/CreatePassengerFromPaxProcessBuilderTest.cls
@isTest
private class CreatePassengerFromPaxProcessBuilderTest {

	@testSetup static void DataForTest() {
		System_Configuration__c sysconfig = (System_Configuration__c)JSON.deserialize('{"Case_Closed_Record_Type_ID__c":"01228000000iqFZ","Case_Group_Member_Record_Type_ID__c":"01228000000iqFf","S3_Tier_1_Queue_ID__c":"00G28000002ZcPZ","S4_First_Platinum_Queue_ID__c":"00G28000002ZcPa","S4_Tier_1_Queue_ID__c":"00G28000002ZcPe","S4_Tier_2_Queue_ID__c":"00G28000002ZcPf","S4_Level_8_In_Flight_Queue_ID__c":"00G28000002ZcPc","S3_Chief_Queue_ID__c":"00G28000002ZcPY","S4_Level_8_Ground_Queue_ID__c":"00G28000002ZcPb","S4_Level_8_Queue_ID__c":"00G28000002ZcPd","AO_Baggage_Claim__c":"00G28000002ZcPX","Reminder_Time__c":"08.00"}', System_Configuration__c.class);
		insert sysconfig;
		Flight__c mockupFlight = MockupData_Test.createFlight('0517', '07Dec16', 1);
		insert mockupFlight;
		Passenger__c pax = new Passenger__c(
		    Name = 'Khun Toey',
		    First_Name__c = 'Toey',
		    Last_Name__c = 'Khun',
		    Email_1__c = 'toey.k@gmail.com',
		    Date_of_Birth_Input__c = Date.newInstance(1994, 11, 12),
		    FlightId__c = mockupFlight.Id,
		    Travel_Document_Number__c = 'TRAVELTEST01'
		);
		insert pax;
		Case newCase1 = MockupData_Test.createCase('BB001F071216', 'Open', 'Maintenance');
		Case newCase2 = MockupData_Test.createCase('BB002F071216', 'Open', 'Maintenance');
		Case newCase3 = MockupData_Test.createCase('BB003F071216', 'Open', 'Maintenance');
		newCase1.Passengerid__c = pax.Id;
		newCase2.Passengerid__c = pax.Id;
		newCase3.Passengerid__c = pax.Id;
		newCase1.Flightid__c = mockupFlight.Id;
		newCase2.Flightid__c = mockupFlight.Id;
		newCase3.Flightid__c = mockupFlight.Id;
		List<Case> caseList = new List<Case> {newCase1, newCase2, newCase3};
		insert caseList;
		CreatePassengerFromPaxProcessBuilder.createAccountFromPax(new List<Passenger__c> {pax});
	}

	@isTest static void testCreateAccountFromPaxShouldCreateAccountAndTravelDocumentWhen4KeyFromPaxAreInclude() {
		List<Account> accountList = [SELECT
		                             Id, Name,
		                             First_Name__c,
		                             Last_Name__c,
		                             Mailling_Address__c,
		                             Date_of_Birth__c,
		                             Travel_Document__c,
		                             Customer_External_Id__c
		                             FROM Account WHERE Customer_External_Id__c = 'Toey_Khun_12NOV94_TRAVELTEST01'];
		Account accountFromMethod = accountList.get(0);
		Account account = new Account(
		    Name = 'Khun Toey',
		    First_Name__c = 'Toey',
		    Last_Name__c = 'Khun',
		    Mailling_Address__c = 'toey.k@gmail.com',
		    Date_of_Birth__c = Date.newInstance(1994, 11, 12),
		    Travel_Document__c = 'TRAVELTEST01',
		    Travel_Document_Expiry_Date__c = null,
		    Customer_External_Id__c = 'Toey_Khun_12NOV94_TRAVELTEST01'
		);

		List<Travel_Document__c> travelList = [SELECT
		                                       Id,
		                                       ExtDocument__c,
		                                       Travel_Document_Number__c
		                                       FROM Travel_Document__c
		                                       WHERE AccountId__c = :accountList.get(0).Id];
		Travel_Document__c travelFromMethod = travelList.get(0);
		Travel_Document__c travel = new Travel_Document__c(
		    ExtDocument__c = 'TRAVELTEST01',
		    Travel_Document_Number__c = 'TRAVELTEST01'
		);
		System.assertEquals(account.Name, accountFromMethod.Name, 'Assert Equal Account Name');
		System.assertEquals(account.First_Name__c, accountFromMethod.First_Name__c, 'Assert Equal Account First Name');
		System.assertEquals(account.Last_Name__c, accountFromMethod.Last_Name__c, 'Assert Equal Account Last Name');
		System.assertEquals(account.Mailling_Address__c, accountFromMethod.Mailling_Address__c, 'Assert Equal Account Mailling Address');
		System.assertEquals(account.Date_of_Birth__c, accountFromMethod.Date_of_Birth__c, 'Assert Equal Account Date of Birth');
		System.assertEquals(account.Travel_Document__c, accountFromMethod.Travel_Document__c, 'Assert Equal Account Travel Document');
		System.assertEquals(account.Customer_External_Id__c, accountFromMethod.Customer_External_Id__c, 'Assert Equal Account Customer External ID');

		System.assertEquals(travel.ExtDocument__c, travelFromMethod.ExtDocument__c, 'Assert Equal Travel Document ExtDocument');
		System.assertEquals(travel.Travel_Document_Number__c, travelFromMethod.Travel_Document_Number__c, 'Assert Equal Travel Document Number');
	}

	@isTest static void testCreateAccountFromPaxShuoldCreateAccountAndCreateLookupRelationFromCaseToAccount() {
		List<Passenger__c> paxList = [SELECT Id FROM Passenger__c];
		System.assertEquals(1, paxList.size());
		Passenger__c pax = paxList.get(0);
		List<Case> casePaxList = [SELECT Id FROM Case WHERE Passengerid__c = :pax.Id];
		List<Account> accountList = [SELECT Id FROM Account WHERE Customer_External_Id__c = 'Toey_Khun_12NOV94_TRAVELTEST01'];
		Account account = accountList.get(0);
		List<Case> caseAccountList = [SELECT Id FROM Case WHERE AccountId = :account.Id];

		System.assertEquals(casePaxList.size(), caseAccountList.size(), 'Assert Equal Case Amount Between Passenger and Account');
	}
}