prd_package/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <description>Used for display</description>
        <externalId>true</externalId>
        <label>Routing</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that uses this membership</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EXTMember__c</fullName>
        <description>The External Id of this membership which is Airline__c + &apos;_&apos; + Name</description>
        <externalId>true</externalId>
        <label>EXT Member</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileages__c</fullName>
        <description>The overall mileages of this membership</description>
        <label>Mileages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Board_Point__c</fullName>
        <description>Board point of this passenger</description>
        <label>Board Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>Used for display. Value sent from backend</description>
        <label>Date of Birth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Upgrade_Seat_Priority__c</fullName>
        <label>Eligible for Upgrade Seat Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Upgrade_Seat__c</fullName>
        <label>Eligible for Upgrade Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP__c</fullName>
        <description>Display : FFP_Carrier__c-FFP_Number__c, Example TG-ZD95870</description>
        <formula>FFP_Carrier__c + &apos;-&apos; +  FFP_Number__c</formula>
        <label>FFP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Destination__c</fullName>
        <formula>FlightId__r.Destination__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Destination</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Origin__c</fullName>
        <formula>FlightId__r.Origin__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Origin</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Off_Point__c</fullName>
        <label>Off Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pax_Key_txt__c</fullName>
        <description>Text version of PaxKey__c</description>
        <externalId>true</externalId>
        <label>Pax Key txt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/MileageUpgradeSeatCalculatorTest.cls
@isTest
private class MileageUpgradeSeatCalculatorTest {

        private static testMethod void testPassengerBKKtoARNClassY() {
                String origin = 'BKK';
                String destination = 'ARN';
                String travelClass = 'Y';
                String ropNumber = 'AB123459';
                Set<String> originSet = new Set<String> {origin};
                Set<String> destinationSet = new Set<String> {destination};

                MileageUpgradeSeatCalculator calculator = new MileageUpgradeSeatCalculator(originSet, destinationSet);

                Flight__c flight = MockupData_Test.getMockUpFlight();
                flight.Origin__c = origin;
                flight.Destination__c = destination;
                flight.Departure_STN__c = origin;
                flight.Arrival_STN__c = destination;
                insert flight;

                Account acc = MockupData_Test.createAccount('TEST');
                insert acc;
                Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, travelClass);
                passenger.AccountId__c = acc.Id;
                insert passenger;
                passenger = [SELECT Id, FlightId__r.Routing__c, Pax_Key_txt__c, Eligible_for_Upgrade_Seat__c, Eligible_for_Upgrade_Seat_Priority__c, Last_Name__c, Board_Point__c, Off_Point__c,  Date_of_Birth_Input__c, Name, Cabin_Code__c, Flight_Origin__c, Flight_Destination__c, FFP__c, FFP_Number__c, FFP_Carrier__c, FlightId__r.Origin__c, FlightId__r.Destination__c, AccountId__r.Last_Name__c, AccountId__r.Date_of_Birth__c, FlightId__r.Departure_STN__c, FlightId__r.Arrival_STN__c FROM Passenger__c WHERE Id = : passenger.Id LIMIT 1];
                System.debug(passenger);
                Membership__c membership = MockupData_Test.createMembership();
                membership.Name = ropNumber;
                membership.EXTMember__c = CSE_SOAPUpdatePax_WS.getMemberExtId(BE8_GlobalConstants.DEFAULT_TG_COMPANY, ropNumber);
                membership.Mileages__c = 90000;
                membership.AccountId__c = acc.Id;
                insert membership;

                calculator.calculateEligibleSeatUpgrade(membership, new List<Passenger__c> {passenger});
                Assert.assert(passenger.Eligible_for_Upgrade_Seat__c != null, 'Eligible_for_Upgrade_Seat__c is not null.');
                Assert.assert(passenger.Eligible_for_Upgrade_Seat__c.contains('A066'), 'Passenger should be available for A058 upgrade.');
        }

        private static testMethod void testPassengerBKKtoHKGtoICNUpgradableFirstLegOnly() {
                String travelClass = 'Y';
                String ropNumber = 'AB123459';
                Set<String> originSet = new Set<String> {'BKK', 'HKG'};
                Set<String> destinationSet = new Set<String> {'ICN'};

                MileageUpgradeSeatCalculator calculator = new MileageUpgradeSeatCalculator(originSet, destinationSet);

                Flight__c flightFirstLeg = MockupData_Test.createFlight('TG628', '2017-03-03', 1);
                flightFirstLeg.Departure_STN__c = 'BKK';
                flightFirstLeg.Arrival_STN__c = 'HKG';
                insert flightFirstLeg;

                Flight__c flightSecondLeg = MockupData_Test.createFlight('TG628', '2017-03-03', 2);
                flightSecondLeg.Departure_STN__c = 'HKG';
                flightSecondLeg.Arrival_STN__c = 'ICN';
                insert flightSecondLeg;

                Account acc = MockupData_Test.createAccount('TEST');
                insert acc;

                Passenger__c passenger1 = MockupData_Test.createPassenger(flightFirstLeg.Id, travelClass);
                passenger1.AccountId__c = acc.Id;
                insert passenger1;

                Passenger__c passenger2 = MockupData_Test.createPassenger(flightSecondLeg.Id, travelClass);
                passenger2.AccountId__c = acc.Id;
                insert passenger2;

                passenger1 = [SELECT Id, FlightId__r.Routing__c, Pax_Key_txt__c, Eligible_for_Upgrade_Seat__c, Eligible_for_Upgrade_Seat_Priority__c, Last_Name__c, Board_Point__c, Off_Point__c,  Date_of_Birth_Input__c, Name, Cabin_Code__c, Flight_Origin__c, Flight_Destination__c, FFP__c, FFP_Number__c, FFP_Carrier__c, FlightId__r.Origin__c, FlightId__r.Destination__c, AccountId__r.Last_Name__c, AccountId__r.Date_of_Birth__c, FlightId__r.Departure_STN__c, FlightId__r.Arrival_STN__c FROM Passenger__c WHERE Id = : passenger1.Id LIMIT 1];
                passenger2 = [SELECT Id, FlightId__r.Routing__c, Pax_Key_txt__c, Eligible_for_Upgrade_Seat__c, Eligible_for_Upgrade_Seat_Priority__c, Last_Name__c, Board_Point__c, Off_Point__c,  Date_of_Birth_Input__c, Name, Cabin_Code__c, Flight_Origin__c, Flight_Destination__c, FFP__c, FFP_Number__c, FFP_Carrier__c, FlightId__r.Origin__c, FlightId__r.Destination__c, AccountId__r.Last_Name__c, AccountId__r.Date_of_Birth__c, FlightId__r.Departure_STN__c, FlightId__r.Arrival_STN__c FROM Passenger__c WHERE Id = : passenger2.Id LIMIT 1];

                Membership__c membership = MockupData_Test.createMembership();
                membership.Name = ropNumber;
                membership.EXTMember__c = CSE_SOAPUpdatePax_WS.getMemberExtId(BE8_GlobalConstants.DEFAULT_TG_COMPANY, ropNumber);
                membership.Mileages__c = 60000;
                membership.AccountId__c = acc.Id;
                insert membership;

                calculator.calculateEligibleSeatUpgrade(membership, new List<Passenger__c> {passenger1, passenger2});
                //Assert.assert(passenger1.Eligible_for_Upgrade_Seat__c != null, 'Eligible_for_Upgrade_Seat__c is not null.');
                System.debug('JK: pax1 - ' + JSON.serialize(passenger1));
                System.debug('JK: pax2 - ' + JSON.serialize(passenger2));
                Assert.assert(passenger1.Eligible_for_Upgrade_Seat__c.contains('A027'), 'Passenger should be available for A027 upgrade.');
                Assert.assert(!passenger1.Eligible_for_Upgrade_Seat__c.contains('A085'), 'Passenger should not be available for A085 upgrade, because this passenger is in the second leg of the flight.');
                Assert.assert(passenger2.Eligible_for_Upgrade_Seat__c.contains('A085'), 'Passenger should be available for A085 upgrade.');
                Assert.assert(!passenger2.Eligible_for_Upgrade_Seat__c.contains('A027'), 'Passenger should not be available for A027 upgrade, because this passenger is in the second leg of the flight.');
        }

}