prd_package/objects/Aircraft_Station__mdt.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Name__c</fullName>
        <label>Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Aircraft Station</label>
    <pluralLabel>Aircraft Stations</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Condition_Multi__c</fullName>
        <description>Displays all the available defect condition for equipments (maintenance case)</description>
        <label>Condition</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ACTIVATE / DEACTIVATE</fullName>
                </value>
                <value>
                    <fullName>ADJUST</fullName>
                </value>
                <value>
                    <fullName>BREAK</fullName>
                </value>
                <value>
                    <fullName>BURST</fullName>
                </value>
                <value>
                    <fullName>CLOG</fullName>
                </value>
                <value>
                    <fullName>COMPLETE / INCOMPLETE</fullName>
                </value>
                <value>
                    <fullName>CONNECT / DISCONNECT</fullName>
                </value>
                <value>
                    <fullName>CONTROL / UNCONTROL</fullName>
                </value>
                <value>
                    <fullName>CHANGE</fullName>
                </value>
                <value>
                    <fullName>DENT</fullName>
                </value>
                <value>
                    <fullName>DEVIATE</fullName>
                </value>
                <value>
                    <fullName>DECLINE</fullName>
                </value>
                <value>
                    <fullName>DISTORT</fullName>
                </value>
                <value>
                    <fullName>ERASE</fullName>
                </value>
                <value>
                    <fullName>FIT</fullName>
                </value>
                <value>
                    <fullName>FIX</fullName>
                </value>
                <value>
                    <fullName>HISSING (NOISE)</fullName>
                </value>
                <value>
                    <fullName>ILLUMINATE</fullName>
                </value>
                <value>
                    <fullName>INOPERATIVE (INOP)</fullName>
                </value>
                <value>
                    <fullName>INSTALL</fullName>
                </value>
                <value>
                    <fullName>JUMP</fullName>
                </value>
                <value>
                    <fullName>LEAK</fullName>
                </value>
                <value>
                    <fullName>LIFT</fullName>
                </value>
                <value>
                    <fullName>LOOSE</fullName>
                </value>
                <value>
                    <fullName>MALFUNCTION</fullName>
                </value>
                <value>
                    <fullName>MISSING</fullName>
                </value>
                <value>
                    <fullName>MOUNT</fullName>
                </value>
                <value>
                    <fullName>OUT OF ORDER</fullName>
                </value>
                <value>
                    <fullName>OVERFLOW</fullName>
                </value>
                <value>
                    <fullName>PEEL OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Maintenance</fullName>
        <active>true</active>
        <businessProcess>Maintenance Case</businessProcess>
        <label>Maintenance</label>
    </recordTypes>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Master_Map__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Description__c</fullName>
        <description>Aircraft Model</description>
        <label>Aircraft Model</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Ver__c</fullName>
        <description>Cabin Ver.</description>
        <label>Cabin Ver.</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Check_by_CA_s_station__c</fullName>
        <description>Check by CA&apos;s station</description>
        <label>Check by CA&apos;s station</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checked_Procedure__c</fullName>
        <description>Checked Procedure</description>
        <label>Checked Procedure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Code__c</fullName>
        <description>Primary External Key for master data</description>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Depend_On_Object_Name__c</fullName>
        <description>Refer to value of parent data level 1</description>
        <formula>Depend_On_Object__r.Name</formula>
        <label>Depend On Object Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depend_On_Object__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refer to parent data level 1</description>
        <label>Depend On Object</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Master Maps</relationshipLabel>
        <relationshipName>Depend_On_Object</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Depend_On_Value__c</fullName>
        <description>Refer to value of parent data as text</description>
        <label>Depend On Value</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Equipment_Type__c</fullName>
        <description>Define type of safety equipment</description>
        <label>Equipment Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>Define type of data</description>
        <externalId>true</externalId>
        <label>Field Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <description>Store parts location on specific aircraft</description>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity_to_be_checked__c</fullName>
        <description>Store amount of parts on specific location of aircraft</description>
        <label>Quantity to be checked</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <description>Total number of equipment item</description>
        <label>Total</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Master Map</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Map</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTMasterDataMaintenanceAppService.cls
@RestResource(urlMapping = '/masterdata/maintenance/*')
global class MB_RESTMasterDataMaintenanceAppService {

	global class MasterData {
		public List<Station> station;
		public List<Equipment> equipment;
		public List<String> condi;
	}

	global class Station {
		public String code;
		public String name;
		public String address;
	}

	global class Equipment {
		public String id;
		public String type;
		public String eqType;
		public String zone;
		public String location;
		public String name;
		public String ataCh;
		public String cCA;
		public String cPro;
		public String descr;
		public String qty;
		public String total;
		public String cabinVer;
		public String airDec;
		public Part[] part;
	}

	global class Part {
		public String id;
		public String name;
	}

	@HttpGet
	global static MasterData getMasterData() {
		MasterData result = new MasterData();
		result.station = new List<Station>();
		List<Aircraft_Station__mdt> stationList = [SELECT Id, Code__c, Full_Name__c, Address__c FROM Aircraft_Station__mdt];
		for (Aircraft_Station__mdt each : stationList) {
			Station eachStation = new Station();
			eachStation.code = each.Code__c;
			eachStation.name = each.Full_Name__c;
			eachStation.address = each.Address__c;
			result.station.add(eachStation);
		}

		List<Master_Map__c> generalEquipmentList = [SELECT Id, Check_by_CA_s_station__c, Checked_Procedure__c, Description__c, Quantity_to_be_checked__c, Total__c, Depend_On_Value__c, Cabin_Ver__c, Depend_On_Object_Name__c, Name, Aircraft_Description__c, Equipment_Type__c, Location__c, Field_Name__c, (SELECT Id, Name, Field_Name__c FROM Depend_On_Object__r) FROM Master_Map__c WHERE Field_Name__c = :BE8_GlobalConstants.SERVICE_EQUIPMENT AND Aircraft_Description__c = null];
		List<Master_Map__c> equipmentByAircraft = [SELECT Id, Check_by_CA_s_station__c, Checked_Procedure__c, Description__c, Quantity_to_be_checked__c, Total__c, Name, Depend_On_Object_Name__c , Cabin_Ver__c, Aircraft_Description__c, Depend_On_Value__c, Equipment_Type__c, Location__c, Field_Name__c FROM Master_Map__c WHERE Aircraft_Description__c != null];
		
		List<Master_Map__c> allEquipmentList = new List<Master_Map__c>();
		allEquipmentList.addAll(generalEquipmentList);
		allEquipmentList.addAll(equipmentByAircraft);

		List<Equipment> equipmentList = new List<Equipment>();
		for (Master_Map__c eachEquipment : allEquipmentList) {
				Equipment eModel = new Equipment();
				eModel.id = eachEquipment.Id;
				eModel.type = eachEquipment.Field_Name__c;
				eModel.eqType = eachEquipment.Equipment_Type__c;
				eModel.zone = eachEquipment.Check_by_CA_s_station__c;
				eModel.location = eachEquipment.Location__c;
				eModel.name = eachEquipment.Name;
				eModel.ataCh = eachEquipment.Depend_On_Object_Name__c;
				eModel.cCA = eachEquipment.Check_by_CA_s_station__c;
				eModel.cPro = eachEquipment.Checked_Procedure__c;
				eModel.descr = eachEquipment.Description__c;
				eModel.qty = '' + eachEquipment.Quantity_to_be_checked__c;
				eModel.total = '' + eachEquipment.Total__c;
				eModel.cabinVer = eachEquipment.Cabin_Ver__c;
				eModel.airDec = eachEquipment.Aircraft_Description__c;
				eModel.part = new List<Part>();
				if (eachEquipment.Depend_On_Object__r != null) {
					for (Master_Map__c eachPart : eachEquipment.Depend_On_Object__r) {
						Part pModel = new Part();
						pModel.id = eachPart.Id;
						pModel.name = eachPart.Name;
						eModel.part.add(pModel);
					}
				}
				equipmentList.add(eModel);
		}
		result.equipment = equipmentList;
        
        result.condi = new List<String>();
        for (Schema.PicklistEntry each : Case.Condition_Multi__c.getDescribe().getPicklistValues()) {
			result.condi.add(each.getValue());
		}
		return result;
	}
}