prd_package/objects/Case_Member__c.object
<CustomObject>
    <fields>
        <fullName>Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Teamid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>relate case team object</description>
        <label>Case Team</label>
        <referenceTo>Case_Team__c</referenceTo>
        <relationshipLabel>Case Members</relationshipLabel>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address for the passenger.</description>
        <label>Email</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Last_Assigned_Time__c</fullName>
        <label>Last Assigned Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Queueid__c</fullName>
        <description>This field use mapping with case owner for point to Case Team</description>
        <formula>Case_Teamid__r.Queue_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Queueid</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Status__c</fullName>
        <description>Display round robin status of member</description>
        <formula>IMAGE(CASE( Type__c, 
&quot;Internal User&quot;, &quot;/resource/icon_case/Priority_High.png&quot;, 
&quot;Round Robin User&quot;, IF(Assigned__c == true,&quot;/resource/icon_case/Priority_Low.png&quot;,&quot;/resource/icon_case/Priority_Medium.png&quot;),  
&quot;/resource/icon_case/Priority_High.png&quot;),&quot;&quot;,24,24)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Display role of member</description>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Booking through TG website</fullName>
                </value>
                <value>
                    <fullName>Ticket Receipt</fullName>
                </value>
                <value>
                    <fullName>BKK Reservation (Thai Contact Center)</fullName>
                </value>
                <value>
                    <fullName>Reservation System Service Management</fullName>
                </value>
                <value>
                    <fullName>Ticketing Dept.</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Larnluang Office</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Head office (Vibhavadee)</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Silom office</fullName>
                </value>
                <value>
                    <fullName>E-Ticketing</fullName>
                </value>
                <value>
                    <fullName>Airport Ticket Office</fullName>
                </value>
                <value>
                    <fullName>Refund office</fullName>
                </value>
                <value>
                    <fullName>Passenger Refund</fullName>
                </value>
                <value>
                    <fullName>Agency Sales</fullName>
                </value>
                <value>
                    <fullName>Airline Industry Relations</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - International</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - Domestic</fullName>
                </value>
                <value>
                    <fullName>Departure - Airside</fullName>
                </value>
                <value>
                    <fullName>BKK Station Manager / Duty Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Service</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Support Dept.</fullName>
                </value>
                <value>
                    <fullName>Baggage Services Dept.</fullName>
                </value>
                <value>
                    <fullName>BKK Lounges</fullName>
                </value>
                <value>
                    <fullName>Lounges at abroad</fullName>
                </value>
                <value>
                    <fullName>Stations</fullName>
                </value>
                <value>
                    <fullName>Load Control</fullName>
                </value>
                <value>
                    <fullName>Ground Support Equipment Operations Control Dept.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Display type of member</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>External User</fullName>
                </value>
                <value>
                    <fullName>Internal User</fullName>
                </value>
                <value>
                    <fullName>Investigation Staff</fullName>
                </value>
                <value>
                    <fullName>Round Robin User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relate with user object</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Case_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays the Status active or inactive for the Case Teams</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Team</label>
    <nameField>
        <label>Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/Round_Robin_Controller.cls
public without sharing class Round_Robin_Controller {

    private static Map<id, list<Case_Member__c>> Mapgroupwithmember;
    private static list<Case_Member__c> listgroupmember;

    static {
        getgroupmember(); //Query and put value to Mapgroupwithmember.
        System.debug('### Map Group with Member : ' + Mapgroupwithmember);
    }


public static void roundrobin_method(list<case> listcase) {

        Map<Case_Member__c, Case_Member__c> mapmemberrecieve = new Map<Case_Member__c, Case_Member__c>();
        Set<Case_Member__c> listfirstmember = new Set<Case_Member__c>();

        for (Case thiscase : listcase) {
            id ownerresultid = thiscase.ownerid;
            Boolean firstroundrobin = true;

            System.debug('### Case Owner id : ' + thiscase.ownerid);

            if (Mapgroupwithmember.ContainsKey(thiscase.ownerid)) {
                list<Case_Member__c> listmember = Mapgroupwithmember.get(thiscase.ownerid);
                Integer i = 0;

                System.debug('### list member size : ' + listmember.size());

                if (listmember.size() > 0) {
                    for (Case_Member__c mb : listmember) {
                        if (mb.Assigned__c) {

                            Case_Member__c lastmember = mb;
                            Case_Member__c thismember = listmember[0];

                            System.debug('### lastmember : ' + mb.Userid__r.name);
                            System.debug('### thismember : ' + listmember[0].Userid__r.name);
                            System.debug('### current i : ' + i);

                            if (i == (listmember.size() - 1))
                                thismember = listmember[0];
                            else
                                thismember = listmember[i + 1];

                            thiscase.ownerid = thismember.userid__c;
                            System.debug('### ownerresultid : ' + ownerresultid);
                            mapmemberrecieve.put(thismember, lastmember);

                            firstroundrobin = false;

                            break;
                        }

                        i++;
                    }

                    if (firstroundrobin) {
                        thiscase.ownerid = listmember[0].userid__c;
                        listfirstmember.add(listmember[0]);
                    }
                }

            }

            System.debug('### Map not containskey : ');
        }

        if (mapmemberrecieve.size() > 0) {
            Markmemberrecieved(mapmemberrecieve);
        }

        if (listfirstmember.size() > 0) {
            Markfirstmemberrecieved(listfirstmember);
        }


        System.debug('### Map size member : ' + mapmemberrecieve.size() + ' ### list size first member : ' + listfirstmember.size());
    }

    public static void roundrobin_method(list<case> listcase, Map<Id, User> roleMap, Map<Id, Case> oldCaseMap) {

        Map<Case_Member__c, Case_Member__c> mapmemberrecieve = new Map<Case_Member__c, Case_Member__c>();
        Set<Case_Member__c> listfirstmember = new Set<Case_Member__c>();

        for (Case thiscase : listcase) {
            id ownerresultid = thiscase.ownerid;
            Boolean firstroundrobin = true;

            System.debug('### Case Owner id : ' + thiscase.ownerid);

            if (Mapgroupwithmember.ContainsKey(thiscase.ownerid)) {
                list<Case_Member__c> listmember = Mapgroupwithmember.get(thiscase.ownerid);
                Integer i = 0;

                System.debug('### list member size : ' + listmember.size());

                if (listmember.size() > 0) {
                    for (Case_Member__c mb : listmember) {
                        if (mb.Assigned__c) {

                            Case_Member__c lastmember = mb;
                            Case_Member__c thismember = listmember[0];

                            System.debug('### lastmember : ' + mb.Userid__r.name);
                            System.debug('### thismember : ' + listmember[0].Userid__r.name);
                            System.debug('### current i : ' + i);

                            if (i == (listmember.size() - 1))
                                thismember = listmember[0];
                            else
                                thismember = listmember[i + 1];

                            thiscase.ownerid = thismember.userid__c;
                            System.debug('### ownerresultid : ' + ownerresultid);
                            mapmemberrecieve.put(thismember, lastmember);

                            firstroundrobin = false;
                            //Case_Management.updateCaseOnEscalatedStatus(thiscase, roleMap, oldCaseMap);

                            break;
                        }

                        i++;
                    }

                    if (firstroundrobin) {
                        thiscase.ownerid = listmember[0].userid__c;
                        listfirstmember.add(listmember[0]);
                        //Case_Management.updateCaseOnEscalatedStatus(thiscase, roleMap, oldCaseMap);
                    }
                }
            }

            System.debug('### Map not containskey : ');
        }

        if (mapmemberrecieve.size() > 0) {
            Markmemberrecieved(mapmemberrecieve);
        }

        if (listfirstmember.size() > 0) {
            Markfirstmemberrecieved(listfirstmember);
        }


        System.debug('### Map size member : ' + mapmemberrecieve.size() + ' ### list size first member : ' + listfirstmember.size());
    }

    private static void Markmemberrecieved(Map<Case_Member__c, Case_Member__c> mapmemberrecieve) {
        List<Case_Member__c> caseMemberListForUpdate = new List<Case_Member__c>();
        for (Case_Member__c thismember : mapmemberrecieve.Keyset()) {
            if (mapmemberrecieve.Containskey(thismember)) {
                Case_Member__c lastmember = mapmemberrecieve.get(thismember);
                thismember.Assigned__c = true;
                thismember.Last_Assigned_Time__c = System.now();
                lastmember.Assigned__c = false;
                caseMemberListForUpdate.add(thismember);
                caseMemberListForUpdate.add(lastmember);
            }
        }
        if(!caseMemberListForUpdate.isEmpty()) {
            //Edit By JK
            Set<Case_Member__c> caseMemberSetForUpdate = new Set<Case_Member__c>(caseMemberListForUpdate);
            update new List<Case_Member__c>(caseMemberSetForUpdate);
            //
            //update caseMemberListForUpdate;
        }
    }

    private static void Markfirstmemberrecieved(Set<Case_Member__c> listfirstmember) {

        List<Case_Member__c> listthismember = new List<Case_Member__c>();

        //This method for mark current assigned member and clear previous assigned member.
        for (Case_Member__c thismember : listfirstmember) {

            thismember.Assigned__c = true;
            thismember.Last_Assigned_Time__c = System.now();
            listthismember.add(thismember);
        }

        update listthismember;
    }

    private static void getgroupmember() {
        Mapgroupwithmember = new Map<id, list<Case_Member__c>>();

        if (listgroupmember == null) {
            listgroupmember = [Select id, name, assigned__c, Last_Assigned_Time__c, Case_Teamid__c, Userid__r.Isactive,
                               Round_Robin_Status__c, Userid__c, Userid__r.name, Type__c, Tier__c, Email__c, Queueid__c
                               from Case_Member__c
                               where Type__c = 'Round Robin User' and Case_Teamid__r.active__c = true and Userid__r.Isactive = true 
                                               order by id ASC];
        }

        if (listgroupmember.size() > 0) {
            for (Case_Member__c gm : listgroupmember) {
                list<Case_Member__c> listnewmember = new list<Case_Member__c>();
                if (Mapgroupwithmember.ContainsKey(gm.Queueid__c)) {
                    listnewmember = Mapgroupwithmember.get(gm.Queueid__c);
                    listnewmember.add(gm);
                    Mapgroupwithmember.put(gm.Queueid__c, listnewmember);
                } else {
                    listnewmember.add(gm);
                    Mapgroupwithmember.put(gm.Queueid__c, listnewmember);
                }
            }

        }
    }

}