prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CTI__c</fullName>
        <description>Counts all the CTI records on the case</description>
        <label>CTI</label>
        <summaryForeignKey>CTI__c.Caseid__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <formula>if(Flightid__r.Sector__c == &quot;-&quot; || Flightid__r.Sector__c == null,&quot;XXX&quot;,Flightid__r.Sector__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>CTI</fullName>
        <active>true</active>
        <businessProcess>Thai Airway Case Process</businessProcess>
        <label>CTI</label>
    </recordTypes>
</CustomObject>

prd_package/objects/CTI__c.object
<CustomObject>
    <fields>
        <fullName>Area__c</fullName>
        <description>Flight area value which from Sector</description>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CTI_Station__c</fullName>
        <description>Station that case occured. This field value is from user input.</description>
        <label>Station</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Case which CTI is related.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Continent_txt__c</fullName>
        <label>Continent txt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <label>Detail</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <description>Flight Carrier which flight reat to CTI&apos;s case</description>
        <formula>LEFT(Flight_Number_F__c , 2 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is look up to Object Flight to relate CTI with Flight.</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>CTIs</relationshipLabel>
        <relationshipName>CTIs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nationality_Fullname__c</fullName>
        <description>Passenger&apos;s nationality in fullname format with Unidentify for blank value.</description>
        <formula>IF(NOT(ISBLANK(TEXT(Nationality_txt__c))),TEXT(Nationality_txt__c),&quot;Unidentified&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nationality</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality_Group__c</fullName>
        <description>Represent passenger&apos;s nationality as &apos;Thai&apos; or &apos;Non-Thai&apos;</description>
        <label>Nationality Group</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Thai</fullName>
                    <color>#000099</color>
                    <label>Thai</label>
                </value>
                <value>
                    <fullName>Non-Thai</fullName>
                    <color>#FF6666</color>
                    <label>Non-Thai</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nationality_txt__c</fullName>
        <description>Passenger&apos;s nationality in fullname format</description>
        <label>Nationality</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Afghan</fullName>
                </value>
                <value>
                    <fullName>Albanian</fullName>
                </value>
                <value>
                    <fullName>Algerian</fullName>
                </value>
                <value>
                    <fullName>American</fullName>
                </value>
                <value>
                    <fullName>American Samoan</fullName>
                </value>
                <value>
                    <fullName>Andorran</fullName>
                </value>
                <value>
                    <fullName>Angolan</fullName>
                </value>
                <value>
                    <fullName>Anguillan</fullName>
                </value>
                <value>
                    <fullName>Antiguans</fullName>
                </value>
                <value>
                    <fullName>Argentine</fullName>
                </value>
                <value>
                    <fullName>Armenian</fullName>
                </value>
                <value>
                    <fullName>Aruban</fullName>
                </value>
                <value>
                    <fullName>Australian</fullName>
                </value>
                <value>
                    <fullName>Austrian</fullName>
                </value>
                <value>
                    <fullName>Azerbaijani</fullName>
                </value>
                <value>
                    <fullName>Bahamian</fullName>
                </value>
                <value>
                    <fullName>Bahraini</fullName>
                </value>
                <value>
                    <fullName>Bangladeshi</fullName>
                </value>
                <value>
                    <fullName>Barbadian</fullName>
                </value>
                <value>
                    <fullName>Belarusian</fullName>
                </value>
                <value>
                    <fullName>Belgian</fullName>
                </value>
                <value>
                    <fullName>Belizean</fullName>
                </value>
                <value>
                    <fullName>Beninese</fullName>
                </value>
                <value>
                    <fullName>Bermudian</fullName>
                </value>
                <value>
                    <fullName>Bhutanese</fullName>
                </value>
                <value>
                    <fullName>Bolivian</fullName>
                </value>
                <value>
                    <fullName>Bosnian</fullName>
                </value>
                <value>
                    <fullName>Brazilian</fullName>
                </value>
                <value>
                    <fullName>British</fullName>
                </value>
                <value>
                    <fullName>British-Dependent Territories Citiz</fullName>
                </value>
                <value>
                    <fullName>Thai</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Return null value which used in DW report.</description>
        <formula>&quot;&quot;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STN__c</fullName>
        <description>To descibe Statin that case ocuured as &apos;Bangkok&apos;, &apos;Abroad&apos; &apos;Provincial&apos;, &apos;Unidentified&apos;.</description>
        <label>STN</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bangkok</fullName>
                </value>
                <value>
                    <fullName>Abroad</fullName>
                </value>
                <value>
                    <fullName>Provincial</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Flight&apos;s Sector from Sector_txt__c which have no &apos;-&apos; between 2 sector and default value as XXX. (e.g. BKKHKG)</description>
        <formula>IF( OR(Sector_txt__c = &quot;XXX&quot;,ISBLANK(Sector_txt__c)),&quot;XXX&quot;, 
LEFT(Sector_txt__c ,3) &amp; RIGHT(Sector_txt__c ,3))</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector_txt__c</fullName>
        <description>Flight&apos;s Sector from user input.</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Meal__c</fullName>
        <label>Special Meal</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <label>CTI</label>
    <nameField>
        <displayFormat>CTI00{0000000000}</displayFormat>
        <label>CTI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CTIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/CTI_Area_with_Sector__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <label>Flight Number</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <label>Sector</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CTI Area with Sector</label>
</CustomObject>

prd_package/objects/CTI_Route_Area__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Area__c</fullName>
        <label>Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STN__c</fullName>
        <label>STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CTI Route Area (Mapping Station - STN)</label>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nationality_Fullname__c</fullName>
        <description>Display Nationality Full name, for In-Flight and Customer Service</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Meal__c</fullName>
        <label>Special Meal</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/CTI_Management.cls
public without sharing class CTI_Management {
    public static final String Unidentified = 'Unidentified';

    public static void getctivalue(list<CTI__c> listgetctivalue, set<ID> setcaseid, Map<String, SObject> flightMap) {
        Map<id, Case> mapcase = getmapcase(setcaseid);
        List<CTI_Route_Area__c> listroutearea = CTI_Route_Area__c.getAll().values();
        List<CTI_Area_with_Sector__c> listsectorwitharea = CTI_Area_with_Sector__c.getall().values();
        Map<String, CTI_Route_Area__c> Maproutearea = getmaproutearea(listroutearea);
        Map<String, CTI_Area_with_Sector__c> Maprsectorarea = getmapsectorarea(listsectorwitharea);
        //String Unidentified = 'Unidentified';
        Boolean areaUnidentified = true;
        Boolean sectorUnidentified = true;

        system.debug('map route area size : ' + Maproutearea.size());
        system.debug('map sector area size : ' + Maprsectorarea.size());

        if (listgetctivalue.size() > 0) {
            for (CTI__c thiscti : listgetctivalue) {
                if (mapcase.Containskey(thiscti.caseid__c)) {

                    Case thiscase = mapcase.get(thiscti.caseid__c);
                    thiscti.detail__c = thiscase.description;
                    thiscti.Special_Meal__c = thiscase.passengerid__r.Special_Meal__c;

                    //M@I:M2 popular nationality group for report Onboard Catering by Nationality
                    if (thiscti.Nationality_txt__c != null && thiscti.Nationality_txt__c != '') {
                        if (thiscti.Nationality_txt__c == 'Thai')
                            thiscti.Nationality_Group__c = 'Thai';
                        else
                            thiscti.Nationality_Group__c = 'Non-Thai';
                    }

                    system.debug('this case : ' + thiscase);
                    system.debug('this cti : ' + JSON.serialize(thiscti));
                    System.debug('JK: Maprsectorarea - ' + JSON.serialize(Maprsectorarea));
                    System.debug('JK: flightMap - ' + JSON.serialize(flightMap));
                    if (Maprsectorarea.size() > 0) {
                        if (thiscti.FlightId__c != null && thiscti.Sector_txt__c != null && flightMap.containsKey(thiscti.FlightId__c)) {
                            String Sector = thiscti.Sector_txt__c;
                            Flight__c thisFlight = (Flight__c) flightMap.get(thiscti.FlightId__c);
                            if ((thisFlight.Flight_Number__c != null || thisFlight.Name == 'TGXXX') && Sector != null) {
                                String ctiAreaWithSectorKey = (thisFlight.Flight_Number__c != null ? thisFlight.Flight_Number__c.right(3) : thisFlight.Name.right(3)) + Sector.remove('-');
                                System.debug('JK: ctiAreaWithSectorKey - ' + ctiAreaWithSectorKey);
                                if (Maprsectorarea.Containskey(ctiAreaWithSectorKey)) {
                                    thiscti.area__c = Maprsectorarea.get(ctiAreaWithSectorKey).Area__c;
                                    //thiscti.Region_txt__c = Maprsectorarea.get(ctiAreaWithSectorKey).Region__c;
                                    areaUnidentified = false;
                                    //break;
                                }
                            }
                        }
                    }

                    if (Maproutearea.size() > 0) {
                        if (thiscti.CTI_Station__c != null) {
                            system.debug('CTI Station : ' + thiscti.CTI_Station__c);
                            system.debug('Map area : ' + Maproutearea);
                            if (Maproutearea.Containskey(thiscti.CTI_Station__c)) {
                                thiscti.STN__c = Maproutearea.get(thiscti.CTI_Station__c).STN__c;
                                sectorUnidentified = false;
                                //break;
                            }
                        }
                    }
                }

                if (areaUnidentified) {
                    thiscti.area__c = Unidentified;
                }
                if (sectorUnidentified) {
                    thiscti.STN__c = Unidentified;
                }
            }
        }
    }

    public static void updateCTIContinent(List<CTI__c> ctilist){
        if(ctilist != null && !ctilist.isEmpty()){
            Set<Id> caseIdSet = getCaseIdSetFromCTIList(ctilist);
            Map<Id, Case> casemap = null;
            if(caseIdSet != null) casemap = getmapcase(caseIdSet);
            if(casemap != null){
                Map<String, String> continentlist = getContinentMapByNationalityFullname();
                for(CTI__c cti : ctilist){
                    if(casemap.containsKey(cti.Caseid__c)){
                        Case eachcase = casemap.get(cti.Caseid__c);
                        if(cti.Nationality_txt__c == eachcase.Passengerid__r.Nationality_Fullname__c){
                            if(continentlist.containsKey(eachcase.Passengerid__r.Nationality_Fullname__c))cti.Continent_txt__c = eachcase.passengerid__r.Continent__c;
                            else cti.Continent_Txt__c = Unidentified;
                        }
                        else{
                            if(continentlist.containsKey(cti.Nationality_txt__c))cti.Continent_txt__c = continentlist.get(cti.Nationality_txt__c);
                            else cti.Continent_Txt__c = Unidentified;
                        }
                    }
                }
            }
        }
    }

    public static Set<Id> getCaseIdSetFromCTIList(List<CTI__c> ctilist){
        Set<Id> returnIdSet = new Set<Id>();
        if(ctilist != null && !ctilist.isEmpty()){
            for(CTI__c cti : ctilist) returnIdSet.add(cti.Caseid__c);
        }
        if(!ctilist.isEmpty()) return returnIdSet;
        return null;
    }

    private static Map<id, Case> getmapcase(set<ID> setcaseid) {
        list<Case> listcase = new list<Case>();
        Map<id, Case> mapcase = new Map<id, Case>();
        listcase = [Select id, flightid__c, flightid__r.Sector__c, flightid__r.Origin__c, flightid__r.Departure_STN__c,
                    flightid__r.Arrival_STN__c, flightid__r.flight_Number__c,
                    description, passengerid__r.Special_Meal__c, passengerid__r.Nationality_Fullname__c, passengerid__r.Continent__c from Case Where id IN: setcaseid];

        if (listcase.size() > 0) {
            for (Case thiscase : listcase) {
                mapcase.put(thiscase.id, thiscase);
            }
        }

        return mapcase;
    }

    private static Map<String, CTI_Route_Area__c> getmaproutearea(List<CTI_Route_Area__c> listroutearea) {
        Map<String, CTI_Route_Area__c> Maproutearea = new Map<String, CTI_Route_Area__c>();
        string result = '';
        for (CTI_Route_Area__c routearea : listroutearea) {
            Maproutearea.put(routearea.name , routearea);
            if (result == '')
                result = routearea.name;
            else
                result += ',' + routearea.name;
        }
        system.debug('result areaaaa : ' + result);
        return Maproutearea;
    }

    private static Map<String, CTI_Area_with_Sector__c> getmapsectorarea(List<CTI_Area_with_Sector__c> listsectorwitharea) {
        Map<String, CTI_Area_with_Sector__c> Maprsectorarea = new Map<String, CTI_Area_with_Sector__c>();
        for (CTI_Area_with_Sector__c sectorarea : listsectorwitharea) {
            Maprsectorarea.put(sectorarea.name , sectorarea);
        }

        return Maprsectorarea;
    }

    public static void setCTISectorFollowFlight(CTI__c thiscti, Map<String, SObject> flightMap) {
        if (thiscti.FlightId__c != null) {
            thiscti.Sector_txt__c = flightMap.get(thiscti.FlightId__c) != null && ((Flight__c)flightMap.get(thiscti.FlightId__c)).Sector__c != '-' ? ((Flight__c)flightMap.get(thiscti.FlightId__c)).Sector__c : thiscti.Sector_txt__c;
        }
    }

    private static Map<String, String> getContinentMapByNationalityFullname(){
        Map<String, String> returnMap = new Map<String, String>();
        List<Nationality_Master__mdt> continentlist = [SELECT Id, Continent__c, Nationality_Full_Name__c FROM Nationality_Master__mdt WHERE Primary__c = true];
        for(Nationality_Master__mdt continent : continentlist){
            returnMap.put(continent.Nationality_Full_Name__c, continent.Continent__c);
        }

        return returnMap;
    }

}