prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Nationality_Full_Name__c</fullName>
        <formula>IF(ISBLANK(Passengerid__r.Nationality_Fullname__c),&quot;Unidentified&quot;,Passengerid__r.Nationality_Fullname__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Nationality Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <description>What ROP Award Code was used to burn mile in this case</description>
        <label>ROP Award Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_Appraisal_Form_Criteria__mdt.object
<CustomObject>
    <fields>
        <fullName>Evaluated_Rank__c</fullName>
        <label>Evaluated Rank</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evaluator_Rank__c</fullName>
        <label>Evaluator Rank</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Numbers__c</fullName>
        <label>Form Numbers</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Crew Appraisal Form Criteria</label>
    <pluralLabel>Crew Appraisal Form Criterias</pluralLabel>
</CustomObject>

prd_package/objects/Currency_Unit__mdt.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Currency__c</fullName>
        <label>Sub Currency</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Currency Unit</label>
    <pluralLabel>Currency Units</pluralLabel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/In_flight_Compensation_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Problem__c</fullName>
        <label>Problem</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Type__c</fullName>
        <label>Sub Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>In-flight Compensation Master</label>
    <pluralLabel>In-flight Compensation Master</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/In_flight_Upgrade_Seat_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of money in THB</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <label>ROP Award Code</label>
        <referenceTo>ROP_Award_Code__mdt</referenceTo>
        <relationshipLabel>In-flight Upgrade Seat Master</relationshipLabel>
        <relationshipName>In_flight_Upgrade_Seat_Master</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Upgrade_From_Class__c</fullName>
        <label>Upgrade From Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upgrade_To_Class__c</fullName>
        <label>Upgrade To Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>In-flight Upgrade Seat Master</label>
    <pluralLabel>In-flight Upgrade Seat Master</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/MD_Appraisal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <label>Default Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Description__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form_Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Number__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Name</formula>
        <label>Form Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD_Appraisal_Item_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>MD Appraisal Item External ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MD_Appraisal_Subject__c</fullName>
        <label>MD Appraisal Subject</label>
        <referenceTo>MD_Appraisal_Subject__c</referenceTo>
        <relationshipLabel>MD Appraisal Items</relationshipLabel>
        <relationshipName>MD_Appraisal_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>YesNo</fullName>
                </value>
                <value>
                    <fullName>YesNoNA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Version__c</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>MD Appraisal Item</label>
    <nameField>
        <label>MD Appraisal Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/MD_Appraisal_Subject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MD Appraisal Subject</label>
    <nameField>
        <label>MD Appraisal Subject Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Nationality_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality_Full_Name__c</fullName>
        <label>Nationality Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Nationality Master</label>
    <pluralLabel>Nationality Masters</pluralLabel>
</CustomObject>

prd_package/objects/ROP_Award_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Mileages__c</fullName>
        <label>Mileages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ROP Award Code</label>
    <pluralLabel>ROP Award Code</pluralLabel>
</CustomObject>

prd_package/classes/MB_RESTMasterDataInFlightService.cls
@RestResource(urlMapping = '/masterdata/inflight/*')
global class MB_RESTMasterDataInFlightService {

	global class PickList {
		public String label;
		public String value;

		public PickList(String label, String value) {
			this.label = label;
			this.value = value;
		}
	}

	global class UpgradeSeatCriteria {
		public String code;
		public String fromClass;
		public String toClass;
		public String amount;
		public String mile;
		public String fltId;
	}

	global class CompensationCriteria {
		public String problem;
		public String type;
		public String subType;
		public String[] classList;
		public Decimal amount;
		public String curr;
		public String region;
	}

	global class CrewAppraisalFormCriteria {
		public String evaluator;
		public String evaluated;
		public String[] formNums;
	}

	global class MasterData {
		public List<PickList> nation;
		public String condi;
		public String accept;
		public String sbUpgradeCondi;
		public String cUpgradeCondi;
		public List<Map<String, String>> crewAppraisal;
		public List<CrewAppraisalFormCriteria> crewAppraisalFormCriteria;
		public List<UpgradeSeatCriteria> upgrade;
		public List<CompensationCriteria> compen;
		public List<CurrencyUnit> currenc;
		public List<String> paymentType;
		public List<TextData> ropMileCondi;
		public List<TextData> mpdCondi;
		public List<TextData> upgradeSeatCondi;
	}

	global class CurrencyUnit {
		public String currencyName;
		public String subCurrency;
	}

	global class TextData {
		public String name;
		public String content;
	}

	@HttpGet
	global static MasterData getMasterData() {
		Set<Id> flightIdSet = BE8_GlobalUtility.getFlightIdSetFromUserId(UserInfo.getUserId());
		List<Flight__c> flightList = [SELECT Id, Origin__c, Destination__c, Flight_Region__c, Departure_STN__c, Arrival_STN__c FROM Flight__c WHERE Id IN : flightIdSet];

		MasterData result = new MasterData();
		List<Nationality_Master__mdt> nationalityMasterList = [SELECT Id, MasterLabel, Nationality_Full_Name__c, Continent__c FROM Nationality_Master__mdt WHERE (NOT MasterLabel LIKE '___')];
		result.nation = new List<PickList>();
		for (Nationality_Master__mdt each : nationalityMasterList) {
			result.nation.add(new PickList(each.Nationality_Full_Name__c, each.MasterLabel));
		}

		Document ropConditions = [SELECT Id, Body FROM Document WHERE Name = 'ROP Conditions' LIMIT 1];
		result.condi = ropConditions.Body.toString();
		Document ropAccept = [SELECT Id, Body FROM Document WHERE Name = 'ROP Accept' LIMIT 1];
		result.accept = ropAccept.Body.toString();
		Document standByUpgradeCertificateCondition = [SELECT Id, Body FROM Document WHERE Name = 'StandByUpgradeCertificateCondition' LIMIT 1];
		result.sbUpgradeCondi = standByUpgradeCertificateCondition.Body.toString();
		Document confirmedUpgradeCertificateCondition = [SELECT Id, Body FROM Document WHERE Name = 'ConfirmedUpgradeCertificateCondition' LIMIT 1];
		result.cUpgradeCondi = confirmedUpgradeCertificateCondition.Body.toString();

		List<Map<String, String>> crewAppraisalDatas = new List<Map<String, String>>();
		List<MD_Appraisal_Item__c> mdItems = [SELECT Id, MD_Appraisal_Item_External_ID__c, Form_Number__c, Form_Description__c, MD_Appraisal_Subject__r.Name, MD_Appraisal_Subject__r.Description__c, MD_Appraisal_Subject__r.Type__c, Version__c, Name, Condition__c, Description__c, Type__c , Default_Value__c FROM MD_Appraisal_Item__c ORDER BY MD_Appraisal_Item_External_ID__c ASC];

		for (MD_Appraisal_Item__c eachMDItem : mdItems) {
			Map<String, String> dataEachItem = new Map<String, String>();
			dataEachItem.put('id', eachMDItem.MD_Appraisal_Item_External_ID__c);
			dataEachItem.put('sfdcId', eachMDItem.Id);
			dataEachItem.put('version', eachMDItem.Version__c);
			dataEachItem.put('formNum', eachMDItem.Form_Number__c);
			dataEachItem.put('formDesc', eachMDItem.Form_Description__c);
			dataEachItem.put('subjType', String.isBlank(eachMDItem.MD_Appraisal_Subject__r.Type__c) ? '' : eachMDItem.MD_Appraisal_Subject__r.Type__c);
			dataEachItem.put('subjNum', eachMDItem.MD_Appraisal_Subject__r.Name);
			dataEachItem.put('subjDesc', eachMDItem.MD_Appraisal_Subject__r.Description__c);
			dataEachItem.put('itemNum', eachMDItem.Name);
			dataEachItem.put('condi', eachMDItem.Condition__c);
			dataEachItem.put('itemDesc', eachMDItem.Description__c);
			dataEachItem.put('type', eachMDItem.Type__c);
			dataEachItem.put('defaultValue', eachMDItem.Default_Value__c);
			crewAppraisalDatas.add(dataEachItem);
		}

		List<CrewAppraisalFormCriteria> crewAppraisalFormCriterias = new List<CrewAppraisalFormCriteria>();
		List<Crew_Appraisal_Form_Criteria__mdt> criterias = [SELECT Id, Evaluator_Rank__c, Evaluated_Rank__c, Form_Numbers__c FROM Crew_Appraisal_Form_Criteria__mdt];
		for (Crew_Appraisal_Form_Criteria__mdt criteria : criterias) {
			CrewAppraisalFormCriteria eachCriteriaData = new CrewAppraisalFormCriteria();
			eachCriteriaData.evaluator = criteria.Evaluator_Rank__c;
			eachCriteriaData.evaluated = criteria.Evaluated_Rank__c;
			eachCriteriaData.formNums = criteria.Form_Numbers__c.split(',');
			crewAppraisalFormCriterias.add(eachCriteriaData);
		}

		result.crewAppraisalFormCriteria = crewAppraisalFormCriterias;
		result.crewAppraisal = crewAppraisalDatas;
		result.upgrade = getUpgradeSeatCriteriaMasterData(flightList);
		result.compen = getCompensationCriteria();
		result.currenc = getCurrencyMasterData();

		result.paymentType = new List<String>();
		for (Schema.PicklistEntry each : Case.Payment_Type__c.getDescribe().getPicklistValues()) {
			result.paymentType.add(each.getValue());
		}

		result.ropMileCondi = getTextDataListFromDocumentsInFolder('ROP_Mileages_Conditions');
		result.mpdCondi = getTextDataListFromDocumentsInFolder('MPD_Conditions');
		result.upgradeSeatCondi = getTextDataListFromDocumentsInFolder('Upgrade_Seat_Conditions');

		return result;
	}

	private static List<UpgradeSeatCriteria> getUpgradeSeatCriteriaMasterData(List<Flight__c> flightList) {
		Set<String> originAndDestinationSet = new Set<String>();
		for (Flight__c flight : flightList) {
			originAndDestinationSet.add(flight.Departure_STN__c);
			originAndDestinationSet.add(flight.Arrival_STN__c);
		}
		List<In_flight_Upgrade_Seat_Master__mdt> allMasterDataList = [SELECT DeveloperName, Origin__c, Destination__c, Upgrade_From_Class__c, Upgrade_To_Class__c, Amount__c, ROP_Award_Code__r.Mileages__c FROM In_flight_Upgrade_Seat_Master__mdt WHERE (Origin__c IN :originAndDestinationSet AND Destination__c IN :originAndDestinationSet)];
		//System.debug('allMasterDataList: ' + allMasterDataList);
		Map<String, List<SObject>> masterDataMapByOriginAndDestination = BE8_GlobalUtility.getSObjectListMap(new Set<String> {'Origin__c', 'Destination__c'}, allMasterDataList);
		//System.debug('masterDataMapByOriginAndDestination: ' + masterDataMapByOriginAndDestination);
		List<UpgradeSeatCriteria> upgradeList = new List<UpgradeSeatCriteria>();
		for (Flight__c flight : flightList) {
			String key = flight.Departure_STN__c + flight.Arrival_STN__c;
			if(!masterDataMapByOriginAndDestination.containsKey(key)){
				key = flight.Arrival_STN__c + flight.Departure_STN__c;
			}
			if (masterDataMapByOriginAndDestination.containsKey(key)) {
				List<In_flight_Upgrade_Seat_Master__mdt> masterDataList = (List<In_flight_Upgrade_Seat_Master__mdt>) masterDataMapByOriginAndDestination.get(key);
				for (In_flight_Upgrade_Seat_Master__mdt masterData : masterDataList) {
					UpgradeSeatCriteria upgrade = new UpgradeSeatCriteria();
					upgrade.code = masterData.DeveloperName;
					upgrade.fromClass = masterData.Upgrade_From_Class__c;
					upgrade.toClass = masterData.Upgrade_To_Class__c;
					upgrade.amount = '' + masterData.Amount__c;
					upgrade.mile = '' + masterData.ROP_Award_Code__r.Mileages__c;
					String originAndDestinationKey = masterData.Origin__c + masterData.Destination__c;
					upgrade.fltId = flight.Id;
					upgradeList.add(upgrade);
				}
			}
		}
		return upgradeList;
	}

	private static List<CompensationCriteria> getCompensationCriteria() {
		List<CompensationCriteria> compensationCriteriaList = new List<CompensationCriteria>();
		List<In_flight_Compensation_Master__mdt> allMasterDataList = [SELECT Id, Amount__c, Class__c, Currency__c, Flight_Region__c, Problem__c, Sub_Type__c, Type__c FROM In_flight_Compensation_Master__mdt];
		for (In_flight_Compensation_Master__mdt masterData : allMasterDataList) {
			CompensationCriteria compensationCriteria = new CompensationCriteria();
			compensationCriteria.problem = masterData.Problem__c;
			compensationCriteria.type = masterData.Type__c;
			compensationCriteria.subType = masterData.Sub_Type__c;
			compensationCriteria.classList = masterData.Class__c.split(',');
			compensationCriteria.amount = masterData.Amount__c;
			compensationCriteria.curr = masterData.Currency__c;
			compensationCriteria.region = masterData.Flight_Region__c;
			compensationCriteriaList.add(compensationCriteria);
		}
		return compensationCriteriaList;
	}

	private static List<CurrencyUnit> getCurrencyMasterData() {
		List<Currency_Unit__mdt> currencyMasterDataList = [SELECT Id, DeveloperName, Currency__c, Sub_Currency__c FROM Currency_Unit__mdt];
		List<CurrencyUnit> currencyModelList = new List<CurrencyUnit>();
		for (Currency_Unit__mdt eachCurrency : currencyMasterDataList) {
			CurrencyUnit currencyModel = new CurrencyUnit();
			currencyModel.currencyName = eachCurrency.DeveloperName;
			currencyModel.subCurrency = eachCurrency.Sub_Currency__c;
			currencyModelList.add(currencyModel);
		}
		return currencyModelList;
	}

	private static List<String> getROPMileagesConditionList() {
		List<String> result = new List<String>();
		for (Document eachDoc : [SELECT Id, Name, Body FROM Document WHERE Folder.Name = 'ROP Mileages Conditions']) {
			result.add(eachDoc.Body.toString());
		}
		return result;
	}

	private static List<String> getMPDConditionList() {
		List<String> result = new List<String>();
		for (Document eachDoc : [SELECT Id, Name, Body FROM Document WHERE Folder.Name = 'MPD Conditions']) {
			result.add(eachDoc.Body.toString());
		}
		return result;
	}

	private static List<TextData> getTextDataListFromDocumentsInFolder(String folderDeveloperName) {
		List<TextData> result = new List<TextData>();
		for (Document eachDoc : [SELECT Id, Name, Body FROM Document WHERE Folder.DeveloperName = :folderDeveloperName]) {
			TextData eachTextData = new TextData();
			eachTextData.name = eachDoc.Name;
			eachTextData.content = eachDoc.Body.toString();
			result.add(eachTextData);
		}
		return result;
	}
}