prd_package/objects/Case_Member__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <description>Display department of member</description>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abroad Stations</fullName>
                </value>
                <value>
                    <fullName>Baggage Claim</fullName>
                </value>
                <value>
                    <fullName>Bangkok Ramp Service</fullName>
                </value>
                <value>
                    <fullName>Bangkok Ticket &amp;	Reservation</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit Crew</fullName>
                </value>
                <value>
                    <fullName>Ground Service at Bangkok Airport</fullName>
                </value>
                <value>
                    <fullName>In-Flight Products</fullName>
                </value>
                <value>
                    <fullName>In-Flight Service</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>S4</fullName>
                </value>
                <value>
                    <fullName>SZ-R</fullName>
                </value>
                <value>
                    <fullName>Technical Service</fullName>
                </value>
                <value>
                    <fullName>Thai Smile Airline</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address for the passenger.</description>
        <label>Email</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Display role of member</description>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Booking through TG website</fullName>
                </value>
                <value>
                    <fullName>Ticket Receipt</fullName>
                </value>
                <value>
                    <fullName>BKK Reservation (Thai Contact Center)</fullName>
                </value>
                <value>
                    <fullName>Reservation System Service Management</fullName>
                </value>
                <value>
                    <fullName>Ticketing Dept.</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Larnluang Office</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Head office (Vibhavadee)</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Silom office</fullName>
                </value>
                <value>
                    <fullName>E-Ticketing</fullName>
                </value>
                <value>
                    <fullName>Airport Ticket Office</fullName>
                </value>
                <value>
                    <fullName>Refund office</fullName>
                </value>
                <value>
                    <fullName>Passenger Refund</fullName>
                </value>
                <value>
                    <fullName>Agency Sales</fullName>
                </value>
                <value>
                    <fullName>Airline Industry Relations</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - International</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - Domestic</fullName>
                </value>
                <value>
                    <fullName>Departure - Airside</fullName>
                </value>
                <value>
                    <fullName>BKK Station Manager / Duty Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Service</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Support Dept.</fullName>
                </value>
                <value>
                    <fullName>Baggage Services Dept.</fullName>
                </value>
                <value>
                    <fullName>BKK Lounges</fullName>
                </value>
                <value>
                    <fullName>Lounges at abroad</fullName>
                </value>
                <value>
                    <fullName>Stations</fullName>
                </value>
                <value>
                    <fullName>Load Control</fullName>
                </value>
                <value>
                    <fullName>Ground Support Equipment Operations Control Dept.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Display type of member</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>External User</fullName>
                </value>
                <value>
                    <fullName>Internal User</fullName>
                </value>
                <value>
                    <fullName>Investigation Staff</fullName>
                </value>
                <value>
                    <fullName>Round Robin User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Members</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Task_Management.cls
public without sharing class Task_Management {
    
    public static string FUTUREFLIGHT = 'Future Flight';
    
    public static void findinvestigationstaff(list<task> listtask){
        map<String,Case_Member__c> Mapinvestigationmember = new map<String,Case_Member__c>();
        
        Mapinvestigationmember = getMapinvestigationmember(); 
        
        if(listtask.size() > 0){
            for(task thistask : listtask){
                if(thistask.Task_Type__c != FUTUREFLIGHT){
                    if(thistask.Investigation_Department__c != null && thistask.Investigation_Category__c != null){
                        String criteriatask = thistask.Investigation_Department__c.Trim().ToUpperCase() + thistask.Investigation_Category__c.Trim().ToUpperCase();
                        if(Mapinvestigationmember.Containskey(criteriatask)){
                            Case_Member__c istaff = Mapinvestigationmember.get(criteriatask);
                            thistask.To_Investigation_Staff__c = getfirstemail(istaff.Email__c);
                            thistask.Investigation_Other__c = istaff.Email__c;
                        }
                    }
                }
            }
        }
        
    }
    
    private static string getfirstemail(string emailstr){
        
        string emailresult = '';
        
        if(emailstr != null){
            list<string> listemail = new list<string>();
            listemail = emailstr.split(',',-2);
            
            if(listemail.size() > 0)
                emailresult = listemail.get(0);
        }
        
        return emailresult;
    }
    
    private static Map<String,Case_Member__c> getMapinvestigationmember(){
        
        map<String,Case_Member__c> Mapinvestigationmember = new map<String,Case_Member__c>();
        list<Case_Member__c> listinvestigationmember = new list<Case_Member__c>();
        
        listinvestigationmember = [Select id, name, Type__c,Tier__c, Department__c, Email__c 
                                   from Case_Member__c 
                                   where RecordType.name = 'Investigation Staff'];
        
        if(listinvestigationmember.size() > 0){
            
            for(Case_Member__c invstaff : listinvestigationmember){
                String criteriainv = invstaff.Department__c.Trim().ToUpperCase() + invstaff.Tier__c.Trim().ToUpperCase();
                Mapinvestigationmember.put(criteriainv , invstaff);
            }
        }
        
        return Mapinvestigationmember;
    }
}