prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_REG_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Aircraft the Case is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Number_Custom_F__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers</description>
        <formula>CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number_Link_For_Console__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers as a hyperlink</description>
        <formula>HYPERLINK(&quot;javascript:openNewTab(&apos;&quot; &amp; Id &amp; &quot;&apos;)&quot;,if( Text(Priority) == &quot;Urgent&quot;,

CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber &amp; &quot; &quot; &amp;   
IMAGE(&quot;/servlet/servlet.FileDownload?file=01528000003KdRV&quot; &amp; 
 
if( Follow_up__c == TRUE, 

IMAGE(&quot;/img/samples/flag_yellow.gif&quot;,&quot;&quot;,13,13), 

&quot;&quot;),&quot;&quot;,13,13), 


CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber &amp; 
 
if( Follow_up__c == TRUE, 

IMAGE(&quot;/img/samples/flag_yellow.gif&quot;,&quot;&quot;,13,13), 

&quot;&quot;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Urgent</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SEQ_No_Display__c</fullName>
        <externalId>true</externalId>
        <label>Seq No.</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

prd_package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Case_Number_F__c</fullName>
        <formula>IF( $User.UIThemeDisplayed == &apos;Theme4t&apos;, HYPERLINK(&quot;/&quot; &amp; Caseid__r.Id, CreatedBy.Station__c &amp; CreatedBy.Department &amp;    Caseid__r.CaseNumber ), HYPERLINK(&quot;javascript:srcUp(&apos;/&quot; &amp;  Caseid__r.Id  &amp; &quot;&apos;)&quot;, CreatedBy.Station__c &amp; CreatedBy.Department &amp;    Caseid__r.CaseNumber   ))</formula>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Defect_Type__c</fullName>
        <description>Displays the defect type from the case that the case group member is related to</description>
        <label>Defect Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Equipment_From_Case__c</fullName>
        <description>Displays the equipment from the case that the case group member is related to</description>
        <formula>Caseid__r.EquipmentId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Equipment</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the value of the equipment the case group member is related to</description>
        <label>Equipment</label>
        <referenceTo>Master_Map__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Impact_Status_Color__c</fullName>
        <formula>IF(  ISPICKVAL( Caseid__r.Action__c, &quot;&quot; ) &amp;&amp;   ISPICKVAL(  Impact__c, &quot;&quot; )  , IMAGE(&quot;/resource/YellowCase&quot;,&quot;&quot;,20,20) + &apos; &apos;,
        
      IF(  ISPICKVAL( Caseid__r.Action__c , &quot;Remain&quot;) &amp;&amp; ISPICKVAL (  Impact__c , &quot;Block&quot;)  , IMAGE(&quot;/resource/RedCase&quot;,&quot;&quot;,20,20) + &apos; &apos;, 

                   IF( ISPICKVAL( Caseid__r.Action__c , &quot;Remain&quot;) &amp;&amp; ISPICKVAL (  Impact__c , &quot;Malfunction&quot;) , IMAGE(&quot;/resource/OrangeCase&quot;,&quot;&quot;,20,20) + &apos; &apos;,

                                IF( ISPICKVAL( Caseid__r.Action__c , &quot;Remain&quot;) &amp;&amp; ISPICKVAL (  Impact__c , &quot;Serviceable&quot;), IMAGE(&quot;/resource/BlueCase&quot;,&quot;&quot;,20,20) + &apos; &apos;,

                                      IF ( ISPICKVAL (  Impact__c , &quot;Complete&quot;) , IMAGE(&quot;/resource/GreenCase&quot;,&quot;&quot;,20,20) + &apos; &apos;,&quot;&quot;)
)
)
)
)</formula>
        <label>Impact Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Part_From_Case__c</fullName>
        <formula>Caseid__r.PartId__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Part</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Alphabet_Only__c</fullName>
        <formula>RIGHT(Position__c, 1)</formula>
        <label>Position Alphabet Only</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position_Number_Only__c</fullName>
        <formula>VALUE(LEFT( Position__c, LEN(Position__c) - 1 ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position Number Only</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Master_Map__c.object
<CustomObject>
    <label>Master Map</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Map</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/MaintenanceCaseController.cls
public with sharing class MaintenanceCaseController {
    public String theme {get; set;}
    public ApexPages.StandardSetController con {get; set;}
    public MaintenanceCaseController (ApexPages.StandardController stdController) {
        Id flightId = Apexpages.currentpage().getparameters().get('id');
        Flight__c flight = [SELECT Id, AircraftId__c FROM Flight__c WHERE Id = :flightId LIMIT 1];
        List<Case_Group_Member__c> caseGroupMemberList = [SELECT Id, Impact_Status_Color__c, Name, CaseId__r.Case_Number_Custom_F__c, CaseId__r.Id, CaseId__r.SEQ_No_Display__c, CaseId__r.Case_Number_Link_For_Console__c, Case_Number_F__c, Position__c, Part_From_Case__c, Defect_Type__c, Impact__c, Equipment_From_Case__c FROM Case_Group_Member__c WHERE Equipment__r.Name = 'PASSENGER SEAT' AND CaseId__r.SEQ_No_Display__c != null AND CaseId__r.A_C_REG_ID__c = :flight.AircraftId__c And CaseId__r.Status = :BE8_GlobalConstants.CASE_STATUS_OPEN ORDER BY Position_Number_Only__c, Position_Alphabet_Only__c LIMIT 1000];
        ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(caseGroupMemberList);
        con = ssc;
        con.setPageSize(8);
        theme = UserInfo.getUiTheme().toLowerCase();
    }
    public List<Case_Group_Member__c> caseGroupMemberList {
        get
        {
            if (con != null)
                return (List<Case_Group_Member__c>)con.getRecords();
            else
                return null ;
        }
        set;
    }
    public Boolean hasNext {
        get
        {
            return con.getHasNext();
        }
        set;
    }
    public Boolean hasPrevious {
        get
        {
            return con.getHasPrevious();
        }
        set;
    }
    public Integer pageNumber {
        get
        {
            return con.getPageNumber();
        }
        set;
    }
    public void previous() {
        con.previous();
    }
    public void next() {
        con.next();
    }

}