prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Displays the booking class of the Passenger that is related to the Case</description>
        <formula>Passengerid__r.Booking_Class__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Booking Class</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Displays value of the new cabin class (code) of the passenger related to the case</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <description>Displays the value of the new seat of the passenger related to the case</description>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Reason__c</fullName>
        <label>Integration Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Upgrade_Seat_Case__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays whether this case concerns seat upgrading</description>
        <label>Is Upgrade Seat Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Mileage</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <description>What ROP Award Code was used to burn mile in this case</description>
        <label>ROP Award Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <formula>if(Flightid__r.Sector__c == &quot;-&quot; || Flightid__r.Sector__c == null,&quot;XXX&quot;,Flightid__r.Sector__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upgrade_Seat_with_Amount__c</fullName>
        <description>The amount of money used to upgrade seat in-flight</description>
        <label>Upgrade Seat with Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Booking class of the passenger which could be any value from A-Z depending on the ticket and the reservation of the passenger</description>
        <label>Booking Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Cabin Code changed to</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Salutation_Auto__c</fullName>
        <description>This field stores the value of salutation of this passenger which is the result of automatic detection of salutation from passenger&apos;s first name.</description>
        <label>Passenger Salutation Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/UpgradeSeat_Summary_Report.cls
public without sharing class UpgradeSeat_Summary_Report {

	private Integer lastNDays;
	private List<Case> cases;

	public UpgradeSeat_Summary_Report() {
		this(7);
	}

	public UpgradeSeat_Summary_Report(Integer lastNDays) {
		AppLogger.setReferenceId('UpgradeSeat_Summary_Report_' + System.today().format());
		AppLogger.debug('UpgradeSeat_Summary_Report', 'Constructor', '', 'Constructor:~lastNDays[' + lastNDays + ']', null);
		this.lastNDays = lastNDays;
		this.cases = queryUpgradeSeatByMileCases();
	}

	public List<Case> queryUpgradeSeatByMileCases() {
		BE8_SoqlBuilder soql = new BE8_SoqlBuilder('Case');
		soql.addField(new Set<String> {'Id', 'Integration_Error_Reason__c', 'Integration_Error__c', 'FlightId__r.Name', 'CreatedDate', 'Passengerid__r.Name', 'PNR__c', 'Passengerid__r.Sector__c', 'Upgrade_Seat_with_Amount__c', 'ROP_Award_Code__c', 'Passengerid__r.FFP_Number__c', 'FlightId__r.Flight_Number__c', 'FlightId__r.Flight_Date_LT__c', 'Passengerid__r.Cabin_Code__c','Passengerid__r.Booking_Class__c','Passengerid__r.Checkin_Seat__c', 'Change_Seat__c', 'Change_Cabin_Class__c', 'PassengerId__r.Passenger_Salutation_Auto__c', 'PassengerId__r.Last_Name__c', 'PassengerId__r.First_Name__c'});
		soql.addCondition('CreatedDate = LAST_N_DAYS:' + this.lastNDays);
		soql.addCondition('Is_Upgrade_Seat_Case__c = TRUE');
		soql.addCondition('Payment_Type__c = \'Mileage\'');
		soql.addOrder('Flightid__c ASC');
		soql.addOrder('Integration_Error__c ASC');
		AppLogger.debug('UpgradeSeat_Summary_Report', 'queryUpgradeSeatByMileCases', '', soql.getQueryStr(), null);
		return Database.query(soql.getQueryStr());
	}

	public void sendSummaryReport() {
		Integer total = this.cases.size();
		Integer success = 0;
		Integer failed = 0;

		List<List<String>> datas = new List<List<String>>();
		List<String> header = new List<String>();
		header.add('\"Flight Number\"');
		header.add('\"Flight Date\"');
		header.add('\"Sector\"');
		header.add('\"OriginalCabinClass\"');
		header.add('\"NewCabinClass\"');
		header.add('\"OriginalBookingClass\"');
		header.add('\"OriginalSeatNumber\"');
		header.add('\"NewSeatNumber\"');
		header.add('\"PNR\"');
		header.add('\"ROP No.\"');

		header.add('\"Salutation\"');
		header.add('\"FirstName\"');
		header.add('\"LastName\"');
		

		header.add('\"AwardCode\"');
		header.add('\"MileageUsed\"');
		header.add('\"Status\"');
		header.add('\"ErrorMessage\"');
		datas.add(header);
		for (Case eachCase : this.cases) {
			List<String> dataEachRow = new List<String>();
			if (!eachCase.Integration_Error__c) {
				success++;
			} else {
				failed++;
			}

			dataEachRow.add('\"' + eachCase.FlightId__r.Flight_Number__c + '\"');
			if (eachCase.FlightId__r.Flight_Date_LT__c != null) {
				dataEachRow.add('\"' + eachCase.FlightId__r.Flight_Date_LT__c + '\"');
			} else {
				dataEachRow.add('\"\"');
			}
			dataEachRow.add('\"' + eachCase.Passengerid__r.Sector__c + '\"');
			dataEachRow.add('\"' + eachCase.Passengerid__r.Cabin_Code__c + '\"');
			dataEachRow.add('\"' + eachCase.Change_Cabin_Class__c + '\"');
			dataEachRow.add('\"' + eachCase.Passengerid__r.Booking_Class__c + '\"');
			dataEachRow.add('\"' + eachCase.Passengerid__r.Checkin_Seat__c + '\"');
			dataEachRow.add('\"' + eachCase.Change_Seat__c + '\"');
			dataEachRow.add('\"' + eachCase.PNR__c + '\"');
			dataEachRow.add('\"' + eachCase.Passengerid__r.FFP_Number__c + '\"');
			
			dataEachRow.add('\"' + eachCase.PassengerId__r.Passenger_Salutation_Auto__c + '\"');
			dataEachRow.add('\"' + eachCase.PassengerId__r.First_Name__c + '\"');
			dataEachRow.add('\"' + eachCase.PassengerId__r.Last_Name__c + '\"');
			

			dataEachRow.add('\"' + eachCase.ROP_Award_Code__c + '\"');
			dataEachRow.add('\"' + eachCase.Upgrade_Seat_with_Amount__c + '\"');
			if (eachCase.Integration_Error__c) {
				dataEachRow.add('\"Error\"');
			} else {
				dataEachRow.add('\"Success\"');
			}
			dataEachRow.add('\"' + eachCase.Integration_Error_Reason__c + '\"');
			datas.add(dataEachRow);
		}

		String bodyMsg = '';
		bodyMsg += System.today().addDays(-this.lastNDays).format() + ' - ' + System.today().format() + '\n';
		bodyMsg += 'Total :' + total + '\n';
		bodyMsg += 'Success :' + success + '\n';
		bodyMsg += 'Failed :' + failed + '\n';

		String attachmentName = System.today().format() +  '_MileageUpgradeOnBoard.csv';
		String toEmails = MailList_Repository.getEmailAddress('Upgrade Seat', 'UpgradeSeatAdmin');

		try {
			Email_Service.sendEmailWithAttachment('SFDC | Mileage Upgrade On-Board: Daily Report', toEmails, bodyMsg, BE8_GlobalUtility.toCSVString(datas), attachmentName);
			AppLogger.debug('UpgradeSeat_Summary_Report', 'sendSummaryReport', '', 'success', null);
		} catch (Exception e) {
			AppLogger.error('UpgradeSeat_Summary_Report', 'sendSummaryReport', '', 'Exception', e);
		}
	}

}