prd_package/objects/Case_Member__c.object
<CustomObject>
    <fields>
        <fullName>Assigned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Assigned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Case_Teamid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>relate case team object</description>
        <label>Case Team</label>
        <referenceTo>Case_Team__c</referenceTo>
        <relationshipLabel>Case Members</relationshipLabel>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>Display department of member</description>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Abroad Stations</fullName>
                </value>
                <value>
                    <fullName>Baggage Claim</fullName>
                </value>
                <value>
                    <fullName>Bangkok Ramp Service</fullName>
                </value>
                <value>
                    <fullName>Bangkok Ticket &amp;	Reservation</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit Crew</fullName>
                </value>
                <value>
                    <fullName>Ground Service at Bangkok Airport</fullName>
                </value>
                <value>
                    <fullName>In-Flight Products</fullName>
                </value>
                <value>
                    <fullName>In-Flight Service</fullName>
                </value>
                <value>
                    <fullName>S3</fullName>
                </value>
                <value>
                    <fullName>S4</fullName>
                </value>
                <value>
                    <fullName>SZ-R</fullName>
                </value>
                <value>
                    <fullName>Technical Service</fullName>
                </value>
                <value>
                    <fullName>Thai Smile Airline</fullName>
                </value>
                <value>
                    <fullName>AO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address for the passenger.</description>
        <label>Email</label>
        <length>130000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>Display role of member</description>
        <label>Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Chief</fullName>
                </value>
                <value>
                    <fullName>Manager</fullName>
                </value>
                <value>
                    <fullName>Booking through TG website</fullName>
                </value>
                <value>
                    <fullName>Ticket Receipt</fullName>
                </value>
                <value>
                    <fullName>BKK Reservation (Thai Contact Center)</fullName>
                </value>
                <value>
                    <fullName>Reservation System Service Management</fullName>
                </value>
                <value>
                    <fullName>Ticketing Dept.</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Larnluang Office</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Head office (Vibhavadee)</fullName>
                </value>
                <value>
                    <fullName>Tickets issued at Silom office</fullName>
                </value>
                <value>
                    <fullName>E-Ticketing</fullName>
                </value>
                <value>
                    <fullName>Airport Ticket Office</fullName>
                </value>
                <value>
                    <fullName>Refund office</fullName>
                </value>
                <value>
                    <fullName>Passenger Refund</fullName>
                </value>
                <value>
                    <fullName>Agency Sales</fullName>
                </value>
                <value>
                    <fullName>Airline Industry Relations</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - International</fullName>
                </value>
                <value>
                    <fullName>Check-in Landside - Domestic</fullName>
                </value>
                <value>
                    <fullName>Departure - Airside</fullName>
                </value>
                <value>
                    <fullName>BKK Station Manager / Duty Manager</fullName>
                </value>
                <value>
                    <fullName>Passenger Service</fullName>
                </value>
                <value>
                    <fullName>Service Delivery Support Dept.</fullName>
                </value>
                <value>
                    <fullName>Baggage Services Dept.</fullName>
                </value>
                <value>
                    <fullName>BKK Lounges</fullName>
                </value>
                <value>
                    <fullName>Lounges at abroad</fullName>
                </value>
                <value>
                    <fullName>Stations</fullName>
                </value>
                <value>
                    <fullName>Load Control</fullName>
                </value>
                <value>
                    <fullName>Ground Support Equipment Operations Control Dept.</fullName>
                </value>
                <value>
                    <fullName>Catering Dept.</fullName>
                </value>
                <value>
                    <fullName>Menu Planning Dept.</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Userid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relate with user object</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Extensions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Member</label>
    <nameField>
        <label>Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Members</pluralLabel>
    <recordTypes>
        <fullName>Investigation_Staff</fullName>
        <active>true</active>
        <label>Investigation Staff</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Case_Team__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Displays the Status active or inactive for the Case Teams</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_ID__c</fullName>
        <description>This field use mapping with case owner for point to Case Team</description>
        <label>Queue ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Case Team</label>
    <nameField>
        <label>Assignment Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Teams</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/Task_Management_Test.cls
@isTest
private class Task_Management_Test {
	
	@isTest static void testTaskManagement() {
		UserRole uRole = new UserRole(name = 'TEST ROLE');
	    insert uRole;

	    User u1Q1 = new User(Alias = 'User1Q1', Email='User1Q1@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
        LocaleSidKey='en_US', UserName='User1Q1@testorg.com', userroleid=uRole.Id, 
        ProfileId = UserInfo.getProfileId(), TimeZoneSidKey='America/Los_Angeles');
        insert u1Q1;

        System.runAs(u1q1){

        	Case_Team__c q1 = new Case_Team__c(Queue_ID__c=String.valueof(u1Q1.Id), Active__c=true);
			insert q1;

	        Case_Member__c m1 = new Case_Member__c(Userid__c=u1q1.id, Case_Teamid__c=q1.id, Assigned__c=true,
	        	recordTypeId=BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case_Member__c', 'Investigation_Staff'), Email__c='m1@email.com',
	        	Department__c='Catering', Tier__c='Catering Dept.');
	        insert m1;

	        Case_Member__c m2 = new Case_Member__c(Userid__c=u1q1.id, Case_Teamid__c=q1.id, Assigned__c=true,
	        	recordTypeId=BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case_Member__c', 'Investigation_Staff'), Email__c='m2@email.com',
	        	Department__c='Catering', Tier__c='Menu Planning Dept.');
	        insert m2;

	        Test.startTest();

	        Task newTask = new Task(Investigation_Department__c='Catering', Investigation_Category__c='Catering Dept.');
	        insert newTask;

	        Task updateTask = [Select To_Investigation_Staff__c from Task where Id=:newTask.Id limit 1];
	        Assert.assertEquals('m1@email.com', updateTask.To_Investigation_Staff__c);

	        newTask.Investigation_Category__c = 'Menu Planning Dept.';
	        update newTask;

	        Task updateTask2 = [Select To_Investigation_Staff__c from Task where Id=:newTask.Id limit 1];
	        Assert.assertEquals('m2@email.com', updateTask2.To_Investigation_Staff__c);

	        Test.stopTest();
        }
	}
	
}