prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_REG_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Refers to the Aircraft the Case is related to</description>
        <label>A/C REG</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Type__c</fullName>
        <description>Displays the value of case type used in case management</description>
        <label>Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Commendation</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Suggestion</fullName>
                </value>
                <value>
                    <fullName>Inquiry</fullName>
                </value>
                <value>
                    <fullName>Incident</fullName>
                </value>
                <value>
                    <fullName>Injury</fullName>
                </value>
                <value>
                    <fullName>Star Alliance</fullName>
                </value>
                <value>
                    <fullName>Baggage Claim</fullName>
                </value>
                <value>
                    <fullName>Court Case</fullName>
                </value>
                <value>
                    <fullName>14 CFR</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Problem</fullName>
                </value>
                <value>
                    <fullName>Feature Request</fullName>
                </value>
                <value>
                    <fullName>Question</fullName>
                </value>
                <value>
                    <fullName>Arrival/Transit/Connections</fullName>
                </value>
                <value>
                    <fullName>Authorities and Airport Facilities</fullName>
                </value>
                <value>
                    <fullName>Boarding and Departure Area</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SPECIAL MEAL</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DGC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - DBC</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - SEAT</fullName>
                </value>
                <value>
                    <fullName>Check-in &amp; Service pre-immigration-SPML</fullName>
                </value>
                <value>
                    <fullName>Check-in and Service before immigration - OTHER</fullName>
                </value>
                <value>
                    <fullName>General Comments on TG Services</fullName>
                </value>
                <value>
                    <fullName>Handling of flight Irregularities</fullName>
                </value>
                <value>
                    <fullName>Lounges</fullName>
                </value>
                <value>
                    <fullName>Unidentified</fullName>
                </value>
                <value>
                    <fullName>Baggage</fullName>
                </value>
                <value>
                    <fullName>Unruly</fullName>
                </value>
                <value>
                    <fullName>Junk</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Displays value of the new cabin class (code) of the passenger related to the case</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <description>Displays the value of the new seat of the passenger related to the case</description>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flightid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the flight that is related to the case</description>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Reason__c</fullName>
        <label>Integration Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Json_Body__c</fullName>
        <description>Source</description>
        <label>Json Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Mobile_App_Key__c</fullName>
        <externalId>true</externalId>
        <label>Mobile App Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Passenger Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Flightid__c</field>
                <operation>equals</operation>
                <valueField>Passenger__c.FlightId__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <description>What ROP Award Code was used to burn mile in this case</description>
        <label>ROP Award Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Case_Type__c</fullName>
        <formula>TEXT(  Caseid__r.Case_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Displays the changed cabin class of case group member</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <description>Displays the new seat for the case group member</description>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <label>FFP Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Passengerid__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Displays the passenger the case group member is related to</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>AircraftId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Aircraft Registration</label>
        <referenceTo>Aircraft__c</referenceTo>
        <relationshipLabel>Flights</relationshipLabel>
        <relationshipName>Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/In_flight_Upgrade_Seat_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of money in THB</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <label>ROP Award Code</label>
        <referenceTo>ROP_Award_Code__mdt</referenceTo>
        <relationshipLabel>In-flight Upgrade Seat Master</relationshipLabel>
        <relationshipName>In_flight_Upgrade_Seat_Master</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Upgrade_From_Class__c</fullName>
        <label>Upgrade From Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upgrade_To_Class__c</fullName>
        <label>Upgrade To Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>In-flight Upgrade Seat Master</label>
    <pluralLabel>In-flight Upgrade Seat Master</pluralLabel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Cabin Code changed to</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Change_Seat_DateTime__c</fullName>
        <label>Last Change Seat Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PaxKey__c</fullName>
        <formula>First_Name__c &amp; &apos;_&apos; &amp;  Last_Name__c &amp; &apos;_&apos; &amp;  PNR__c &amp; &apos;_&apos; &amp; Flight_Master__c</formula>
        <label>PaxKey</label>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/ROP_Award_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Mileages__c</fullName>
        <label>Mileages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Promotion_Code__c</fullName>
        <label>Promotion Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ROP Award Code</label>
    <pluralLabel>ROP Award Code</pluralLabel>
</CustomObject>

prd_package/classes/MB_RESTUpgradeSeat.cls
@RestResource(urlMapping = '/upgradeseat/*')
global without sharing class MB_RESTUpgradeSeat {
	@HttpPost
	global static List<MB_RestResponseInfoModel.upgradeSeat> upgradeSeat(List<MB_RESTRequestInfoModel.upgradeSeat> upgradeSeatList) {
		if (upgradeSeatList != null && upgradeSeatList.size() > 0) {
			AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '', '', 'Upgrade Seat List from Mobile App', System.JSON.serialize(upgradeSeatList), null, System.currentTimeMillis());
			Set<Id> flightIdSet = new Set<Id>();
			Set<String> paxKeySet = new Set<String>();
			Set<String> upgradeSeatCodeSet = new Set<String>();
			for (MB_RESTRequestInfoModel.upgradeSeat each : upgradeSeatList) {
				paxKeySet.add(each.paxKey);
				upgradeSeatCodeSet.add(each.upcode);
				flightIdSet.add(each.fltId);
			}
			Map<Id, Flight__c> flightMapById = new Map<Id, Flight__c>([SELECT Id, AircraftId__c FROM Flight__c WHERE Id IN : flightIdSet]);
			List<Passenger__c> passengerList = [SELECT Id, FFP_Number__c, PaxKey__c, FlightId__r.Name FROM Passenger__c WHERE PaxKey__c IN : paxKeySet];
			List<In_flight_Upgrade_Seat_Master__mdt> masterDataList = [SELECT DeveloperName, Origin__c, Destination__c, Upgrade_From_Class__c, Upgrade_To_Class__c, Amount__c, ROP_Award_Code__r.Promotion_Code__c, ROP_Award_Code__r.Mileages__c, ROP_Award_Code__r.DeveloperName FROM In_flight_Upgrade_Seat_Master__mdt WHERE DeveloperName IN :upgradeSeatCodeSet];
			Map<Id, Passenger__c> passengerMapByPaxId = new Map<Id, Passenger__c>(passengerList);
			Map<String, SObject> masterDataMapByCode = BE8_GlobalUtility.getSObjectMap('DeveloperName', masterDataList);
			List<Passenger__c> passengerListToBeUpdated = new List<Passenger__c>();
			//Map<String, List<Case>> upgradeSeatCaseListMapByPaxKey = new Map<String, List<Case>>();
			Map<Id, Case> upgradeSeatCaseMapByPaxId = new Map<Id, Case>();
			Map<Id, Case_Group_Member__c> caseGroupMemberMapByPaxId = new Map<Id, Case_Group_Member__c>();
			List<Case> failedCaseList = new List<Case>();

			CSE_SOAP_ROPMANAGEAWARD_WS ws = new CSE_SOAP_ROPMANAGEAWARD_WS();
			for (MB_RESTRequestInfoModel.upgradeSeat each : upgradeSeatList) {
				Id aircraftId = flightMapById.get(each.fltId).AircraftId__c;
				Boolean isVoided = BE8_GlobalConstants.INTEGER_TO_BOOLEAN.get(each.isVoided);
				if (passengerMapByPaxId.containsKey(each.paxId)) {
					Passenger__c passengerToChangeSeat = passengerMapByPaxId.get(each.paxId);
					WS_ROPManageAward_Model response;
					Boolean useMoney = each.payType == 'Cash' || each.payType == 'Credit Card';
					Boolean burnMileageWithTG = !isVoided && !useMoney && masterDataMapByCode.containsKey(each.upCode);
					String awardPackage = null;
					Decimal mileageToBeUsed = null;

					if (burnMileageWithTG) {
						In_flight_Upgrade_Seat_Master__mdt award = ((In_flight_Upgrade_Seat_Master__mdt)masterDataMapByCode.get(each.upcode));
						mileageToBeUsed = award.ROP_Award_Code__r.Mileages__c;
						String promotionCode = award.ROP_Award_Code__r.Promotion_Code__c;
						awardPackage = award.ROP_Award_Code__r.DeveloperName;
						String ropNumber = passengerToChangeSeat.FFP_Number__c;
						each.ropNumber = ropNumber;
						try {
							AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', each.ropNumber, 'ROP Number to Upgrade Seat', 'Burn Mileage with ROP Number: ' + each.ropNumber + ' Promotion Code: ' + promotionCode + ' Award Package: ' + awardPackage + ' Mileage Used: ' + mileageToBeUsed, System.JSON.serialize(each), null, System.currentTimeMillis());
							response = ws.burnMileage(each.ropNumber, promotionCode, awardPackage);
							//AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', each.ropNumber, 'ROP Number to Upgrade Seat', 'Burn Mileage Response of ROP Number: ' + each.ropNumber + ' Promotion Code: ' + promotionCode + ' Award Package: ' + awardPackage, System.JSON.serialize(response), null, System.currentTimeMillis());
						} catch (Exception e) {
							String message = 'Problem occured during integration with THAI.\n' + e.getMessage() + '\n' + e.getStackTraceString();
							AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'upgradeSeat', each.ropNumber, 'ROP Number to Upgrade Seat', message, System.JSON.serialize(each), null, System.currentTimeMillis());
						}
					}

					if (!isVoided) {
						passengerToChangeSeat.Change_Seat__c = each.toSeat;
						passengerToChangeSeat.Change_Cabin_Class__c = each.toClass;
						passengerToChangeSeat.Last_Change_Seat_DateTime__c = BE8_DateUtility.convertFromStringToDateTimeFromMobile(each.creDT);
						passengerListToBeUpdated.add(passengerToChangeSeat);
					}

					Case upgradeSeatCase = createUpgradeSeatCase(each, passengerToChangeSeat, aircraftId, response, awardPackage, mileageToBeUsed);
					Case_Group_Member__c caseGroupMember = createUpgradeSeatCaseGroupMember(each, passengerToChangeSeat, aircraftId);
					upgradeSeatCaseMapByPaxId.put(passengerToChangeSeat.Id, upgradeSeatCase);
					caseGroupMemberMapByPaxId.put(passengerToChangeSeat.Id, caseGroupMember);

					if (response != null && response.hasError()) {
						String responseJSON = System.JSON.serialize(response);
						String message = 'ROP Burn Mileage Web Service with THAI returned with error.\n' + responseJSON;
						AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'upgradeSeat', each.ropNumber, 'ROP Number to Upgrade Seat', message, System.JSON.serialize(each), null, System.currentTimeMillis());
						upgradeSeatCase.Status = BE8_GlobalConstants.CASE_STATUS_VOID;
						upgradeSeatCase.Integration_Error__c = true;
						upgradeSeatCase.Integration_Error_Reason__c = response != null ? response.getErrorMessage() : 'Response is null or it is not serializable.';
						failedCaseList.add(upgradeSeatCase);
					}
				}
			}

			Set<Id> passengerToBeUpdatedIdSet = BE8_GlobalUtility.getIdSet('Id', passengerListToBeUpdated);
			try {
				AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '' + passengerToBeUpdatedIdSet, 'Passenger__c', 'Passenger List to be updated with change seat and change class.', System.JSON.serialize(passengerListToBeUpdated), null, System.currentTimeMillis());
				update PassengerService.dedupPassengerToChangeSeatList(passengerListToBeUpdated);
			} catch (Exception e) {
				String message = 'Error while updating Passenger.\n' + e.getMessage() + '\n' + e.getStackTraceString();
				AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'upgradeSeat', '' + passengerToBeUpdatedIdSet, 'Passenger__c', message, System.JSON.serialize(passengerListToBeUpdated), null, System.currentTimeMillis());
			}

			try {
				AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '', 'Case', 'Case to be created with change seat and change class.', System.JSON.serialize(upgradeSeatCaseMapByPaxId), null, System.currentTimeMillis());
				insert upgradeSeatCaseMapByPaxId.values();
				AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '' + BE8_GlobalUtility.getIdSet('Id', upgradeSeatCaseMapByPaxId.values()), 'Case', 'Case after insert with change seat and change class.', System.JSON.serialize(upgradeSeatCaseMapByPaxId), null, System.currentTimeMillis());
			} catch (Exception e) {
				String message = 'Error while inserting Case.\n' + e.getMessage() + '\n' + e.getStackTraceString();
				AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'upgradeSeat', '', 'Case', message, System.JSON.serialize(upgradeSeatCaseMapByPaxId), null, System.currentTimeMillis());
			}

			try {
				AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '', 'Case', 'Case Group Member to be created with change seat and change class.', System.JSON.serialize(caseGroupMemberMapByPaxId), null, System.currentTimeMillis());
				for (Case eachCase : upgradeSeatCaseMapByPaxId.values()) {
					if (caseGroupMemberMapByPaxId.containsKey(eachCase.Passengerid__c)) {
						caseGroupMemberMapByPaxId.get(eachCase.Passengerid__c).CaseId__c = eachCase.Id;
					}
				}
				insert caseGroupMemberMapByPaxId.values();
				AppLogger.add(BE8_GlobalConstants.LEVEL_INFO, 'MB_RESTUpgradeSeat', 'upgradeSeat', '' + BE8_GlobalUtility.getIdSet('Id', caseGroupMemberMapByPaxId.values()), 'Case', 'Case Group Member after insert with change seat and change class.', System.JSON.serialize(caseGroupMemberMapByPaxId.values()), null, System.currentTimeMillis());
			} catch (Exception e) {
				String message = 'Error while inserting Case Group Member.\n' + e.getMessage() + '\n' + e.getStackTraceString();
				AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'upgradeSeat', '', 'Case_Group_Member__c', message, System.JSON.serialize(caseGroupMemberMapByPaxId.values()), null, System.currentTimeMillis());
			}

			sendEmailNotifyFailedBurnMileage(failedCaseList, passengerList);
			AppLogger.insertLogs();
		}
		return createMobileResponseList(upgradeSeatList);
	}

	private static List<MB_RestResponseInfoModel.upgradeSeat> createMobileResponseList(List<MB_RESTRequestInfoModel.upgradeSeat> upgradeSeatList) {
		List<MB_RestResponseInfoModel.upgradeSeat> responseList = new List<MB_RestResponseInfoModel.upgradeSeat>();
		for (MB_RESTRequestInfoModel.upgradeSeat each : upgradeSeatList) {
			MB_RestResponseInfoModel.upgradeSeat responseModel = new MB_RestResponseInfoModel.upgradeSeat();
			responseModel.ropNumber = each.ropNumber;
			responseModel.toClass = each.toClass;
			responseModel.toSeat = each.toSeat;
			responseModel.paxKey = each.paxKey;
			responseModel.fltId = each.fltId;
			responseModel.paxId = each.paxId;
			responseModel.upcode = each.upcode;
			responseModel.creDT = each.creDT;
			responseList.add(responseModel);
		}
		return responseList;
	}

	public static void sendEmailNotifyFailedBurnMileage(List<Case> caseList, List<Passenger__c> passengerList) {
		Map<Id, Passenger__c> passengerMapById = new Map<Id, Passenger__c>(passengerList);
		List<String> emailAddressList = MailList_Repository.getEmailList('Upgrade Seat').values();

		List<Messaging.SingleEmailMessage> emailMessageList = new List<Messaging.SingleEmailMessage>();
		for (Case eachCase : caseList) {
			Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
			List<String> toAddresses = new List<String>();
			toAddresses.addAll(emailAddressList);
			mail.setToAddresses(toAddresses);
			Passenger__c thisPassenger = passengerMapById.get(eachCase.Passengerid__c);
			if (thisPassenger != null) {
				String flightName = thisPassenger.FlightId__r.Name;
				String ropNumber = thisPassenger.FFP_Number__c;
				String subject = 'Failed Upgrade Seat by Mileage: ' + ropNumber + ' ' + flightName;
				String bodyMsg = 'The upgrade seat that occured during ' + flightName + ' has failed.\n'
				                 + 'Please proceed to check for any error messages and notify administrator to resolve this issue.\n'
				                 + 'You can check the record of this case in Salesforce at ' + URL.getSalesforceBaseUrl().toExternalForm() + '/' + eachCase.Id;
				mail.setSubject(subject);
				mail.setPlainTextBody(bodyMsg);
				emailMessageList.add(mail);
			}
		}

		try {
			AppLogger.add(BE8_GlobalConstants.LEVEL_DEBUG, 'MB_RESTUpgradeSeat', 'sendEmailNotifyFailedBurnMileage', '', '', 'Sent Email', System.JSON.serialize(emailMessageList), null, System.currentTimeMillis());
			Messaging.sendEmail(emailMessageList);
		} catch (Exception e) {
			String message = e.getMessage() + '\n' + e.getStackTraceString();
			AppLogger.add(BE8_GlobalConstants.LEVEL_ERROR, 'MB_RESTUpgradeSeat', 'sendEmailNotifyFailedBurnMileage', '', '', message, System.JSON.serialize(caseList), null, System.currentTimeMillis());
			AppLogger.insertLogs();
		}
	}

	private static Case createUpgradeSeatCase(MB_RESTRequestInfoModel.upgradeSeat eachUpgradeSeatRequest, Passenger__c eachPassenger, Id aircraftId, WS_ROPManageAward_Model response, String awardPackage, Decimal mileageToBeUsed) {
		Case upgradeSeatCase = new Case();
		upgradeSeatCase.Mobile_App_Key__c = eachUpgradeSeatRequest.id;
		upgradeSeatCase.Subject = 'Upgrade Seat';
		upgradeSeatCase.Passengerid__c = eachPassenger.Id;
		upgradeSeatCase.Flightid__c = eachUpgradeSeatRequest.fltId;
		upgradeSeatCase.A_C_REG_ID__c = aircraftId;
		upgradeSeatCase.Case_Type__c = BE8_GlobalConstants.CASE_TYPE_INFORMATION;
		upgradeSeatCase.Origin = BE8_GlobalConstants.CASE_CHANNEL_IN_FLIGHT;
		upgradeSeatCase.Priority = BE8_GlobalConstants.CASE_PRIORITY_MEDIUM;
		upgradeSeatCase.Json_Body__c = 'request: ' + JSON.serialize(eachUpgradeSeatRequest);
		if (response != null) {
			upgradeSeatCase.Json_Body__c += '\n\nresponse: ' + JSON.serialize(response);
			Integer jsonBodyFieldLength = Case.Json_Body__c.getDescribe().getLength();
			if (upgradeSeatCase.Json_Body__c.length() > jsonBodyFieldLength) {
				upgradeSeatCase.Json_Body__c = upgradeSeatCase.Json_Body__c.substring(0, jsonBodyFieldLength);
			}
		}
		upgradeSeatCase.RecordTypeId = BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case', BE8_GlobalConstants.CASE_RECORD_TYPE_IN_FLIGHT);
		upgradeSeatCase.Status = BE8_GlobalConstants.INTEGER_TO_BOOLEAN.get(eachUpgradeSeatRequest.isVoided) ? BE8_GlobalConstants.CASE_STATUS_VOID : BE8_GlobalConstants.CASE_STATUS_CLOSED;
		upgradeSeatCase.Change_Seat__c = eachUpgradeSeatRequest.toSeat;
		upgradeSeatCase.Change_Cabin_Class__c = eachUpgradeSeatRequest.toClass;
		upgradeSeatCase.Payment_Type__c = eachUpgradeSeatRequest.payType;
		upgradeSeatCase.Upgrade_Seat_with_Amount__c = eachUpgradeSeatRequest.amount;
		upgradeSeatCase.Upgrade_Seat_Amount_Currency__c = eachUpgradeSeatRequest.currenc;
		upgradeSeatCase.Description = eachUpgradeSeatRequest.detail;
		upgradeSeatCase.Incident_Category_Mobile__c = '' + 1; // Passenger
		upgradeSeatCase.Upgrade_Change_Seat_Type__c = 'upgradeSeat';
		upgradeSeatCase.Created_At_Mobile__c = BE8_DateUtility.convertFromStringToDateTimeFromMobile(eachUpgradeSeatRequest.creDT);
		upgradeSeatCase.Is_Upgrade_Seat_Case__c = true;
		upgradeSeatCase.ROP_Award_Code__c = awardPackage;
		if(mileageToBeUsed != null){
			upgradeSeatCase.Upgrade_Seat_with_Amount__c = mileageToBeUsed;
		}
		return upgradeSeatCase;
	}

	private static Case_Group_Member__c createUpgradeSeatCaseGroupMember(MB_RESTRequestInfoModel.upgradeSeat eachUpgradeSeatRequest, Passenger__c eachPassenger, Id aircraftId) {
		Case_Group_Member__c caseGroupMember = new Case_Group_Member__c();
		caseGroupMember.FlightId__c = eachUpgradeSeatRequest.fltId;
		caseGroupMember.Passengerid__c = eachPassenger.Id;
		caseGroupMember.Aircraft__c = aircraftId;
		caseGroupMember.Change_Seat__c = eachUpgradeSeatRequest.toSeat;
		caseGroupMember.Change_Cabin_Class__c = eachUpgradeSeatRequest.toClass;
		caseGroupMember.RecordTypeId = BE8_GlobalUtility.getRecordTypeIdFromSObjectByDevName('Case_Group_Member__c', BE8_GlobalConstants.CASE_GROUP_MEMBER_RECORD_TYPE_GROUND_SERVICE);
		return caseGroupMember;
	}
}
/*
{"upgradeSeatList":[
{"ropNumber":"ZD65332", "toClass":"C", "toSeat":"2A", "paxKey":"LUCE_HAZANPINTO_6E5K4R_TG0930_19FEB17", "fltId":"a0IN0000004bkGs", "paxId":"a0NN0000006caIa", "code":"A001"}
]}
*/