prd_package/objects/Case.object
<CustomObject>
    <fields>
        <fullName>A_C_Type__c</fullName>
        <description>Displays the Aircraft Type that the Case is related to (via Aircraft)</description>
        <formula>A_C_REG_ID__r.Aircraft_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>A/C Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number_Custom_F__c</fullName>
        <description>Displays the Case Number as a combination of Station Created by, Department and the automated Salesforce generated numbers</description>
        <formula>CreatedBy.Station__c &amp; CreatedBy.Department &amp; CaseNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number_txt__c</fullName>
        <label>Flight Number txt</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <description>Displayed authorized person&apos;s position which support for both of BKK and non-BKK. This field is used to be a pert of autorized signatue in email and print feature.</description>
        <formula>IF(	Owner:User.Station__c != &apos;BKK&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;CNX&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;HKT&apos; &amp;&amp; 
	Owner:User.Station__c != &apos;KBV&apos; &amp;&amp;
	Owner:User.Station__c != &apos;USM&apos;,
        Position_txt__c,
IF(
Text(Authorize_Signature__c) != null,
IF(
Text(Letter_Language__c) == &quot;TH&quot;,
Position_TH_txt__c ,
Position_EN_txt__c
),
null)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Position</label>
        <type>Text</type>
    </fields>
</CustomObject>

prd_package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>Caseid__c</fullName>
        <description>Displays the case that the case group member is related to</description>
        <label>Case Number</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Group Members</relationshipLabel>
        <relationshipName>Case_Group_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Position__c</fullName>
        <label>Position</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>TEXT( Caseid__r.Status )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>มูลค่าเป็นเงินของสิ่งที่ Compensate</description>
        <label>Amount (Cash/EMD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>ID of the case associated with this compensation.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Case_Group_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>ID of the case group member associated with this compensation.</description>
        <label>Case Group Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.CaseId__c</field>
                <operation>equals</operation>
                <valueField>Case_Group_Member__c.Caseid__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Group_Member__c</referenceTo>
        <relationshipLabel>Compensations</relationshipLabel>
        <relationshipName>Compensations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Compensation_Account_Center__c</fullName>
        <label>Compensation Account Center</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1030100</fullName>
                </value>
                <value>
                    <fullName>1015519</fullName>
                </value>
                <value>
                    <fullName>1301220</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Account_Number__c</fullName>
        <label>Compensation Account Number</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Center__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>631070</fullName>
                    <label>631070 - Baggage Claims Compensation</label>
                </value>
                <value>
                    <fullName>631071</fullName>
                    <label>631071 - Injury</label>
                </value>
                <value>
                    <fullName>631080</fullName>
                    <label>631080 - Compensation EX-Gratia Passenger Complaint&amp;Claim</label>
                </value>
                <value>
                    <fullName>631130</fullName>
                    <label>631130 - DBC / DGC</label>
                </value>
                <value>
                    <fullName>631140</fullName>
                    <label>631140 - Customer Relations EMD</label>
                </value>
                <value>
                    <fullName>631150</fullName>
                    <label>631150 - Inflight Service Compliment</label>
                </value>
                <value>
                    <fullName>811106</fullName>
                    <label>811106 -  Int.Charge for Other Flight Kitchen (for Lounge Access Voucher)</label>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compensation_Tools__c</fullName>
        <label>Compensation Tools</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Compensation_Account_Number__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Complimentary Ticket</fullName>
                </value>
                <value>
                    <fullName>Duty Free</fullName>
                </value>
                <value>
                    <fullName>EMD</fullName>
                </value>
                <value>
                    <fullName>Excess Baggage</fullName>
                </value>
                <value>
                    <fullName>Gifts</fullName>
                </value>
                <value>
                    <fullName>Lounge Access Voucher</fullName>
                </value>
                <value>
                    <fullName>Mileage Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Upgrading</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>SO code of the currency. Must be one of the valid alphabetic, three-letter currency ISO codes defined by the ISO 4217 standard, such as USD, GBP, or JPY.</description>
        <label>Currency</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Unit__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>USD</fullName>
                </value>
                <value>
                    <fullName>THB</fullName>
                </value>
                <value>
                    <fullName>GBP</fullName>
                </value>
                <value>
                    <fullName>AUD</fullName>
                </value>
                <value>
                    <fullName>EUR</fullName>
                </value>
                <value>
                    <fullName>BHD</fullName>
                </value>
                <value>
                    <fullName>BDT</fullName>
                </value>
                <value>
                    <fullName>KHR</fullName>
                </value>
                <value>
                    <fullName>CAD</fullName>
                </value>
                <value>
                    <fullName>CNY</fullName>
                </value>
                <value>
                    <fullName>DKK</fullName>
                </value>
                <value>
                    <fullName>HKD</fullName>
                </value>
                <value>
                    <fullName>INR</fullName>
                </value>
                <value>
                    <fullName>IDR</fullName>
                </value>
                <value>
                    <fullName>IRR</fullName>
                </value>
                <value>
                    <fullName>JPY</fullName>
                </value>
                <value>
                    <fullName>KRW</fullName>
                </value>
                <value>
                    <fullName>LAK</fullName>
                </value>
                <value>
                    <fullName>MOP</fullName>
                </value>
                <value>
                    <fullName>MYR</fullName>
                </value>
                <value>
                    <fullName>MMK</fullName>
                </value>
                <value>
                    <fullName>NPR</fullName>
                </value>
                <value>
                    <fullName>NZD</fullName>
                </value>
                <value>
                    <fullName>NOK</fullName>
                </value>
                <value>
                    <fullName>OMR</fullName>
                </value>
                <value>
                    <fullName>PKR</fullName>
                </value>
                <value>
                    <fullName>PHP</fullName>
                </value>
                <value>
                    <fullName>RUB</fullName>
                </value>
                <value>
                    <fullName>SGD</fullName>
                </value>
                <value>
                    <fullName>LKR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Is_Individual__c</fullName>
        <description>Checks whether the compensation is meant for an individual</description>
        <formula>!ISBLANK(Case_Group_Member__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Individual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ROE__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Rate of exchange</description>
        <label>ROE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Obsolete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_THB__c</fullName>
        <formula>IF( ROE__c &gt; 0 &amp;&amp;  Amount__c &gt; 0 , Amount__c * ROE__c ,  Amount__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total (THB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/classes/PVController.cls
public with sharing class PVController {

    public PVView view {get; set;}
    public String logoURL {get; set;}
    public String selectedCaseGroupMemberId {get; set;}
    public String selectedAccountNumber {get; set;}
    public String selectedAccountCenter {get; set;}
    public String selectedAccountNumberPartial {get; set;}
    public String selectedAccountCenterPartial {get; set;}
    public Boolean displayTHB {get; set;}
    public String currencyWord;
    public String subCurrencyWord;
    public String targetCurrency {get; set;}
    public Integer noCaseGroupMember = 0;
    public String pdfName {get; set;}

    public class PVView {
        public String caseNumber {get; set;}
        public String caseNumberSTD {get; set;}
        public String position {get; set;}
        public String amountInWords {get; set;}
        public Decimal amountInFigures {get; set;}
        public String amountInFiguresDec {get; set;}
        public String freeTextComment {get; set;}
        public Boolean isCash {get; set;}
        public Boolean isCheque {get; set;}
        public Case caseObj {get; set;}
        public List<Compensation__c> compensations {get; set;}
    }

    public PVController(ApexPages.StandardController stdController) {
        System.debug('SJ : Case ID' + stdController.getId());
        selectedAccountNumber = Apexpages.Currentpage().getParameters().get('selectedAccountNumber');
        selectedAccountCenter = Apexpages.Currentpage().getParameters().get('selectedAccountCenter');
        pdfName = Apexpages.Currentpage().getParameters().get('pdfName');
        Case currentCase;

        String compensationIds = Apexpages.Currentpage().getParameters().get('compensationIds');
        if(String.isBlank(compensationIds)) {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select compensation'));
            return;
        } else {
            List<Id> compensationIdList = compensationIds.split(',');
            currentCase = [SELECT Id, CaseNumber, Case_Number_Custom_F__c, Position__c, A_C_Type__c, Flight_Number_txt__c, (SELECT Id, Total_THB__c, Compensation_Account_Center__c, Compensation_Account_Number__c, Compensation_Tools__c, ROE__c, Amount__c, Currency__c, Is_Individual__c, Case_Group_Member__c FROM Compensations__r WHERE Id IN :compensationIdList AND Status__c = 'Approved') FROM Case WHERE Id = : stdController.getId() LIMIT 1];


            if(!Compensation_Service.validateAccountNumberAndAccountCenter(currentCase.Compensations__r)) {
                //ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, 'Invalid Account Number or Account Center'));
                return;
            }
        }
        
        selectedAccountNumberPartial = Apexpages.Currentpage().getParameters().get('selectedAccountNumberPartial');
        selectedAccountCenterPartial = Apexpages.Currentpage().getParameters().get('selectedAccountCenterPartial');
        
        //System.debug('currentCase :' + currentCase);
        System.debug('currentCase :' + JSON.serialize(currentCase));
        List<Case_Group_Member__c> caseGroupMembers = [SELECT Id FROM Case_Group_Member__c WHERE CaseID__c = :currentCase.Id];
        noCaseGroupMember = caseGroupMembers.size();

        String comment = Apexpages.Currentpage().getParameters().get('comment');
        comment = comment.replaceAll('  ', '&nbsp;&nbsp;');
        selectedCaseGroupMemberId = Apexpages.Currentpage().getParameters().get('selectedCaseGroupMemberId');
        String displayTHBStr = Apexpages.Currentpage().getParameters().get('displayTHB');
        currencyWord = Apexpages.Currentpage().getParameters().get('currencyWord');
        subCurrencyWord = Apexpages.Currentpage().getParameters().get('subCurrencyWord');
        if (String.isBlank(displayTHBStr)) {
            displayTHB = false;
        } else {
            displayTHB = Boolean.valueOf(displayTHBStr);
        }
        //if (!String.isBlank(selectedCaseGroupMemberIdStr )) {
        //    selectedCaseGroupMemberId = selectedCaseGroupMemberIdStr ;
        //}
        view = createPVView(currentCase, comment);
        List<Document> docList = [SELECT id FROM Document where name = 'THAI_Logo'];
        if (docList != null && docList.size() > 0) {
            logoURL = '/servlet/servlet.FileDownload?file=' + docList.get(0).Id;
        }

        Apexpages.currentPage().getHeaders().put('content-disposition', 'inline; filename=' + pdfName);
        //Apexpages.currentPage().getHeaders().put('content-disposition', 'attachment; filename=' + pdfName);

        System.debug('ctrl.view.amountInFigures : ' + view.amountInFigures);
        System.debug('ctrl.view.amountInFiguresDec : ' + view.amountInFiguresDec);
    }

    private PVView createPVView(Case caseObj, String comment) {
        PVView view = new PVView();
        view.caseObj = caseObj;
        view.caseNumberSTD = caseObj.CaseNumber;
        view.caseNumber = caseObj.Case_Number_Custom_F__c;
        view.position = caseObj.Position__c;
        view.compensations = caseObj.Compensations__r;
        //if (!String.isBlank(comment)) {
        //    view.freeTextComment = comment.replace('\n', '<br/>').replace(' ', ' ');
        //}
        view.freeTextComment = comment;

        String isChequeStr = Apexpages.CurrentPage().getParameters().get('isCheque');
        if (!String.isBlank(isChequeStr)) {
            view.isCheque = Boolean.valueOf(isChequeStr);
        }

        String isCashStr = Apexpages.CurrentPage().getParameters().get('isCash');
        if (!String.isBlank(isCashStr)) {
            view.isCash = Boolean.valueOf(isCashStr);
        }

        Decimal totalAmount = 0;
        targetCurrency = 'THB';
        System.debug('caseObj.Compensations__r: ' + JSON.serialize(caseObj.Compensations__r));
        for (Compensation__c each : caseObj.Compensations__r) {
            if (each.Compensation_Tools__c == 'Cash' || each.Compensation_Tools__c == 'EMD') {
                if (each.Amount__c != null) {
                    if (each.Is_Individual__c && each.Case_Group_Member__c != selectedCaseGroupMemberId) {
                        continue;
                    }

                    totalAmount += Compensation_Service.getAmountPerPassenger(each, displayTHB);
                    if (displayTHB) {
                        currencyWord = 'BAHT';
                        subCurrencyWord = 'SATANG';
                    } else {
                        targetCurrency = each.Currency__c;
                    }
                }
            }
        }
        totalAmount = totalAmount.setScale(2);
        System.debug('totalAmount :' + totalAmount);
        if (totalAmount > 0) {
            String amount = String.valueOf(totalAmount);
            view.amountInFigures = Decimal.valueOf(amount.substring(0, amount.indexOf('.')));
            System.debug('view.amountInFigures :' + view.amountInFigures);
            view.amountInFiguresDec = amount.substring(amount.indexOf('.') + 1);
            view.amountInWords = new NumbersToWordsClass().convert((Long)view.amountInFigures).toUpperCase() + ' ' + currencyWord + ' ' + (Long.valueOf(view.amountInFiguresDec) > 0 ? new NumbersToWordsClass().convert(Long.valueOf(view.amountInFiguresDec)).toUpperCase() + ' ' + subCurrencyWord : 'ONLY');
        }

        return view;
    }
}