prd_package/objects/Case_Group_Member__c.object
<CustomObject>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <label>FFP Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact__c</fullName>
        <label>Impact</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Serviceable</fullName>
                </value>
                <value>
                    <fullName>Malfunction</fullName>
                </value>
                <value>
                    <fullName>Block</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Group Member</label>
    <nameField>
        <displayFormat>CGM-{0000000000}</displayFormat>
        <label>Case Group Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Match_with_ROP__c</fullName>
        <description>Check if the passenger is ROP member with matching last name and date of birth</description>
        <formula>AND(FFP_Carrier__c == &apos;TG&apos;, AccountId__r.ROP_Number__c != null, AccountId__c != null, AccountId__r.Last_Name__c == Last_Name__c, AccountId__r.Date_of_Birth__c == Date_of_Birth_Input__c)</formula>
        <label>Match with ROP</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/InFlightLOPAStatusHandler.cls
public with sharing class InFlightLOPAStatusHandler implements LOPAStatusHandler {

	public String getLOPAPositionStatus(String position, String positionType, Passenger__c matchedPassenger, List<Case_Group_Member__c> matchedCaseList, MB_RestResponseInfoModel.lopaInfo_lopaPos lopaPos) {
		Boolean isPassengerSeat = positionType == BE8_GlobalConstants.TYPE_SEAT;
		Boolean isPassengerSeatOccupied = isPassengerSeat && (matchedPassenger != null);
		Boolean isROP = isPassengerSeatOccupied && (matchedPassenger.FFP_Carrier__c == BE8_GlobalConstants.DEFAULT_TG_COMPANY);

		Boolean hasCase = matchedCaseList != null;
		Boolean isServiceable = !hasCase || matchedCaseList.size() == 0;

		Boolean isOccupied = isPassengerSeatOccupied;
		Boolean isBlock = false;
		Boolean isMalfunction = false;
		Boolean isGold = false;
		Boolean isPlatinum = false;

		Boolean isBlockedFromLOPA = lopaPos.sOcp != null && BE8_GlobalConstants.SEAT_OCCUPATION_BLOCKED_SEAT.contains(lopaPos.sOcp);

		String status = '';
		if (isPassengerSeat) {
			if (!isServiceable) {
				for (Case_Group_Member__c eachMember : matchedCaseList) {
					if (eachMember.Impact__c == BE8_GlobalConstants.IMPACT_BLOCK) {
						isBlock = true;
						break;
					}
					if (eachMember.Impact__c == BE8_GlobalConstants.IMPACT_MALFUNCTION) {
						isMalfunction = true;
						break;
					}
				}
			}
		}

		if (isROP && matchedPassenger.Match_with_ROP__c) {
			isGold = matchedPassenger.FFP_Tier__c != null && matchedPassenger.FFP_Tier__c == BE8_GlobalConstants.FFP_TIER_GOLD;
			isPlatinum = matchedPassenger.FFP_Tier__c != null && matchedPassenger.FFP_Tier__c == BE8_GlobalConstants.FFP_TIER_PLATINUM;
		}


		if (isBlockedFromLOPA && !isOccupied) {
			return BE8_GlobalConstants.LOPA_STATUS_BLOCKED_FROM_LOPA;
		}
		if (isMalfunction && isGold) {
			return BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_GOLD;
		}
		if (isMalfunction && isPlatinum) {
			return BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_PLATINUM;
		}
		if (isBlock && isGold) {
			return BE8_GlobalConstants.LOPA_STATUS_BLOCK_GOLD;
		}
		if (isBlock && isPlatinum) {
			return BE8_GlobalConstants.LOPA_STATUS_BLOCK_PLATINUM;
		}
		if (isOccupied && isGold) {
			return BE8_GlobalConstants.LOPA_STATUS_OCCUPIED_GOLD;
		}
		if (isOccupied && isPlatinum) {
			return BE8_GlobalConstants.LOPA_STATUS_OCCUPIED_PLATINUM;
		}
		if (isMalfunction && isOccupied) {
			return BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION_OCCUPIED;
		}
		if (isBlock && isOccupied) {
			return BE8_GlobalConstants.LOPA_STATUS_BLOCK_OCCUPIED;
		}
		if (isMalfunction) {
			return BE8_GlobalConstants.LOPA_STATUS_MALFUNCTION;
		}
		if (isBlock) {
			return BE8_GlobalConstants.LOPA_STATUS_BLOCK;
		}
		if (isOccupied) {
			return BE8_GlobalConstants.LOPA_STATUS_OCCUPIED;
		} else {
			return BE8_GlobalConstants.LOPA_STATUS_AVAILABLE;
		}
	}
}