prd_package/objects/Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Mobile_App_Key__c</fullName>
        <label>Mobile App Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Compensation</label>
    <nameField>
        <displayFormat>CMP-{0000000000}</displayFormat>
        <label>Running Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/classes/MB_RESTCompensationAttachment.cls
@RestResource(urlMapping = '/compensation/attachment/*')
global class MB_RESTCompensationAttachment {

	@HttpPost
	global static MB_RestRequestInfoModel.attachment_response doPost(MB_RestRequestInfoModel.attachment_list receiveAttachment) {
		Compensation__c compensation = [SELECT Id FROM Compensation__c WHERE Mobile_App_Key__c = : receiveAttachment.parentId LIMIT 1];
		return AttachmentService.createAttachmentFromMobile(compensation, receiveAttachment);
	}
}