prd_package/objects/Crew_Mapping__c.object
<CustomObject>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Mappings</relationshipLabel>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_Sync_Time__c</fullName>
        <label>Last Sync Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Crew_Mappings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Crew Mapping</label>
    <nameField>
        <displayFormat>CM-{00000000}</displayFormat>
        <label>Crew Mapping No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Crew Mappings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/CrewHandler.cls
public class CrewHandler {
	public static Map<Id, Crew_Mapping__c> mapCrewMappingByCrewId;

	public static Map<Id, Crew_Mapping__c> getMapCrewMappingByCrewId(Set<Id> setCrewId){
		if(mapCrewMappingByCrewId==null){
			setMapCrewMappingByCrewId(setCrewId);
		}
		return mapCrewMappingByCrewId;
	}
	public static Map<Id, Crew_Mapping__c> getMapCrewMappingByCrewId(){
		if(mapCrewMappingByCrewId==null){
			setMapCrewMappingByCrewId();
		}
		return mapCrewMappingByCrewId;
	}
	public static void setMapCrewMappingByCrewId(){
		List<Crew_Mapping__c> listCrewMapping = [Select Id, 
														Name ,
														CrewId__c,
														Last_Sync_Time__c,
														UserId__c
													From Crew_Mapping__c
													Where isActive__c = true ];
		if(mapCrewMappingByCrewId==null)	mapCrewMappingByCrewId = new Map<Id, Crew_Mapping__c>();
		for(Crew_Mapping__c eachCrew :listCrewMapping){
			mapCrewMappingByCrewId.put(eachCrew.CrewId__c, eachCrew);
		}
	}
	public static void setMapCrewMappingByCrewId(Set<Id> setCrewId){
		List<Crew_Mapping__c> listCrewMapping = [Select Id, 
														Name ,
														CrewId__c,
														Last_Sync_Time__c,
														UserId__c
													From Crew_Mapping__c
													Where isActive__c = true 
													and CrewId__c in :setCrewId ];
		if(mapCrewMappingByCrewId==null)	mapCrewMappingByCrewId = new Map<Id, Crew_Mapping__c>();
		for(Crew_Mapping__c eachCrew :listCrewMapping){
			mapCrewMappingByCrewId.put(eachCrew.CrewId__c, eachCrew);
		}
	}

}