prd_package/objects/Crew__c.object
<CustomObject>
    <fields>
        <fullName>Personel_Id__c</fullName>
        <description>The crew’s employee number.</description>
        <externalId>true</externalId>
        <label>Personel Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Rank of the crew such as FC or AP.</description>
        <label>Rank</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Crew</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_Appraisal_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Appraisal_Id__c</fullName>
        <label>Appraisal Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evaluated_Personel_Id__c</fullName>
        <label>Evaluated Personel Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Evaluator_Personel_Id__c</fullName>
        <label>Evaluator Personel Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_Id__c</fullName>
        <label>Flight External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Number__c</fullName>
        <label>Form Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Raw__c</fullName>
        <label>Raw</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Crew Appraisal Answer</label>
    <nameField>
        <label>Crew Appraisal Answer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Appraisal Answers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Crew_List__c.object
<CustomObject>
    <fields>
        <fullName>Acting_Rank__c</fullName>
        <label>Acting Rank</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CrewId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Crew</label>
        <referenceTo>Crew__c</referenceTo>
        <relationshipLabel>Crew Lists</relationshipLabel>
        <relationshipName>Crew_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Crew_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Crew External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Duty_Assignment__c</fullName>
        <label>Duty Assignment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Duty_Code__c</fullName>
        <label>Duty Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipName>Crews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POS_Fly__c</fullName>
        <label>POS Fly</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Rank of the crew such as FC or AP.</description>
        <label>Rank</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Crew List</label>
    <nameField>
        <label>Crew Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Lists</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Type__c</fullName>
        <label>Aircraft Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Airline_Code__c</fullName>
        <formula>IF(LEFT(Name, 2)==&apos;TG&apos;, &apos;TG&apos;, &apos;&apos;)</formula>
        <label>Airline Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Block_Time__c</fullName>
        <description>Displays actual flying time in units of minutes</description>
        <label>Block Time</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/MD_Appraisal_Item__c.object
<CustomObject>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Value__c</fullName>
        <label>Default Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Description__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Description__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Form_Description</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Number__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Name</formula>
        <label>Form Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MD_Appraisal_Item_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>MD Appraisal Item External ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MD_Appraisal_Subject__c</fullName>
        <label>MD Appraisal Subject</label>
        <referenceTo>MD_Appraisal_Subject__c</referenceTo>
        <relationshipLabel>MD Appraisal Items</relationshipLabel>
        <relationshipName>MD_Appraisal_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>FreeText</fullName>
                </value>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>YesNo</fullName>
                </value>
                <value>
                    <fullName>YesNoNA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <formula>MD_Appraisal_Subject__r.MD_Appraisal_Form__r.Version__c</formula>
        <label>Version</label>
        <type>Text</type>
    </fields>
    <label>MD Appraisal Item</label>
    <nameField>
        <label>MD Appraisal Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/MD_Appraisal_Subject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MD Appraisal Subject</label>
    <nameField>
        <label>MD Appraisal Subject Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MD_CrewAppraisal_RestResource.cls
@RestResource(urlMapping = '/crewappraisal')
global with sharing class MD_CrewAppraisal_RestResource {

    //@HttpGet
    //global static List<Map<String, String>> get() {
    //    List<Map<String, String>> responseDatas = new List<Map<String, String>>();
    //    List<MD_Appraisal_Item__c> mdItems = [SELECT Id, MD_Appraisal_Item_External_ID__c, Form_Number__c, Form_Description__c, MD_Appraisal_Subject__r.Name, MD_Appraisal_Subject__r.Description__c, MD_Appraisal_Subject__r.Type__c, Version__c, Name, Condition__c, Description__c, Type__c FROM MD_Appraisal_Item__c ORDER BY MD_Appraisal_Item_External_ID__c ASC];

    //    for (MD_Appraisal_Item__c eachMDItem : mdItems) {
    //        Map<String, String> dataEachItem = new Map<String, String>();
    //        dataEachItem.put('id', eachMDItem.MD_Appraisal_Item_External_ID__c);
    //        dataEachItem.put('sfdcId', eachMDItem.Id);
    //        dataEachItem.put('version', eachMDItem.Version__c);
    //        dataEachItem.put('formNum', eachMDItem.Form_Number__c);
    //        dataEachItem.put('formDesc', eachMDItem.Form_Description__c);
    //        dataEachItem.put('subjType', String.isBlank(eachMDItem.MD_Appraisal_Subject__r.Type__c) ? '' : eachMDItem.MD_Appraisal_Subject__r.Type__c);
    //        dataEachItem.put('subjNum', eachMDItem.MD_Appraisal_Subject__r.Name);
    //        dataEachItem.put('subjDesc', eachMDItem.MD_Appraisal_Subject__r.Description__c);
    //        dataEachItem.put('itemNum', eachMDItem.Name);
    //        dataEachItem.put('condi', eachMDItem.Condition__c);
    //        dataEachItem.put('itemDesc', eachMDItem.Description__c);
    //        dataEachItem.put('type', eachMDItem.Type__c);
    //        dataEachItem.put('defaultValue', eachMDItem.Default_Value__c);
    //        responseDatas.add(dataEachItem);
    //    }
    //    return responseDatas;
    //}

    @HttpPost
    global static List<MB_RESTRequestInfoModel.crewAppraisalFormAnswer> submitAnswers(List<MB_RESTRequestInfoModel.crewAppraisalFormAnswer> crewAppraisalAnswers) {
        if(crewAppraisalAnswers == null || crewAppraisalAnswers.isEmpty()) {
            return crewAppraisalAnswers;
        }
        
        String refInfo = '';
        Set<String> crewListExternalIdSet = new Set<String>();
        Set<String> flightIdSet = new Set<String>();

        if (!crewAppraisalAnswers.isEmpty()) {
            refInfo += crewAppraisalAnswers.get(0).evaFltExtId;
            for (MB_RESTRequestInfoModel.crewAppraisalFormAnswer answer : crewAppraisalAnswers) {
                refInfo += '|' + answer.evaStaffNum + ',' + answer.staffNum + ',' + answer.formNum;
                crewListExternalIdSet.add(answer.evaStaffNum + '_' + crewAppraisalAnswers.get(0).evaFltExtId);
                crewListExternalIdSet.add(answer.staffNum + '_' + crewAppraisalAnswers.get(0).evaFltExtId);
                flightIdSet.add(answer.evaFltSfdcId);
            }
        }

        Map<Id, Flight__c> flightMap = new Map<Id, Flight__c>([SELECT Id, Airline_Code__c, Aircraft_Type__c, Arrival_STN__c, Block_Time__c, Departure_STN__c, Flight_Date_LT__c, Flight_Number__c FROM Flight__c WHERE Id IN :flightIdSet]);
        List<Crew_List__c> crewLists = [SELECT Id, Rank__c, Acting_Rank__c, POS_Fly__c, Duty_Code__c, CrewId__r.Personel_Id__c, Crew_External_ID__c, Duty_Assignment__c FROM Crew_List__c WHERE Crew_External_ID__c IN :crewListExternalIdSet];
        Map<String, Crew_List__c> crewListMap = new Map<String, Crew_List__c>();
        for (Crew_List__c crewList : crewLists) {
            crewListMap.put(crewList.Crew_External_ID__c, crewList);
        }

        Map<Id, Map<String, Integer>> classMapByFlightId = new Map<Id, Map<String, Integer>>();
        for (Passenger__c  eachPassenger : [SELECT Id, Cabin_Code__c, Checkin_Seat__c, FlightId__c FROM Passenger__c WHERE FlightId__c IN :flightIdSet]) {
            if (!classMapByFlightId.containsKey(eachPassenger.FlightId__c)) {
                classMapByFlightId.put(eachPassenger.FlightId__c, new Map<String, Integer>());
            }

            String classCode = eachPassenger.Cabin_Code__c;
            if (!classMapByFlightId.get(eachPassenger.FlightId__c).containsKey(classCode)) {
                classMapByFlightId.get(eachPassenger.FlightId__c).put(classCode, 0);
            }

            if (eachPassenger.Checkin_Seat__c != null) {
                Integer count = classMapByFlightId.get(eachPassenger.FlightId__c).get(classCode);
                classMapByFlightId.get(eachPassenger.FlightId__c).put(classCode, count + 1);
            }
        }


        AppLogger.add(BE8_GlobalConstants.LEVEL_DEBUG, 'MD_CrewAppraisal_RestResource', 'submitAnswers', '', refInfo, 'request from InflightApp to SFDC', JSON.serializePretty(crewAppraisalAnswers), null, System.currentTimeMillis());

        CSE_SOAP_SUBMITCREWAPPRAISAL_WS ws = new CSE_SOAP_SUBMITCREWAPPRAISAL_WS();
        String requestBody = ws.getRequestBody(crewAppraisalAnswers, crewListMap, flightMap, classMapByFlightId);
        System.debug('requestBody :' + requestBody);
        WS_SUBMITCrewAppraisal_Model response = ws.submit(requestBody);
        System.debug('response WS_SUBMITCrewAppraisal_Model:' + response);

        List<Crew_Appraisal_Answer__c> logAnswers = new List<Crew_Appraisal_Answer__c>();
        for (MB_RESTRequestInfoModel.crewAppraisalFormAnswer answer : crewAppraisalAnswers) {
            Crew_Appraisal_Answer__c logAnswer = new Crew_Appraisal_Answer__c();
            logAnswer.Evaluator_Personel_Id__c = answer.evaStaffNum;
            logAnswer.Evaluated_Personel_Id__c = answer.staffNum;
            logAnswer.Form_Number__C = answer.formNum;
            logAnswer.Flight_External_Id__c = answer.evaFltExtId;
            logAnswer.Raw__c = JSON.serialize(answer);
            logAnswer.Appraisal_Id__c = answer.appraisalId;

            if (response != null && !response.hasError()) {
                for (WS_SUBMITCrewAppraisal_Model.return_z eachReturn : response.Envelope.Body.InsertCrewAppraisalRes.return_z) {
                    if (eachReturn.evaluateStaffID == answer.evaStaffNum
                            && eachReturn.staffID == answer.staffNum
                            && eachReturn.formNumber == answer.formNum) {
                        if (eachReturn.description.toLowerCase() == 'complete') {
                            logAnswer.Status__c = 'complete';
                            answer.isSynced = 1;
                        } else {
                            logAnswer.Status__c = eachReturn.description;
                            answer.isSynced = 0;
                        }
                        break;
                    }
                }
            }
            logAnswers.add(logAnswer);
        }
        Database.SaveResult[] saveResults = Database.insert(logAnswers, false);
        for (Crew_Appraisal_Answer__c logAnswer : logAnswers) {
            if (logAnswer.Id != null) {
                for (MB_RESTRequestInfoModel.crewAppraisalFormAnswer answer : crewAppraisalAnswers) {
                    if (answer.appraisalId == logAnswer.Appraisal_Id__c) {
                        answer.sfdcId = logAnswer.Id;
                        break;
                    }
                }
            }
        }

        if (response != null ) {
            AppLogger.add(BE8_GlobalConstants.LEVEL_DEBUG, 'MD_CrewAppraisal_RestResource', 'submitAnswers', '', refInfo, 'response from SFDC to InflightApp', JSON.serializePretty(response), null, System.currentTimeMillis());
            AppLogger.insertLogs();
        } else {
            AppLogger.insertLogs();
            throw new CustomException('Unknow Exception: MD_CrewAppraisal_RestResource.submitAnswers');
        }
        return crewAppraisalAnswers;
    }
}