prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Configuration__c</fullName>
        <label>Aircraft Configuration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_Passengers__c</fullName>
        <description>Used for display</description>
        <label>Booking Passengers</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing__c</fullName>
        <description>Used for display</description>
        <externalId>true</externalId>
        <label>Routing</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Booking class of the passenger which could be any value from A-Z depending on the ticket and the reservation of the passenger</description>
        <label>Booking Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerSectorPage_Test.cls
@isTest
private class PassengerSectorPage_Test {
	@isTest
	static void test() {
		Flight__c flight = MockupData_Test.createFlight('TG123', '2017-03-27', 1);
		flight.Aircraft_Configuration__c = 'C20 Y300';
		flight.Departure_STN__c = 'HKG';
		insert flight;

		List<Passenger__c> passengersForInsert = new List<Passenger__c>();
		Passenger__c checkInPassenger = MockupData_Test.createPassenger(flight.Id, 'C');
		checkInPassenger.Checkin_Seat__c = 'A00';
		checkInPassenger.Sector__c = 'BKK-HKG';
		passengersForInsert.add(checkInPassenger);

		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'C');
		passenger.Sector__c = 'BKK-HKG';
		passengersForInsert.add(passenger);
		insert passengersForInsert;

		ApexPages.currentPage().getParameters().put('id', flight.Id);

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(flight);
		PassengerSectorPage ctrl = new PassengerSectorPage(stdCtrl);
	}

	@isTest
	static void testAcceptedPercentageEqualsToZero() {
		Flight__c flight = MockupData_Test.createFlight('TG123', '2017-03-27', 1);
		flight.Aircraft_Configuration__c = 'C20 Y300';
		flight.Departure_STN__c = 'HKG';
		insert flight;

		List<Passenger__c> passengersForInsert = new List<Passenger__c>();
		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'C');
		passenger.Sector__c = 'BKK-HKG';
		passengersForInsert.add(passenger);
		insert passengersForInsert;

		ApexPages.currentPage().getParameters().put('id', flight.Id);

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(flight);
		PassengerSectorPage ctrl = new PassengerSectorPage(stdCtrl);
	}

	//@isTest
	//static void testBookingEqualsToTwoAndAcceptedEqualsToOne() {
	//	Flight__c flight = MockupData_Test.createFlight('TG XXX', '', 1);
	//	flight.Aircraft_Configuration__c = 'C20 Y300';
	//	flight.Departure_STN__c = 'HKG';
	//	insert flight;

	//	List<Passenger__c> passengersForInsert = new List<Passenger__c>();
	//	List<Passenger__c> bookingPassengers = MockupData_Test.createBookingPassengers(10, flight.Id, 'C', 'BKK-HKG');
	//	passengersForInsert.addAll(bookingPassengers);

	//	Passenger__c acceptedPassenger = MockupData_Test.createPassenger(flight.Id, 'C');
	//	acceptedPassenger.Sector__c = 'BKK-HKG';
	//	acceptedPassenger.Checkin_Seat__c = 'A03';
	//	passengersForInsert.add(acceptedPassenger);

	//	insert passengersForInsert;

	//	ApexPages.currentPage().getParameters().put('id', flight.Id);

	//	ApexPages.StandardController stdCtrl = new ApexPages.StandardController(flight);
	//	PassengerSectorPage ctrl = new PassengerSectorPage(stdCtrl);
	//}

	@isTest
	static void testBookingEqualsToTwoAndAcceptedEqualsToOne() {
		Flight__c flight = MockupData_Test.createFlight('TG123', '2017-03-27', 1);
		flight.Aircraft_Configuration__c = 'C20 Y300';
		flight.Booking_Passengers__c = 'C5 Y5';
		flight.Departure_STN__c = 'HKG';
		flight.Routing__c = 'BKK-HKG-ICN';
		insert flight;

		List<Passenger__c> passengersForInsert = new List<Passenger__c>();
		List<Passenger__c> acceptedPassengers = MockupData_Test.createAcceptedPassengers(10, flight.Id, 'C', 'BKK-HKG');
		passengersForInsert.addAll(acceptedPassengers);

		Passenger__c bookingPassenger = MockupData_Test.createPassenger(flight.Id, 'C');
		bookingPassenger.Sector__c = 'BKK-HKG';
		bookingPassenger.Booking_Class__c = 'A03';
		passengersForInsert.add(bookingPassenger);

		insert passengersForInsert;

		ApexPages.currentPage().getParameters().put('id', flight.Id);

		ApexPages.StandardController stdCtrl = new ApexPages.StandardController(flight);
		PassengerSectorPage ctrl = new PassengerSectorPage(stdCtrl);
	}
}