prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Manual_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Run</label>
        <type>Checkbox</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Job_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Which class originated this Job Queue</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Name of the Job Queue</description>
        <externalId>true</externalId>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manual_Run__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Force this job to run immediately without waiting for the Schedule Time to be reached</description>
        <label>Manual Run</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>Parameter for the Apex Job or Batch to run</description>
        <label>Parameter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <description>The time that this Job Queue should run</description>
        <label>Schedule Time</label>
        <type>DateTime</type>
    </fields>
    <label>Job Queue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/JobQueueTrigger_Test.cls
@isTest
public class JobQueueTrigger_Test {
	@testSetup static void setup() {

	}

	@isTest
	static void test() {
		Flight__c flight = MockupData_Test.createFlight('TG0916', '2017-03-30', 1);
		insert flight;

		Job_Queue__c jobQueue = new Job_Queue__c();
		jobQueue.Job_Name__c = 'JobName';
		jobQueue.Class_Name__c = 'PreFlightBatchScheduler';
		jobQueue.Manual_Run__c = true;
		jobQueue.Parameter__c = '{"flightMaster":"TG0916_30Mar17","flightId":"a0IN0000004tXAgMAM","flightDate":"2017-03-30","flightNumber":"TG0916", "flightLeg":"1"}';
		jobQueue.Schedule_Time__c = System.now();
		Test.startTest();
		insert jobQueue;
		Test.stopTest();

		List<Job_Queue__c> actualJobQueues = [SELECT Id, Manual_Run__c FROM Job_Queue__c];
		Assert.assertEquals(1, actualJobQueues.size());
		Assert.assertEquals(false, actualJobQueues.get(0).Manual_Run__c);
	}

}