prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Aircraft_Configuration__c</fullName>
        <label>Aircraft Configuration</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth_Input__c</fullName>
        <label>Date of  Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Infant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Infant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SSR_Service__c</fullName>
        <label>Service</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SSR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SSR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Meal__c</fullName>
        <label>Special Meal</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VIP_VVIP_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP/VVIP Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerListControllerTest.cls
@isTest
private class PassengerListControllerTest {
	
	@isTest static void testGetPassengerList() {
		Flight__c flight = MockupData_Test.createFlight('TG123', '2017-03-27', 1);
		flight.Aircraft_Configuration__c = 'C20 Y300';
		flight.Departure_STN__c = 'HKG';
		insert flight;

		List<Passenger__c> passengersForInsert = new List<Passenger__c>();
		Passenger__c passenger = MockupData_Test.createPassenger(flight.Id, 'C');
		passenger.Sector__c = 'BKK-HKG';
		passenger.SSR__c = true;
		passenger.SSR_Service__c = 'MAAS CIP';
		passenger.VIP_VVIP_Flag__c = true;
		passenger.Infant__c = true;
		passenger.Special_Meal__c = 'VGML';
		passenger.Date_of_Birth_Input__c = Date.today();
		passengersForInsert.add(passenger);
		insert passengersForInsert;
		List<PassengerListController.PassengerView> passengerList = PassengerListController.getPassengerList(flight.Id);
		Assert.assertEquals(passengersForInsert.size(), passengerList.size());
	}
}