prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <externalId>true</externalId>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Used for display</description>
        <label>Leg Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PreFlight_Queueable.cls
public with sharing class PreFlight_Queueable implements Queueable, Database.AllowsCallouts {
    public String flightMaster;
    public String flightNumber;
    public Date flightDate;
    public String timeMode;
    public Integer leg;
    public String jobName;
    public String suffixJobName;
    public List<Flight__c> flights;

    //public PreFlight_Queueable(List<Flight__c> flights, String suffixJobName) {
    //    Flight__c flight = flights.get(0);
    //    this.suffixJobName = suffixJobName;
    //    this.flightMaster = flight.Flight_Master__c;
    //    this.flightNumber = flight.Flight_Number__c;
    //    this.flightDate = Date.valueOf(flight.Flight_Date_UTC__c);
    //    this.timeMode = 'UTC';
    //    this.leg = Integer.valueOf(flight.Leg_Number__c);
    //    this.jobName = 'FLIGHT_' + flight.Flight_External_ID__c  + '_' + this.suffixJobName;
    //    flights.remove(0);
    //    this.flights = flights;
    //}

    public PreFlight_Queueable(String flightMaster, String flightNumber, Date flightDate, String timeMode, Integer leg, String jobName) {
        this.flightMaster = flightMaster;
        this.flightNumber = flightNumber;
        this.flightDate = flightDate;
        this.timeMode = timeMode;
        this.jobName = jobName;
        this.leg = leg;
    }

    public void execute(QueueableContext context) {
        try {
            PreFlight_Sync preFlightSync = new PreFlight_Sync(this.flightMaster, this.flightNumber, this.flightDate, this.timeMode, this.leg, this.jobName);
            preFlightSync.sync();
        } catch(Exception e) {
            AppLogger.error('PreFlight_Queueable', 'execute', jobName, 'exception', e);
        }

        //try {
        //    if(this.flights != null && !this.flights.isEmpty()) {
        //        Id jobId = System.enqueueJob(new PreFlight_Queueable(this.flights, this.suffixJobName));
        //        if(jobId != null) {
        //            AppLogger.debug('PreFlight_Queueable', 'next execute', jobName, 'enqueueJob :' + jobId, null);
        //        } else {
        //            AppLogger.error('PreFlight_Queueable', 'next execute', jobName, 'error to enqueueJob', null);
        //        }    
        //    }
            
        //} catch (Exception e) {
        //    AppLogger.error('PreFlight_Queueable', 'next execute', jobName, 'exception', e);
        //}

        AppLogger.insertLogs();
    }
}