prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_STN__c</fullName>
        <label>Arrival STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/In_flight_Upgrade_Seat_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of money in THB</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Destination__c</fullName>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Award_Code__c</fullName>
        <label>ROP Award Code</label>
        <referenceTo>ROP_Award_Code__mdt</referenceTo>
        <relationshipLabel>In-flight Upgrade Seat Master</relationshipLabel>
        <relationshipName>In_flight_Upgrade_Seat_Master</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Upgrade_From_Class__c</fullName>
        <label>Upgrade From Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upgrade_To_Class__c</fullName>
        <label>Upgrade To Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>In-flight Upgrade Seat Master</label>
    <pluralLabel>In-flight Upgrade Seat Master</pluralLabel>
</CustomObject>

prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Mileages_Current_Quater__c</fullName>
        <description>The expiring mileages of the upcoming quater</description>
        <label>Mileages Current Quater</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_1_Expiry_Date__c</fullName>
        <description>The expiry date of the first quater of the year</description>
        <label>Mileages Q+1 Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_1__c</fullName>
        <description>The expiring mileages of the first quater of the year</description>
        <label>Mileages Q+1</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_2_Expiry_Date__c</fullName>
        <description>The expiry date of the second quater of the year</description>
        <label>Mileages Q+2 Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_2__c</fullName>
        <description>The expiring mileages of the second quater of the year</description>
        <label>Mileages Q+2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_3_Expiry_Date__c</fullName>
        <description>The expiry date of the third quater of the year</description>
        <label>Mileages Q+3 Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_3__c</fullName>
        <description>The expiring mileages of the third quater of the year</description>
        <label>Mileages Q+3</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_4_Expiry_Date__c</fullName>
        <description>The expiry date of the fourth quater of the year</description>
        <label>Mileages Q+4 Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mileages_Q_4__c</fullName>
        <description>The expiring mileages of the fourth quater of the year</description>
        <label>Mileages Q+4</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mileages__c</fullName>
        <description>The overall mileages of this membership</description>
        <label>Mileages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Upgrade_Seat_Priority__c</fullName>
        <label>Eligible for Upgrade Seat Priority</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Eligible_for_Upgrade_Seat__c</fullName>
        <label>Eligible for Upgrade Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pax_Key_txt__c</fullName>
        <description>Text version of PaxKey__c</description>
        <externalId>true</externalId>
        <label>Pax Key txt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/ROP_Award_Code__mdt.object
<CustomObject>
    <fields>
        <fullName>Mileages__c</fullName>
        <label>Mileages</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>ROP Award Code</label>
    <pluralLabel>ROP Award Code</pluralLabel>
</CustomObject>

prd_package/classes/MileageUpgradeSeatCalculator.cls
public with sharing class MileageUpgradeSeatCalculator {

	public Map<String, In_flight_Upgrade_Seat_Master__mdt> masterDataMapByRouteAndClass;
	private Map<String, List<String>> nextClassAvailableForUpgradeMap = new Map<String, List<String>> {
		'Y' => new List<String> {'C', 'U'},
		'U' => new List<String> {'C'}
	};

	public MileageUpgradeSeatCalculator(Set<String> originSet, Set<String> destinationSet) {
		Set<String> originAndDestinationSet = new Set<String>();
		masterDataMapByRouteAndClass = new Map<String, In_flight_Upgrade_Seat_Master__mdt>();
		List<In_flight_Upgrade_Seat_Master__mdt> allMasterDataList = new List<In_flight_Upgrade_Seat_Master__mdt>();
		if (originSet == null && destinationSet == null) {
			allMasterDataList = [SELECT DeveloperName, Origin__c, Destination__c, Upgrade_From_Class__c, Upgrade_To_Class__c, Amount__c, ROP_Award_Code__r.Mileages__c FROM In_flight_Upgrade_Seat_Master__mdt];
		} else {
			originAndDestinationSet.addAll(originSet);
			originAndDestinationSet.addAll(destinationSet);
			allMasterDataList = [SELECT DeveloperName, Origin__c, Destination__c, Upgrade_From_Class__c, Upgrade_To_Class__c, Amount__c, ROP_Award_Code__r.Mileages__c FROM In_flight_Upgrade_Seat_Master__mdt WHERE (Origin__c IN :originAndDestinationSet AND Destination__c IN :originAndDestinationSet)];
		}
		for (In_flight_Upgrade_Seat_Master__mdt each : allMasterDataList) {
			String key = getMasterDataMapByRouteAndClassKey(each.Origin__c, each.Destination__c, each.Upgrade_From_Class__c, each.Upgrade_To_Class__c);
			masterDataMapByRouteAndClass.put(key, each);
		}
	}

	public List<Passenger__c> calculateEligibleSeatUpgrade(Membership__c membership, List<Passenger__c> passengerList) {
		if (membership != null && passengerList != null && passengerList.size() > 0) {
			Map<String, List<SObject>> passengerMapByPaxKey = BE8_GlobalUtility.getSObjectListMap('Pax_Key_txt__c', passengerList);
			for (String eachPaxKey : passengerMapByPaxKey.keySet()) {
				List<Passenger__c> passengerListOfSinglePassengerWithinTheRoute = (List<Passenger__c>) passengerMapByPaxKey.get(eachPaxKey);
				System.debug('passengerListOfSinglePassengerWithinTheRoute: ' + passengerListOfSinglePassengerWithinTheRoute);
				List<In_flight_Upgrade_Seat_Master__mdt> masterDataListForThisPassengerList = getMasterDataList(passengerListOfSinglePassengerWithinTheRoute);
				Map<String, List<In_flight_Upgrade_Seat_Master__mdt>> masterDataListMapByFromClassAndToClass = createMasterDataListMapByFromClassAndToClass(masterDataListForThisPassengerList);

				Decimal currentQuaterMileages = membership.Mileages_Current_Quater__c;
				Decimal allMileages = membership.Mileages__c;
				String travelClass = passengerListOfSinglePassengerWithinTheRoute[0].Cabin_Code__c;
				System.debug(eachPaxKey + ' currentQuaterMileages: ' + currentQuaterMileages + ' allMileages: ' + allMileages + ' travelClass: ' + travelClass);
				List<String> nextClassAvailableForUpgradeList = nextClassAvailableForUpgradeMap.get(travelClass);

				if (nextClassAvailableForUpgradeList != null) {
					for (String eachNextAvailableClass : nextClassAvailableForUpgradeList) {
						List<In_flight_Upgrade_Seat_Master__mdt> masterDataListWithMatchedClass = masterDataListMapByFromClassAndToClass.get(travelClass + '-' + eachNextAvailableClass);
						if (masterDataListWithMatchedClass != null) {
							Decimal requiredMileages = 0;
							for (In_flight_Upgrade_Seat_Master__mdt eachMasterData : masterDataListWithMatchedClass) {
								System.debug('eachMasterData: ' + eachMasterData);
								requiredMileages += eachMasterData.ROP_Award_Code__r.Mileages__c;
							}

							System.debug(travelClass + '-' + eachNextAvailableClass + ' requiredMileages:' + requiredMileages);
							if (currentQuaterMileages >= requiredMileages) {
								provideUpgradeSeatEligibilityToPassenger(passengerListOfSinglePassengerWithinTheRoute, masterDataListWithMatchedClass, 'Eligible_for_Upgrade_Seat_Priority__c');
							}
							if (allMileages >= requiredMileages) {
								provideUpgradeSeatEligibilityToPassenger(passengerListOfSinglePassengerWithinTheRoute, masterDataListWithMatchedClass, 'Eligible_for_Upgrade_Seat__c');
							}
						}
					}
				}
			}
		}
		return passengerList;
	}

	private Map<String, List<In_flight_Upgrade_Seat_Master__mdt>> createMasterDataListMapByFromClassAndToClass(List<In_flight_Upgrade_Seat_Master__mdt> masterDataList) {
		Map<String, List<In_flight_Upgrade_Seat_Master__mdt>> masterDataListMapByFromClassAndToClass = new Map<String, List<In_flight_Upgrade_Seat_Master__mdt>>();
		for (In_flight_Upgrade_Seat_Master__mdt each : masterDataList) {
			String key = each.Upgrade_From_Class__c + '-' + each.Upgrade_To_Class__c;
			List<In_flight_Upgrade_Seat_Master__mdt> tempList = masterDataListMapByFromClassAndToClass.get(key);
			if (tempList == null) {
				tempList = new List<In_flight_Upgrade_Seat_Master__mdt>();
				masterDataListMapByFromClassAndToClass.put(key, tempList);
			}
			tempList.add(each);
		}
		return masterDataListMapByFromClassAndToClass;
	}

	//private Decimal getCurrentQuaterMileagesFromMembership(Membership__c membership) {
	//	Map<Date, Decimal> mileageMapByExpiryDate = new Map<Date, Decimal>();
	//	if (membership.Mileages_Q_1_Expiry_Date__c != null) {
	//		mileageMapByExpiryDate.put(membership.Mileages_Q_1_Expiry_Date__c, membership.Mileages_Q_1__c);
	//	}
	//	if (membership.Mileages_Q_2_Expiry_Date__c != null) {
	//		mileageMapByExpiryDate.put(membership.Mileages_Q_2_Expiry_Date__c, membership.Mileages_Q_2__c);
	//	}
	//	if (membership.Mileages_Q_3_Expiry_Date__c != null) {
	//		mileageMapByExpiryDate.put(membership.Mileages_Q_3_Expiry_Date__c, membership.Mileages_Q_3__c);
	//	}
	//	if (membership.Mileages_Q_4_Expiry_Date__c != null) {
	//		mileageMapByExpiryDate.put(membership.Mileages_Q_4_Expiry_Date__c, membership.Mileages_Q_4__c);
	//	}

	//	if(!mileageMapByExpiryDate.isEmpty()){
	//		List<Date> mileageExpiryDateList = new List<Date>(mileageMapByExpiryDate.keySet());
	//		mileageExpiryDateList.sort();
	//		Date mostRecentExpiryDate = mileageExpiryDateList.get(0);
	//		return mileageMapByExpiryDate.get(mostRecentExpiryDate);
	//	}
	//	return 0;
	//}

	//private List<In_flight_Upgrade_Seat_Master__mdt> getMasterDataList(String origin, String destination) {
	//	List<In_flight_Upgrade_Seat_Master__mdt> masterDataList = null;
	//	if (masterDataMapByRoute.containsKey(origin + '-' + destination)) {
	//		return masterDataMapByRoute.get(origin + '-' + destination);
	//	} else if (masterDataMapByRoute.containsKey(destination + '-' + origin)) {
	//		return masterDataMapByRoute.get(destination + '-' + origin);
	//	}
	//	return null;
	//}

	private List<In_flight_Upgrade_Seat_Master__mdt> getMasterDataList(List<Passenger__c> passengerList) {
		List<In_flight_Upgrade_Seat_Master__mdt> masterDataList = new List<In_flight_Upgrade_Seat_Master__mdt>();
		Set<String> keySet = getMasterDataMapByRouteAndClassKeySetFromPassengerList(passengerList);
		for (String eachKey : keySet) {
			if (masterDataMapByRouteAndClass.containsKey(eachKey)) {
				masterDataList.add(masterDataMapByRouteAndClass.get(eachKey));
			}
		}
		return masterDataList;
	}

	private Set<String> getMasterDataMapByRouteAndClassKeySetFromPassengerList(List<Passenger__c> passengerList) {
		Set<String> keySet = new Set<String>();
		for (Passenger__c eachPassenger : passengerList) {
			String origin = eachPassenger.FlightId__r.Departure_STN__c;
			String destination = eachPassenger.FlightId__r.Arrival_STN__c;
			String currentClass = eachPassenger.Cabin_Code__c;
			List<String> nextClassAvailableForUpgradeList = nextClassAvailableForUpgradeMap.get(currentClass);
			if (nextClassAvailableForUpgradeList != null) {
				for (String eachNextAvailableClass : nextClassAvailableForUpgradeList) {
					keySet.add(getMasterDataMapByRouteAndClassKey(origin, destination, currentClass, eachNextAvailableClass));
					keySet.add(getMasterDataMapByRouteAndClassKey(destination, origin, currentClass, eachNextAvailableClass));
				}
			}
		}
		return keySet;
	}

	private String getMasterDataMapByRouteAndClassKey(String origin, String destination, String fromClass, String toClass) {
		return origin + '-' + destination + '_' + fromClass + '-' + toClass;
	}

	private List<Passenger__c> provideUpgradeSeatEligibilityToPassenger(List<Passenger__c> passengerList, List<In_flight_Upgrade_Seat_Master__mdt> upgradeSeatItemList, String fieldName) {
		for (Passenger__c eachPassenger : passengerList) {
			String origin = eachPassenger.FlightId__r.Departure_STN__c;
			String destination = eachPassenger.FlightId__r.Arrival_STN__c;
			String currentClass = eachPassenger.Cabin_Code__c;
			for (In_flight_Upgrade_Seat_Master__mdt upgradeSeatItem : upgradeSeatItemList) {
				Boolean matchOriginDestination = (upgradeSeatItem.Origin__c == origin && upgradeSeatItem.Destination__c == destination) || (upgradeSeatItem.Origin__c == destination && upgradeSeatItem.Destination__c == origin);
				Boolean matchClass = upgradeSeatItem.Upgrade_From_Class__c == currentClass;
				if (matchOriginDestination && matchClass) {
					String fieldValue = eachPassenger.get(fieldName) != null ? (String) eachPassenger.get(fieldName) : null;
					if (fieldValue == null) {
						eachPassenger.put(fieldName, '');
						fieldValue = '';
					}
					if (fieldValue.indexOf(upgradeSeatItem.DeveloperName) == -1) {
						eachPassenger.put(fieldName, fieldValue + upgradeSeatItem.DeveloperName + ',');
					}
				}
			}
		}
		return passengerList;
	}
}