prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Area__c</fullName>
        <label>Flight Area</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Should save the data like :16OCT16 instead of 2016-10-16, Trigger do convert 10OCT16 to 2016-10-16 automatically.</description>
        <label>Flight Date UTC</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <externalId>true</externalId>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Date_UTC__c</fullName>
        <description>Used for verifying result of PaxFlowDetail_Batch</description>
        <formula>FlightId__r.Flight_Date_UTC_F__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Flight Date UTC</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/PAX_Flown_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Data_Date_Key__c</fullName>
        <externalId>true</externalId>
        <label>Data Date Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Data_Date__c</fullName>
        <label>Data Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight_Area__c</fullName>
        <label>Flight Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Indo-China</fullName>
                </value>
                <value>
                    <fullName>Western</fullName>
                </value>
                <value>
                    <fullName>Southern</fullName>
                </value>
                <value>
                    <fullName>Northern</fullName>
                </value>
                <value>
                    <fullName>Middle-East</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Europe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Flight_Region__c</fullName>
        <label>Flight Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Regional</fullName>
                </value>
                <value>
                    <fullName>Domestic</fullName>
                </value>
                <value>
                    <fullName>Intercontinental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PAX_Flown_Summary__c</fullName>
        <label>PAX Flown Summary</label>
        <referenceTo>PAX_Flown_Summary__c</referenceTo>
        <relationshipLabel>PAX Flown Detail</relationshipLabel>
        <relationshipName>PAX_Flown_Detail</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Passengers__c</fullName>
        <label>Total Passengers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PAX Flown Detail</label>
    <nameField>
        <displayFormat>PXF-{00000}</displayFormat>
        <label>Ref Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PAX Flown Detail</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

prd_package/objects/PAX_Flown_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Data_Date_Key__c</fullName>
        <description>yyyy-MM-dd example 2017-02-01. Always put day = 01</description>
        <externalId>true</externalId>
        <label>Data Date Key</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Data_Date__c</fullName>
        <label>Data Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Total_Passengers__c</fullName>
        <label>Total Passengers</label>
        <summarizedField>PAX_Flown_Detail__c.Total_Passengers__c</summarizedField>
        <summaryForeignKey>PAX_Flown_Detail__c.PAX_Flown_Summary__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>PAX Flown Summary</label>
    <nameField>
        <label>PAX Flown Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PAX Flown Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/classes/PaxFlownDetailBatch_Test.cls
@isTest
private class PaxFlownDetailBatch_Test {
	
	@isTest
	static void test() {
		TriggerActivator.overrideTriggerActivation('Flight_Trigger__c', false);
		TriggerActivator.overrideTriggerActivation('Passenger_Trigger__c', false);
		List<Flight__c> insertFlightList = new List<Flight__c>();
		List<Passenger__c> insertPassengerList = new List<Passenger__c>();
		String pnrPrefix = '2BSJ62';

		Date flightDateUTC = System.today().addDays(-1);
		String flightDateText = DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),flightDateUTC.day()).format('YYYY-MM-dd');
		//String conditionDate =DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),01).format('YYYY-MM-dd');
		//PAX_Flown_Summary__c masterPaxFlownSummary = new PAX_Flown_Summary__c(Name=(DateTime.newInstance(flightDateUTC.year(),flightDateUTC.month(),01).format('YYYY-MM')),Data_Date_Key__c=conditionDate,Data_Date__c=date.newInstance(flightDateUTC.year(),flightDateUTC.month(),01));
		String fltdate = BE8_DateUtility.convertDateFormatToTraditionalFormat(flightDateText);
		System.debug('JK: fltdate - ' + fltdate);
		Flight__c flightno1 = new Flight__c (Name = 'TG410',Flight_Date_UTC__c = flightDateText,Flight_Area__c='Europe',Flight_Region__c='Intercontinental',Flight_Number__c='TG410', Flight_External_ID__c = 'TG0410_' + fltdate + '_1', STD_LT__c = flightDateText + ' 09:00:00');
		Flight__c flightno2 = new Flight__c (Name = 'TG8903',Flight_Date_UTC__c = flightDateText,Flight_Area__c='Northern',Flight_Region__c='Regional',Flight_Number__c='TG8903', Flight_External_ID__c = 'TG8903_' + fltdate + '_1', STD_LT__c = flightDateText + ' 09:00:00');
		Flight__c flightno3 = new Flight__c (Name = 'TG430',Flight_Date_UTC__c = flightDateText,Flight_Area__c='Northern',Flight_Region__c='Intercontinental',Flight_Number__c='TG430', Flight_External_ID__c = 'TG0430_' + fltdate + '_1', STD_LT__c = flightDateText + ' 09:00:00');
		
		
		insertFlightList.add(flightno1);
		insertFlightList.add(flightno2);
		insertFlightList.add(flightno3);
		insert insertFlightList;

		Passenger__c passenger1_1 = new Passenger__c(First_Name__c='F1',Last_Name__c='L1',FlightId__c=flightno1.ID,Cabin_Code__c='Y',Flight_Master__c='TG410'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15A');
		Passenger__c passenger1_2 = new Passenger__c(First_Name__c='F2',Last_Name__c='L2',FlightId__c=flightno1.ID,Cabin_Code__c='Y',Flight_Master__c='TG410'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15B');
		Passenger__c passenger1_3 = new Passenger__c(First_Name__c='F3',Last_Name__c='L3',FlightId__c=flightno1.ID,Cabin_Code__c='Y',Flight_Master__c='TG410'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15C');
		Passenger__c passenger1_4 = new Passenger__c(First_Name__c='F4',Last_Name__c='L4',FlightId__c=flightno1.ID,Cabin_Code__c='C',Flight_Master__c='TG410'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15D');
		Passenger__c passenger1_5 = new Passenger__c(First_Name__c='F5',Last_Name__c='L5',FlightId__c=flightno1.ID,Cabin_Code__c='C',Flight_Master__c='TG410'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15E');
		
		Passenger__c passenger2_1 = new Passenger__c(First_Name__c='F1',Last_Name__c='L1',FlightId__c=flightno2.ID,Cabin_Code__c='Y',Flight_Master__c='TG8903'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15A');
		Passenger__c passenger2_2 = new Passenger__c(First_Name__c='F2',Last_Name__c='L2',FlightId__c=flightno2.ID,Cabin_Code__c='Y',Flight_Master__c='TG8903'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15B');
		Passenger__c passenger2_3 = new Passenger__c(First_Name__c='F3',Last_Name__c='L3',FlightId__c=flightno2.ID,Cabin_Code__c='C',Flight_Master__c='TG8903'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15C');
		Passenger__c passenger2_4 = new Passenger__c(First_Name__c='F4',Last_Name__c='L4',FlightId__c=flightno2.ID,Cabin_Code__c='C',Flight_Master__c='TG8903'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15D');
		
		//Duplicate person paxkey
		Passenger__c passenger3_1 = new Passenger__c(First_Name__c='F1',Last_Name__c='L1',FlightId__c=flightno3.ID,Cabin_Code__c='Y',Flight_Master__c='TG430'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15A');
		Passenger__c passenger3_2 = new Passenger__c(First_Name__c='F1',Last_Name__c='L1',FlightId__c=flightno3.ID,Cabin_Code__c='Y',Flight_Master__c='TG430'+flightDateText,PNR__c='PNR', Checkin_Seat__c='15B');

		insertPassengerList.add(passenger1_1);
		insertPassengerList.add(passenger1_2);
		insertPassengerList.add(passenger1_3);
		insertPassengerList.add(passenger1_4);
		insertPassengerList.add(passenger1_5);
		insertPassengerList.add(passenger2_1);
		insertPassengerList.add(passenger2_2);
		insertPassengerList.add(passenger2_3);
		insertPassengerList.add(passenger2_4);
		insertPassengerList.add(passenger3_1);
		insertPassengerList.add(passenger3_2);

		insert insertPassengerList;

		Test.startTest();
            Database.executeBatch(new PaxFlownDetailBatch(),200);
        Test.stopTest();

		//List<PAX_Flown_Summary__c> summaryList = [SELECT ID,Total_Passengers__c FROM PAX_Flown_Summary__c WHERE Data_Date_Key__c ='2017-03-01'];
		List<PAX_Flown_Summary__c> summaryList = [SELECT ID,Total_Passengers__c FROM PAX_Flown_Summary__c];
		List<PAX_Flown_Detail__c> detailList = [SELECT ID,Total_Passengers__c FROM PAX_Flown_Detail__c ];
		System.debug('JK: summaryList - ' + summaryList);
		System.debug('JK: detailList - ' + detailList);
		System.assertEquals(1,summaryList.size());
		System.assertEquals(5,detailList.size());
		System.assertEquals(10,summaryList.get(0).Total_Passengers__c);
	}
	
	
}