prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <externalId>true</externalId>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Nationality_Master__mdt.object
<CustomObject>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality_Full_Name__c</fullName>
        <label>Nationality Full Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Nationality Master</label>
    <pluralLabel>Nationality Masters</pluralLabel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Change_Cabin_Class__c</fullName>
        <description>Cabin Code changed to</description>
        <label>Change Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Change_Seat__c</fullName>
        <label>Change Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Continent__c</fullName>
        <label>Continent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier_WS__c</fullName>
        <description>Data of FFP Tier from Web Service without conversion</description>
        <label>FFP Tier WS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Flight_Master__c</fullName>
        <description>Flight Master used for group LEG by the same flight date and flight number, Example data = TG676_16OCT16</description>
        <label>Flight Master</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Change_Seat_DateTime__c</fullName>
        <label>Last Change Seat Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality_Fullname__c</fullName>
        <description>Display Nationality Full name, for In-Flight and Customer Service</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality for Integration and Ground</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_First_Name_Auto__c</fullName>
        <label>Passenger First Name Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Name_Formatted__c</fullName>
        <label>Passenger Name Formatted</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Salutation_Auto__c</fullName>
        <description>This field stores the value of salutation of this passenger which is the result of automatic detection of salutation from passenger&apos;s first name.</description>
        <label>Passenger Salutation Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pax_Key_txt__c</fullName>
        <description>Text version of PaxKey__c</description>
        <externalId>true</externalId>
        <label>Pax Key txt</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerService.cls
public with sharing class PassengerService {
	public static Set<String> SALUTATION_SET = new Set<String> {'MR', 'MS', 'MISS', 'MRS', 'MSTR'};
	public static Map<String, String> SALUTATION_MAP = new Map<String, String> {'MR' => 'Mr.', 'MS' => 'Ms.', 'MISS' => 'Miss', 'MRS' => 'Mrs.', 'MSTR' => 'Mstr.'};

	public static List<Passenger__c> convertSubTierToActualTier(List<Passenger__c> passengerList){
		for(Passenger__c eachPassenger : passengerList){
			if(eachPassenger.FFP_Carrier__c == BE8_GlobalConstants.DEFAULT_TG_COMPANY){
				eachPassenger.FFP_Tier_WS__c = eachPassenger.FFP_Tier__c;
				eachPassenger.FFP_Tier__c = MembershipService.getHardTierFromSubTierString(eachPassenger.FFP_Tier__c);
			}
		}
		return passengerList;
	}

	public static List<Passenger__c> populateFullNationalityName(List<Passenger__c> passengerList) {
		Set<String> nationalityAbbrStringSet = BE8_GlobalUtility.getStringSet('Nationality__c', passengerList);
		Map<String, SObject> nationalityFullNameMap = BE8_GlobalUtility.getSObjectMap('MasterLabel', [SELECT Id, MasterLabel, Nationality_Full_Name__c, Continent__c FROM Nationality_Master__mdt WHERE MasterLabel IN :nationalityAbbrStringSet]);

		for (Passenger__c each : passengerList) {
			if (nationalityFullNameMap.containsKey(each.Nationality__c)) {
				Nationality_Master__mdt nationalityMaster = (Nationality_Master__mdt) nationalityFullNameMap.get(each.Nationality__c);
				each.Nationality_Fullname__c = nationalityMaster.Nationality_Full_Name__c;
				each.Continent__c = nationalityMaster.Continent__c;
			}
		}

		return passengerList;
	}

	public static List<Passenger__c> populatePaxKeyTXT(List<Passenger__c> passengerList) {
		Set<Id> flightIdSet = BE8_GlobalUtility.getIdSet('FlightId__c', passengerList);
		Map<Id, Flight__c> flightMap = new Map<Id, Flight__c>([SELECT Id, Flight_Master__c FROM Flight__c WHERE Id IN :flightIdSet]);
		for (Passenger__c passenger : passengerList) {
			if (flightMap.containsKey(passenger.FlightId__c)) {
				Flight__c flight = flightMap.get(passenger.FlightId__c);
				passenger.Pax_Key_txt__c = passenger.First_Name__c + '_' + passenger.Last_Name__c + '_' + passenger.PNR__c + '_' + flight.Flight_Master__c;
			}
		}
		return passengerList;
	}

	public static void changePassengersSeat(Map<Id, Passenger__c> oldMap, List<Passenger__c> passengerList) {
		if (oldMap != null) {
			for (Passenger__c newPassenger : passengerList) {
				Passenger__c oldPassenger = oldMap.get(newPassenger.Id);
				if (oldPassenger != null) {
					if (oldPassenger.Last_Change_Seat_DateTime__c != null) {
						Boolean isOverrideOldSeat = oldPassenger.Last_Change_Seat_DateTime__c < newPassenger.Last_Change_Seat_DateTime__c;
						if (!isOverrideOldSeat) {
							newPassenger.Change_Seat__c = oldPassenger.Change_Seat__c;
							newPassenger.Change_Cabin_Class__c = oldPassenger.Change_Cabin_Class__c;
						}
					}
				}
			}
		}
	}

	public static List<Passenger__c> dedupPassengerToChangeSeatList(List<Passenger__c> passengerList) {
		Map<Id, Passenger__c> passengerMap = new Map<Id, Passenger__c>();
		for(Passenger__c eachPassenger : passengerList){
			if(!passengerMap.containsKey(eachPassenger.Id)){
				passengerMap.put(eachPassenger.Id, eachPassenger);
			} else {
				Passenger__c passengerFromMap = passengerMap.get(eachPassenger.Id);
				if(passengerFromMap.Last_Change_Seat_DateTime__c < eachPassenger.Last_Change_Seat_DateTime__c){
					passengerMap.put(eachPassenger.Id, eachPassenger);
				}
			}
		}
		return passengerMap.values();
	}

	public static List<Passenger__c> formatPassengerNameFromList(List<Passenger__c> passengerList) {
		for(Passenger__c eachPassenger : passengerList){
			getFormattedPassengerName(eachPassenger);
		}
		return passengerList;
	}

	public static Passenger__c getFormattedPassengerName(Passenger__c passenger) {
		String firstName = passenger.First_Name__c;
		String lastName = passenger.Last_Name__c;
		String newFirstName = '';
		String newLastName = '';
		if (firstName != null && !String.isEmpty(firstName) && lastName != null && !String.isEmpty(lastName)) {
			List<String> splittedFirstName = firstName.split(' ');
			String lastStringOfSplittedFirstName = splittedFirstName.get(splittedFirstName.size() - 1);
			List<String> rearrangedFirstNameList = new List<String>();
			if (isSalutation(lastStringOfSplittedFirstName)) {
				String salutation = lastStringOfSplittedFirstName;
				splittedFirstName.remove(splittedFirstName.size() - 1);
				rearrangedFirstNameList.add(capitalizeFirstLetter(salutation) + '.');

				//passenger.Passenger_Salutation_Auto__c = salutation;
				passenger.Passenger_Salutation_Auto__c = SALUTATION_MAP.get(salutation);
				passenger.Passenger_First_Name_Auto__c = String.join(splittedFirstName, ' ');
			}
			for (String eachString : splittedFirstName) {
				rearrangedFirstNameList.add(capitalizeFirstLetter(eachString));
			}
			newFirstName = String.join(rearrangedFirstNameList, ' ');

			List<String> splittedLastName = lastName.split(' ');
			List<String> rearrangedLastNameList = new List<String>();
			for (String eachString : splittedLastName) {
				rearrangedLastNameList.add(capitalizeFirstLetter(eachString));
			}
			newLastName = String.join(rearrangedLastNameList, ' ');

			passenger.Passenger_Name_Formatted__c = newFirstName + ' ' + newLastName;
		}
		return passenger;
	}

	private static Boolean isSalutation(String text) {
		return SALUTATION_SET.contains(text);
	}

	private static String capitalizeFirstLetter(String text) {
		String lowerCaseText = text.toLowerCase();
		return text.left(1).toUpperCase() + lowerCaseText.substring(1);
	}
}