prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Departure_STN__c</fullName>
        <description>Used for display</description>
        <label>Departure STN</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>Flight External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STD_LT__c</fullName>
        <label>STD LT</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>WS_KEY__c</fullName>
        <description>Flight number + Flight date + RLOC + First name + Last name</description>
        <externalId>true</externalId>
        <label>WS KEY</label>
        <length>150</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/NewPaxList_Queueable.cls
public class NewPaxList_Queueable implements Queueable, Database.AllowsCallouts {
	private Flight__c eachFlight;
	private List<Passenger__c> passengers;
    private NewPaxList_Queueable nextNewPaxListQueueable;

	public NewPaxList_Queueable(Flight__c eachFlight, List<Passenger__c> passengers){
		this.eachFlight = eachFlight;
		this.passengers = passengers;
	}

    public void setNextNewPaxListQueueable(NewPaxList_Queueable nextNewPaxListQueueable) {
        this.nextNewPaxListQueueable = nextNewPaxListQueueable;
    }


	public void execute(QueueableContext context) {
		String flightDateLTFromSTDLT = eachFlight.STD_LT__c.split(' ').get(0);
        try {
            List<Map<String, String>> filterListMap = new List<Map<String, String>>();
            List<String> groupIndicator = new List<String>();
            groupIndicator.add('OFD');
            CSE_SOAPNewPaxList_WS ws = new CSE_SOAPNewPaxList_WS();
            String fltNo = String.valueOf(Integer.valueOf(eachFlight.Flight_Number__c.remove('TG')));
            WS_New_Pax_List_Model newPaxListModel = ws.getPaxModel(filterListMap, groupIndicator, 'TG', fltNo, flightDateLTFromSTDLT, eachFlight.Departure_STN__c);
            Map<String, Passenger__c> updatedPaxMap = New_Pax_List_Management.updatePaxConnectingFltInfoAndTkt(passengers, eachFlight, newPaxListModel);
            upsert updatedPaxMap.values() WS_Key__c;
            AppLogger.debug('NewPaxList_Queueable', 'execute', eachFlight.Flight_External_ID__c, 'success ' + updatedPaxMap.size(), null);
        } catch (Exception e) {
            AppLogger.error('NewPaxList_Queueable', 'execute', eachFlight.Flight_External_ID__c, 'Exception: ', e);
        }

        if(nextNewPaxListQueueable != null) {
            Id jobId = System.enqueueJob(nextNewPaxListQueueable);
            if (jobId != null) {
                AppLogger.debug('NewPaxList_Queueable', 'enqueueJob next job', nextNewPaxListQueueable.eachFlight.Flight_External_Id__c, 'enqueueJob next job:' + jobId, null);
            } else {
                AppLogger.error('NewPaxList_Queueable', 'enqueueJob next job', nextNewPaxListQueueable.eachFlight.Flight_External_Id__c, 'error to enqueueJob next job', null);
            }
        } 
        AppLogger.insertLogs();
	}

	public static void execute(Flight__c eachFlight, List<Passenger__c> passengers, String jobName){
		if(passengers != null && !passengers.isEmpty()){
			NewPaxList_Queueable queueable = new NewPaxList_Queueable(eachFlight, passengers);
			Id jobId = System.enqueueJob(queueable);
			if (jobId != null) {
			    AppLogger.debug('NewPaxList_Queueable', 'enqueueJob', jobName, 'enqueueJob :' + jobId, null);
			} else {
			    AppLogger.error('NewPaxList_Queueable', 'enqueueJob', jobName, 'error to enqueueJob', null);
			}
		}
	}

    public static void execute(NewPaxList_Queueable newPaxListQueueable, String jobName) {
        Id jobId = System.enqueueJob(newPaxListQueueable);
        if (jobId != null) {
            AppLogger.debug('NewPaxList_Queueable', 'enqueueJob', jobName, 'enqueueJob :' + jobId, null);
        } else {
            AppLogger.error('NewPaxList_Queueable', 'enqueueJob', jobName, 'error to enqueueJob', null);
        }
    }
}