prd_package/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/ROP_Number_Inventory__c.object
<CustomObject>
    <fields>
        <fullName>ROP_Number__c</fullName>
        <description>This field keeps the ROP Numbers. It also acts as the external key to prevent duplicate ROP Numbers in the system.</description>
        <externalId>true</externalId>
        <label>ROP Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ROP Number Inventory</label>
    <nameField>
        <label>ROP Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Number Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MB_RESTROPEnrollmentTest.cls
@isTest
private class MB_RESTROPEnrollmentTest {

	@isTest static void testEnrollROPNumberPositiveCase() {
		MockupData_Test.initializeWebServiceCustomSetting();
		Test.setMock(HttpCalloutMock.class, new MockROPEnrollmentWSFactory.MockROPEnrollmentWSSUCCESS());
		Flight__c flight = MockupData_Test.getMockUpFlight();
		insert flight;
		List<Passenger__c> passengerList = MockupData_Test.createBookingPassengers(10, flight.Id, 'Y', 'BKK-HKG');
		insert passengerList;
		insert MockupData_Test.createROPNumberInventoryList(1000);

		List<MB_RestRequestInfoModel.ropEnrollment> ropEnrollmentList = new List<MB_RestRequestInfoModel.ropEnrollment>();
		List<ROP_Number_Inventory__c> ropNumberList = ROPEnrollmentService.getUnregisteredROPNumberList(100);
		for (Integer i = 0; i < passengerList.size() ; i++) {
			Passenger__c passenger = passengerList.get(i);
			ROP_Number_Inventory__c ropNumberObject = ropNumberList.get(i);
			String ropNumber = ropNumberObject.ROP_Number__c;
			ropEnrollmentList.add(MockupData_Test.createROPEnrollmentRequest(ropNumber, flight.Id, passenger.Id));
		}

		Test.startTest();
		List<MB_RestResponseInfoModel.ropEnrollment> result = MB_RESTROPEnrollment.enrollROPNumber(ropEnrollmentList);
		Test.stopTest();
		MB_RESTROPEnrollment.getROPEnrollment();
	}
}