prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Booking class of the passenger which could be any value from A-Z depending on the ticket and the reservation of the passenger</description>
        <label>Booking Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality for Integration and Ground</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Salutation_Auto__c</fullName>
        <description>This field stores the value of salutation of this passenger which is the result of automatic detection of salutation from passenger&apos;s first name.</description>
        <label>Passenger Salutation Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/ROP_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Area code of phone number</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Country code of phone number</description>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the customer</description>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the customer</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Flight that originated this ROP Enrollment</description>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>ROP Enrollments</relationshipLabel>
        <relationshipName>ROP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the customer</description>
        <label>Gender</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the customer</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality of the customer in 3 alphabets</description>
        <label>Nationality</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Passenger that enrolled</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ROP Enrollment</relationshipLabel>
        <relationshipName>ROP_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Phone number of the customer</description>
        <label>Phone Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Salutation of the customer</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ROP Enrollment</label>
    <nameField>
        <label>ROP Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/classes/ROPEnrollment_Manual_Queueable.cls
public with sharing class ROPEnrollment_Manual_Queueable implements Queueable, Database.AllowsCallouts {
	private Id ropEnrollmentId;

	public ROPEnrollment_Manual_Queueable(Id ropEnrollmentId) {
		this.ropEnrollmentId = ropEnrollmentId;
		AppLogger.setReferenceId('ROPEnrollment_Manual_Queueable_' + ropEnrollmentId);
		AppLogger.debug('ROPEnrollment_Manual_Queueable', 'Constructor', ropEnrollmentId, 'ropEnrollmentId:' + ropEnrollmentId, null);
	}

	public void execute(QueueableContext context) {
		String toEmails = MailList_Repository.getEmailAddress('ROP Enrollment', 'ROPEnrollment_Manual');
		ROP_Enrollment__c ropEnrollment = [SELECT Id, Salutation__c, Country_Code__c, PassengerId__r.Passenger_Salutation_Auto__c, Area_Code__c, First_Name__c, Last_Name__c, Birthdate__c, Gender__c, Email__c, Phone_Number__c, FlightId__r.Name, PassengerId__r.Sector__c, PassengerId__r.Nationality__c, PassengerId__r.Name, PassengerId__r.Booking_Class__c, PassengerId__r.Cabin_Code__c, PassengerId__r.Checkin_Seat__c FROM ROP_Enrollment__c WHERE Id = : ropEnrollmentId LIMIT 1];
		String bodyMsg = '';
		bodyMsg += 'Salutation:\n';
		bodyMsg += 'First Name: ' + ropEnrollment.First_Name__c + '\n';
		bodyMsg += 'Last Name: ' + ropEnrollment.Last_Name__c + '\n';
		bodyMsg += 'Date of Birth: ' + ropEnrollment.Birthdate__c + '\n';
		bodyMsg += 'Gender: ' + ropEnrollment.Gender__c + '\n';
		bodyMsg += 'Nationality: ' + ropEnrollment.PassengerId__r.Nationality__c + '\n';
		bodyMsg += 'Email: ' + ropEnrollment.Email__c + '\n';
		bodyMsg += 'Phone Number: ' + ropEnrollment.Country_Code__c + ' ' + ropEnrollment.Area_Code__c + ' ' + ropEnrollment.Phone_Number__c + '\n';
		bodyMsg += 'Flight No.: ' + ropEnrollment.FlightId__r.Name + '\n';
		bodyMsg += 'Origin-Destination: ' + ropEnrollment.PassengerId__r.Sector__c + '\n';
		bodyMsg += 'Booking Class: ' + ropEnrollment.PassengerId__r.Booking_Class__c + '\n';
		bodyMsg += 'Flown Cabin Class: ' + ropEnrollment.PassengerId__r.Cabin_Code__c + '\n';
		bodyMsg += 'Seat No.: ' + ropEnrollment.PassengerId__r.Checkin_Seat__c + '\n';

		try {
			Email_Service.sendEmail('SFDC | Manual ROP Enrollment On-Board: ' + ropEnrollment.PassengerId__r.Name, toEmails, bodyMsg);
			AppLogger.debug('ROPEnrollment_Manual_Queueable', 'execute', 'ROPEnrollment_Manual_Queueable_' + ropEnrollmentId, 'success', null);
		} catch (Exception e) {
			AppLogger.error('ROPEnrollment_Manual_Queueable', 'execute', 'ROPEnrollment_Manual_Queueable_' + ropEnrollmentId, 'exception', e);

		}
	}

	public static Id process(Id ropEnrollmentId) {
		Id jobId;
		try {
			ROPEnrollment_Manual_Queueable manual = new ROPEnrollment_Manual_Queueable(ropEnrollmentId);
			jobId = System.enqueueJob(manual);
			AppLogger.debug('ROPEnrollment_Manual_Queueable', 'enqueueJob', 'ROPEnrollment_Manual_Queueable_' + ropEnrollmentId, 'jobId:' + jobId, null);
		} catch (Exception e) {
			AppLogger.error('ROPEnrollment_Manual_Queueable', 'enqueueJob', 'ROPEnrollment_Manual_Queueable_' + ropEnrollmentId, 'exception', e);
		}
		return jobId;
	}
}