prd_package/objects/Flight__c.object
<CustomObject>
    <fields>
        <fullName>Destination__c</fullName>
        <description>Displays the flight departing with respect to the current user&apos;s station</description>
        <label>Destination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Date_LT__c</fullName>
        <description>Used for display</description>
        <label>Flight Date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flight_Number__c</fullName>
        <description>Data format :TG999</description>
        <label>Flight Numbers</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>Used for display</description>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used for display</description>
        <formula>Departure_STN__c + &quot;-&quot; +  Arrival_STN__c</formula>
        <label>Sector</label>
        <type>Text</type>
    </fields>
    <label>Flight</label>
    <nameField>
        <label>Flight Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <recordTypes>
        <fullName>Flight</fullName>
        <active>true</active>
        <label>Flight</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Class__c</fullName>
        <description>Booking class of the passenger which could be any value from A-Z depending on the ticket and the reservation of the passenger</description>
        <label>Booking Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cabin_Code__c</fullName>
        <description>Cabin class of the passenger which could be F, Y, U, or C.</description>
        <label>Cabin Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality for Integration and Ground</description>
        <label>Nationality</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Passenger_Salutation_Auto__c</fullName>
        <description>This field stores the value of salutation of this passenger which is the result of automatic detection of salutation from passenger&apos;s first name.</description>
        <label>Passenger Salutation Auto</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/ROP_Enrollment__c.object
<CustomObject>
    <fields>
        <fullName>Area_Code__c</fullName>
        <description>Area code of phone number</description>
        <label>Area Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Birthdate__c</fullName>
        <label>Birthdate</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Country code of phone number</description>
        <label>Country Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email of the customer</description>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Date__c</fullName>
        <description>The date that this ROP Enrollment occured</description>
        <label>Enrollment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <description>Date of birth of the customer enrolling</description>
        <formula>IF( TEXT(Status__c) == &apos;Enroll&apos;, &apos;Enroll&apos;, IF(AND(TEXT(Status__c) == &apos;Void&apos;,  ROP_Number__r.Name == NULL) ,&apos;Void Before Sync&apos;, IF(AND(TEXT(Status__c) == &apos;Void&apos;,  ROP_Number__r.Name != NULL),&apos;Void After Sync&apos;, &apos;&apos; ) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enrollment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Type__c</fullName>
        <description>The type of enrollment whether it is via TG Web Service or manually enrolled</description>
        <label>Enrollment Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Web Service</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First name of the customer</description>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Flight that originated this ROP Enrollment</description>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>ROP Enrollments</relationshipLabel>
        <relationshipName>ROP_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Gender of the customer</description>
        <label>Gender</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error_Reason__c</fullName>
        <description>The error from Web Service Callout</description>
        <label>Integration Error Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicate whether this ROP Enrollment encountered error during Web Service Callout</description>
        <label>Integration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last name of the customer</description>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nationality__c</fullName>
        <description>Nationality of the customer in 3 alphabets</description>
        <label>Nationality</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PassengerId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Passenger that enrolled</description>
        <label>Passenger</label>
        <referenceTo>Passenger__c</referenceTo>
        <relationshipLabel>ROP Enrollment</relationshipLabel>
        <relationshipName>ROP_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>Phone number of the customer</description>
        <label>Phone Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ROP_Number_F__c</fullName>
        <description>The text version of the ROP Number</description>
        <formula>ROP_Number__r.ROP_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ROP Number Formula</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Salutation__c</fullName>
        <description>Salutation of the customer</description>
        <label>Salutation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ROP Enrollment</label>
    <nameField>
        <label>ROP Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ROP Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/classes/ROPEnrollment_Summary_Report.cls
public without sharing class ROPEnrollment_Summary_Report {

	private Integer lastNDays;
	private List<ROP_Enrollment__c> ropEnrollments;

	public ROPEnrollment_Summary_Report() {
		this(7);
	}

	public ROPEnrollment_Summary_Report(Integer lastNDays) {
		AppLogger.setReferenceId('UpgradeSeat_Summary_Report_' + System.today().format());
		AppLogger.debug('ROPEnrollment_Summary_Report', 'Constructor', '', 'Constructor:~lastNDays[' + lastNDays + ']', null);
		this.lastNDays = lastNDays;
		this.ropEnrollments = queryROPEnrollments();
	}

	public List<ROP_Enrollment__c> queryROPEnrollments() {
		BE8_SoqlBuilder soql = new BE8_SoqlBuilder('ROP_Enrollment__c');
		soql.addField(new Set<String> {'Id', 'Nationality__c', 'Enrollment_Date__c', 'Enrollment_Status__c', 'Enrollment_Type__c', 'Salutation__c', 'First_Name__c', 'Last_Name__c', 'Birthdate__c', 'Gender__c', 'Email__c', 'Phone_Number__c', 'FlightId__r.Name', 'FlightId__r.Flight_Number__c', 'FlightId__r.Origin__c', 'FlightId__r.Destination__c', 'Integration_Error_Reason__c', 'Integration_Error__c', 'ROP_Number_F__c', 'Country_Code__c', 'Area_Code__c', 'Phone_Number__c', 'PassengerId__r.Nationality__c', 'PassengerId__r.Sector__c', 'PassengerId__r.Booking_Class__c', 'PassengerId__r.Cabin_Code__c', 'PassengerId__r.Checkin_Seat__c', 'FlightId__r.Flight_Date_LT__c', 'PassengerId__r.Passenger_Salutation_Auto__c'});
		soql.addCondition('Enrollment_Date__c = LAST_N_DAYS:' + this.lastNDays);
		soql.addCondition('(Enrollment_Status__c = \'Enroll\' OR Enrollment_Status__c = \'Void After Sync\')');
		soql.addOrder('FlightId__c ASC');
		soql.addOrder('Integration_Error__c ASC');
		AppLogger.debug('ROPEnrollment_Summary_Report', 'queryROPEnrollments', '', soql.getQueryStr(), null);
		return Database.query(soql.getQueryStr());
	}

	public void sendSummaryReport() {
		Integer total = this.ropEnrollments.size();
		Integer success = 0;
		Integer failed = 0;

		List<List<String>> datas = new List<List<String>>();
		List<String> header = new List<String>();
		header.add('\"ROP No.\"');
		header.add('\"Status\"');
		header.add('\"ErrorMessage\"');
		header.add('\"EnrollmentStatus\"');
		header.add('\"EnrollmentType\"');

		header.add('\"Salutation\"');
		header.add('\"FirstName\"');
		header.add('\"LastName\"');
		header.add('\"Date of Birth\"');
		header.add('\"Gender\"');
		header.add('\"Nationality\"');
		header.add('\"Email\"');

		header.add('\"CountryCode\"');
		header.add('\"AreaCode\"');
		header.add('\"PhoneNumber\"');

		header.add('\"Flight Number\"');
		header.add('\"Flight Date\"');
		header.add('\"Sector\"');
		header.add('\"BookingClass\"');
		header.add('\"FlownCabinClass\"');
		header.add('\"Seat No.\"');
		header.add('\"EnrollmentDate\"');

		datas.add(header);
		for (ROP_Enrollment__c ropEnrollment : this.ropEnrollments) {
			List<String> dataEachRow = new List<String>();
			if (!ropEnrollment.Integration_Error__c) {
				success++;
			} else {
				failed++;
			}

			String status = ropEnrollment.Integration_Error__c ? 'error' : 'success';

			dataEachRow.add('\"' + ropEnrollment.ROP_Number_F__c + '\"');
			dataEachRow.add('\"' + status + '\"');
			dataEachRow.add('\"' + ropEnrollment.Integration_Error_Reason__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Enrollment_Status__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Enrollment_Type__c + '\"');

			dataEachRow.add('\"' + ropEnrollment.PassengerId__r.Passenger_Salutation_Auto__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.First_Name__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Last_Name__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Birthdate__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Gender__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Nationality__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Email__c + '\"');
			
			dataEachRow.add('\"' + ropEnrollment.Country_Code__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Area_Code__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Phone_Number__c + '\"');

			dataEachRow.add('\"' + ropEnrollment.FlightId__r.Flight_Number__c + '\"');
			if (ropEnrollment.FlightId__r.Flight_Date_LT__c != null) {
				dataEachRow.add('\"' + ropEnrollment.FlightId__r.Flight_Date_LT__c + '\"');
			} else {
				dataEachRow.add('\"\"');
			}

			dataEachRow.add('\"' + ropEnrollment.PassengerId__r.Sector__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.PassengerId__r.Booking_Class__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.PassengerId__r.Cabin_Code__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.PassengerId__r.Checkin_Seat__c + '\"');
			dataEachRow.add('\"' + ropEnrollment.Enrollment_Date__c + '\"');
			datas.add(dataEachRow);
		}

		String bodyMsg = '';
		bodyMsg += System.today().addDays(-this.lastNDays).format() + ' - ' + System.today().format() + '\n';
		bodyMsg += 'Total :' + total + '\n';
		bodyMsg += 'Success :' + success + '\n';
		bodyMsg += 'Failed :' + failed + '\n';

		String attachmentName = System.today().format() +  '_ROPEnrollmentWeeklyOnBoard.csv';
		String toEmails = MailList_Repository.getEmailAddress('ROP Enrollment', 'ROPEnrollment_Summary_Report');


		try {
			Email_Service.sendEmailWithAttachment('SFDC | ROP Enrollment On-Board: Weekly Report', toEmails, bodyMsg, BE8_GlobalUtility.toCSVString(datas), attachmentName);
			AppLogger.debug('ROPEnrollment_Summary_Report', 'sendSummaryReport', '', 'success', null);
		} catch (Exception e) {
			AppLogger.error('ROPEnrollment_Summary_Report', 'sendSummaryReport', '', 'Exception', e);
		}
	}
}