prd_package/objects/Job_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <description>How long this Job Queue has been created</description>
        <formula>IF ( NOT(ISNULL(Queued_Time__c))
,TODAY() - DATEVALUE(Queued_Time__c),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Which class originated this Job Queue</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Name of the Job Queue</description>
        <externalId>true</externalId>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>Parameter for the Apex Job or Batch to run</description>
        <label>Parameter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Queued_Time__c</fullName>
        <description>The timestamp when this Job Queue entered Scheduled Job in Salesforce</description>
        <label>Queued Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>The Id that is used to reference the record that originated this Job Queue</description>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Result__c</fullName>
        <description>Result when the Job is scheduled into Scheuled Job in Salesforce</description>
        <label>Result</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <description>The time that this Job Queue should run</description>
        <label>Schedule Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Scheduled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the Job Queue has been scheduled</description>
        <label>Scheduled</label>
        <type>Checkbox</type>
    </fields>
    <label>Job Queue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/objects/Trigger_Activation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Job_Queue_Scheduler__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Job Queue Scheduler</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Job_Queue_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Job Queue Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>Trigger Activation</label>
</CustomObject>

prd_package/classes/JobQueueService.cls
global with sharing class JobQueueService {

	global class JobQueueWrapper implements Comparable {
		public Job_Queue__c job;

		public JobQueueWrapper(Job_Queue__c job) {
			this.job = job;
		}

		global Integer compareTo(Object compareTo) {
			JobQueueWrapper otherObj = (JobQueueWrapper) compareTo;
			if (this.job.Schedule_Time__c > otherObj.job.Schedule_Time__c) {
				return 1;
			} else if (this.job.Schedule_Time__c < otherObj.job.Schedule_Time__c) {
				return -1;
			} else {
				return 0;
			}
		}
	}

	public static Job_Queue__c scheduleJob(String jobName, String cron, Schedulable schedulable, Job_Queue__c job) {
		Boolean isJobQueueSchedulerActive = Trigger_Activation__c.getInstance().Job_Queue_Scheduler__c;
		if (isJobQueueSchedulerActive) {
			System.schedule(jobName, cron, schedulable);
		}
		job.Scheduled__c = true;
		job.Queued_Time__c = DateTime.now();
		return job;
	}

	public static List<Job_Queue__c> enqueueJob() {
		//Boolean isJobQueueTriggerActive = Trigger_Activation__c.getInstance().Job_Queue_Trigger__c;
		List<CronTrigger> jobInSFDCQueue = [SELECT Id, State, CronJobDetail.Id, CronJobDetail.Name, CronJobDetail.JobType
		                                    FROM CronTrigger WHERE State = 'WAITING'];
		Integer numberOfJobInSFDCQueue = jobInSFDCQueue.size();
		if (numberOfJobInSFDCQueue < BE8_GlobalConstants.JOB_QUEUE_LIMIT) {
			Integer numberOfJobToBeQueued = BE8_GlobalConstants.JOB_QUEUE_LIMIT - numberOfJobInSFDCQueue;
			DateTime conditionDateTime = System.now().addHours(1);
			List<Job_Queue__c> jobToBeQueued = [SELECT Id, Schedule_Time__c FROM Job_Queue__c WHERE CreatedDate >= LAST_N_DAYS:14 AND Scheduled__c = false AND Schedule_Time__c < :conditionDateTime ORDER BY Schedule_Time__c ASC LIMIT 1000];
			Set<Id> jobIdSet = new Set<Id>();
			for (Job_Queue__c job : jobToBeQueued) {
				//System.debug(job.Schedule_Time__c);
				job.Scheduled__c = true;
				jobIdSet.add(job.Id);
			}
			System.debug(jobToBeQueued);
			Database.update(jobToBeQueued, false);
			return [SELECT Id, Class_Name__c, Job_Name__c, Parameter__c, Reference_Id__c, Result__c, Scheduled__c, Schedule_Time__c FROM Job_Queue__c WHERE Id IN :jobIdSet AND Scheduled__c = true];
		} else {
			return null;
		}
	}

	public static void deleteOutdatedScheduledJob() {
		DELETE [SELECT Id FROM Job_Queue__c WHERE Scheduled__c = true AND Age__c > :BE8_GlobalConstants.JOB_QUEUE_AGE_IN_DAYS LIMIT 1000];
	}
}