prd_package/objects/Job_Queue__c.object
<CustomObject>
    <fields>
        <fullName>Class_Name__c</fullName>
        <description>Which class originated this Job Queue</description>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Job_Name__c</fullName>
        <description>Name of the Job Queue</description>
        <externalId>true</externalId>
        <label>Job Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameter__c</fullName>
        <description>Parameter for the Apex Job or Batch to run</description>
        <label>Parameter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reference_Id__c</fullName>
        <description>The Id that is used to reference the record that originated this Job Queue</description>
        <label>Reference Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <description>The time that this Job Queue should run</description>
        <label>Schedule Time</label>
        <type>DateTime</type>
    </fields>
    <label>Job Queue</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Job Queue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Queues</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/classes/JobQueueServiceTest.cls
@isTest
private class JobQueueServiceTest {
	
	@isTest static void testScheduleJob() {
		Job_Queue__c jq = new Job_Queue__c();
		JobQueueService.scheduleJob('TEST', MockupData_Test.TEST_CRON, new PreFlightBatchScheduler('TG123','TG123', Date.today(), 'UTC', 1), jq);
	}

	@isTest static void testEnqueueJob() {
		Map<String, Object> parameter = new Map<String, Object> {
			'flightNumber' => '1234',
			'flightDate' => Date.today()
		};
		Job_Queue__c jobQueue = new Job_Queue__c(Class_Name__c = 'PreFlightBatchScheduler', Schedule_Time__c = DateTime.now(), Parameter__c = System.json.serialize(parameter), Job_Name__c = 'TEST', Reference_Id__c = '');
		insert jobQueue;
		JobQueueService.enqueueJob();
	}

	@isTest static void testDeleteOutdatedScheduledJob(){
		JobQueueService.deleteOutdatedScheduledJob();
	}

	@isTest static void testJobQueueWrapper(){
		JobQueueService.JobQueueWrapper jq1 = new JobQueueService.JobQueueWrapper(new Job_Queue__c(Class_Name__c = 'PreFlightBatchScheduler', Schedule_Time__c = DateTime.now(), Job_Name__c = 'TEST', Reference_Id__c = ''));
		JobQueueService.JobQueueWrapper jq2 = new JobQueueService.JobQueueWrapper(new Job_Queue__c(Class_Name__c = 'PreFlightBatchScheduler', Schedule_Time__c = DateTime.now().addHours(1), Job_Name__c = 'TEST', Reference_Id__c = ''));
		System.assertEquals(-1, jq1.compareTo(jq2));
	}
	
}