prd_package/objects/MD_Appraisal_Form__c.object
<CustomObject>
    <label>MD Appraisal Form</label>
    <nameField>
        <label>MD Appraisal Form Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

prd_package/objects/MD_Appraisal_Subject__c.object
<CustomObject>
    <fields>
        <fullName>MD_Appraisal_Form__c</fullName>
        <label>MD Appraisal Form</label>
        <referenceTo>MD_Appraisal_Form__c</referenceTo>
        <relationshipLabel>MD Appraisal Subjects</relationshipLabel>
        <relationshipName>MD_Appraisal_Subjects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MD_Appraisal_Subject_External_ID__c</fullName>
        <externalId>true</externalId>
        <label>MD Appraisal Subject External ID</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Rating</fullName>
                </value>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MD Appraisal Subject</label>
    <nameField>
        <label>MD Appraisal Subject Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MD Appraisal Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MDAppraisalSubject_Repository.cls
public with sharing class MDAppraisalSubject_Repository {
	private static MDAppraisalSubject_Repository instance = null;
	private Map<String, MD_Appraisal_Subject__c> subjectMap = new Map<String, MD_Appraisal_Subject__c>();
	public MDAppraisalSubject_Repository() {

	}

	public static Map<String, MD_Appraisal_Subject__c> getSubjectMapByKey() {
		if (getInstance().subjectMap.isEmpty()) {
			for (MD_Appraisal_Subject__c subject : [SELECT Id, Name, MD_Appraisal_Form__r.Name, MD_Appraisal_Subject_External_ID__c, Type__c FROM MD_Appraisal_Subject__c]) {
				getInstance().subjectMap.put(subject.MD_Appraisal_Form__r.Name + subject.Name, subject);
			}
		}
		return getInstance().subjectMap;
	}

	public static MDAppraisalSubject_Repository getInstance() {
		if (instance == null) instance = new MDAppraisalSubject_Repository();
		return instance;
	}
}