prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Airline__c</fullName>
        <description>The airline that issued this membership</description>
        <label>Airline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier_WS__c</fullName>
        <description>The tier of the membership according to the raw data from web service</description>
        <label>Tier WS</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>The tier of the membership (for Royal Orchid Plus, the tier will be translated to user-friendly term such as GOLD, PLAT or BASE)</description>
        <label>Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

prd_package/objects/ROP_Tier__mdt.object
<CustomObject>
    <fields>
        <fullName>Hard_Tier__c</fullName>
        <label>Hard Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Tier__c</fullName>
        <label>Sub Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ROP Tier</label>
    <pluralLabel>ROP Tiers</pluralLabel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MembershipService.cls
public with sharing class MembershipService {
	public static Map<String, String> subTierToHardTierMap;
	
	public static List<Membership__c> convertSubTierToActualTier(List<Membership__c> membershipList){
		for(Membership__c eachMem : membershipList){
			if(eachMem.Airline__c == BE8_GlobalConstants.DEFAULT_TG_COMPANY){
				eachMem.Tier_WS__c = eachMem.Tier__c;
				eachMem.Tier__c = getHardTierFromSubTierString(eachMem.Tier__c);
			}
		}
		return membershipList;
	}

	public static void initializeSubTierToHardTierMap(){
		if(subTierToHardTierMap == null){
			List<ROP_Tier__mdt> ropTierList = [SELECT DeveloperName, Sub_Tier__c, Hard_Tier__c FROM ROP_Tier__mdt];
			subTierToHardTierMap = new Map<String, String>();
			for(ROP_Tier__mdt eachRopTier : ropTierList){
				subTierToHardTierMap.put(eachRopTier.Sub_Tier__c, eachRopTier.Hard_Tier__c);
			}
		}
	}

	public static String getHardTierFromSubTierString(String subTier){
		initializeSubTierToHardTierMap();
		String hardTier = subTierToHardTierMap.get(subTier);
		return hardTier != null ? hardTier : subTier;
	}
}