prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer that uses this membership</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Memberships</relationshipLabel>
        <relationshipName>Memberships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Airline__c</fullName>
        <description>The airline that issued this membership</description>
        <label>Airline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXTMember__c</fullName>
        <description>The External Id of this membership which is Airline__c + &apos;_&apos; + Name</description>
        <externalId>true</externalId>
        <label>EXT Member</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MembershipsSelector.cls
public class MembershipsSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField>{
			Membership__c.Id,
			Membership__c.Name,
			Membership__c.AccountId__c,
			Membership__c.EXTMember__c,
			Membership__c.Airline__c
		};
	}

	public Schema.SObjectType getSObjectType() {
		return Membership__c.sObjectType;
	}	

	public Map<String, Membership__c> getMembershipsMapByExternalId(List<String> externalIds){
		if(externalIds == null || externalIds.isEmpty())
			return null;
		return null;

	}

	public List<Membership__c> getMembershipsByExternalId(List<String> externalIds){
		if(externalIds == null || externalIds.isEmpty())
			return null;
		return null;
	}

	public String buildQueryMembershipByExternalId(){
		//return newQueryFactory().setCondition('id in :idSet').toSOQL();
		return null;
	}
}