prd_package/objects/Membership__c.object
<CustomObject>
    <fields>
        <fullName>Airline__c</fullName>
        <description>The airline that issued this membership</description>
        <label>Airline</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tier__c</fullName>
        <description>The tier of the membership (for Royal Orchid Plus, the tier will be translated to user-friendly term such as GOLD, PLAT or BASE)</description>
        <label>Tier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <label>Membership Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/MembershipServiceTest.cls
@isTest
private class MembershipServiceTest {

	@isTest static void testConvertSubTierToActualTier() {
		Membership__c mem = new Membership__c(
		    Name = 'ZZ99999',
		    Airline__c = BE8_GlobalConstants.DEFAULT_TG_COMPANY,
		    Tier__c = 'SILVER O'
		);
		List<Membership__c> membershipList = new List<Membership__c>();
		membershipList.add(mem);

		MembershipService.convertSubTierToActualTier(membershipList);
		Assert.assertEquals('SILV', mem.Tier__c);
	}
}