prd_package/objects/Passenger__c.object
<CustomObject>
    <fields>
        <fullName>Cabin_Code_F__c</fullName>
        <formula>CASE( Cabin_Code__c , &quot;F&quot;, &quot;First&quot;, &quot;C&quot;, &quot;Business&quot;, &quot;Y&quot;, &quot;Economy&quot;, &quot;U&quot;, &quot;Premium Economy&quot;, &quot;&quot;)</formula>
        <label>Cabin Class Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Checkin_Seat__c</fullName>
        <description>The seat that will be assigned after the passenger has checked in</description>
        <label>Accepted Seat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Display__c</fullName>
        <description>Used for input.</description>
        <formula>Date_of_Birth_Input__c</formula>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FFP_Carrier__c</fullName>
        <label>FFP Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Number__c</fullName>
        <description>Used for display</description>
        <label>FFP Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP_Tier__c</fullName>
        <description>Used for display</description>
        <label>FFP Tier</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FFP__c</fullName>
        <description>Display : FFP_Carrier__c-FFP_Number__c, Example TG-ZD95870</description>
        <formula>FFP_Carrier__c + &apos;-&apos; +  FFP_Number__c</formula>
        <label>FFP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Used for display</description>
        <label>First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FlightId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Number</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Infant__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Infant</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Used for display</description>
        <label>Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Show__c</fullName>
        <formula>IF(   FlightId__r.STD_LT_DateTime__c   - ( NOW() + 420/1440 )  &lt;= 0.03125 &amp;&amp; Checkin_Seat__c = &quot;&quot;, TRUE, FALSE)</formula>
        <label>No Show</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PNR__c</fullName>
        <label>PNR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SSR_Service__c</fullName>
        <label>Service</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SSR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>SSR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sector__c</fullName>
        <description>Used to display. Information displayed is the origin and destination of the whole flight of the passenger</description>
        <label>Sector</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_Meal__c</fullName>
        <label>Special Meal</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>VIP_VVIP_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VIP/VVIP Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>Passenger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/PassengerListController.cls
global with sharing class PassengerListController {
	global class PassengerView {
		public String id;
		public String firstName;
		public String lastName;
		public String name;
		public String pnr;
		public String sector;
		public String ffpNumber;
		public String ffpTier;
		public Boolean isVIP;
		public Boolean isCIP;
		public Boolean noShow;
		public String seatNumber;
		public String travelClass;
		public Boolean isBirthdayToday;
		public String ssr;
		public String specialMeal;
		public String passengerStatus;
		public Boolean hasInfant;
	}

	public Id flightId {get; set;}

	public PassengerListController(ApexPages.StandardController controller) {
		flightId = controller.getRecord().Id;
	}

	@RemoteAction
	global static List<PassengerView> getPassengerList(Id flightId) {
		List<PassengerView> resultList = new List<PassengerView>();
		if (flightId != null) {
			for (Passenger__c eachPassenger : [SELECT Id, No_Show__c, Name, Date_of_Birth_Display__c, First_Name__c, Last_Name__c, Sector__c, PNR__c, FFP__c, FFP_Carrier__c, FFP_Number__c, FFP_Tier__c, VIP_VVIP_Flag__c, Checkin_Seat__c, Cabin_Code_F__c, SSR__c, SSR_Service__c, Special_Meal__c, Infant__c FROM Passenger__c WHERE FlightId__c = :flightId]) {
				PassengerView view = new PassengerView();
				view.id = eachPassenger.Id;
				view.firstName = eachPassenger.First_Name__c;
				view.lastName = eachPassenger.Last_Name__c;
				view.name = eachPassenger.Name;
				view.pnr = eachPassenger.PNR__c;
				view.sector = eachPassenger.Sector__c;
				view.ffpNumber = eachPassenger.FFP__c;
				view.ffpTier = eachPassenger.FFP_Tier__c;
				view.seatNumber = eachPassenger.Checkin_Seat__c;
				view.travelClass = eachPassenger.Cabin_Code_F__c;
				view.isBirthdayToday = isBirthdayToday(eachPassenger.Date_of_Birth_Display__c);
				view.noShow = eachPassenger.No_Show__c;
				view.hasInfant = eachPassenger.Infant__c;

				view.isVIP = eachPassenger.VIP_VVIP_Flag__c;
				view.passengerStatus = view.isVIP ? 'VIP' : '';
				if (eachPassenger.SSR_Service__c != null && eachPassenger.SSR_Service__c.contains(BE8_GlobalConstants.SSR_CODE_MAAS) && eachPassenger.SSR_Service__c.contains(BE8_GlobalConstants.SSR_CODE_CIP)) {
					view.isCIP = true;
					view.passengerStatus += 'CIP';
				}

				view.ssr = '';
				if (view.hasInfant) {
					view.ssr += ' INFT';
				}
				if (eachPassenger.SSR_Service__c != null) {
					view.ssr += ' ' + eachPassenger.SSR_Service__c;
				}
				if(view.ssr.length() > 0){
					view.ssr = 'SSR:' + view.ssr;
				}

				if (eachPassenger.Special_Meal__c != null) {
					if (view.ssr != null) {
						view.ssr += ' | MEAL: ' + eachPassenger.Special_Meal__c;
					} else {
						view.ssr = 'MEAL:' + eachPassenger.Special_Meal__c;
					}
					view.specialMeal = eachPassenger.Special_Meal__c;
				}

				resultList.add(view);
			}
		}
		return resultList;
	}

	private static Boolean isBirthdayToday(Date birthday) {
		if (birthday != null) {
			Decimal birthdayDay = birthday.day();
			Decimal birthdayMonth = birthday.month();

			Date today = Date.today();
			Decimal todayDay = today.day();
			Decimal todayMonth = today.month();
			return birthdayDay == todayDay && birthdayMonth == todayMonth;
		} else {
			return false;
		}
	}
}