prd_package/objects/SFDC_External_Key__c.object
<CustomObject>
    <fields>
        <fullName>Group_Key__c</fullName>
        <externalId>true</externalId>
        <label>Group Key</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Key__c</fullName>
        <label>Last Key</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SFDC External Key</label>
    <nameField>
        <displayFormat>EK-{0000}</displayFormat>
        <label>SFDC External Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SFDC External Keys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

p2ws_package/Devpp2ws-Package/classes/SFDCExternalKeyHandler_Test.cls
@isTest
public class SFDCExternalKeyHandler_Test {
	@isTest
	static void testConstructure() {
		SFDCExternalKeyHandler classObj = new SFDCExternalKeyHandler();
	}
	@isTest
	static void test_reservedExternalKey() {
		String objectType = 'Account';
		Set<String> setGroupKey = new Set<String> {'ACC01', 'ACC02'};
		Integer sizess = 10;

		List<SFDC_External_Key__c> listExternalObj = [Select Id, Name From SFDC_External_Key__c ];

		System.assertEquals(listExternalObj.size(), 0);

		Map<String, Integer> mapReserved = SFDCExternalKeyHandler.reservedExternalKey(objectType, setGroupKey, sizess);

		List<SFDC_External_Key__c> listAfterReserve = [Select Id, Name From SFDC_External_Key__c ];
		System.assertEquals(listAfterReserve.size(), 2);
		System.assertEquals(mapReserved.get('ACC01'), 1 );
		System.assertEquals(mapReserved.get('ACC02'), 1 );
	}
	@isTest
	static void test_existingCase() {
		mockUpSFDCKeyObj();
		//for(Integer i=0; i<15000; i++){}
		String objectType = 'Account';
		Set<String> setGroupKey = new Set<String> {'ACC01', 'ACC02'};
		Integer sizess = 10;

		List<SFDC_External_Key__c> listExternalObj = [Select Id, Name From SFDC_External_Key__c ];

		System.assertEquals(listExternalObj.size(),1 );

		Map<String, Integer> mapReserved = SFDCExternalKeyHandler.reservedExternalKey(objectType, setGroupKey, sizess);

		List<SFDC_External_Key__c> listAfterReserve = [Select Id, Name From SFDC_External_Key__c ];
		System.debug('DEBUG - test_existingCase');
		System.debug(mapReserved);
		System.debug(listAfterReserve);
		System.assertEquals(listAfterReserve.size(), 2);
		System.assertEquals(mapReserved.get('ACC01'), 10 );
		System.assertEquals(mapReserved.get('ACC02'), 1 );
	}

	@isTest
	static void test_leadingZeroFormat() {
		Integer givenNumber = 10;
		Integer length = 3;
		String afterLeading  = SFDCExternalKeyHandler.leadingZeroFormat(givenNumber, length);
		System.assertEquals('010', afterLeading);
	}
	@isTest
	static void test_getMonthYearKey() {
		Date thisDate = System.Today();
		SFDCExternalKeyHandler.getMonthYearKey(thisDate);
	}

	public static void mockUpSFDCKeyObj() {
		SFDC_External_Key__c thisObj = new SFDC_External_Key__c(
		    Object_Type__c = 'Account',
		    Group_Key__c = 'ACC01',
		    Last_Key__c = 10
		);
		insert thisObj;
	}
}